delete from cm_match_details where game_id in (select game_id from cm_matches where cpn_id = (select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'));
delete from cm_matches where cpn_id = (select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%');
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-09-2014','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444445,'De Sterrekijkers.......','Cue  Palace  Almelo',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444445,'Frank Hekhuis','Herman Fokkert',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444445,'Roger Wolthuis','Gerald Bont',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444445,'Frank Hekhuis','Gerald Bont',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444445,'Roger Wolthuis','Gerben Slot',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444445,'Roger Wolthuis','Herman Fokkert',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444445,'Frank Hekhuis','Gerben Slot',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-09-2014','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444446,'good goan','DIE HARDS',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-09-2014','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444447,'BLACK BALL HENGELO','Cue Palace 3',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444447,'Stuart Knowles','Gerko Reints',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444447,'Gerland Keun','Henk Regeling',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444447,'Gerrie Siersema','Herman van der Veen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444447,'Stuart Knowles','Henk Regeling',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444447,'Gerland Keun','Herman van der Veen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444447,'Gerrie Siersema','Gerko Reints',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444447,'Gerrie Siersema','Henk Regeling',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444447,'Gerland Keun','Gerko Reints',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444447,'Stuart Knowles','Herman van der Veen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-09-2014','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444448,'THE FOUR ACES 1','Peng Peng in the Pocket',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444448,'Hans Reese','Pieter Alberts',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444448,'Colin Middleton','Arjan ter Avest',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444448,'David Daniels','Marco Markerink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444448,'Hans Reese','Arjan ter Avest',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444448,'Colin Middleton','Marco Markerink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444448,'David Daniels','Pieter Alberts',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444448,'David Daniels','Arjan ter Avest',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444448,'Colin Middleton','Pieter Alberts',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444448,'Hans Reese','Marco Markerink',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('29-09-2014','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444449,'Cue Palace 3','good goan',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444449,'Herman van der Veen','Gemo Meis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444449,'Henk Regeling','Tonny Vos',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444449,'Gerko Reints','Bob Meis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444449,'Herman van der Veen','Tonny Vos',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444449,'Henk Regeling','Bob Meis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444449,'Gerko Reints','Gemo Meis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444449,'Gerko Reints','Tonny Vos',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444449,'Henk Regeling','Gemo Meis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444449,'Herman van der Veen','Bob Meis',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('30-09-2014','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444450,'Peng Peng in the Pocket','De Sterrekijkers.......',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444450,'Arjan ter Avest','Roger Wolthuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444450,'Pieter Alberts','Frank Embsen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444450,'Marco Markerink','Frank Hekhuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444450,'Arjan ter Avest','Frank Embsen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444450,'Pieter Alberts','Frank Hekhuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444450,'Marco Markerink','Roger Wolthuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444450,'Marco Markerink','Frank Embsen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444450,'Pieter Alberts','Roger Wolthuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444450,'Arjan ter Avest','Frank Hekhuis',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('30-09-2014','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444451,'DIE HARDS','SPC ENSCHEDE 1',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444451,'Colin Adams','Andor Uding',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444451,'John Schoor','Remco Stoffer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444451,'Martin Montanaro','Patrick Folkers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444451,'Colin Adams','Remco Stoffer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444451,'John Schoor','Patrick Folkers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444451,'Martin Montanaro','Andor Uding',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444451,'Martin Montanaro','Remco Stoffer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444451,'John Schoor','Andor Uding',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444451,'Colin Adams','Patrick Folkers',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('01-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444452,'Cue  Palace  Almelo','BLACK BALL HENGELO',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444452,'Jos Wesselink','Paul Bruns',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444452,'Herman Fokkert','Raimund Leussink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444452,'Gerald Bont','Gerland Keun',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444452,'Jos Wesselink','Raimund Leussink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444452,'Herman Fokkert','Gerland Keun',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444452,'Gerald Bont','Paul Bruns',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444452,'Gerald Bont','Raimund Leussink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444452,'Herman Fokkert','Paul Bruns',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444452,'Jos Wesselink','Gerland Keun',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444453,'De Sterrekijkers.......','THE FOUR ACES 1',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444453,'Frank Embsen','David Daniels',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444453,'Roger Wolthuis','Henk Oosterhof',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444453,'Frank Hekhuis','Jos Everhard',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444453,'Frank Embsen','Henk Oosterhof',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444453,'Roger Wolthuis','Jos Everhard',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444453,'Frank Hekhuis','David Daniels',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444453,'Frank Hekhuis','Henk Oosterhof',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444453,'Roger Wolthuis','David Daniels',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444453,'Frank Embsen','Jos Everhard',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444454,'SPC ENSCHEDE 1','Cue Palace 3',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444454,'Patrick Folkers','Henk Regeling',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444454,'Andor Uding','Jordy Achten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444454,'Remco Stoffer','Gerko Reints',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444454,'Patrick Folkers','Jordy Achten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444454,'Andor Uding','Gerko Reints',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444454,'Remco Stoffer','Henk Regeling',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444454,'Remco Stoffer','Jordy Achten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444454,'Andor Uding','Henk Regeling',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444454,'Patrick Folkers','Gerko Reints',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444455,'good goan','Cue  Palace  Almelo',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444455,'Tonny Vos','Herman Fokkert',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444455,'Bob Meis','Gerald Bont',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444455,'Gemo Meis','Jos Wesselink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444455,'Tonny Vos','Gerald Bont',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444455,'Bob Meis','Jos Wesselink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444455,'Gemo Meis','Herman Fokkert',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444455,'Gemo Meis','Gerald Bont',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444455,'Bob Meis','Herman Fokkert',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444455,'Tonny Vos','Jos Wesselink',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444456,'BLACK BALL HENGELO','Peng Peng in the Pocket',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444456,'Raimund Leussink','Pieter Alberts',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444456,'Stuart Knowles','Marco Markerink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444456,'Gerrie Siersema','Arjan ter Avest',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444456,'Raimund Leussink','Marco Markerink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444456,'Stuart Knowles','Arjan ter Avest',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444456,'Gerrie Siersema','Pieter Alberts',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444456,'Gerrie Siersema','Marco Markerink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444456,'Stuart Knowles','Pieter Alberts',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444456,'Raimund Leussink','Arjan ter Avest',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),448196,'Cue  Palace  Almelo','SPC ENSCHEDE 1',8,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444457,'Cue Palace 3','DIE HARDS',0,9);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('28-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444458,'Peng Peng in the Pocket','good goan',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444458,'Arjan ter Avest','Bob Meis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444458,'Pieter Alberts','Meindert Grootehaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444458,'Marco Markerink','Tonny Vos',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444458,'Arjan ter Avest','Meindert Grootehaar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444458,'Pieter Alberts','Tonny Vos',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444458,'Marco Markerink','Bob Meis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444458,'Marco Markerink','Meindert Grootehaar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444458,'Pieter Alberts','Bob Meis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444458,'Arjan ter Avest','Tonny Vos',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('29-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444459,'THE FOUR ACES 1','BLACK BALL HENGELO',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444459,'David Daniels','Gerrie Siersema',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444459,'Hans Reese','Gerland Keun',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444459,'Jean Pierre Arp','Stuart Knowles',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444459,'David Daniels','Gerland Keun',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444459,'Hans Reese','Stuart Knowles',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444459,'Jean Pierre Arp','Gerrie Siersema',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444459,'Jean Pierre Arp','Gerland Keun',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444459,'Hans Reese','Gerrie Siersema',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444459,'David Daniels','Stuart Knowles',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444461,'DIE HARDS','Cue  Palace  Almelo',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444461,'Colin Adams','Jos Wesselink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444461,'John Schoor','Gerald Bont',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444461,'Martin Engbers','Gerben Slot',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444461,'Colin Adams','Gerald Bont',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444461,'John Schoor','Gerben Slot',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444461,'Martin Engbers','Jos Wesselink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444461,'Martin Engbers','Gerald Bont',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444461,'John Schoor','Jos Wesselink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444461,'Colin Adams','Gerben Slot',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444462,'SPC ENSCHEDE 1','Peng Peng in the Pocket',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444462,'Patrick Folkers','Pieter Alberts',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444462,'Andor Uding','Marco Markerink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444462,'Remco Stoffer','Arjan ter Avest',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444462,'Patrick Folkers','Marco Markerink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444462,'Andor Uding','Arjan ter Avest',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444462,'Remco Stoffer','Pieter Alberts',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444462,'Remco Stoffer','Marco Markerink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444462,'Andor Uding','Pieter Alberts',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444462,'Patrick Folkers','Arjan ter Avest',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444463,'good goan','THE FOUR ACES 1',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444464,'BLACK BALL HENGELO','De Sterrekijkers.......',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444464,'Gerrie Siersema','Frank Embsen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444464,'Raimund Leussink','Frank Hekhuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444464,'Gerland Keun','Roger Wolthuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444464,'Gerrie Siersema','Frank Hekhuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444464,'Raimund Leussink','Roger Wolthuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444464,'Gerland Keun','Frank Embsen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444464,'Gerland Keun','Frank Hekhuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444464,'Raimund Leussink','Frank Embsen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444464,'Gerrie Siersema','Roger Wolthuis',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444466,'Peng Peng in the Pocket','DIE HARDS',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444466,'Arjan ter Avest','Martin Montanaro',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444466,'Marco Markerink','John Schoor',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444466,'Pieter Alberts','Martin Engbers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444466,'Arjan ter Avest','John Schoor',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444466,'Marco Markerink','Martin Engbers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444466,'Pieter Alberts','Martin Montanaro',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444466,'Pieter Alberts','John Schoor',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444466,'Marco Markerink','Martin Montanaro',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444466,'Arjan ter Avest','Martin Engbers',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444467,'THE FOUR ACES 1','SPC ENSCHEDE 1',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444467,'Jos Everhard','Andor Uding',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444467,'Colin Middleton','Remco Stoffer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444467,'Henk Oosterhof','Patrick Folkers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444467,'Jos Everhard','Remco Stoffer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444467,'Colin Middleton','Patrick Folkers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444467,'Henk Oosterhof','Andor Uding',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444467,'Henk Oosterhof','Remco Stoffer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444467,'Colin Middleton','Andor Uding',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444467,'Jos Everhard','Patrick Folkers',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444468,'Cue  Palace  Almelo','Cue Palace 3',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444468,'Jos Wesselink','Jordy Achten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444468,'Herman Fokkert','Gerko Reints',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444468,'Gerald Bont','Henk Regeling',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444468,'Jos Wesselink','Gerko Reints',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444468,'Herman Fokkert','Henk Regeling',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444468,'Gerald Bont','Jordy Achten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444468,'Gerald Bont','Gerko Reints',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444468,'Herman Fokkert','Jordy Achten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444468,'Jos Wesselink','Henk Regeling',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444470,'DIE HARDS','THE FOUR ACES 1',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444470,'Colin Adams','Henk Oosterhof',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444470,'John Schoor','Jean Pierre Arp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444470,'Martin Montanaro','Colin Middleton',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444470,'Colin Adams','Jean Pierre Arp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444470,'John Schoor','Colin Middleton',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444470,'Martin Montanaro','Henk Oosterhof',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444470,'Martin Montanaro','Jean Pierre Arp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444470,'John Schoor','Henk Oosterhof',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444470,'Colin Adams','Colin Middleton',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444471,'SPC ENSCHEDE 1','De Sterrekijkers.......',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444471,'Patrick Folkers','Roger Wolthuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444471,'Andor Uding','Frank Embsen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444471,'Remco Stoffer','Frank Hekhuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444471,'Patrick Folkers','Frank Embsen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444471,'Andor Uding','Frank Hekhuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444471,'Remco Stoffer','Roger Wolthuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444471,'Remco Stoffer','Frank Embsen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444471,'Andor Uding','Roger Wolthuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444471,'Patrick Folkers','Frank Hekhuis',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444472,'good goan','BLACK BALL HENGELO',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('25-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444474,'Peng Peng in the Pocket','Cue  Palace  Almelo',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444474,'Arjan ter Avest','Jos Wesselink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444474,'Pieter Alberts','Gerald Bont',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444474,'Marco Markerink','Gerben Slot',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444474,'Arjan ter Avest','Gerald Bont',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444474,'Pieter Alberts','Gerben Slot',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444474,'Marco Markerink','Jos Wesselink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444474,'Marco Markerink','Gerald Bont',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444474,'Pieter Alberts','Jos Wesselink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444474,'Arjan ter Avest','Gerben Slot',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('26-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444476,'THE FOUR ACES 1','Cue Palace 3',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444476,'Colin Middleton','Henk Regeling',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444476,'Hans Reese','Michel Brand',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444476,'David Daniels','Herman van der Veen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444476,'Colin Middleton','Michel Brand',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444476,'Hans Reese','Herman van der Veen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444476,'David Daniels','Henk Regeling',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444476,'David Daniels','Michel Brand',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444476,'Hans Reese','Henk Regeling',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444476,'Colin Middleton','Herman van der Veen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),448385,'Cue Palace 3','Peng Peng in the Pocket',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448385,'Herman van der Veen','Pieter Alberts',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448385,'Henk Regeling','Marco Markerink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448385,'Jordy Achten','Arjan ter Avest',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448385,'Herman van der Veen','Marco Markerink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448385,'Henk Regeling','Arjan ter Avest',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448385,'Jordy Achten','Pieter Alberts',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448385,'Jordy Achten','Marco Markerink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448385,'Henk Regeling','Pieter Alberts',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448385,'Herman van der Veen','Arjan ter Avest',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('01-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444477,'Cue Palace 3','De Sterrekijkers.......',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444477,'Henk Regeling','Frank Embsen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444477,'Michel Brand','Frank Hekhuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444477,'Jordy Achten','Roger Wolthuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444477,'Henk Regeling','Frank Hekhuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444477,'Michel Brand','Roger Wolthuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444477,'Jordy Achten','Frank Embsen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444477,'Jordy Achten','Frank Hekhuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444477,'Michel Brand','Frank Embsen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444477,'Henk Regeling','Roger Wolthuis',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444478,'DIE HARDS','BLACK BALL HENGELO',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444478,'Martin Engbers','Paul Bruns',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444478,'Colin Adams','Gerrie Siersema',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444478,'Martin Montanaro','Raimund Leussink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444478,'Martin Engbers','Gerrie Siersema',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444478,'Colin Adams','Raimund Leussink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444478,'Martin Montanaro','Paul Bruns',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444478,'Martin Montanaro','Gerrie Siersema',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444478,'Colin Adams','Paul Bruns',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444478,'Martin Engbers','Raimund Leussink',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444479,'SPC ENSCHEDE 1','good goan',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444479,'Patrick Folkers','Meindert Grootehaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444479,'Andor Uding','Gemo Meis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444479,'Remco Stoffer','Bob Meis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444479,'Patrick Folkers','Gemo Meis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444479,'Andor Uding','Bob Meis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444479,'Remco Stoffer','Meindert Grootehaar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444479,'Remco Stoffer','Gemo Meis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444479,'Andor Uding','Meindert Grootehaar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444479,'Patrick Folkers','Bob Meis',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444480,'Cue  Palace  Almelo','THE FOUR ACES 1',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444480,'Herman Fokkert','Hans Reese',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444480,'Jos Wesselink','Henk Oosterhof',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444480,'Gerben Slot','Colin Middleton',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444480,'Herman Fokkert','Henk Oosterhof',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444480,'Jos Wesselink','Colin Middleton',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444480,'Gerben Slot','Hans Reese',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444480,'Gerben Slot','Henk Oosterhof',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444480,'Jos Wesselink','Hans Reese',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444480,'Herman Fokkert','Colin Middleton',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),448356,'BLACK BALL HENGELO','SPC ENSCHEDE 1',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448356,'Gerland Keun','Andor Uding',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448356,'Paul Bruns','Remco Stoffer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448356,'Gerrie Siersema','Patrick Folkers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448356,'Gerland Keun','Remco Stoffer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448356,'Paul Bruns','Patrick Folkers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448356,'Gerrie Siersema','Andor Uding',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448356,'Gerrie Siersema','Remco Stoffer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448356,'Paul Bruns','Andor Uding',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448356,'Gerland Keun','Patrick Folkers',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),448441,'De Sterrekijkers.......','good goan',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448441,'Frank Hekhuis','Bob Meis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448441,'Roger Wolthuis','Meindert Grootehaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448441,'Frank Embsen','Tonny Vos',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448441,'Frank Hekhuis','Meindert Grootehaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448441,'Roger Wolthuis','Tonny Vos',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448441,'Frank Embsen','Bob Meis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448441,'Frank Embsen','Meindert Grootehaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448441,'Roger Wolthuis','Bob Meis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448441,'Frank Hekhuis','Tonny Vos',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),448364,'De Sterrekijkers.......','DIE HARDS',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448364,'Frank Embsen','John Schoor',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448364,'Roger Wolthuis','Martin Montanaro',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448364,'Frank Hekhuis','Colin Adams',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448364,'Frank Embsen','Martin Montanaro',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448364,'Roger Wolthuis','Colin Adams',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448364,'Frank Hekhuis','John Schoor',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448364,'Frank Hekhuis','Martin Montanaro',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448364,'Roger Wolthuis','John Schoor',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448364,'Frank Embsen','Colin Adams',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444481,'Cue Palace 3','BLACK BALL HENGELO',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444481,'Herman van der Veen','Gerrie Siersema',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444481,'Henk Regeling','Gerland Keun',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444481,'Jordy Achten','Raimund Leussink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444481,'Herman van der Veen','Gerland Keun',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444481,'Henk Regeling','Raimund Leussink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444481,'Jordy Achten','Gerrie Siersema',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444481,'Jordy Achten','Gerland Keun',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444481,'Henk Regeling','Gerrie Siersema',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444481,'Herman van der Veen','Raimund Leussink',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444482,'Peng Peng in the Pocket','THE FOUR ACES 1',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444482,'Arjan ter Avest','Henk Oosterhof',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444482,'Pieter Alberts','Jean Pierre Arp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444482,'Marco Markerink','Jos Everhard',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444482,'Arjan ter Avest','Jean Pierre Arp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444482,'Pieter Alberts','Jos Everhard',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444482,'Marco Markerink','Henk Oosterhof',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444482,'Marco Markerink','Jean Pierre Arp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444482,'Pieter Alberts','Henk Oosterhof',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444482,'Arjan ter Avest','Jos Everhard',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444483,'DIE HARDS','good goan',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444483,'Colin Adams','Bob Meis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444483,'John Schoor','Meindert Grootehaar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444483,'Martin Montanaro','Tonny Vos',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444483,'Colin Adams','Meindert Grootehaar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444483,'John Schoor','Tonny Vos',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444483,'Martin Montanaro','Bob Meis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444483,'Martin Montanaro','Meindert Grootehaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444483,'John Schoor','Bob Meis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444483,'Colin Adams','Tonny Vos',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444484,'Cue  Palace  Almelo','De Sterrekijkers.......',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444484,'Gerben Slot','Roger Wolthuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444484,'Herman Fokkert','Frank Embsen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444484,'Gerald Bont','Frank Hekhuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444484,'Gerben Slot','Frank Embsen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444484,'Herman Fokkert','Frank Hekhuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444484,'Gerald Bont','Roger Wolthuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444484,'Gerald Bont','Frank Embsen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444484,'Herman Fokkert','Roger Wolthuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444484,'Gerben Slot','Frank Hekhuis',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444485,'De Sterrekijkers.......','Peng Peng in the Pocket',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444485,'Frank Hekhuis','Marco Markerink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444485,'Frank Embsen','Arjan ter Avest',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444485,'Roger Wolthuis','Arjan ter Avest',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444485,'Frank Embsen','Marco Markerink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444485,'Roger Wolthuis','Marco Markerink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444485,'Frank Hekhuis','Arjan ter Avest',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444486,'SPC ENSCHEDE 1','DIE HARDS',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444486,'Patrick Folkers','John Schoor',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444486,'Andor Uding','Martin Montanaro',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444486,'Remco Stoffer','Colin Adams',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444486,'Patrick Folkers','Martin Montanaro',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444486,'Andor Uding','Colin Adams',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444486,'Remco Stoffer','John Schoor',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444486,'Remco Stoffer','Martin Montanaro',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444486,'Andor Uding','John Schoor',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444486,'Patrick Folkers','Colin Adams',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444487,'good goan','Cue Palace 3',8,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444488,'BLACK BALL HENGELO','Cue  Palace  Almelo',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444488,'Gerland Keun','Jos Wesselink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444488,'Stuart Knowles','Herman Fokkert',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444488,'Paul Bruns','Gerald Bont',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444488,'Gerland Keun','Herman Fokkert',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444488,'Stuart Knowles','Gerald Bont',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444488,'Paul Bruns','Jos Wesselink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444488,'Paul Bruns','Herman Fokkert',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444488,'Stuart Knowles','Jos Wesselink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444488,'Gerland Keun','Gerald Bont',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),449510,'THE FOUR ACES 1','De Sterrekijkers.......',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449510,'Colin Middleton','Roger Wolthuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449510,'Hans Reese','Frank Hekhuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449510,'Henk Oosterhof','Frank Embsen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449510,'Colin Middleton','Frank Hekhuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449510,'Hans Reese','Frank Embsen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449510,'Henk Oosterhof','Roger Wolthuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449510,'Henk Oosterhof','Frank Hekhuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449510,'Hans Reese','Roger Wolthuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449510,'Colin Middleton','Frank Embsen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444489,'Cue Palace 3','SPC ENSCHEDE 1',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444489,'Henk Regeling','Andor Uding',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444489,'Jordy Achten','Remco Stoffer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444489,'Gerko Reints','Patrick Folkers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444489,'Henk Regeling','Remco Stoffer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444489,'Jordy Achten','Patrick Folkers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444489,'Gerko Reints','Andor Uding',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444489,'Gerko Reints','Remco Stoffer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444489,'Jordy Achten','Andor Uding',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444489,'Henk Regeling','Patrick Folkers',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444490,'Peng Peng in the Pocket','BLACK BALL HENGELO',0,9);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444490,'Arjan ter Avest','Gerland Keun',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444490,'Pieter Alberts','Stuart Knowles',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444490,'Marco Markerink','Gerrie Siersema',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444490,'Arjan ter Avest','Stuart Knowles',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444490,'Pieter Alberts','Gerrie Siersema',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444490,'Marco Markerink','Gerland Keun',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444490,'Marco Markerink','Stuart Knowles',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444490,'Pieter Alberts','Gerland Keun',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444490,'Arjan ter Avest','Gerrie Siersema',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444492,'Cue  Palace  Almelo','good goan',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444492,'Jos Wesselink','Bob Meis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444492,'Herman Fokkert','Meindert Grootehaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444492,'Gerald Bont','Tonny Vos',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444492,'Jos Wesselink','Meindert Grootehaar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444492,'Herman Fokkert','Tonny Vos',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444492,'Gerald Bont','Bob Meis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444492,'Gerald Bont','Meindert Grootehaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444492,'Herman Fokkert','Bob Meis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444492,'Jos Wesselink','Tonny Vos',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444493,'DIE HARDS','Cue Palace 3',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444493,'Colin Adams','Michel Brand',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444493,'John Schoor','Jordy Achten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444493,'Martin Montanaro','Henk Regeling',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444493,'Colin Adams','Jordy Achten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444493,'John Schoor','Henk Regeling',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444493,'Martin Montanaro','Michel Brand',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444493,'Martin Montanaro','Jordy Achten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444493,'John Schoor','Michel Brand',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444493,'Colin Adams','Henk Regeling',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('25-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444494,'SPC ENSCHEDE 1','Cue  Palace  Almelo',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('25-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444495,'good goan','Peng Peng in the Pocket',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('25-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444496,'BLACK BALL HENGELO','THE FOUR ACES 1',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444496,'Stuart Knowles','Jos Everhard',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444496,'Raimund Leussink','David Daniels',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444496,'Paul Bruns','Jean Pierre Arp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444496,'Stuart Knowles','David Daniels',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444496,'Raimund Leussink','Jean Pierre Arp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444496,'Paul Bruns','Jos Everhard',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444496,'Paul Bruns','David Daniels',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444496,'Raimund Leussink','Jos Everhard',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444496,'Stuart Knowles','Jean Pierre Arp',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('30-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444497,'De Sterrekijkers.......','BLACK BALL HENGELO',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444497,'Frank Embsen','Stuart Knowles',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444497,'Roger Wolthuis','Paul Bruns',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444497,'Frank Hekhuis','Gerland Keun',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444497,'Frank Embsen','Paul Bruns',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444497,'Roger Wolthuis','Gerland Keun',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444497,'Frank Hekhuis','Stuart Knowles',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444497,'Frank Hekhuis','Paul Bruns',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444497,'Roger Wolthuis','Stuart Knowles',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444497,'Frank Embsen','Gerland Keun',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('31-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444498,'Peng Peng in the Pocket','SPC ENSCHEDE 1',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('01-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444499,'THE FOUR ACES 1','good goan',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444499,'David Daniels','Gemo Meis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444499,'Colin Middleton','Bob Meis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444499,'Jean Pierre Arp','Meindert Grootehaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444499,'David Daniels','Bob Meis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444499,'Colin Middleton','Meindert Grootehaar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444499,'Jean Pierre Arp','Gemo Meis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444499,'Jean Pierre Arp','Bob Meis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444499,'Colin Middleton','Gemo Meis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444499,'David Daniels','Meindert Grootehaar',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('01-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444500,'Cue  Palace  Almelo','DIE HARDS',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444500,'Jos Wesselink','Martin Montanaro',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444500,'Herman Fokkert','John Schoor',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444500,'Gerald Bont','Martin Engbers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444500,'Jos Wesselink','John Schoor',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444500,'Herman Fokkert','Martin Engbers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444500,'Gerald Bont','Martin Montanaro',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444500,'Gerald Bont','John Schoor',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444500,'Herman Fokkert','Martin Montanaro',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444500,'Jos Wesselink','Martin Engbers',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444501,'Cue Palace 3','Cue  Palace  Almelo',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444501,'Herman van der Veen','Herman Fokkert',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444501,'Henk Regeling','Gerald Bont',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444501,'Michel Brand','Gerben Slot',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444501,'Herman van der Veen','Gerald Bont',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444501,'Henk Regeling','Gerben Slot',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444501,'Michel Brand','Herman Fokkert',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444501,'Michel Brand','Gerald Bont',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444501,'Henk Regeling','Herman Fokkert',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444501,'Herman van der Veen','Gerben Slot',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444502,'DIE HARDS','Peng Peng in the Pocket',9,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444503,'SPC ENSCHEDE 1','THE FOUR ACES 1',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444503,'Patrick Folkers','Jos Everhard',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444503,'Andor Uding','Colin Middleton',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444503,'Remco Stoffer','Jean Pierre Arp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444503,'Patrick Folkers','Colin Middleton',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444503,'Andor Uding','Jean Pierre Arp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444503,'Remco Stoffer','Jos Everhard',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444503,'Remco Stoffer','Colin Middleton',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444503,'Andor Uding','Jos Everhard',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444503,'Patrick Folkers','Jean Pierre Arp',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444504,'good goan','De Sterrekijkers.......',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444504,'Bob Meis','Roger Wolthuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444504,'Meindert Grootehaar','Frank Hekhuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444504,'Gemo Meis','Frank Embsen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444504,'Bob Meis','Frank Hekhuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444504,'Meindert Grootehaar','Frank Embsen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444504,'Gemo Meis','Roger Wolthuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444504,'Gemo Meis','Frank Hekhuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444504,'Meindert Grootehaar','Roger Wolthuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444504,'Bob Meis','Frank Embsen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444505,'De Sterrekijkers.......','SPC ENSCHEDE 1',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444505,'Frank Embsen','Remco Stoffer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444505,'Frank Hekhuis','Patrick Folkers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444505,'Roger Wolthuis','Patrick Folkers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444505,'Frank Hekhuis','Remco Stoffer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444505,'Roger Wolthuis','Remco Stoffer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444505,'Frank Embsen','Patrick Folkers',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444506,'Peng Peng in the Pocket','Cue Palace 3',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444506,'Arjan ter Avest','Henk Regeling',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444506,'Pieter Alberts','Michel Brand',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444506,'Marco Markerink','Herman van der Veen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444506,'Arjan ter Avest','Michel Brand',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444506,'Pieter Alberts','Herman van der Veen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444506,'Marco Markerink','Henk Regeling',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444506,'Marco Markerink','Michel Brand',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444506,'Pieter Alberts','Henk Regeling',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444506,'Arjan ter Avest','Herman van der Veen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444507,'BLACK BALL HENGELO','good goan',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444507,'Paul Bruns','Gemo Meis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444507,'Gerland Keun','Tonny Vos',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444507,'Raimund Leussink','Meindert Grootehaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444507,'Paul Bruns','Tonny Vos',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444507,'Gerland Keun','Meindert Grootehaar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444507,'Raimund Leussink','Gemo Meis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444507,'Raimund Leussink','Tonny Vos',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444507,'Gerland Keun','Gemo Meis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444507,'Paul Bruns','Meindert Grootehaar',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444508,'THE FOUR ACES 1','DIE HARDS',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444508,'Henk Oosterhof','Martin Engbers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444508,'Colin Middleton','Colin Adams',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444508,'Hans Reese','Martin Montanaro',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444508,'Henk Oosterhof','Colin Adams',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444508,'Colin Middleton','Martin Montanaro',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444508,'Hans Reese','Martin Engbers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444508,'Hans Reese','Colin Adams',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444508,'Colin Middleton','Martin Engbers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444508,'Henk Oosterhof','Martin Montanaro',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('28-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444510,'DIE HARDS','De Sterrekijkers.......',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444510,'Martin Engbers','Roger Wolthuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444510,'Colin Adams','Frank Hekhuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444510,'John Schoor','Frank Embsen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444510,'Martin Engbers','Frank Hekhuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444510,'Colin Adams','Frank Embsen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444510,'John Schoor','Roger Wolthuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444510,'John Schoor','Frank Hekhuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444510,'Colin Adams','Roger Wolthuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444510,'Martin Engbers','Frank Embsen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('29-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444511,'SPC ENSCHEDE 1','BLACK BALL HENGELO',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444511,'Patrick Folkers','Stuart Knowles',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444511,'Andor Uding','Paul Bruns',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444511,'Remco Stoffer','Gerland Keun',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444511,'Patrick Folkers','Paul Bruns',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444511,'Andor Uding','Gerland Keun',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444511,'Remco Stoffer','Stuart Knowles',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444511,'Remco Stoffer','Paul Bruns',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444511,'Andor Uding','Stuart Knowles',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444511,'Patrick Folkers','Gerland Keun',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('29-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444512,'Cue  Palace  Almelo','Peng Peng in the Pocket',9,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444512,'Gerben Slot','Arjan ter Avest',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444512,'Jos Wesselink','Pieter Alberts',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444512,'Herman Fokkert','Marco Markerink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444512,'Gerben Slot','Pieter Alberts',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444512,'Jos Wesselink','Marco Markerink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444512,'Herman Fokkert','Arjan ter Avest',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444512,'Herman Fokkert','Pieter Alberts',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444512,'Jos Wesselink','Arjan ter Avest',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444512,'Gerben Slot','Marco Markerink',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444513,'De Sterrekijkers.......','Cue Palace 3',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444513,'Frank Embsen','Jordy Achten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444513,'Roger Wolthuis','Gerko Reints',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444513,'Frank Hekhuis','Henk Regeling',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444513,'Frank Embsen','Gerko Reints',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444513,'Roger Wolthuis','Henk Regeling',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444513,'Frank Hekhuis','Jordy Achten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444513,'Frank Hekhuis','Gerko Reints',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444513,'Roger Wolthuis','Jordy Achten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444513,'Frank Embsen','Henk Regeling',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444515,'BLACK BALL HENGELO','DIE HARDS',9,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444515,'Gerland Keun','John Schoor',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444515,'Stuart Knowles','Martin Montanaro',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444515,'Gerrie Siersema','Martin Engbers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444515,'Gerland Keun','Martin Montanaro',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444515,'Stuart Knowles','Martin Engbers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444515,'Gerrie Siersema','John Schoor',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444515,'Gerrie Siersema','Martin Montanaro',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444515,'Stuart Knowles','John Schoor',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444515,'Gerland Keun','Martin Engbers',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),444516,'THE FOUR ACES 1','Cue  Palace  Almelo',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444516,'Jos Everhard','Jos Wesselink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444516,'Colin Middleton','Herman Fokkert',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444516,'Hans Reese','Gerben Slot',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444516,'Jos Everhard','Herman Fokkert',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444516,'Colin Middleton','Gerben Slot',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444516,'Hans Reese','Jos Wesselink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444516,'Hans Reese','Herman Fokkert',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444516,'Colin Middleton','Jos Wesselink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444516,'Jos Everhard','Gerben Slot',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),449811,'Cue Palace 3','THE FOUR ACES 1',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449811,'Herman van der Veen','Hans Reese',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449811,'Henk Regeling','Jean Pierre Arp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449811,'Michel Brand','David Daniels',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449811,'Herman van der Veen','Jean Pierre Arp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449811,'Henk Regeling','David Daniels',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449811,'Michel Brand','Hans Reese',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449811,'Michel Brand','Jean Pierre Arp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449811,'Henk Regeling','Hans Reese',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449811,'Herman van der Veen','David Daniels',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = '1e klasse Oost' and ssn_id like '2014%'),449804,'good goan','SPC ENSCHEDE 1',5,4);
