delete from cm_match_details where game_id in (select game_id from cm_matches where cpn_id = (select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'));
delete from cm_matches where cpn_id = (select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%');
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-09-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214636,'SNOOKERCAFE 8','Team Ballistics',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214636,'Peter Vos','Jordy de Groot',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214636,'Roeland van Schie','Roy de Lepper',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214636,'Wim Daens','Ho Bang Tang',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214636,'Peter Vos','Roy de Lepper',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214636,'Roeland van Schie','Ho Bang Tang',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214636,'Wim Daens','Jordy de Groot',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214636,'Wim Daens','Roy de Lepper',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214636,'Roeland van Schie','Jordy de Groot',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214636,'Peter Vos','Ho Bang Tang',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-09-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214638,'Spijkenisse Quattro','SPIJKENISSE 9',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214638,'Dennis de Ruiter','Arie Beljaars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214638,'Leslie van Leeuwen','Arie van den Houwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214638,'Marcel Paulus','Remco van Brenkelen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214638,'Dennis de Ruiter','Arie van den Houwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214638,'Leslie van Leeuwen','Remco van Brenkelen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214638,'Marcel Paulus','Arie Beljaars',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214638,'Marcel Paulus','Arie van den Houwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214638,'Leslie van Leeuwen','Arie Beljaars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214638,'Dennis de Ruiter','Remco van Brenkelen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-09-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214639,'REYERBOS 4','SNOOKERPALACE PUTTE',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214639,'Bert van der Linden','Jeroen van Driel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214639,'René de Winter','Sien Hoppenbrouwers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214639,'Robert van Dam','Domingo Peeters',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214639,'Bert van der Linden','Sien Hoppenbrouwers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214639,'René de Winter','Domingo Peeters',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214639,'Robert van Dam','Jeroen van Driel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214639,'Robert van Dam','Sien Hoppenbrouwers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214639,'René de Winter','Jeroen van Driel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214639,'Bert van der Linden','Domingo Peeters',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-09-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214640,'SNOOKERPALACE PUTTE','Spijkenisse Quattro',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214640,'Marc Witkam','Leslie van Leeuwen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214640,'Marc Bruijne','Marcel Paulus',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214640,'Peter van Someren','Dennis de Ruiter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214640,'Marc Witkam','Marcel Paulus',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214640,'Marc Bruijne','Dennis de Ruiter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214640,'Peter van Someren','Leslie van Leeuwen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214640,'Peter van Someren','Marcel Paulus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214640,'Marc Bruijne','Leslie van Leeuwen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214640,'Marc Witkam','Dennis de Ruiter',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-09-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214642,'THE GREEN SENSATIONS','REYERBOS 4',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214642,'Jeffrey de Wijs','Arno van Vlokhoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214642,'Jeroen Gode','René de Winter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214642,'Dennis van der Marel','Robert van Dam',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214642,'Jeffrey de Wijs','René de Winter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214642,'Jeroen Gode','Robert van Dam',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214642,'Dennis van der Marel','Arno van Vlokhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214642,'Dennis van der Marel','René de Winter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214642,'Jeroen Gode','Arno van Vlokhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214642,'Jeffrey de Wijs','Robert van Dam',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-09-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214644,'SNOOKERCAFE 8','SPIJKENISSE 9',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214644,'Peter Vos','Patrick Beljaars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214644,'Alexander Stolk','Arie Beljaars',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214644,'Peter Vos','Arie Beljaars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214644,'Alexander Stolk','Arie van den Houwen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214644,'Alexander Stolk','Patrick Beljaars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214644,'Peter Vos','Arie van den Houwen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('28-09-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214646,'Spijkenisse Quattro','THE GREEN SENSATIONS',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214646,'Bas Lange','Roel Pet',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214646,'Leslie van Leeuwen','Jeffrey de Wijs',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214646,'Marcel Paulus','Rick van den Berg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214646,'Bas Lange','Jeffrey de Wijs',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214646,'Leslie van Leeuwen','Rick van den Berg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214646,'Marcel Paulus','Roel Pet',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214646,'Marcel Paulus','Jeffrey de Wijs',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214646,'Leslie van Leeuwen','Roel Pet',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214646,'Bas Lange','Rick van den Berg',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-10-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214650,'SPIJKENISSE 9','Team Ballistics',0,9);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214650,'Remco van Brenkelen','Jordy de Groot',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214650,'Rob van Doorn','Richard van Giesen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214650,'Patrick Beljaars','Patrick van Hilst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214650,'Remco van Brenkelen','Richard van Giesen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214650,'Rob van Doorn','Patrick van Hilst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214650,'Patrick Beljaars','Jordy de Groot',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214650,'Patrick Beljaars','Richard van Giesen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214650,'Rob van Doorn','Jordy de Groot',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214650,'Remco van Brenkelen','Patrick van Hilst',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-10-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214651,'REYERBOS 4','Spijkenisse Quattro',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214651,'Bert van der Linden','Dennis de Ruiter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214651,'Arno van Vlokhoven','Leslie van Leeuwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214651,'Gozewijn van Laatum','Bas Lange',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214651,'Bert van der Linden','Leslie van Leeuwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214651,'Arno van Vlokhoven','Bas Lange',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214651,'Gozewijn van Laatum','Dennis de Ruiter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214651,'Gozewijn van Laatum','Leslie van Leeuwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214651,'Arno van Vlokhoven','Dennis de Ruiter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214651,'Bert van der Linden','Bas Lange',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-10-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214652,'SNOOKERCAFE 8','THE GREEN SENSATIONS',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214652,'Peter Vos','Dennis van der Marel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214652,'Wim Daens','Jeroen Gode',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214652,'Roeland van Schie','Jeroen Hofmeester',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214652,'Peter Vos','Jeroen Gode',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214652,'Wim Daens','Jeroen Hofmeester',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214652,'Roeland van Schie','Dennis van der Marel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214652,'Roeland van Schie','Jeroen Gode',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214652,'Wim Daens','Dennis van der Marel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214652,'Peter Vos','Jeroen Hofmeester',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214658,'THE GREEN SENSATIONS','Team Ballistics',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214658,'Jeroen Hofmeester','Patrick van Hilst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214658,'Roland van der Wulp','Ho Bang Tang',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214658,'Roel Pet','Patrick van Hilst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214658,'Jeroen Hofmeester','Ho Bang Tang',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214658,'Roland van der Wulp','Patrick van Hilst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214658,'Roel Pet','Ho Bang Tang',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214659,'REYERBOS 4','SNOOKERCAFE 8',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214659,'Bert van der Linden','Roeland van Schie',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214659,'Arno van Vlokhoven','Wim Daens',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214659,'Bert van der Linden','Wim Daens',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214659,'René de Winter','Roeland van Schie',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214659,'René de Winter','Wim Daens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214659,'Arno van Vlokhoven','Roeland van Schie',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214660,'SNOOKERCAFE 8','Spijkenisse Quattro',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214660,'Willem Poot','Dennis de Ruiter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214660,'Roeland van Schie','Marcel Paulus',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214660,'Peter Vos','Bas Lange',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214660,'Willem Poot','Marcel Paulus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214660,'Roeland van Schie','Bas Lange',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214660,'Peter Vos','Dennis de Ruiter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214660,'Peter Vos','Marcel Paulus',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214660,'Roeland van Schie','Dennis de Ruiter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214660,'Willem Poot','Bas Lange',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214662,'SPIJKENISSE 9','SNOOKERPALACE PUTTE',0,9);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214663,'Team Ballistics','REYERBOS 4',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214663,'Vincent van den Berg','René de Winter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214663,'Richard van Giesen','Gozewijn van Laatum',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214663,'Ho Bang Tang','Robert van Dam',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214663,'Vincent van den Berg','Gozewijn van Laatum',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214663,'Richard van Giesen','Robert van Dam',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214663,'Ho Bang Tang','René de Winter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214663,'Ho Bang Tang','Gozewijn van Laatum',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214663,'Richard van Giesen','René de Winter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214663,'Vincent van den Berg','Robert van Dam',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214665,'Spijkenisse Quattro','Team Ballistics',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214665,'Bas Lange','Jordy de Groot',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214665,'Dennis de Ruiter','Ho Bang Tang',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214665,'Bas Lange','Ho Bang Tang',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214665,'Leslie van Leeuwen','Jordy de Groot',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214665,'Leslie van Leeuwen','Ho Bang Tang',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214665,'Dennis de Ruiter','Jordy de Groot',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214666,'THE GREEN SENSATIONS','SPIJKENISSE 9',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214666,'Michael van der Wulp','Arie van den Houwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214666,'Roland van der Wulp','Patrick Beljaars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214666,'Jeroen Gode','Arie Beljaars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214666,'Michael van der Wulp','Patrick Beljaars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214666,'Roland van der Wulp','Arie Beljaars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214666,'Jeroen Gode','Arie van den Houwen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214666,'Jeroen Gode','Patrick Beljaars',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214666,'Roland van der Wulp','Arie van den Houwen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214666,'Michael van der Wulp','Arie Beljaars',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214668,'SNOOKERPALACE PUTTE','THE GREEN SENSATIONS',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('25-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214670,'SPIJKENISSE 9','REYERBOS 4',0,9);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214670,'Arie Beljaars','Arno van Vlokhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214670,'Rob van Doorn','René de Winter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214670,'Roland Bos','Bert van der Linden',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214670,'Arie Beljaars','René de Winter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214670,'Rob van Doorn','Bert van der Linden',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214670,'Roland Bos','Arno van Vlokhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214670,'Roland Bos','René de Winter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214670,'Rob van Doorn','Arno van Vlokhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214670,'Arie Beljaars','Bert van der Linden',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('30-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214673,'SNOOKERPALACE PUTTE','REYERBOS 4',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-12-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214674,'SPIJKENISSE 9','Spijkenisse Quattro',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214674,'Patrick Beljaars','Dennis de Ruiter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214674,'Arie Beljaars','Leslie van Leeuwen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214674,'Arie van den Houwen','Bas Lange',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214674,'Patrick Beljaars','Leslie van Leeuwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214674,'Arie Beljaars','Bas Lange',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214674,'Arie van den Houwen','Dennis de Ruiter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214674,'Arie van den Houwen','Leslie van Leeuwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214674,'Arie Beljaars','Dennis de Ruiter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214674,'Patrick Beljaars','Bas Lange',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-12-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214679,'REYERBOS 4','THE GREEN SENSATIONS',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214679,'Gozewijn van Laatum','Jeffrey de Wijs',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214679,'René de Winter','Jeroen Gode',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214679,'Arno van Vlokhoven','Rick van den Berg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214679,'Gozewijn van Laatum','Jeroen Gode',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214679,'René de Winter','Rick van den Berg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214679,'Arno van Vlokhoven','Jeffrey de Wijs',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214679,'Arno van Vlokhoven','Jeroen Gode',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214679,'René de Winter','Jeffrey de Wijs',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214679,'Gozewijn van Laatum','Rick van den Berg',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-12-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214683,'THE GREEN SENSATIONS','Spijkenisse Quattro',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214683,'Rick van den Berg','Dennis de Ruiter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214683,'Roel Pet','Marcel Paulus',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214683,'Jeffrey de Wijs','Bas Lange',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214683,'Rick van den Berg','Marcel Paulus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214683,'Roel Pet','Bas Lange',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214683,'Jeffrey de Wijs','Dennis de Ruiter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214683,'Jeffrey de Wijs','Marcel Paulus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214683,'Roel Pet','Dennis de Ruiter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214683,'Rick van den Berg','Bas Lange',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-12-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),230635,'SNOOKERPALACE PUTTE','SNOOKERCAFE 8',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-01-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214685,'SNOOKERCAFE 8','SNOOKERPALACE PUTTE',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-01-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214686,'Spijkenisse Quattro','REYERBOS 4',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214686,'Bas Lange','René de Winter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214686,'Dennis de Ruiter','Arno van Vlokhoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214686,'Leslie van Leeuwen','Bert van der Linden',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214686,'Bas Lange','Arno van Vlokhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214686,'Dennis de Ruiter','Bert van der Linden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214686,'Leslie van Leeuwen','René de Winter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214686,'Leslie van Leeuwen','Arno van Vlokhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214686,'Dennis de Ruiter','René de Winter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214686,'Bas Lange','Bert van der Linden',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-01-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214687,'Team Ballistics','SPIJKENISSE 9',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214687,'Patrick van Hilst','Roland Bos',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214687,'Vincent van den Berg','Arie Beljaars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214687,'Ho Bang Tang','Arie van den Houwen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214687,'Patrick van Hilst','Arie Beljaars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214687,'Vincent van den Berg','Arie van den Houwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214687,'Ho Bang Tang','Roland Bos',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214687,'Ho Bang Tang','Arie Beljaars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214687,'Vincent van den Berg','Roland Bos',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214687,'Patrick van Hilst','Arie van den Houwen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-01-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214688,'SNOOKERPALACE PUTTE','Team Ballistics',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214688,'Jeroen van Driel','Richard van Giesen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214688,'Marc Witkam','Jordy de Groot',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214688,'Jeroen van Driel','Jordy de Groot',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214688,'Walter Ketelaars','Richard van Giesen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214688,'Walter Ketelaars','Jordy de Groot',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214688,'Marc Witkam','Richard van Giesen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-01-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214690,'THE GREEN SENSATIONS','SNOOKERCAFE 8',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214690,'Michael van der Wulp','Peter Vos',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214690,'Jeroen Gode','Roeland van Schie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214690,'Jeffrey de Wijs','Alexander Stolk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214690,'Michael van der Wulp','Roeland van Schie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214690,'Jeroen Gode','Alexander Stolk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214690,'Jeffrey de Wijs','Peter Vos',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214690,'Jeffrey de Wijs','Roeland van Schie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214690,'Jeroen Gode','Peter Vos',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214690,'Michael van der Wulp','Alexander Stolk',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-01-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),232260,'Team Ballistics','SNOOKERPALACE PUTTE',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232260,'Jordy de Groot','Marc Witkam',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232260,'Ho Bang Tang','Jeroen van Driel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232260,'Jordy de Groot','Jeroen van Driel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232260,'Ho Bang Tang','Sien Hoppenbrouwers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232260,'Ho Bang Tang','Marc Witkam',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232260,'Jordy de Groot','Sien Hoppenbrouwers',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-01-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214693,'SNOOKERCAFE 8','REYERBOS 4',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214693,'Peter Vos','Arno van Vlokhoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214693,'Alexander Stolk','Gozewijn van Laatum',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214693,'Willem Poot','Robert van Dam',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214693,'Peter Vos','Gozewijn van Laatum',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214693,'Alexander Stolk','Robert van Dam',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214693,'Willem Poot','Arno van Vlokhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214693,'Willem Poot','Gozewijn van Laatum',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214693,'Alexander Stolk','Arno van Vlokhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214693,'Peter Vos','Robert van Dam',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-01-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214695,'Team Ballistics','THE GREEN SENSATIONS',9,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214695,'Vincent van den Berg','Michael van der Wulp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214695,'Richard van Giesen','Jeroen Gode',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214695,'Vincent van den Berg','Jeroen Gode',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214695,'Richard van Giesen','Dennis van der Marel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214695,'Richard van Giesen','Michael van der Wulp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214695,'Vincent van den Berg','Dennis van der Marel',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('28-01-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214698,'REYERBOS 4','Team Ballistics',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214698,'Robert van Dam','Ho Bang Tang',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214698,'René de Winter','Patrick van Hilst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214698,'Robert van Dam','Patrick van Hilst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214698,'Arno van Vlokhoven','Ho Bang Tang',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214698,'Arno van Vlokhoven','Patrick van Hilst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214698,'René de Winter','Ho Bang Tang',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-02-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214701,'SPIJKENISSE 9','THE GREEN SENSATIONS',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214701,'Arie van den Houwen','Dennis van der Marel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214701,'Patrick Beljaars','Michael van der Wulp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214701,'Remco van Brenkelen','Roel Pet',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214701,'Arie van den Houwen','Michael van der Wulp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214701,'Patrick Beljaars','Roel Pet',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214701,'Remco van Brenkelen','Dennis van der Marel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214701,'Remco van Brenkelen','Michael van der Wulp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214701,'Patrick Beljaars','Dennis van der Marel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214701,'Arie van den Houwen','Roel Pet',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-02-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214702,'Team Ballistics','Spijkenisse Quattro',9,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214702,'Vincent van den Berg','Leslie van Leeuwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214702,'Richard van Giesen','Bas Lange',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214702,'Vincent van den Berg','Bas Lange',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214702,'Richard van Giesen','Dennis de Ruiter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214702,'Richard van Giesen','Leslie van Leeuwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214702,'Vincent van den Berg','Dennis de Ruiter',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-02-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214705,'THE GREEN SENSATIONS','SNOOKERPALACE PUTTE',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214705,'Roland van der Wulp','Peter de Brie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214705,'Jeroen Gode','Walter Ketelaars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214705,'Michael van der Wulp','Walter Ketelaars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214705,'Jeroen Gode','Peter de Brie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214705,'Michael van der Wulp','Peter de Brie',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214705,'Roland van der Wulp','Walter Ketelaars',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-02-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214706,'REYERBOS 4','SPIJKENISSE 9',9,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214706,'Gozewijn van Laatum','Roland Bos',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214706,'Robert van Dam','Rob van Doorn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214706,'René de Winter','Arie Beljaars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214706,'Gozewijn van Laatum','Rob van Doorn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214706,'Robert van Dam','Arie Beljaars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214706,'René de Winter','Roland Bos',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214706,'René de Winter','Rob van Doorn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214706,'Robert van Dam','Roland Bos',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214706,'Gozewijn van Laatum','Arie Beljaars',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-02-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214707,'SNOOKERCAFE 8','Team Ballistics',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214707,'Peter Vos','Jordy de Groot',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214707,'Roeland van Schie','Ho Bang Tang',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214707,'Wim Daens','Patrick van Hilst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214707,'Peter Vos','Ho Bang Tang',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214707,'Roeland van Schie','Patrick van Hilst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214707,'Wim Daens','Jordy de Groot',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214707,'Wim Daens','Ho Bang Tang',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214707,'Roeland van Schie','Jordy de Groot',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214707,'Peter Vos','Patrick van Hilst',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-02-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214709,'Spijkenisse Quattro','SPIJKENISSE 9',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214709,'Bas Lange','Rob van Doorn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214709,'Dennis de Ruiter','Patrick Beljaars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214709,'Leslie van Leeuwen','Remco van Brenkelen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214709,'Bas Lange','Patrick Beljaars',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214709,'Dennis de Ruiter','Remco van Brenkelen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214709,'Leslie van Leeuwen','Rob van Doorn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214709,'Leslie van Leeuwen','Patrick Beljaars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214709,'Dennis de Ruiter','Rob van Doorn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214709,'Bas Lange','Remco van Brenkelen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-02-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214711,'Spijkenisse Quattro','SNOOKERCAFE 8',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214711,'Bas Lange','Peter Vos',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214711,'Marcel Paulus','Wim Daens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214711,'Leslie van Leeuwen','Wim Daens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214711,'Marcel Paulus','Peter Vos',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214711,'Leslie van Leeuwen','Peter Vos',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214711,'Bas Lange','Wim Daens',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-03-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214712,'SNOOKERPALACE PUTTE','Spijkenisse Quattro',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214712,'Peter van Someren','Leslie van Leeuwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214712,'Marc Witkam','Marcel Paulus',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214712,'Marc Bruijne','Dennis de Ruiter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214712,'Peter van Someren','Marcel Paulus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214712,'Marc Witkam','Dennis de Ruiter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214712,'Marc Bruijne','Leslie van Leeuwen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214712,'Marc Bruijne','Marcel Paulus',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214712,'Marc Witkam','Leslie van Leeuwen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214712,'Peter van Someren','Dennis de Ruiter',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-03-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214714,'THE GREEN SENSATIONS','REYERBOS 4',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214714,'Michael van der Wulp','Arno van Vlokhoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214714,'Roel Pet','René de Winter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214714,'Jeroen Hofmeester','Robert van Dam',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214714,'Michael van der Wulp','René de Winter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214714,'Roel Pet','Robert van Dam',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214714,'Jeroen Hofmeester','Arno van Vlokhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214714,'Jeroen Hofmeester','René de Winter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214714,'Roel Pet','Arno van Vlokhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214714,'Michael van der Wulp','Robert van Dam',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-03-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214716,'SNOOKERCAFE 8','SPIJKENISSE 9',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-03-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214718,'Spijkenisse Quattro','THE GREEN SENSATIONS',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214718,'Bas Lange','Michael van der Wulp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214718,'Dennis de Ruiter','Roland van der Wulp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214718,'Marcel Paulus','Rick van den Berg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214718,'Bas Lange','Roland van der Wulp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214718,'Dennis de Ruiter','Rick van den Berg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214718,'Marcel Paulus','Michael van der Wulp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214718,'Marcel Paulus','Roland van der Wulp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214718,'Dennis de Ruiter','Michael van der Wulp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214718,'Bas Lange','Rick van den Berg',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('29-03-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214720,'SNOOKERPALACE PUTTE','SNOOKERCAFE 8',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214720,'Peter de Brie','Alexander Stolk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214720,'Jeroen van Driel','Peter Vos',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214720,'Domingo Peeters','Willem Poot',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214720,'Peter de Brie','Peter Vos',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214720,'Jeroen van Driel','Willem Poot',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214720,'Domingo Peeters','Alexander Stolk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214720,'Domingo Peeters','Peter Vos',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214720,'Jeroen van Driel','Alexander Stolk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214720,'Peter de Brie','Willem Poot',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('31-03-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214722,'SPIJKENISSE 9','Team Ballistics',0,9);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214722,'Remco van Brenkelen','Patrick van Hilst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214722,'Rob van Doorn','Jordy de Groot',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214722,'Remco van Brenkelen','Jordy de Groot',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214722,'Patrick Beljaars','Patrick van Hilst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214722,'Patrick Beljaars','Jordy de Groot',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214722,'Rob van Doorn','Patrick van Hilst',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-04-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214724,'SNOOKERCAFE 8','THE GREEN SENSATIONS',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214724,'Peter Vos','Jeroen Gode',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214724,'Willem Poot','Roland van der Wulp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214724,'Roeland van Schie','Jeffrey de Wijs',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214724,'Peter Vos','Roland van der Wulp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214724,'Willem Poot','Jeffrey de Wijs',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214724,'Roeland van Schie','Jeroen Gode',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214724,'Roeland van Schie','Roland van der Wulp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214724,'Willem Poot','Jeroen Gode',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214724,'Peter Vos','Jeffrey de Wijs',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-04-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),232658,'Spijkenisse Quattro','SNOOKERPALACE PUTTE',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232658,'Bas Lange','Walter Ketelaars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232658,'Dennis de Ruiter','Marc Bruijne',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232658,'Marcel Paulus','Sien Hoppenbrouwers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232658,'Bas Lange','Marc Bruijne',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232658,'Dennis de Ruiter','Sien Hoppenbrouwers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232658,'Marcel Paulus','Walter Ketelaars',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232658,'Marcel Paulus','Marc Bruijne',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232658,'Dennis de Ruiter','Walter Ketelaars',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232658,'Bas Lange','Sien Hoppenbrouwers',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-04-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214727,'Team Ballistics','SNOOKERPALACE PUTTE',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-04-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214730,'THE GREEN SENSATIONS','Team Ballistics',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214730,'Jeroen Hofmeester','Roy de Lepper',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214730,'Michael van der Wulp','Patrick van Hilst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214730,'Jeroen Hofmeester','Patrick van Hilst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214730,'Dennis van der Marel','Roy de Lepper',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214730,'Dennis van der Marel','Patrick van Hilst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214730,'Michael van der Wulp','Roy de Lepper',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-04-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),233775,'REYERBOS 4','SNOOKERPALACE PUTTE',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233775,'Bert van der Linden','Jeroen van Driel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233775,'René de Winter','Sien Hoppenbrouwers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233775,'René de Winter','Jeroen van Driel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233775,'Bert van der Linden','Sien Hoppenbrouwers',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-05-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214732,'SNOOKERCAFE 8','Spijkenisse Quattro',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-05-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),233903,'SNOOKERPALACE PUTTE','SPIJKENISSE 9',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233903,'Jeroen van Driel','Arie Beljaars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233903,'Peter de Brie','Patrick Beljaars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233903,'David Smeekens','Arie van den Houwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233903,'Jeroen van Driel','Patrick Beljaars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233903,'Peter de Brie','Arie van den Houwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233903,'David Smeekens','Arie Beljaars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233903,'David Smeekens','Patrick Beljaars',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233903,'Peter de Brie','Arie Beljaars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233903,'Jeroen van Driel','Arie van den Houwen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-05-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),233902,'SPIJKENISSE 9','SNOOKERPALACE PUTTE',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233902,'Arie van den Houwen','Peter de Brie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233902,'Arie Beljaars','David Smeekens',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233902,'Patrick Beljaars','Jeroen van Driel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233902,'Arie van den Houwen','David Smeekens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233902,'Arie Beljaars','Jeroen van Driel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233902,'Patrick Beljaars','Peter de Brie',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233902,'Patrick Beljaars','David Smeekens',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233902,'Arie Beljaars','Peter de Brie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233902,'Arie van den Houwen','Jeroen van Driel',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-05-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214735,'Team Ballistics','REYERBOS 4',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214735,'Richard van Giesen','Gozewijn van Laatum',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214735,'Vincent van den Berg','Robert van Dam',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214735,'Richard van Giesen','Robert van Dam',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214735,'Vincent van den Berg','René de Winter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214735,'Vincent van den Berg','Gozewijn van Laatum',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214735,'Richard van Giesen','René de Winter',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-05-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214737,'Spijkenisse Quattro','Team Ballistics',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214737,'Bas Lange','Jordy de Groot',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214737,'Leslie van Leeuwen','Ho Bang Tang',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214737,'Bas Lange','Ho Bang Tang',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214737,'Dennis de Ruiter','Jordy de Groot',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214737,'Dennis de Ruiter','Ho Bang Tang',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214737,'Leslie van Leeuwen','Jordy de Groot',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-05-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214738,'THE GREEN SENSATIONS','SPIJKENISSE 9',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214738,'Jeffrey de Wijs','Arie van den Houwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214738,'Jeroen Gode','Patrick Beljaars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214738,'Jeroen Hofmeester','Arie Beljaars',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214738,'Jeffrey de Wijs','Patrick Beljaars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214738,'Jeroen Gode','Arie Beljaars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214738,'Jeroen Hofmeester','Arie van den Houwen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214738,'Jeroen Hofmeester','Patrick Beljaars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214738,'Jeroen Gode','Arie van den Houwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214738,'Jeffrey de Wijs','Arie Beljaars',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-05-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214740,'SNOOKERPALACE PUTTE','THE GREEN SENSATIONS',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214740,'Marc Witkam','Michael van der Wulp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214740,'Marc Bruijne','Roland van der Wulp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214740,'Walter Ketelaars','Jeffrey de Wijs',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214740,'Marc Witkam','Roland van der Wulp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214740,'Marc Bruijne','Jeffrey de Wijs',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214740,'Walter Ketelaars','Michael van der Wulp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214740,'Walter Ketelaars','Roland van der Wulp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214740,'Marc Bruijne','Michael van der Wulp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214740,'Marc Witkam','Jeffrey de Wijs',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-05-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 6' and ssn_id like '2010%'),214742,'SPIJKENISSE 9','REYERBOS 4',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214742,'Patrick Beljaars','Arno van Vlokhoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214742,'Arie Beljaars','René de Winter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214742,'Arie van den Houwen','Bert van der Linden',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214742,'Patrick Beljaars','René de Winter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214742,'Arie Beljaars','Bert van der Linden',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214742,'Arie van den Houwen','Arno van Vlokhoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214742,'Arie van den Houwen','René de Winter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214742,'Arie Beljaars','Arno van Vlokhoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214742,'Patrick Beljaars','Bert van der Linden',0,1);
