delete from cm_match_details where game_id in (select game_id from cm_matches where cpn_id = (select id from cm_competitions where name = '2e divisie poule 5' and ssn_id like '2010%'));
delete from cm_matches where cpn_id = (select id from cm_competitions where name = '2e divisie poule 5' and ssn_id like '2010%');
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-09-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 5' and ssn_id like '2010%'),214574,'De Dieze 4','VEGHEL 2',1,8);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-09-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 5' and ssn_id like '2010%'),214575,'MAGIC BALLS','Ames 1 The Bluez',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214575,'Marcel Potters','Ed van de Hagen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214575,'Wally Sparidans','Eric Scalé',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214575,'Johan Erven','Hans Moerkerk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214575,'Marcel Potters','Eric Scalé',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214575,'Wally Sparidans','Hans Moerkerk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214575,'Johan Erven','Ed van de Hagen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214575,'Johan Erven','Eric Scalé',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214575,'Wally Sparidans','Ed van de Hagen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214575,'Marcel Potters','Hans Moerkerk',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('29-09-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 5' and ssn_id like '2010%'),214578,'Ames 1 The Bluez','De Dieze 4',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214578,'Hans Moerkerk','Richard Belzer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214578,'Ed van de Hagen','Jo van Dinther',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214578,'Eric Scalé','Bart Sprengers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214578,'Hans Moerkerk','Jo van Dinther',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214578,'Ed van de Hagen','Bart Sprengers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214578,'Eric Scalé','Richard Belzer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214578,'Eric Scalé','Jo van Dinther',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214578,'Ed van de Hagen','Richard Belzer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214578,'Hans Moerkerk','Bart Sprengers',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-10-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 5' and ssn_id like '2010%'),214580,'VEGHEL 2','Ames 1 The Bluez',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214580,'Gertjan Huiskes','Ed van de Hagen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214580,'Gertjan Huiskes','Eric Scalé',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214580,'Gertjan Huiskes','Ralf Schmitz',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-10-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 5' and ssn_id like '2010%'),214582,'Ames 2 De Zwervers','MAGIC BALLS',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214582,'Math van der Linden','Roeland Houben',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214582,'Ko van Zeeland','Steve Binns',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214582,'Wim Manders','Wally Sparidans',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214582,'Math van der Linden','Steve Binns',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214582,'Ko van Zeeland','Wally Sparidans',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214582,'Wim Manders','Roeland Houben',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214582,'Wim Manders','Steve Binns',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214582,'Ko van Zeeland','Roeland Houben',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214582,'Math van der Linden','Wally Sparidans',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 5' and ssn_id like '2010%'),214585,'De Dieze 4','Ames 2 De Zwervers',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214585,'Henk Laudy','Wim Manders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214585,'Richard Belzer','Frans van Poppel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214585,'Jo van Dinther','Math van der Linden',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214585,'Henk Laudy','Frans van Poppel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214585,'Richard Belzer','Math van der Linden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214585,'Jo van Dinther','Wim Manders',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214585,'Jo van Dinther','Frans van Poppel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214585,'Richard Belzer','Wim Manders',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214585,'Henk Laudy','Math van der Linden',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 5' and ssn_id like '2010%'),214588,'Ames 2 De Zwervers','VEGHEL 2',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214588,'Math van der Linden','Theo van den Anker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214588,'Frans van Poppel','Gertjan Huiskes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214588,'Ko van Zeeland','Theo van den Anker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214588,'Math van der Linden','Gertjan Huiskes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214588,'Frans van Poppel','Theo van den Anker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214588,'Ko van Zeeland','Gertjan Huiskes',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 5' and ssn_id like '2010%'),214590,'MAGIC BALLS','De Dieze 4',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214590,'Johan Erven','Gerard van Rooij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214590,'Steve Binns','Bart Sprengers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214590,'Frans de Laat','Stephan van Rooij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214590,'Johan Erven','Bart Sprengers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214590,'Steve Binns','Stephan van Rooij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214590,'Frans de Laat','Gerard van Rooij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214590,'Frans de Laat','Bart Sprengers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214590,'Steve Binns','Gerard van Rooij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214590,'Johan Erven','Stephan van Rooij',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 5' and ssn_id like '2010%'),214592,'Ames 1 The Bluez','Ames 2 De Zwervers',9,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214592,'Ed van de Hagen','Math van der Linden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214592,'Ralf Schmitz','Wim Manders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214592,'Eric Scalé','Ko van Zeeland',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214592,'Ed van de Hagen','Wim Manders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214592,'Ralf Schmitz','Ko van Zeeland',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214592,'Eric Scalé','Math van der Linden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214592,'Eric Scalé','Wim Manders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214592,'Ralf Schmitz','Math van der Linden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214592,'Ed van de Hagen','Ko van Zeeland',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 5' and ssn_id like '2010%'),214593,'VEGHEL 2','MAGIC BALLS',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214593,'Gertjan Huiskes','Steve Binns',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214593,'Carlo Hommeles','Wally Sparidans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214593,'Gertjan Huiskes','Wally Sparidans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214593,'Carlo Hommeles','Roeland Houben',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214593,'Carlo Hommeles','Steve Binns',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214593,'Gertjan Huiskes','Roeland Houben',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('01-12-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 5' and ssn_id like '2010%'),214595,'Ames 1 The Bluez','MAGIC BALLS',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214595,'Hans Moerkerk','Steve Binns',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214595,'Ralf Schmitz','Wally Sparidans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214595,'Ed van de Hagen','Roeland Houben',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214595,'Hans Moerkerk','Wally Sparidans',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214595,'Ralf Schmitz','Roeland Houben',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214595,'Ed van de Hagen','Steve Binns',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214595,'Ed van de Hagen','Wally Sparidans',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214595,'Ralf Schmitz','Steve Binns',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214595,'Hans Moerkerk','Roeland Houben',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('01-12-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 5' and ssn_id like '2010%'),214596,'VEGHEL 2','De Dieze 4',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214596,'Theo van den Anker','Richard Belzer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214596,'Gertjan Huiskes','Stephan van Rooij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214596,'Theo van den Anker','Stephan van Rooij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214596,'Gertjan Huiskes','Bart Sprengers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214596,'Gertjan Huiskes','Richard Belzer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214596,'Theo van den Anker','Bart Sprengers',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-12-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 5' and ssn_id like '2010%'),214598,'De Dieze 4','Ames 1 The Bluez',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214598,'Henk Laudy','Ed van de Hagen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214598,'Gerard van Rooij','Ralf Schmitz',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214598,'Richard Belzer','Eric Scalé',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214598,'Henk Laudy','Ralf Schmitz',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214598,'Gerard van Rooij','Eric Scalé',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214598,'Richard Belzer','Ed van de Hagen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214598,'Richard Belzer','Ralf Schmitz',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214598,'Gerard van Rooij','Ed van de Hagen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214598,'Henk Laudy','Eric Scalé',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-01-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 5' and ssn_id like '2010%'),214602,'Ames 1 The Bluez','VEGHEL 2',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214602,'Ralf Schmitz','Gertjan Huiskes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214602,'Eric Scalé','Theo van den Anker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214602,'Ed van de Hagen','Pieter Anne van Melis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214602,'Ralf Schmitz','Theo van den Anker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214602,'Eric Scalé','Pieter Anne van Melis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214602,'Ed van de Hagen','Gertjan Huiskes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214602,'Ed van de Hagen','Theo van den Anker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214602,'Eric Scalé','Gertjan Huiskes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214602,'Ralf Schmitz','Pieter Anne van Melis',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-01-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 5' and ssn_id like '2010%'),214605,'MAGIC BALLS','Ames 2 De Zwervers',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-01-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 5' and ssn_id like '2010%'),214606,'Ames 2 De Zwervers','De Dieze 4',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214606,'Frans van Poppel','Gerard van Rooij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214606,'Math van der Linden','Stephan van Rooij',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214606,'Wim Manders','Bart Sprengers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214606,'Frans van Poppel','Stephan van Rooij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214606,'Math van der Linden','Bart Sprengers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214606,'Wim Manders','Gerard van Rooij',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214606,'Wim Manders','Stephan van Rooij',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214606,'Math van der Linden','Gerard van Rooij',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214606,'Frans van Poppel','Bart Sprengers',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-02-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 5' and ssn_id like '2010%'),214609,'De Dieze 4','MAGIC BALLS',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-02-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 5' and ssn_id like '2010%'),214611,'VEGHEL 2','Ames 2 De Zwervers',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214611,'Carlo Hommeles','Anthony Bisschops',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214611,'Gertjan Huiskes','Math van der Linden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214611,'Carlo Hommeles','Math van der Linden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214611,'Gertjan Huiskes','Ko van Zeeland',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214611,'Gertjan Huiskes','Anthony Bisschops',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214611,'Carlo Hommeles','Ko van Zeeland',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-02-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 5' and ssn_id like '2010%'),214612,'Ames 2 De Zwervers','Ames 1 The Bluez',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214612,'Math van der Linden','Ed van de Hagen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214612,'Frans van Poppel','Eric Scalé',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214612,'Anthony Bisschops','Hans Moerkerk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214612,'Math van der Linden','Eric Scalé',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214612,'Frans van Poppel','Hans Moerkerk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214612,'Anthony Bisschops','Ed van de Hagen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214612,'Anthony Bisschops','Eric Scalé',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214612,'Frans van Poppel','Ed van de Hagen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214612,'Math van der Linden','Hans Moerkerk',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-02-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 5' and ssn_id like '2010%'),214614,'MAGIC BALLS','VEGHEL 2',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214614,'Steve Binns','Theo van den Anker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214614,'Roeland Houben','Gertjan Huiskes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214614,'Johan Erven','Gertjan Huiskes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214614,'Roeland Houben','Theo van den Anker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214614,'Johan Erven','Theo van den Anker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214614,'Steve Binns','Gertjan Huiskes',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-02-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 5' and ssn_id like '2010%'),214616,'De Dieze 4','VEGHEL 2',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-02-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 5' and ssn_id like '2010%'),214617,'MAGIC BALLS','Ames 1 The Bluez',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214617,'Johan Erven','Eric Scalé',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214617,'Roeland Houben','Ed van de Hagen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214617,'Frans de Laat','Hans Moerkerk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214617,'Johan Erven','Ed van de Hagen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214617,'Roeland Houben','Hans Moerkerk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214617,'Frans de Laat','Eric Scalé',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214617,'Frans de Laat','Ed van de Hagen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214617,'Roeland Houben','Eric Scalé',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214617,'Johan Erven','Hans Moerkerk',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-03-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 5' and ssn_id like '2010%'),214620,'Ames 1 The Bluez','De Dieze 4',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214620,'Ed van de Hagen','Bart Sprengers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214620,'Eric Scalé','Jo van Dinther',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214620,'Ralf Schmitz','Henk Laudy',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214620,'Ed van de Hagen','Jo van Dinther',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214620,'Eric Scalé','Henk Laudy',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214620,'Ralf Schmitz','Bart Sprengers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214620,'Ralf Schmitz','Jo van Dinther',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214620,'Eric Scalé','Bart Sprengers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214620,'Ed van de Hagen','Henk Laudy',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('30-03-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 5' and ssn_id like '2010%'),214622,'VEGHEL 2','Ames 1 The Bluez',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214622,'Carlo Hommeles','Ralf Schmitz',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214622,'Han van Gemert','Eric Scalé',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214622,'Gertjan Huiskes','Hans Moerkerk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214622,'Carlo Hommeles','Eric Scalé',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214622,'Han van Gemert','Hans Moerkerk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214622,'Gertjan Huiskes','Ralf Schmitz',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214622,'Gertjan Huiskes','Eric Scalé',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214622,'Han van Gemert','Ralf Schmitz',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214622,'Carlo Hommeles','Hans Moerkerk',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-04-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 5' and ssn_id like '2010%'),214624,'Ames 2 De Zwervers','MAGIC BALLS',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214624,'Frans van Poppel','Steve Binns',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214624,'Wim Manders','Roeland Houben',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214624,'Anthony Bisschops','Wally Sparidans',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214624,'Frans van Poppel','Roeland Houben',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214624,'Wim Manders','Wally Sparidans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214624,'Anthony Bisschops','Steve Binns',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214624,'Anthony Bisschops','Roeland Houben',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214624,'Wim Manders','Steve Binns',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214624,'Frans van Poppel','Wally Sparidans',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-04-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 5' and ssn_id like '2010%'),214627,'De Dieze 4','Ames 2 De Zwervers',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214627,'Jo van Dinther','Math van der Linden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214627,'Stephan van Rooij','Ko van Zeeland',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214627,'Gerard van Rooij','Frans van Poppel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214627,'Jo van Dinther','Ko van Zeeland',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214627,'Stephan van Rooij','Frans van Poppel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214627,'Gerard van Rooij','Math van der Linden',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214627,'Gerard van Rooij','Ko van Zeeland',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214627,'Stephan van Rooij','Math van der Linden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214627,'Jo van Dinther','Frans van Poppel',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-05-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 5' and ssn_id like '2010%'),214632,'MAGIC BALLS','De Dieze 4',9,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214632,'Roeland Houben','Gerard van Rooij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214632,'Johan Erven','Bart Sprengers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214632,'Wally Sparidans','Stephan van Rooij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214632,'Roeland Houben','Bart Sprengers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214632,'Johan Erven','Stephan van Rooij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214632,'Wally Sparidans','Gerard van Rooij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214632,'Wally Sparidans','Bart Sprengers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214632,'Johan Erven','Gerard van Rooij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214632,'Roeland Houben','Stephan van Rooij',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-05-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 5' and ssn_id like '2010%'),214634,'Ames 1 The Bluez','Ames 2 De Zwervers',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214634,'Hans Moerkerk','Frans van Poppel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214634,'Ed van de Hagen','Math van der Linden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214634,'Eric Scalé','Anthony Bisschops',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214634,'Hans Moerkerk','Math van der Linden',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214634,'Ed van de Hagen','Anthony Bisschops',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214634,'Eric Scalé','Frans van Poppel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214634,'Eric Scalé','Math van der Linden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214634,'Ed van de Hagen','Frans van Poppel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214634,'Hans Moerkerk','Anthony Bisschops',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-05-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 5' and ssn_id like '2010%'),214635,'VEGHEL 2','MAGIC BALLS',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214635,'Theo van den Anker','Steve Binns',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214635,'Gertjan Huiskes','Wally Sparidans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214635,'Carlo Hommeles','Roeland Houben',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214635,'Theo van den Anker','Wally Sparidans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214635,'Gertjan Huiskes','Roeland Houben',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214635,'Carlo Hommeles','Steve Binns',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214635,'Carlo Hommeles','Wally Sparidans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214635,'Gertjan Huiskes','Steve Binns',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214635,'Theo van den Anker','Roeland Houben',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-05-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e divisie poule 5' and ssn_id like '2010%'),233993,'Ames 2 De Zwervers','VEGHEL 2',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233993,'Ko van Zeeland','Theo van den Anker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233993,'Wim Manders','Gertjan Huiskes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233993,'Frans van Poppel','Han van Gemert',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233993,'Ko van Zeeland','Gertjan Huiskes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233993,'Wim Manders','Han van Gemert',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233993,'Frans van Poppel','Theo van den Anker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233993,'Frans van Poppel','Gertjan Huiskes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233993,'Wim Manders','Theo van den Anker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233993,'Ko van Zeeland','Han van Gemert',0,1);
