delete from cm_match_details where game_id in (select game_id from cm_matches where cpn_id = (select id from cm_competitions where name = '2e klasse poule 1' and ssn_id like '2010%'));
delete from cm_matches where cpn_id = (select id from cm_competitions where name = '2e klasse poule 1' and ssn_id like '2010%');
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-09-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 1' and ssn_id like '2010%'),214210,'Level one','THE FIFTH PLANET 5',9,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214210,'Chi Chui','Fred Wurtz',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214210,'Tommy Wong','Thom Leenders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214210,'Iven Lo','Cor Wever',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214210,'Chi Chui','Thom Leenders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214210,'Tommy Wong','Cor Wever',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214210,'Iven Lo','Fred Wurtz',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214210,'Iven Lo','Thom Leenders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214210,'Tommy Wong','Fred Wurtz',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214210,'Chi Chui','Cor Wever',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-09-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 1' and ssn_id like '2010%'),214212,'Team 1048','Foul 7 and the Duvels',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('28-09-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 1' and ssn_id like '2010%'),214214,'THE FIFTH PLANET 5','Team 1048',8,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('30-09-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 1' and ssn_id like '2010%'),214215,'Sneeuwwitje e/d 7 dwergen','Level one',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-10-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 1' and ssn_id like '2010%'),214217,'Foul 7 and the Duvels','THE FIFTH PLANET 5',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214217,'Hans Ragas','Fred Wurtz',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214217,'Marnix Renne','Cor Wever',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214217,'Henny Piet','Peter Fokker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214217,'Hans Ragas','Cor Wever',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214217,'Marnix Renne','Peter Fokker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214217,'Henny Piet','Fred Wurtz',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214217,'Henny Piet','Cor Wever',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214217,'Marnix Renne','Fred Wurtz',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214217,'Hans Ragas','Peter Fokker',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-10-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 1' and ssn_id like '2010%'),214218,'Team 1048','Sneeuwwitje e/d 7 dwergen',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214218,'Krystel Simaleavich','Ronald Peeters',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214218,'Pieter van Tilburg','Hennie van Houten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214218,'Juan Moreno','René Verheyden',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214218,'Krystel Simaleavich','Hennie van Houten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214218,'Pieter van Tilburg','René Verheyden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214218,'Juan Moreno','Ronald Peeters',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214218,'Juan Moreno','Hennie van Houten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214218,'Pieter van Tilburg','Ronald Peeters',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214218,'Krystel Simaleavich','René Verheyden',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-10-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 1' and ssn_id like '2010%'),214221,'Sneeuwwitje e/d 7 dwergen','Foul 7 and the Duvels',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 1' and ssn_id like '2010%'),214223,'THE FIFTH PLANET 5','Sneeuwwitje e/d 7 dwergen',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214223,'Marcel Groenland','Robert Tump',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214223,'Peter Fokker','Rob Kanninga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214223,'Thom Leenders','René Verheyden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214223,'Marcel Groenland','Rob Kanninga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214223,'Peter Fokker','René Verheyden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214223,'Thom Leenders','Robert Tump',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214223,'Thom Leenders','Rob Kanninga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214223,'Peter Fokker','Robert Tump',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214223,'Marcel Groenland','René Verheyden',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 1' and ssn_id like '2010%'),214225,'Level one','Team 1048',9,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214225,'King Tse','Krystel Simaleavich',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214225,'Thim Wong','Juan Moreno',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214225,'Tommy Wong','Wouter Kager',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214225,'King Tse','Juan Moreno',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214225,'Thim Wong','Wouter Kager',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214225,'Tommy Wong','Krystel Simaleavich',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214225,'Tommy Wong','Juan Moreno',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214225,'Thim Wong','Krystel Simaleavich',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214225,'King Tse','Wouter Kager',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 1' and ssn_id like '2010%'),214229,'Foul 7 and the Duvels','Level one',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214229,'Kilian Steen','Tommy Wong',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214229,'Alex van Hensbergen','King Tse',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214229,'Hans Ragas','Chi Chui',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214229,'Kilian Steen','King Tse',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214229,'Alex van Hensbergen','Chi Chui',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214229,'Hans Ragas','Tommy Wong',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214229,'Hans Ragas','King Tse',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214229,'Alex van Hensbergen','Tommy Wong',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214229,'Kilian Steen','Chi Chui',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('30-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 1' and ssn_id like '2010%'),214231,'THE FIFTH PLANET 5','Level one',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214231,'Cor Wever','Iven Lo',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214231,'Peter Fokker','Chi Chui',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214231,'Fred Wurtz','King Tse',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214231,'Cor Wever','Chi Chui',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214231,'Peter Fokker','King Tse',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214231,'Fred Wurtz','Iven Lo',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214231,'Fred Wurtz','Chi Chui',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214231,'Peter Fokker','Iven Lo',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214231,'Cor Wever','King Tse',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('30-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 1' and ssn_id like '2010%'),214232,'Foul 7 and the Duvels','Team 1048',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-12-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 1' and ssn_id like '2010%'),214234,'Level one','Sneeuwwitje e/d 7 dwergen',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214234,'Chi Chui','Ronald Peeters',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214234,'King Tse','Robert Tump',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214234,'Iven Lo','Rob Kanninga',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214234,'Chi Chui','Robert Tump',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214234,'King Tse','Rob Kanninga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214234,'Iven Lo','Ronald Peeters',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214234,'Iven Lo','Robert Tump',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214234,'King Tse','Ronald Peeters',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214234,'Chi Chui','Rob Kanninga',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-12-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 1' and ssn_id like '2010%'),214236,'Team 1048','THE FIFTH PLANET 5',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-01-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 1' and ssn_id like '2010%'),214238,'THE FIFTH PLANET 5','Foul 7 and the Duvels',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214238,'Peter Fokker','Hans Ragas',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214238,'Cor Wever','Marnix Renne',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214238,'Thom Leenders','Kilian Steen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214238,'Peter Fokker','Marnix Renne',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214238,'Cor Wever','Kilian Steen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214238,'Thom Leenders','Hans Ragas',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214238,'Thom Leenders','Marnix Renne',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214238,'Cor Wever','Hans Ragas',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214238,'Peter Fokker','Kilian Steen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-01-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 1' and ssn_id like '2010%'),214239,'Sneeuwwitje e/d 7 dwergen','Team 1048',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214239,'Hennie van Houten','Erik Veerman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214239,'Rob Kanninga','Pieter van Tilburg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214239,'Ronald Peeters','Krystel Simaleavich',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214239,'Hennie van Houten','Pieter van Tilburg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214239,'Rob Kanninga','Krystel Simaleavich',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214239,'Ronald Peeters','Erik Veerman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214239,'Ronald Peeters','Pieter van Tilburg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214239,'Rob Kanninga','Erik Veerman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214239,'Hennie van Houten','Krystel Simaleavich',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-01-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 1' and ssn_id like '2010%'),214245,'Sneeuwwitje e/d 7 dwergen','THE FIFTH PLANET 5',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214245,'Rob Kanninga','Thom Leenders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214245,'Berend Bruins','Peter Fokker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214245,'René Verheyden','Fred Wurtz',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214245,'Rob Kanninga','Peter Fokker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214245,'Berend Bruins','Fred Wurtz',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214245,'René Verheyden','Thom Leenders',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214245,'René Verheyden','Peter Fokker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214245,'Berend Bruins','Thom Leenders',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214245,'Rob Kanninga','Fred Wurtz',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('25-01-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 1' and ssn_id like '2010%'),231825,'Foul 7 and the Duvels','Sneeuwwitje e/d 7 dwergen',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-02-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 1' and ssn_id like '2010%'),214248,'Level one','Foul 7 and the Duvels',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-02-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 1' and ssn_id like '2010%'),214251,'Level one','THE FIFTH PLANET 5',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214251,'King Tse','Marcel Groenland',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214251,'Chi Chui','Peter Fokker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214251,'Iven Lo','Fred Wurtz',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214251,'King Tse','Peter Fokker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214251,'Chi Chui','Fred Wurtz',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214251,'Iven Lo','Marcel Groenland',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214251,'Iven Lo','Peter Fokker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214251,'Chi Chui','Marcel Groenland',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214251,'King Tse','Fred Wurtz',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-02-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 1' and ssn_id like '2010%'),214253,'Team 1048','Foul 7 and the Duvels',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-03-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 1' and ssn_id like '2010%'),233055,'Team 1048','Level one',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233055,'Wouter Kager','King Tse',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233055,'Erik Veerman','Chi Chui',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233055,'Juan Moreno','Kenny Chui',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233055,'Wouter Kager','Chi Chui',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233055,'Erik Veerman','Kenny Chui',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233055,'Juan Moreno','King Tse',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233055,'Juan Moreno','Chi Chui',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233055,'Erik Veerman','King Tse',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233055,'Wouter Kager','Kenny Chui',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-03-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 1' and ssn_id like '2010%'),214257,'THE FIFTH PLANET 5','Team 1048',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-03-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 1' and ssn_id like '2010%'),214258,'Sneeuwwitje e/d 7 dwergen','Level one',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214258,'Ronald Peeters','Chi Chui',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214258,'Rob Kanninga','Iven Lo',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214258,'Robert Tump','King Tse',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214258,'Ronald Peeters','Iven Lo',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214258,'Rob Kanninga','King Tse',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214258,'Robert Tump','Chi Chui',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214258,'Robert Tump','Iven Lo',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214258,'Rob Kanninga','Chi Chui',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214258,'Ronald Peeters','King Tse',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-04-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 1' and ssn_id like '2010%'),214264,'Sneeuwwitje e/d 7 dwergen','Foul 7 and the Duvels',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214264,'Robert Tump','Alex van Hensbergen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214264,'Ronald Peeters','Henny Piet',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214264,'René Verheyden','Kilian Steen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214264,'Robert Tump','Henny Piet',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214264,'Ronald Peeters','Kilian Steen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214264,'René Verheyden','Alex van Hensbergen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214264,'René Verheyden','Henny Piet',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214264,'Ronald Peeters','Alex van Hensbergen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214264,'Robert Tump','Kilian Steen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-04-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 1' and ssn_id like '2010%'),233624,'Team 1048','Sneeuwwitje e/d 7 dwergen',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233624,'Krystel Simaleavich','Rob Kanninga',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233624,'Erik Veerman','Ronald Peeters',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233624,'Juan Moreno','Robert Tump',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233624,'Krystel Simaleavich','Ronald Peeters',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233624,'Erik Veerman','Robert Tump',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233624,'Juan Moreno','Rob Kanninga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233624,'Juan Moreno','Ronald Peeters',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233624,'Erik Veerman','Rob Kanninga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233624,'Krystel Simaleavich','Robert Tump',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-04-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 1' and ssn_id like '2010%'),233559,'THE FIFTH PLANET 5','Sneeuwwitje e/d 7 dwergen',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233559,'Marcel Groenland','René Verheyden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233559,'Peter Fokker','Robert Tump',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233559,'Thom Leenders','Rob Kanninga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233559,'Marcel Groenland','Robert Tump',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233559,'Peter Fokker','Rob Kanninga',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233559,'Thom Leenders','René Verheyden',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233559,'Thom Leenders','Robert Tump',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233559,'Peter Fokker','René Verheyden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233559,'Marcel Groenland','Rob Kanninga',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-05-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 1' and ssn_id like '2010%'),214267,'Level one','Team 1048',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('31-05-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 1' and ssn_id like '2010%'),233997,'Foul 7 and the Duvels','Level one',5,4);
