delete from cm_match_details where game_id in (select game_id from cm_matches where cpn_id = (select id from cm_competitions where name = '2e klasse poule 3' and ssn_id like '2010%'));
delete from cm_matches where cpn_id = (select id from cm_competitions where name = '2e klasse poule 3' and ssn_id like '2010%');
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-09-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 3' and ssn_id like '2010%'),214381,'SNOOKERIJ 6','JUMBO 3',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214381,'David Mourette','Henk Versteeg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214381,'Edwin van Orssagen','Rob Oudshoorn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214381,'Fabian Carrasco','Rob Oudshoorn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214381,'Edwin van Orssagen','Henk Versteeg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214381,'Fabian Carrasco','Henk Versteeg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214381,'David Mourette','Rob Oudshoorn',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-09-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 3' and ssn_id like '2010%'),214383,'HOGEWOERD 2','Jumbo back in business',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214383,'Rogier Wijnans','René Sirre',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214383,'Michiel Peter Sjouke','Jan Hangelbroek',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214383,'Akhi Kalicharan','Eelco van der Meer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214383,'Rogier Wijnans','Jan Hangelbroek',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214383,'Michiel Peter Sjouke','Eelco van der Meer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214383,'Akhi Kalicharan','René Sirre',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214383,'Akhi Kalicharan','Jan Hangelbroek',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214383,'Michiel Peter Sjouke','René Sirre',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214383,'Rogier Wijnans','Eelco van der Meer',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('29-09-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 3' and ssn_id like '2010%'),214387,'JUMBO 3','HOGEWOERD 2',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214387,'Debbie Anthonissen','Rogier Wijnans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214387,'Henk Versteeg','Akhi Kalicharan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214387,'Huibert van de Putte','Michiel Peter Sjouke',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214387,'Debbie Anthonissen','Akhi Kalicharan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214387,'Henk Versteeg','Michiel Peter Sjouke',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214387,'Huibert van de Putte','Rogier Wijnans',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214387,'Huibert van de Putte','Akhi Kalicharan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214387,'Henk Versteeg','Rogier Wijnans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214387,'Debbie Anthonissen','Michiel Peter Sjouke',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('29-09-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 3' and ssn_id like '2010%'),214388,'Jumbo back in business','THE POCKET 2',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214388,'Eelco van der Meer','Marcel van de Oever',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214388,'René Sirre','Johan Keizer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214388,'Ronald Niesthoven','Jaco van Duijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214388,'Eelco van der Meer','Johan Keizer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214388,'René Sirre','Jaco van Duijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214388,'Ronald Niesthoven','Marcel van de Oever',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214388,'Ronald Niesthoven','Johan Keizer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214388,'René Sirre','Marcel van de Oever',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214388,'Eelco van der Meer','Jaco van Duijn',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-10-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 3' and ssn_id like '2010%'),214389,'BSCZ 1','Jumbo back in business',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214389,'Glenn van Polanen','Ronald Niesthoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214389,'Ron Reeuwijk','Arnold Roelen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214389,'Glenn van Polanen','René Sirre',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214389,'Ron Reeuwijk','Ronald Niesthoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214389,'Ron Reeuwijk','René Sirre',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214389,'Glenn van Polanen','Arnold Roelen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-10-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 3' and ssn_id like '2010%'),214390,'THE POCKET 2','JUMBO 3',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214390,'Jaco van Duijn','Rob Oudshoorn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214390,'Thomas Glasbergen','Huibert van de Putte',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214390,'Johan Keizer','Debbie Anthonissen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214390,'Jaco van Duijn','Huibert van de Putte',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214390,'Thomas Glasbergen','Debbie Anthonissen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214390,'Johan Keizer','Rob Oudshoorn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214390,'Johan Keizer','Huibert van de Putte',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214390,'Thomas Glasbergen','Rob Oudshoorn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214390,'Jaco van Duijn','Debbie Anthonissen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-10-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 3' and ssn_id like '2010%'),214393,'SNOOKERIJ 6','HOGEWOERD 2',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214393,'Roger Planje','Akhi Kalicharan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214393,'Edwin van Orssagen','Akhi Kalicharan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214393,'Robert van Nieuwkoop','Akhi Kalicharan',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-10-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 3' and ssn_id like '2010%'),214395,'JUMBO 3','BSCZ 1',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214395,'Rob Oudshoorn','Glenn van Polanen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214395,'Henk Versteeg','Ron Reeuwijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214395,'Rob Oudshoorn','Ron Reeuwijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214395,'Henk Versteeg','Peter den Boer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214395,'Henk Versteeg','Glenn van Polanen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214395,'Rob Oudshoorn','Peter den Boer',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 3' and ssn_id like '2010%'),214398,'Jumbo back in business','JUMBO 3',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214398,'René Sirre','Huibert van de Putte',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214398,'Arnold Roelen','Rob Oudshoorn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214398,'Eelco van der Meer','Rob Oudshoorn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214398,'Arnold Roelen','Huibert van de Putte',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214398,'Eelco van der Meer','Huibert van de Putte',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214398,'René Sirre','Rob Oudshoorn',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 3' and ssn_id like '2010%'),214399,'THE POCKET 2','SNOOKERIJ 6',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214399,'Jaco van Duijn','Mark van Vliet',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214399,'Kees van Duijn','Fabian Carrasco',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214399,'Johan Keizer','David Mourette',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214399,'Jaco van Duijn','Fabian Carrasco',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214399,'Kees van Duijn','David Mourette',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214399,'Johan Keizer','Mark van Vliet',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214399,'Johan Keizer','Fabian Carrasco',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214399,'Kees van Duijn','Mark van Vliet',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214399,'Jaco van Duijn','David Mourette',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 3' and ssn_id like '2010%'),226156,'THE POCKET 2','BSCZ 1',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(226156,'Marcel van de Oever','Peter den Boer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(226156,'Thomas Glasbergen','Ron Reeuwijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(226156,'Marcel van de Oever','Ron Reeuwijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(226156,'Thomas Glasbergen','Peter den Boer',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 3' and ssn_id like '2010%'),214401,'SNOOKERIJ 6','BSCZ 1',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214401,'Robert van Nieuwkoop','Glenn van Polanen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214401,'Edwin van Orssagen','Ron Reeuwijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214401,'Roger Planje','Ron Reeuwijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214401,'Edwin van Orssagen','Glenn van Polanen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214401,'Roger Planje','Glenn van Polanen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214401,'Robert van Nieuwkoop','Ron Reeuwijk',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 3' and ssn_id like '2010%'),214404,'HOGEWOERD 2','THE POCKET 2',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214404,'Michiel Peter Sjouke','Kees van Duijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214404,'Rogier Wijnans','Marcel van de Oever',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214404,'Akhi Kalicharan','Johan Keizer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214404,'Michiel Peter Sjouke','Marcel van de Oever',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214404,'Rogier Wijnans','Johan Keizer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214404,'Akhi Kalicharan','Kees van Duijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214404,'Akhi Kalicharan','Marcel van de Oever',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214404,'Rogier Wijnans','Kees van Duijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214404,'Michiel Peter Sjouke','Johan Keizer',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 3' and ssn_id like '2010%'),214405,'BSCZ 1','HOGEWOERD 2',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214405,'Peter den Boer','Rogier Wijnans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214405,'Glenn van Polanen','Akhi Kalicharan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214405,'Peter den Boer','Akhi Kalicharan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214405,'Glenn van Polanen','Michiel Peter Sjouke',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214405,'Glenn van Polanen','Rogier Wijnans',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214405,'Peter den Boer','Michiel Peter Sjouke',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 3' and ssn_id like '2010%'),214407,'Jumbo back in business','SNOOKERIJ 6',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214407,'René Sirre','Fabian Carrasco',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214407,'Arnold Roelen','Roger Planje',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214407,'Ronald Niesthoven','David Mourette',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214407,'René Sirre','Roger Planje',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214407,'Arnold Roelen','David Mourette',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214407,'Ronald Niesthoven','Fabian Carrasco',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214407,'Ronald Niesthoven','Roger Planje',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214407,'Arnold Roelen','Fabian Carrasco',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214407,'René Sirre','David Mourette',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('30-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 3' and ssn_id like '2010%'),214410,'BSCZ 1','THE POCKET 2',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214410,'Ron Reeuwijk','Jaco van Duijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214410,'Ron Reeuwijk','Kees van Duijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214410,'Koos Drunen','Jaco van Duijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214410,'Koos Drunen','Kees van Duijn',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('01-12-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 3' and ssn_id like '2010%'),214411,'JUMBO 3','SNOOKERIJ 6',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214411,'Debbie Anthonissen','Mark van Vliet',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214411,'Henk Versteeg','David Mourette',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214411,'Huibert van de Putte','Robert van Nieuwkoop',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214411,'Debbie Anthonissen','David Mourette',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214411,'Henk Versteeg','Robert van Nieuwkoop',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214411,'Huibert van de Putte','Mark van Vliet',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214411,'Huibert van de Putte','David Mourette',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214411,'Henk Versteeg','Mark van Vliet',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214411,'Debbie Anthonissen','Robert van Nieuwkoop',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('01-12-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 3' and ssn_id like '2010%'),214412,'Jumbo back in business','HOGEWOERD 2',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214412,'Eelco van der Meer','Rogier Wijnans',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214412,'René Sirre','Akhi Kalicharan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214412,'Arnold Roelen','Michiel Peter Sjouke',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214412,'Eelco van der Meer','Akhi Kalicharan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214412,'René Sirre','Michiel Peter Sjouke',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214412,'Arnold Roelen','Rogier Wijnans',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214412,'Arnold Roelen','Akhi Kalicharan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214412,'René Sirre','Rogier Wijnans',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214412,'Eelco van der Meer','Michiel Peter Sjouke',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-12-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 3' and ssn_id like '2010%'),214414,'THE POCKET 2','Jumbo back in business',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214414,'Jaco van Duijn','Ronald Niesthoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214414,'Thomas Glasbergen','Jan Hangelbroek',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214414,'Johan Keizer','René Sirre',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214414,'Jaco van Duijn','Jan Hangelbroek',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214414,'Thomas Glasbergen','René Sirre',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214414,'Johan Keizer','Ronald Niesthoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214414,'Johan Keizer','Jan Hangelbroek',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214414,'Thomas Glasbergen','Ronald Niesthoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214414,'Jaco van Duijn','René Sirre',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-12-2010','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 3' and ssn_id like '2010%'),214415,'HOGEWOERD 2','JUMBO 3',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-01-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 3' and ssn_id like '2010%'),214420,'Jumbo back in business','BSCZ 1',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214420,'René Sirre','Ron Reeuwijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214420,'Joost Kwestro','Glenn van Polanen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214420,'Eelco van der Meer','Glenn van Polanen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214420,'Joost Kwestro','Ron Reeuwijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214420,'Eelco van der Meer','Ron Reeuwijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214420,'René Sirre','Glenn van Polanen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-01-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 3' and ssn_id like '2010%'),214421,'BSCZ 1','JUMBO 3',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214421,'Peter den Boer','Henk Versteeg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214421,'Koos Drunen','Debbie Anthonissen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214421,'Peter den Boer','Rob Oudshoorn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214421,'Koos Drunen','Henk Versteeg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214421,'Koos Drunen','Rob Oudshoorn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214421,'Peter den Boer','Debbie Anthonissen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-01-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 3' and ssn_id like '2010%'),214423,'HOGEWOERD 2','SNOOKERIJ 6',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214423,'Akhi Kalicharan','Edwin van Orssagen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214423,'Akhi Kalicharan','Roger Planje',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214423,'Akhi Kalicharan','Robert van Nieuwkoop',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-01-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 3' and ssn_id like '2010%'),214425,'SNOOKERIJ 6','THE POCKET 2',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214425,'Mark van Vliet','Thomas Glasbergen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214425,'David Mourette','Johan Keizer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214425,'Mark van Vliet','Johan Keizer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214425,'Fabian Carrasco','Thomas Glasbergen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214425,'Fabian Carrasco','Johan Keizer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214425,'David Mourette','Thomas Glasbergen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-01-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 3' and ssn_id like '2010%'),214427,'JUMBO 3','Jumbo back in business',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214427,'Debbie Anthonissen','Joost Kwestro',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214427,'Henk Versteeg','René Sirre',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214427,'Debbie Anthonissen','René Sirre',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214427,'Henk Versteeg','Eelco van der Meer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214427,'Henk Versteeg','Joost Kwestro',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214427,'Debbie Anthonissen','Eelco van der Meer',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('26-01-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 3' and ssn_id like '2010%'),232135,'JUMBO 3','THE POCKET 2',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232135,'Rob Oudshoorn','Kees van Duijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232135,'Huibert van de Putte','Jaco van Duijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232135,'Rob Oudshoorn','Johan Keizer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232135,'Huibert van de Putte','Kees van Duijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232135,'Huibert van de Putte','Johan Keizer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232135,'Rob Oudshoorn','Jaco van Duijn',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('01-02-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 3' and ssn_id like '2010%'),214429,'BSCZ 1','SNOOKERIJ 6',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214429,'Glenn van Polanen','Mark van Vliet',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214429,'Ron Reeuwijk','Edwin van Orssagen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214429,'Koos Drunen','Robert van Nieuwkoop',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214429,'Glenn van Polanen','Edwin van Orssagen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214429,'Ron Reeuwijk','Robert van Nieuwkoop',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214429,'Koos Drunen','Mark van Vliet',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214429,'Koos Drunen','Edwin van Orssagen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214429,'Ron Reeuwijk','Mark van Vliet',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214429,'Glenn van Polanen','Robert van Nieuwkoop',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-02-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 3' and ssn_id like '2010%'),214431,'THE POCKET 2','HOGEWOERD 2',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214431,'Jaco van Duijn','Rogier Wijnans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214431,'Thomas Glasbergen','Akhi Kalicharan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214431,'Johan Keizer','Michiel Peter Sjouke',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214431,'Jaco van Duijn','Akhi Kalicharan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214431,'Thomas Glasbergen','Michiel Peter Sjouke',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214431,'Johan Keizer','Rogier Wijnans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214431,'Johan Keizer','Akhi Kalicharan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214431,'Thomas Glasbergen','Rogier Wijnans',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214431,'Jaco van Duijn','Michiel Peter Sjouke',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-02-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 3' and ssn_id like '2010%'),214433,'SNOOKERIJ 6','Jumbo back in business',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214433,'Edwin van Orssagen','Joost Kwestro',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214433,'Mark van Vliet','René Sirre',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214433,'Robert van Nieuwkoop','Eelco van der Meer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214433,'Edwin van Orssagen','René Sirre',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214433,'Mark van Vliet','Eelco van der Meer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214433,'Robert van Nieuwkoop','Joost Kwestro',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214433,'Robert van Nieuwkoop','René Sirre',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214433,'Mark van Vliet','Joost Kwestro',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214433,'Edwin van Orssagen','Eelco van der Meer',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-02-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 3' and ssn_id like '2010%'),214436,'HOGEWOERD 2','BSCZ 1',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-02-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 3' and ssn_id like '2010%'),214437,'SNOOKERIJ 6','JUMBO 3',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214437,'Robert van Nieuwkoop','Huibert van de Putte',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214437,'Roger Planje','Rob Oudshoorn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214437,'Fabian Carrasco','Rob Oudshoorn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214437,'Roger Planje','Huibert van de Putte',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214437,'Fabian Carrasco','Huibert van de Putte',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214437,'Robert van Nieuwkoop','Rob Oudshoorn',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-02-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 3' and ssn_id like '2010%'),214438,'THE POCKET 2','BSCZ 1',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214438,'Jaco van Duijn','Koos Drunen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214438,'Kees van Duijn','Peter den Boer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214438,'Jaco van Duijn','Peter den Boer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214438,'Kees van Duijn','Glenn van Polanen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214438,'Kees van Duijn','Koos Drunen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214438,'Jaco van Duijn','Glenn van Polanen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-02-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 3' and ssn_id like '2010%'),214439,'HOGEWOERD 2','Jumbo back in business',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-03-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 3' and ssn_id like '2010%'),214443,'JUMBO 3','HOGEWOERD 2',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214443,'Debbie Anthonissen','Rogier Wijnans',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214443,'Henk Versteeg','Akhi Kalicharan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214443,'Rob Oudshoorn','Michiel Peter Sjouke',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214443,'Debbie Anthonissen','Akhi Kalicharan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214443,'Henk Versteeg','Michiel Peter Sjouke',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214443,'Rob Oudshoorn','Rogier Wijnans',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214443,'Rob Oudshoorn','Akhi Kalicharan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214443,'Henk Versteeg','Rogier Wijnans',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214443,'Debbie Anthonissen','Michiel Peter Sjouke',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-03-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 3' and ssn_id like '2010%'),214444,'Jumbo back in business','THE POCKET 2',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214444,'Ronald Niesthoven','Thomas Glasbergen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214444,'René Sirre','Johan Keizer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214444,'Jan Hangelbroek','Kees van Duijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214444,'Ronald Niesthoven','Johan Keizer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214444,'René Sirre','Kees van Duijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214444,'Jan Hangelbroek','Thomas Glasbergen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214444,'Jan Hangelbroek','Johan Keizer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214444,'René Sirre','Thomas Glasbergen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214444,'Ronald Niesthoven','Kees van Duijn',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('29-03-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 3' and ssn_id like '2010%'),214445,'BSCZ 1','Jumbo back in business',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('31-03-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 3' and ssn_id like '2010%'),214446,'THE POCKET 2','JUMBO 3',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-04-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 3' and ssn_id like '2010%'),214449,'SNOOKERIJ 6','HOGEWOERD 2',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214449,'David Mourette','Akhi Kalicharan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214449,'Roger Planje','Michiel Peter Sjouke',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214449,'Edwin van Orssagen','Michiel Peter Sjouke',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214449,'Roger Planje','Akhi Kalicharan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214449,'Edwin van Orssagen','Akhi Kalicharan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214449,'David Mourette','Michiel Peter Sjouke',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-04-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 3' and ssn_id like '2010%'),214451,'JUMBO 3','BSCZ 1',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214451,'Debbie Anthonissen','Peter den Boer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214451,'Henk Versteeg','Glenn van Polanen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214451,'Debbie Anthonissen','Glenn van Polanen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214451,'Huibert van de Putte','Peter den Boer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214451,'Huibert van de Putte','Glenn van Polanen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214451,'Henk Versteeg','Peter den Boer',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-04-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 3' and ssn_id like '2010%'),214454,'Jumbo back in business','JUMBO 3',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-04-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 3' and ssn_id like '2010%'),214455,'THE POCKET 2','SNOOKERIJ 6',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214455,'Thomas Glasbergen','Robert van Nieuwkoop',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214455,'Johan Keizer','Mark van Vliet',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214455,'Thomas Glasbergen','Mark van Vliet',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214455,'Johan Keizer','David Mourette',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214455,'Johan Keizer','Robert van Nieuwkoop',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214455,'Thomas Glasbergen','David Mourette',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-05-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 3' and ssn_id like '2010%'),214457,'SNOOKERIJ 6','BSCZ 1',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-05-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 3' and ssn_id like '2010%'),214460,'HOGEWOERD 2','THE POCKET 2',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-05-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 3' and ssn_id like '2010%'),214461,'BSCZ 1','HOGEWOERD 2',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214461,'Peter den Boer','Rogier Wijnans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214461,'Glenn van Polanen','Akhi Kalicharan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214461,'Ron Reeuwijk','Michiel Peter Sjouke',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214461,'Peter den Boer','Akhi Kalicharan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214461,'Glenn van Polanen','Michiel Peter Sjouke',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214461,'Ron Reeuwijk','Rogier Wijnans',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214461,'Ron Reeuwijk','Akhi Kalicharan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214461,'Glenn van Polanen','Rogier Wijnans',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214461,'Peter den Boer','Michiel Peter Sjouke',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-05-2011','%d-%m-%Y'),(select id from cm_competitions where name = '2e klasse poule 3' and ssn_id like '2010%'),214463,'Jumbo back in business','SNOOKERIJ 6',2,7);
