delete from cm_match_details where game_id in (select game_id from cm_matches where cpn_id = (select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'));
delete from cm_matches where cpn_id = (select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%');
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-09-2010','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214744,'Fluke je snooker','OP HERHALING',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214744,'Paul Groot','Rob van den Berg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214744,'Jeroen de Jong','Fred Reijninga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214744,'Paul Groot','Fred Reijninga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214744,'Jeroen de Jong','Peter Schuddeboom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214744,'Jeroen de Jong','Rob van den Berg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214744,'Paul Groot','Peter Schuddeboom',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-09-2010','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214745,'OLD REBELS','Chicks With Sticks',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-09-2010','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214746,'Triickshot','Greenball',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214746,'Frank Oudshoorn','Martin van Zeelt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214746,'Stanisa Klisoric','Frans Gemser',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214746,'Hans Visser','Ton Oud',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214746,'Frank Oudshoorn','Frans Gemser',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214746,'Stanisa Klisoric','Ton Oud',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214746,'Hans Visser','Martin van Zeelt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214746,'Hans Visser','Frans Gemser',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214746,'Stanisa Klisoric','Martin van Zeelt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214746,'Frank Oudshoorn','Ton Oud',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-09-2010','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214747,'The Blue Men','Fluke je snooker 2',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-09-2010','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214748,'Chicks With Sticks','Fluke je snooker',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-09-2010','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214749,'Greenball','The Blue Men',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-09-2010','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214752,'Fluke je snooker','De Biljartmakers 3',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('29-09-2010','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214753,'Fluke je snooker 2','Greenball',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('01-10-2010','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214755,'The Blue Men','OP HERHALING',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-10-2010','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214756,'Chicks With Sticks','The Blue Men',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214756,'Dagmar van Gils','Cees Castricum',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214756,'Eva Groen','Cees Castricum',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214756,'Tens Tensen','Cees Castricum',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-10-2010','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214757,'OLD REBELS','Fluke je snooker',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214757,'Eric Feteridge','Dim Gerven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214757,'John Rodrigues Garcia','Anton Geschev',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214757,'Jef Raber','Paul Groot',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214757,'Eric Feteridge','Anton Geschev',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214757,'John Rodrigues Garcia','Paul Groot',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214757,'Jef Raber','Dim Gerven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214757,'Jef Raber','Anton Geschev',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214757,'John Rodrigues Garcia','Dim Gerven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214757,'Eric Feteridge','Paul Groot',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-10-2010','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214759,'OP HERHALING','Fluke je snooker 2',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214759,'Fred Reijninga','Lester Noom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214759,'Peter Schuddeboom','Jordi Bron',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214759,'Rob van den Berg','Jordi Bron',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214759,'Peter Schuddeboom','Lester Noom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214759,'Rob van den Berg','Lester Noom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214759,'Fred Reijninga','Jordi Bron',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-10-2010','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214760,'Greenball','OP HERHALING',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-10-2010','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214761,'Fluke je snooker 2','Chicks With Sticks',1,8);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-10-2010','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214762,'Triickshot','OLD REBELS',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214762,'Frank Oudshoorn','John Rodrigues Garcia',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214762,'Stanisa Klisoric','Eric Feteridge',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214762,'Henk Visser','Jef Raber',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214762,'Frank Oudshoorn','Eric Feteridge',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214762,'Stanisa Klisoric','Jef Raber',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214762,'Henk Visser','John Rodrigues Garcia',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214762,'Henk Visser','Eric Feteridge',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214762,'Stanisa Klisoric','John Rodrigues Garcia',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214762,'Frank Oudshoorn','Jef Raber',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-10-2010','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214763,'The Blue Men','De Biljartmakers 3',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214763,'Jan de Haas','Hans Slier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214763,'Walter Kramer','Wim Koudstaal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214763,'Jan de Haas','Wim Koudstaal',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214763,'Walter Kramer','Maurijn Maas',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214763,'Walter Kramer','Hans Slier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214763,'Jan de Haas','Maurijn Maas',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-10-2010','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),229540,'De Biljartmakers 3','OLD REBELS',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(229540,'Fred Ensel','Eric Feteridge',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(229540,'Maurijn Maas','John Rodrigues Garcia',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(229540,'Wim Koudstaal','Jef Raber',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(229540,'Fred Ensel','John Rodrigues Garcia',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(229540,'Maurijn Maas','Jef Raber',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(229540,'Wim Koudstaal','Eric Feteridge',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(229540,'Wim Koudstaal','John Rodrigues Garcia',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(229540,'Maurijn Maas','Eric Feteridge',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(229540,'Fred Ensel','Jef Raber',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-10-2010','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),229854,'OP HERHALING','Triickshot',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(229854,'Henk Leegwater','Hans Visser',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(229854,'Rob van den Berg','Stanisa Klisoric',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(229854,'Peter Schuddeboom','Ruud Docter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(229854,'Henk Leegwater','Stanisa Klisoric',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(229854,'Rob van den Berg','Ruud Docter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(229854,'Peter Schuddeboom','Hans Visser',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(229854,'Peter Schuddeboom','Stanisa Klisoric',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(229854,'Rob van den Berg','Hans Visser',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(229854,'Henk Leegwater','Ruud Docter',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-10-2010','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),230182,'Triickshot','Chicks With Sticks',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(230182,'Ruud Docter','Eva Groen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(230182,'Hans Visser','Lisette de Groot',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(230182,'Ruud Docter','Lisette de Groot',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(230182,'Stanisa Klisoric','Eva Groen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(230182,'Stanisa Klisoric','Lisette de Groot',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(230182,'Hans Visser','Eva Groen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('01-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214764,'Fluke je snooker','Triickshot',0,9);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('01-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214765,'Chicks With Sticks','Greenball',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214766,'OLD REBELS','The Blue Men',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214766,'Eric Feteridge','Walter Kramer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214766,'Jef Raber','Kim Pothof',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214766,'John Rodrigues Garcia','Kim Pothof',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214766,'Jef Raber','Walter Kramer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214766,'John Rodrigues Garcia','Walter Kramer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214766,'Eric Feteridge','Kim Pothof',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214768,'Greenball','De Biljartmakers 3',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214769,'OP HERHALING','Chicks With Sticks',8,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214771,'The Blue Men','Fluke je snooker',9,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214771,'Cees Castricum','Dim Gerven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214771,'Cees Castricum','Anton Geschev',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214772,'Fluke je snooker','Fluke je snooker 2',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214773,'OLD REBELS','Greenball',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214773,'Eric Feteridge','Martin van Zeelt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214773,'John Rodrigues Garcia','Ton Oud',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214773,'Jef Raber','Jeroen Zonneveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214773,'Eric Feteridge','Ton Oud',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214773,'John Rodrigues Garcia','Jeroen Zonneveld',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214773,'Jef Raber','Martin van Zeelt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214773,'Jef Raber','Ton Oud',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214773,'John Rodrigues Garcia','Martin van Zeelt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214773,'Eric Feteridge','Jeroen Zonneveld',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214774,'Triickshot','The Blue Men',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214774,'Frank Oudshoorn','Jan de Haas',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214774,'Ruud Docter','Kim Pothof',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214774,'Stanisa Klisoric','Walter Kramer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214774,'Frank Oudshoorn','Kim Pothof',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214774,'Ruud Docter','Walter Kramer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214774,'Stanisa Klisoric','Jan de Haas',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214774,'Stanisa Klisoric','Kim Pothof',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214774,'Ruud Docter','Jan de Haas',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214774,'Frank Oudshoorn','Walter Kramer',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214775,'De Biljartmakers 3','OP HERHALING',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214775,'Fred Ensel','Rob van den Berg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214775,'Wim Koudstaal','Willem Visser',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214775,'Maurijn Maas','Fred Reijninga',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214775,'Fred Ensel','Willem Visser',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214775,'Wim Koudstaal','Fred Reijninga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214775,'Maurijn Maas','Rob van den Berg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214775,'Maurijn Maas','Willem Visser',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214775,'Wim Koudstaal','Rob van den Berg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214775,'Fred Ensel','Fred Reijninga',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214776,'Chicks With Sticks','De Biljartmakers 3',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214776,'Tens Tensen','Fred Ensel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214776,'Lisette de Groot','Maurijn Maas',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214776,'Dagmar van Gils','Wim Koudstaal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214776,'Tens Tensen','Maurijn Maas',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214776,'Lisette de Groot','Wim Koudstaal',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214776,'Dagmar van Gils','Fred Ensel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214776,'Dagmar van Gils','Maurijn Maas',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214776,'Lisette de Groot','Fred Ensel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214776,'Tens Tensen','Wim Koudstaal',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214777,'Greenball','Fluke je snooker',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214779,'Fluke je snooker 2','Triickshot',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('29-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214780,'Greenball','Triickshot',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('29-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214781,'Chicks With Sticks','OLD REBELS',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('01-12-2010','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214782,'Fluke je snooker 2','The Blue Men',1,8);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('01-12-2010','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214783,'OP HERHALING','Fluke je snooker',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-12-2010','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214784,'Fluke je snooker','Chicks With Sticks',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-12-2010','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214785,'OLD REBELS','De Biljartmakers 3',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214785,'Eric Feteridge','Wim Koudstaal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214785,'John Rodrigues Garcia','Hans Slier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214785,'Jef Raber','Maurijn Maas',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214785,'Eric Feteridge','Hans Slier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214785,'John Rodrigues Garcia','Maurijn Maas',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214785,'Jef Raber','Wim Koudstaal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214785,'Jef Raber','Hans Slier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214785,'John Rodrigues Garcia','Wim Koudstaal',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214785,'Eric Feteridge','Maurijn Maas',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-12-2010','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),230893,'De Biljartmakers 3','Fluke je snooker 2',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(230893,'Wil van Vliet','Stefan van Lieshout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(230893,'Maurijn Maas','Lester Noom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(230893,'Wim Koudstaal','Jordi Bron',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(230893,'Wil van Vliet','Lester Noom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(230893,'Maurijn Maas','Jordi Bron',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(230893,'Wim Koudstaal','Stefan van Lieshout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(230893,'Wim Koudstaal','Lester Noom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(230893,'Maurijn Maas','Stefan van Lieshout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(230893,'Wil van Vliet','Jordi Bron',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-12-2010','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214787,'The Blue Men','Greenball',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214787,'Jan de Haas','Ton Oud',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214787,'Kim Pothof','Jeroen Zonneveld',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214787,'Jan de Haas','Frans Gemser',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214787,'Kim Pothof','Ton Oud',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214787,'Kim Pothof','Frans Gemser',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214787,'Jan de Haas','Jeroen Zonneveld',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-12-2010','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214788,'Greenball','Fluke je snooker 2',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-12-2010','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214789,'Chicks With Sticks','Triickshot',1,8);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-12-2010','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214790,'OP HERHALING','The Blue Men',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214790,'Willem Visser','Cees Castricum',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214790,'Peter Schuddeboom','Walter Kramer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214790,'Rob van den Berg','Walter Kramer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214790,'Peter Schuddeboom','Cees Castricum',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214790,'Rob van den Berg','Cees Castricum',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214790,'Willem Visser','Walter Kramer',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-12-2010','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214791,'De Biljartmakers 3','Fluke je snooker',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214791,'Wil van Vliet','Dim Gerven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214791,'Maurijn Maas','Anton Geschev',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214791,'Wim Koudstaal','Paul Groot',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214791,'Wil van Vliet','Anton Geschev',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214791,'Maurijn Maas','Paul Groot',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214791,'Wim Koudstaal','Dim Gerven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214791,'Wim Koudstaal','Anton Geschev',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214791,'Maurijn Maas','Dim Gerven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214791,'Wil van Vliet','Paul Groot',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('29-12-2010','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),231607,'OP HERHALING','OLD REBELS',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(231607,'Peter Schuddeboom','John Rodrigues Garcia',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(231607,'Henk Leegwater','Eric Feteridge',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(231607,'Rob van den Berg','Jef Raber',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(231607,'Peter Schuddeboom','Eric Feteridge',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(231607,'Henk Leegwater','Jef Raber',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(231607,'Rob van den Berg','John Rodrigues Garcia',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(231607,'Rob van den Berg','Eric Feteridge',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(231607,'Henk Leegwater','John Rodrigues Garcia',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(231607,'Peter Schuddeboom','Jef Raber',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-01-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214792,'Fluke je snooker','OLD REBELS',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-01-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214793,'Triickshot','De Biljartmakers 3',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214793,'Stanisa Klisoric','Wim Koudstaal',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214793,'Frank Oudshoorn','Maurijn Maas',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214793,'Ruud Docter','Fred Ensel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214793,'Stanisa Klisoric','Maurijn Maas',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214793,'Frank Oudshoorn','Fred Ensel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214793,'Ruud Docter','Wim Koudstaal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214793,'Ruud Docter','Maurijn Maas',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214793,'Frank Oudshoorn','Wim Koudstaal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214793,'Stanisa Klisoric','Fred Ensel',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-01-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214794,'Fluke je snooker 2','OP HERHALING',0,9);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-01-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214795,'The Blue Men','Chicks With Sticks',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-01-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214796,'Chicks With Sticks','Fluke je snooker 2',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-01-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214797,'OLD REBELS','Triickshot',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214797,'Eric Feteridge','Henk Visser',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214797,'John Rodrigues Garcia','Frank Oudshoorn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214797,'Jef Raber','Stanisa Klisoric',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214797,'Eric Feteridge','Frank Oudshoorn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214797,'John Rodrigues Garcia','Stanisa Klisoric',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214797,'Jef Raber','Henk Visser',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214797,'Jef Raber','Frank Oudshoorn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214797,'John Rodrigues Garcia','Henk Visser',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214797,'Eric Feteridge','Stanisa Klisoric',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-01-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214798,'OP HERHALING','Greenball',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214798,'Peter Schuddeboom','Ton Oud',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214798,'Rob van den Berg','Martin van Zeelt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214798,'Willem Visser','Frans Gemser',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214798,'Peter Schuddeboom','Martin van Zeelt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214798,'Rob van den Berg','Frans Gemser',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214798,'Willem Visser','Ton Oud',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214798,'Willem Visser','Martin van Zeelt',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214798,'Rob van den Berg','Ton Oud',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214798,'Peter Schuddeboom','Frans Gemser',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-01-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214799,'De Biljartmakers 3','The Blue Men',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214799,'Wim Koudstaal','Kim Pothof',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214799,'Fred Ensel','Kim Pothof',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214799,'Maurijn Maas','Kim Pothof',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-01-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214802,'Fluke je snooker 2','De Biljartmakers 3',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-01-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214803,'The Blue Men','OLD REBELS',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-01-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214804,'Chicks With Sticks','OP HERHALING',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214804,'Tens Tensen','Peter Schuddeboom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214804,'Lisette de Groot','Henk Leegwater',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214804,'Eva Groen','Fred Reijninga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214804,'Tens Tensen','Henk Leegwater',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214804,'Lisette de Groot','Fred Reijninga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214804,'Eva Groen','Peter Schuddeboom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214804,'Eva Groen','Henk Leegwater',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214804,'Lisette de Groot','Peter Schuddeboom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214804,'Tens Tensen','Fred Reijninga',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-01-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214805,'Fluke je snooker','The Blue Men',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('25-01-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214806,'OLD REBELS','Fluke je snooker 2',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214806,'Eric Feteridge','Stefan van Lieshout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214806,'John Rodrigues Garcia','Lester Noom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214806,'Jef Raber','Jordi Bron',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214806,'Eric Feteridge','Lester Noom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214806,'John Rodrigues Garcia','Jordi Bron',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214806,'Jef Raber','Stefan van Lieshout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214806,'Jef Raber','Lester Noom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214806,'John Rodrigues Garcia','Stefan van Lieshout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214806,'Eric Feteridge','Jordi Bron',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-02-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),232296,'Greenball','OLD REBELS',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-02-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214809,'Fluke je snooker 2','Fluke je snooker',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-02-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214810,'OP HERHALING','De Biljartmakers 3',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214810,'Henk Leegwater','Wim Koudstaal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214810,'Willem Visser','Fred Ensel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214810,'Henk Leegwater','Fred Ensel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214810,'Willem Visser','Maurijn Maas',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214810,'Willem Visser','Wim Koudstaal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214810,'Henk Leegwater','Maurijn Maas',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-02-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214811,'The Blue Men','Triickshot',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214811,'Jan de Haas','Stanisa Klisoric',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214811,'Jan de Haas','Frank Oudshoorn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214811,'Jan de Haas','Hans Visser',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-02-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214812,'Fluke je snooker','Greenball',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-02-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214813,'OLD REBELS','OP HERHALING',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214813,'Eric Feteridge','Rob van den Berg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214813,'John Rodrigues Garcia','Willem Visser',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214813,'Jef Raber','Henk Leegwater',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214813,'Eric Feteridge','Willem Visser',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214813,'John Rodrigues Garcia','Henk Leegwater',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214813,'Jef Raber','Rob van den Berg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214813,'Jef Raber','Willem Visser',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214813,'John Rodrigues Garcia','Rob van den Berg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214813,'Eric Feteridge','Henk Leegwater',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-02-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214816,'Fluke je snooker','OP HERHALING',0,9);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-02-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214817,'OLD REBELS','Chicks With Sticks',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214817,'Eric Feteridge','Eva Groen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214817,'John Rodrigues Garcia','Lisette de Groot',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214817,'Jef Raber','Tens Tensen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214817,'Eric Feteridge','Lisette de Groot',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214817,'John Rodrigues Garcia','Tens Tensen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214817,'Jef Raber','Eva Groen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214817,'Jef Raber','Lisette de Groot',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214817,'John Rodrigues Garcia','Eva Groen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214817,'Eric Feteridge','Tens Tensen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-02-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214818,'Triickshot','Greenball',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214818,'Hans Visser','Frans Gemser',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214818,'Frank Oudshoorn','Martin van Zeelt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214818,'Stanisa Klisoric','Ton Oud',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214818,'Hans Visser','Martin van Zeelt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214818,'Frank Oudshoorn','Ton Oud',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214818,'Stanisa Klisoric','Frans Gemser',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214818,'Stanisa Klisoric','Martin van Zeelt',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214818,'Frank Oudshoorn','Frans Gemser',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214818,'Hans Visser','Ton Oud',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-02-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214819,'The Blue Men','Fluke je snooker 2',8,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-03-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),232548,'Triickshot','OP HERHALING',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232548,'Stanisa Klisoric','Rob van den Berg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232548,'Frank Oudshoorn','Henk Leegwater',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232548,'Ruud Docter','Willem Visser',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232548,'Stanisa Klisoric','Henk Leegwater',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232548,'Frank Oudshoorn','Willem Visser',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232548,'Ruud Docter','Rob van den Berg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232548,'Ruud Docter','Henk Leegwater',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232548,'Frank Oudshoorn','Rob van den Berg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232548,'Stanisa Klisoric','Willem Visser',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-03-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),232587,'De Biljartmakers 3','Greenball',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232587,'Wil van Vliet','Frans Gemser',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232587,'Wim Koudstaal','Jeroen Zonneveld',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232587,'Maurijn Maas','Ton Oud',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232587,'Wil van Vliet','Jeroen Zonneveld',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232587,'Wim Koudstaal','Ton Oud',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232587,'Maurijn Maas','Frans Gemser',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232587,'Maurijn Maas','Jeroen Zonneveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232587,'Wim Koudstaal','Frans Gemser',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232587,'Wil van Vliet','Ton Oud',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-03-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),232613,'Fluke je snooker 2','OLD REBELS',1,8);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-03-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),233114,'Greenball','Chicks With Sticks',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-03-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214820,'OLD REBELS','The Blue Men',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214820,'Eric Feteridge','Kim Pothof',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214820,'John Rodrigues Garcia','Walter Kramer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214820,'Eric Feteridge','Walter Kramer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214820,'Jef Raber','Kim Pothof',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214820,'Jef Raber','Walter Kramer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214820,'John Rodrigues Garcia','Kim Pothof',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-03-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),233026,'De Biljartmakers 3','Chicks With Sticks',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233026,'Fred Ensel','Eva Groen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233026,'Maurijn Maas','Dagmar van Gils',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233026,'Wim Koudstaal','Tens Tensen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233026,'Fred Ensel','Dagmar van Gils',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233026,'Maurijn Maas','Tens Tensen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233026,'Wim Koudstaal','Eva Groen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233026,'Wim Koudstaal','Dagmar van Gils',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233026,'Maurijn Maas','Eva Groen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233026,'Fred Ensel','Tens Tensen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-03-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),232651,'Triickshot','Fluke je snooker 2',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-03-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214821,'Chicks With Sticks','Fluke je snooker',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214821,'Dagmar van Gils','Anton Geschev',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214821,'Eva Groen','Jeroen de Jong',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214821,'Tens Tensen','Anton Geschev',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214821,'Dagmar van Gils','Jeroen de Jong',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214821,'Eva Groen','Anton Geschev',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214821,'Tens Tensen','Jeroen de Jong',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-03-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214822,'Greenball','The Blue Men',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-03-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214823,'De Biljartmakers 3','OLD REBELS',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214823,'Fred Ensel','John Rodrigues Garcia',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214823,'Wim Koudstaal','Eric Feteridge',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214823,'Maurijn Maas','Jef Raber',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214823,'Fred Ensel','Eric Feteridge',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214823,'Wim Koudstaal','Jef Raber',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214823,'Maurijn Maas','John Rodrigues Garcia',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214823,'Maurijn Maas','Eric Feteridge',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214823,'Wim Koudstaal','John Rodrigues Garcia',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214823,'Fred Ensel','Jef Raber',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-03-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214824,'OP HERHALING','Triickshot',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-03-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214825,'Fluke je snooker','De Biljartmakers 3',1,8);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-03-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214826,'Fluke je snooker 2','Greenball',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-03-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214827,'Triickshot','Chicks With Sticks',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214827,'Ruud Docter','Eva Groen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214827,'Frank Oudshoorn','Tens Tensen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214827,'Hans Visser','Tens Tensen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214827,'Frank Oudshoorn','Eva Groen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214827,'Hans Visser','Eva Groen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214827,'Ruud Docter','Tens Tensen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('25-03-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214828,'The Blue Men','OP HERHALING',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214828,'Walter Kramer','Fred Reijninga',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214828,'Jan de Haas','Willem Visser',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214828,'Walter Kramer','Willem Visser',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214828,'Jan de Haas','Henk Leegwater',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214828,'Jan de Haas','Fred Reijninga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214828,'Walter Kramer','Henk Leegwater',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('28-03-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214829,'Chicks With Sticks','The Blue Men',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('30-03-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214831,'De Biljartmakers 3','Triickshot',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214831,'Maurijn Maas','Hans Visser',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214831,'Fred Ensel','Stanisa Klisoric',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214831,'Wim Koudstaal','Ruud Docter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214831,'Maurijn Maas','Stanisa Klisoric',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214831,'Fred Ensel','Ruud Docter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214831,'Wim Koudstaal','Hans Visser',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214831,'Wim Koudstaal','Stanisa Klisoric',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214831,'Fred Ensel','Hans Visser',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214831,'Maurijn Maas','Ruud Docter',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('30-03-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214832,'OP HERHALING','Fluke je snooker 2',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214832,'Willem Visser','Lester Noom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214832,'Rob van den Berg','Lester Noom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214832,'Henk Leegwater','Lester Noom',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-04-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214833,'Greenball','OP HERHALING',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-04-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),233640,'OLD REBELS','Fluke je snooker',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-04-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214834,'Fluke je snooker 2','Chicks With Sticks',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-04-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214836,'The Blue Men','De Biljartmakers 3',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-04-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214837,'Fluke je snooker','Triickshot',1,8);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-04-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214838,'Chicks With Sticks','Greenball',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-04-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),233641,'Triickshot','OLD REBELS',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233641,'Frank Oudshoorn','Jef Raber',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233641,'Stanisa Klisoric','John Rodrigues Garcia',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233641,'Hans Visser','Eric Feteridge',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233641,'Frank Oudshoorn','John Rodrigues Garcia',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233641,'Stanisa Klisoric','Eric Feteridge',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233641,'Hans Visser','Jef Raber',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233641,'Hans Visser','John Rodrigues Garcia',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233641,'Stanisa Klisoric','Jef Raber',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233641,'Frank Oudshoorn','Eric Feteridge',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-04-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214839,'De Biljartmakers 3','Fluke je snooker 2',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214839,'Maurijn Maas','Lester Noom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214839,'Fred Ensel','Stefan van Lieshout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214839,'Wim Koudstaal','Jordi Bron',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214839,'Maurijn Maas','Stefan van Lieshout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214839,'Fred Ensel','Jordi Bron',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214839,'Wim Koudstaal','Lester Noom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214839,'Wim Koudstaal','Stefan van Lieshout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214839,'Fred Ensel','Lester Noom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214839,'Maurijn Maas','Jordi Bron',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-04-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),233340,'De Biljartmakers 3','Triickshot',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233340,'Maurijn Maas','Stanisa Klisoric',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233340,'Wil van Vliet','Ruud Docter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233340,'Wim Koudstaal','Hans Visser',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233340,'Maurijn Maas','Ruud Docter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233340,'Wil van Vliet','Hans Visser',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233340,'Wim Koudstaal','Stanisa Klisoric',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233340,'Wim Koudstaal','Ruud Docter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233340,'Wil van Vliet','Stanisa Klisoric',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233340,'Maurijn Maas','Hans Visser',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-05-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214840,'Greenball','De Biljartmakers 3',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-05-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214841,'OP HERHALING','Chicks With Sticks',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-05-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214842,'Fluke je snooker 2','OLD REBELS',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214842,'Jordi Bron','John Rodrigues Garcia',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214842,'Stefan van Lieshout','Jef Raber',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214842,'Lester Noom','Eric Feteridge',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214842,'Jordi Bron','Jef Raber',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214842,'Stefan van Lieshout','Eric Feteridge',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214842,'Lester Noom','John Rodrigues Garcia',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214842,'Lester Noom','Jef Raber',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214842,'Stefan van Lieshout','John Rodrigues Garcia',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214842,'Jordi Bron','Eric Feteridge',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-05-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214843,'The Blue Men','Fluke je snooker',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-05-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214846,'Triickshot','The Blue Men',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214846,'Frank Oudshoorn','Jan de Haas',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214846,'Ruud Docter','Cees Castricum',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214846,'Frank Oudshoorn','Cees Castricum',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214846,'Hans Visser','Jan de Haas',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214846,'Hans Visser','Cees Castricum',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214846,'Ruud Docter','Jan de Haas',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-05-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214847,'De Biljartmakers 3','OP HERHALING',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214847,'Wil van Vliet','Fred Reijninga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214847,'Maurijn Maas','Peter Schuddeboom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214847,'Wim Koudstaal','Henk Leegwater',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214847,'Wil van Vliet','Peter Schuddeboom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214847,'Maurijn Maas','Henk Leegwater',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214847,'Wim Koudstaal','Fred Reijninga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214847,'Wim Koudstaal','Peter Schuddeboom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214847,'Maurijn Maas','Fred Reijninga',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214847,'Wil van Vliet','Henk Leegwater',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-05-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214848,'Chicks With Sticks','De Biljartmakers 3',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214848,'Tens Tensen','Maurijn Maas',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214848,'Lisette de Groot','Hans Slier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214848,'Eva Groen','Wim Koudstaal',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214848,'Tens Tensen','Hans Slier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214848,'Lisette de Groot','Wim Koudstaal',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214848,'Eva Groen','Maurijn Maas',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214848,'Eva Groen','Hans Slier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214848,'Lisette de Groot','Maurijn Maas',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214848,'Tens Tensen','Wim Koudstaal',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-05-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214849,'Greenball','Fluke je snooker',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-05-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214850,'OP HERHALING','OLD REBELS',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214850,'Henk Leegwater','John Rodrigues Garcia',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214850,'Willem Visser','Jef Raber',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214850,'Peter Schuddeboom','Eric Feteridge',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214850,'Henk Leegwater','Jef Raber',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214850,'Willem Visser','Eric Feteridge',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214850,'Peter Schuddeboom','John Rodrigues Garcia',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214850,'Peter Schuddeboom','Jef Raber',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214850,'Willem Visser','John Rodrigues Garcia',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(214850,'Henk Leegwater','Eric Feteridge',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-05-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),214851,'Fluke je snooker 2','Triickshot',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('25-05-2011','%d-%m-%Y'),(select id from cm_competitions where name = '3e klasse poule 1' and ssn_id like '2010%'),233905,'Triickshot','Fluke je snooker',5,4);
