delete from cm_match_details where game_id in (select game_id from cm_matches where cpn_id = (select id from cm_competitions where name = 'Combi 2e-3e klasse poule 4' and ssn_id like '2014%'));
delete from cm_matches where cpn_id = (select id from cm_competitions where name = 'Combi 2e-3e klasse poule 4' and ssn_id like '2014%');
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-09-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 4' and ssn_id like '2014%'),444362,'pocket 2','SNOOKERIJ 12',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-09-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 4' and ssn_id like '2014%'),446965,'OLD REBELS','JUMBO 13',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(446965,'Eric Feteridge','Lea Lindhout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(446965,'John Rodrigues Garcia','Menno Beugelsdijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(446965,'Ed van den Berg','Jeroen Keijzer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(446965,'Eric Feteridge','Menno Beugelsdijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(446965,'John Rodrigues Garcia','Jeroen Keijzer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(446965,'Ed van den Berg','Lea Lindhout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(446965,'Ed van den Berg','Menno Beugelsdijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(446965,'John Rodrigues Garcia','Lea Lindhout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(446965,'Eric Feteridge','Jeroen Keijzer',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 4' and ssn_id like '2014%'),444366,'SNOOKERIJ 10','HOGEWOERD 3',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444366,'Steve Course','Michiel Peter Sjouke',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444366,'Harry Bartels','Martijn Korner',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444366,'Margot Olree','Debbie Anthonissen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444366,'Steve Course','Martijn Korner',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444366,'Harry Bartels','Debbie Anthonissen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444366,'Margot Olree','Michiel Peter Sjouke',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444366,'Margot Olree','Martijn Korner',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444366,'Harry Bartels','Michiel Peter Sjouke',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444366,'Steve Course','Debbie Anthonissen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 4' and ssn_id like '2014%'),444368,'JUMBO 13','SNOOKERIJ 12',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444368,'Harry Vogelzang','Martin van Rijsbergen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444368,'Menno Beugelsdijk','Bas Langeveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444368,'Jeroen Keijzer','Ben den Dulk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444368,'Harry Vogelzang','Bas Langeveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444368,'Menno Beugelsdijk','Ben den Dulk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444368,'Jeroen Keijzer','Martin van Rijsbergen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444368,'Jeroen Keijzer','Bas Langeveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444368,'Menno Beugelsdijk','Martin van Rijsbergen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444368,'Harry Vogelzang','Ben den Dulk',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 4' and ssn_id like '2014%'),444369,'pocket 2','SNOOKERIJ 10',0,9);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444369,'Kees van Duijn','Nico Seisveld',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444369,'Thomas Glasbergen','Harry Bartels',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444369,'Kees van Duijn','Steve Course',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444369,'Thomas Glasbergen','Nico Seisveld',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444369,'Thomas Glasbergen','Steve Course',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444369,'Kees van Duijn','Harry Bartels',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 4' and ssn_id like '2014%'),444372,'SNOOKERIJ 10','OLD REBELS',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 4' and ssn_id like '2014%'),444374,'OLD REBELS','HOGEWOERD 3',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444374,'Ed van den Berg','Soerin Ganga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444374,'Eric Feteridge','Debbie Anthonissen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444374,'John Rodrigues Garcia','Michiel Peter Sjouke',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444374,'Ed van den Berg','Debbie Anthonissen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444374,'Eric Feteridge','Michiel Peter Sjouke',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444374,'John Rodrigues Garcia','Soerin Ganga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444374,'John Rodrigues Garcia','Debbie Anthonissen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444374,'Eric Feteridge','Soerin Ganga',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444374,'Ed van den Berg','Michiel Peter Sjouke',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 4' and ssn_id like '2014%'),444375,'JUMBO 13','SNOOKERIJ 10',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444375,'Menno Beugelsdijk','Margot Olree',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444375,'Jeroen Keijzer','Nico Seisveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444375,'Harry Vogelzang','Harry Bartels',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444375,'Menno Beugelsdijk','Nico Seisveld',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444375,'Jeroen Keijzer','Harry Bartels',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444375,'Harry Vogelzang','Margot Olree',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444375,'Harry Vogelzang','Nico Seisveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444375,'Jeroen Keijzer','Margot Olree',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444375,'Menno Beugelsdijk','Harry Bartels',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('30-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 4' and ssn_id like '2014%'),448180,'HOGEWOERD 3','pocket 2',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448180,'Debbie Anthonissen','Thomas Glasbergen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448180,'Martijn Korner','Johan Keizer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448180,'Michiel Peter Sjouke','Thomas Glasbergen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448180,'Debbie Anthonissen','Johan Keizer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448180,'Martijn Korner','Thomas Glasbergen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448180,'Michiel Peter Sjouke','Johan Keizer',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 4' and ssn_id like '2014%'),448109,'SNOOKERIJ 12','OLD REBELS',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448109,'Huib den Hartog','John Rodrigues Garcia',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448109,'Bas Langeveld','Ed van den Berg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448109,'Martin van Rijsbergen','Jef Raber',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448109,'Huib den Hartog','Ed van den Berg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448109,'Bas Langeveld','Jef Raber',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448109,'Martin van Rijsbergen','John Rodrigues Garcia',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448109,'Martin van Rijsbergen','Ed van den Berg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448109,'Bas Langeveld','John Rodrigues Garcia',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448109,'Huib den Hartog','Jef Raber',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 4' and ssn_id like '2014%'),444376,'pocket 2','OLD REBELS',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444376,'Kees van Duijn','Eric Feteridge',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444376,'Johan Keizer','Jef Raber',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444376,'Kees van Duijn','Ed van den Berg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444376,'Johan Keizer','Eric Feteridge',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444376,'Johan Keizer','Ed van den Berg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444376,'Kees van Duijn','Jef Raber',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 4' and ssn_id like '2014%'),444377,'HOGEWOERD 3','JUMBO 13',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444377,'Michiel Peter Sjouke','Harry Vogelzang',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444377,'Debbie Anthonissen','Menno Beugelsdijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444377,'Martijn Korner','Jeroen Keijzer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444377,'Michiel Peter Sjouke','Menno Beugelsdijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444377,'Debbie Anthonissen','Jeroen Keijzer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444377,'Martijn Korner','Harry Vogelzang',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444377,'Martijn Korner','Menno Beugelsdijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444377,'Debbie Anthonissen','Harry Vogelzang',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444377,'Michiel Peter Sjouke','Jeroen Keijzer',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 4' and ssn_id like '2014%'),444378,'SNOOKERIJ 10','SNOOKERIJ 12',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444378,'Harry Bartels','Huib den Hartog',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444378,'Steve Course','Martin van Rijsbergen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444378,'Nico Seisveld','Bas Langeveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444378,'Harry Bartels','Martin van Rijsbergen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444378,'Steve Course','Bas Langeveld',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444378,'Nico Seisveld','Huib den Hartog',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444378,'Nico Seisveld','Martin van Rijsbergen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444378,'Steve Course','Huib den Hartog',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444378,'Harry Bartels','Bas Langeveld',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 4' and ssn_id like '2014%'),444379,'SNOOKERIJ 12','HOGEWOERD 3',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444379,'Huib den Hartog','Michiel Peter Sjouke',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444379,'Martin van Rijsbergen','Martijn Korner',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444379,'Bas Langeveld','Debbie Anthonissen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444379,'Huib den Hartog','Martijn Korner',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444379,'Martin van Rijsbergen','Debbie Anthonissen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444379,'Bas Langeveld','Michiel Peter Sjouke',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444379,'Bas Langeveld','Martijn Korner',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444379,'Martin van Rijsbergen','Michiel Peter Sjouke',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444379,'Huib den Hartog','Debbie Anthonissen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 4' and ssn_id like '2014%'),444381,'JUMBO 13','pocket 2',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444381,'Menno Beugelsdijk','Thomas Glasbergen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444381,'Lea Lindhout','Johan Keizer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444381,'Harry Vogelzang','Kees van Duijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444381,'Menno Beugelsdijk','Johan Keizer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444381,'Lea Lindhout','Kees van Duijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444381,'Harry Vogelzang','Thomas Glasbergen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444381,'Harry Vogelzang','Johan Keizer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444381,'Lea Lindhout','Thomas Glasbergen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444381,'Menno Beugelsdijk','Kees van Duijn',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 4' and ssn_id like '2014%'),444382,'SNOOKERIJ 12','pocket 2',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444382,'Huib den Hartog','Thomas Glasbergen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444382,'Ben den Dulk','Johan Keizer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444382,'Bas Langeveld','Thomas Glasbergen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444382,'Huib den Hartog','Johan Keizer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444382,'Ben den Dulk','Thomas Glasbergen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444382,'Bas Langeveld','Johan Keizer',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('25-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 4' and ssn_id like '2014%'),444385,'OLD REBELS','SNOOKERIJ 12',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444385,'Eric Feteridge','Bas Langeveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444385,'John Rodrigues Garcia','Huib den Hartog',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444385,'Ed van den Berg','Martin van Rijsbergen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444385,'Eric Feteridge','Huib den Hartog',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444385,'John Rodrigues Garcia','Martin van Rijsbergen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444385,'Ed van den Berg','Bas Langeveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444385,'Ed van den Berg','Huib den Hartog',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444385,'John Rodrigues Garcia','Bas Langeveld',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444385,'Eric Feteridge','Martin van Rijsbergen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 4' and ssn_id like '2014%'),444387,'HOGEWOERD 3','SNOOKERIJ 10',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444387,'Debbie Anthonissen','Steve Course',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444387,'Michiel Peter Sjouke','Nico Seisveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444387,'Martijn Korner','Harry Bartels',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444387,'Debbie Anthonissen','Nico Seisveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444387,'Michiel Peter Sjouke','Harry Bartels',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444387,'Martijn Korner','Steve Course',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444387,'Martijn Korner','Nico Seisveld',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444387,'Michiel Peter Sjouke','Steve Course',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444387,'Debbie Anthonissen','Harry Bartels',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('01-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 4' and ssn_id like '2014%'),444388,'SNOOKERIJ 12','JUMBO 13',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444388,'Martin van Rijsbergen','Jeroen Keijzer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444388,'Huib den Hartog','Lea Lindhout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444388,'Bas Langeveld','Harry Vogelzang',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444388,'Martin van Rijsbergen','Lea Lindhout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444388,'Huib den Hartog','Harry Vogelzang',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444388,'Bas Langeveld','Jeroen Keijzer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444388,'Bas Langeveld','Lea Lindhout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444388,'Huib den Hartog','Jeroen Keijzer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444388,'Martin van Rijsbergen','Harry Vogelzang',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 4' and ssn_id like '2014%'),444390,'SNOOKERIJ 10','pocket 2',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444390,'Steve Course','Marcel van de Oever',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444390,'Nico Seisveld','Johan Keizer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444390,'Peter Hoekstra','Kees van Duijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444390,'Steve Course','Johan Keizer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444390,'Nico Seisveld','Kees van Duijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444390,'Peter Hoekstra','Marcel van de Oever',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444390,'Peter Hoekstra','Johan Keizer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444390,'Nico Seisveld','Marcel van de Oever',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444390,'Steve Course','Kees van Duijn',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 4' and ssn_id like '2014%'),444391,'OLD REBELS','SNOOKERIJ 10',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444391,'Eric Feteridge','Margot Olree',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444391,'John Rodrigues Garcia','Kitt van der Jagt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444391,'Jef Raber','Nico Seisveld',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444391,'Eric Feteridge','Kitt van der Jagt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444391,'John Rodrigues Garcia','Nico Seisveld',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444391,'Jef Raber','Margot Olree',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444391,'Jef Raber','Kitt van der Jagt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444391,'John Rodrigues Garcia','Margot Olree',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444391,'Eric Feteridge','Nico Seisveld',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 4' and ssn_id like '2014%'),444393,'pocket 2','HOGEWOERD 3',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444393,'Marcel van de Oever','Soerin Ganga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444393,'Thomas Glasbergen','Michiel Peter Sjouke',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444393,'Marcel van de Oever','Michiel Peter Sjouke',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444393,'Thomas Glasbergen','Debbie Anthonissen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444393,'Thomas Glasbergen','Soerin Ganga',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444393,'Marcel van de Oever','Debbie Anthonissen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 4' and ssn_id like '2014%'),444395,'HOGEWOERD 3','OLD REBELS',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444395,'Michiel Peter Sjouke','Eric Feteridge',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444395,'Soerin Ganga','Ed van den Berg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444395,'Debbie Anthonissen','Jef Raber',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444395,'Michiel Peter Sjouke','Ed van den Berg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444395,'Soerin Ganga','Jef Raber',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444395,'Debbie Anthonissen','Eric Feteridge',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444395,'Debbie Anthonissen','Ed van den Berg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444395,'Soerin Ganga','Eric Feteridge',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444395,'Michiel Peter Sjouke','Jef Raber',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 4' and ssn_id like '2014%'),444396,'SNOOKERIJ 10','JUMBO 13',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444396,'Harry Bartels','Anton Lindhout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444396,'Steve Course','Jeroen Keijzer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444396,'Nico Seisveld','Menno Beugelsdijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444396,'Harry Bartels','Jeroen Keijzer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444396,'Steve Course','Menno Beugelsdijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444396,'Nico Seisveld','Anton Lindhout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444396,'Nico Seisveld','Jeroen Keijzer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444396,'Steve Course','Anton Lindhout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444396,'Harry Bartels','Menno Beugelsdijk',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 4' and ssn_id like '2014%'),448431,'JUMBO 13','OLD REBELS',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 4' and ssn_id like '2014%'),444397,'SNOOKERIJ 12','SNOOKERIJ 10',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444397,'Bas Langeveld','Kitt van der Jagt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444397,'Martin van Rijsbergen','Nico Seisveld',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444397,'Ben den Dulk','Steve Course',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444397,'Bas Langeveld','Nico Seisveld',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444397,'Martin van Rijsbergen','Steve Course',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444397,'Ben den Dulk','Kitt van der Jagt',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444397,'Ben den Dulk','Nico Seisveld',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444397,'Martin van Rijsbergen','Kitt van der Jagt',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444397,'Bas Langeveld','Steve Course',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 4' and ssn_id like '2014%'),444398,'OLD REBELS','pocket 2',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444398,'Eric Feteridge','Johan Keizer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444398,'Ed van den Berg','Kees van Duijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444398,'John Rodrigues Garcia','Kees van Duijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444398,'Ed van den Berg','Johan Keizer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444398,'John Rodrigues Garcia','Johan Keizer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444398,'Eric Feteridge','Kees van Duijn',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 4' and ssn_id like '2014%'),444399,'JUMBO 13','HOGEWOERD 3',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444399,'Anton Lindhout','Martijn Korner',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444399,'Lea Lindhout','Michiel Peter Sjouke',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444399,'Harry Vogelzang','Debbie Anthonissen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444399,'Anton Lindhout','Michiel Peter Sjouke',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444399,'Lea Lindhout','Debbie Anthonissen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444399,'Harry Vogelzang','Martijn Korner',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444399,'Harry Vogelzang','Michiel Peter Sjouke',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444399,'Lea Lindhout','Martijn Korner',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444399,'Anton Lindhout','Debbie Anthonissen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 4' and ssn_id like '2014%'),444400,'pocket 2','JUMBO 13',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444400,'Marcel van de Oever','Harry Vogelzang',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444400,'Thomas Glasbergen','Menno Beugelsdijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444400,'Marcel van de Oever','Menno Beugelsdijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444400,'Thomas Glasbergen','Jeroen Keijzer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444400,'Thomas Glasbergen','Harry Vogelzang',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444400,'Marcel van de Oever','Jeroen Keijzer',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 4' and ssn_id like '2014%'),444401,'HOGEWOERD 3','SNOOKERIJ 12',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444401,'Michiel Peter Sjouke','Martin van Rijsbergen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444401,'Martijn Korner','Bas Langeveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444401,'Debbie Anthonissen','Huib den Hartog',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444401,'Michiel Peter Sjouke','Bas Langeveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444401,'Martijn Korner','Huib den Hartog',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444401,'Debbie Anthonissen','Martin van Rijsbergen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444401,'Debbie Anthonissen','Bas Langeveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444401,'Martijn Korner','Martin van Rijsbergen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444401,'Michiel Peter Sjouke','Huib den Hartog',1,0);
