delete from cm_match_details where game_id in (select game_id from cm_matches where cpn_id = (select id from cm_competitions where name = 'Combi 2e-3e klasse poule 5' and ssn_id like '2014%'));
delete from cm_matches where cpn_id = (select id from cm_competitions where name = 'Combi 2e-3e klasse poule 5' and ssn_id like '2014%');
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-09-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 5' and ssn_id like '2014%'),444403,'Hogewoerd 4','NNPV',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444403,'Piotr Nerka','Rob Molier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444403,'Ilja Steenhorst','Marco Roeleveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444403,'Laurens Steernberg','Ruud Heufke Kantelaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444403,'Piotr Nerka','Marco Roeleveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444403,'Ilja Steenhorst','Ruud Heufke Kantelaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444403,'Laurens Steernberg','Rob Molier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444403,'Laurens Steernberg','Marco Roeleveld',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444403,'Ilja Steenhorst','Rob Molier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444403,'Piotr Nerka','Ruud Heufke Kantelaar',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-09-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 5' and ssn_id like '2014%'),444903,'SNOOKERIJ 3','SNOOKERIJ 9',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 5' and ssn_id like '2014%'),444406,'SNOOKERIJ 4','SNOOKERIJ 3',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444406,'Hans van der Meijden','Pim Monteba',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444406,'Wally Hovens','Arjen Joosten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444406,'Jeroen van Kins','John van Ruiten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444406,'Hans van der Meijden','Arjen Joosten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444406,'Wally Hovens','John van Ruiten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444406,'Jeroen van Kins','Pim Monteba',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444406,'Jeroen van Kins','Arjen Joosten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444406,'Wally Hovens','Pim Monteba',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444406,'Hans van der Meijden','John van Ruiten',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 5' and ssn_id like '2014%'),444409,'NNPV','Jumbo 11',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 5' and ssn_id like '2014%'),444410,'Hogewoerd 4','SNOOKERIJ 9',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444410,'Thomas Janmaat','Patrick van der Hoorn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444410,'Ilja Steenhorst','Martijn Scholten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444410,'Piotr Nerka','Wilco Smit',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444410,'Thomas Janmaat','Martijn Scholten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444410,'Ilja Steenhorst','Wilco Smit',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444410,'Piotr Nerka','Patrick van der Hoorn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444410,'Piotr Nerka','Martijn Scholten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444410,'Ilja Steenhorst','Patrick van der Hoorn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444410,'Thomas Janmaat','Wilco Smit',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 5' and ssn_id like '2014%'),444414,'SNOOKERIJ 9','NNPV',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444414,'Martijn Scholten','Mark Molier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444414,'Bert van Hogeloon','Marco Roeleveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444414,'Wilco Smit','Nico van Veen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444414,'Martijn Scholten','Marco Roeleveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444414,'Bert van Hogeloon','Nico van Veen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444414,'Wilco Smit','Mark Molier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444414,'Wilco Smit','Marco Roeleveld',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444414,'Bert van Hogeloon','Mark Molier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444414,'Martijn Scholten','Nico van Veen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 5' and ssn_id like '2014%'),444413,'SNOOKERIJ 4','Hogewoerd 4',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444413,'René Bousie','Ilja Steenhorst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444413,'Hans van der Meijden','Emiel van der Hart',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444413,'Jeroen van Kins','Thomas Janmaat',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444413,'René Bousie','Emiel van der Hart',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444413,'Hans van der Meijden','Thomas Janmaat',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444413,'Jeroen van Kins','Ilja Steenhorst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444413,'Jeroen van Kins','Emiel van der Hart',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444413,'Hans van der Meijden','Ilja Steenhorst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444413,'René Bousie','Thomas Janmaat',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 5' and ssn_id like '2014%'),444415,'NNPV','SNOOKERIJ 4',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444415,'Rob Molier','Wally Hovens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444415,'Nico van Veen','Jeroen van Kins',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444415,'Ruud Heufke Kantelaar','René Bousie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444415,'Rob Molier','Jeroen van Kins',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444415,'Nico van Veen','René Bousie',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444415,'Ruud Heufke Kantelaar','Wally Hovens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444415,'Ruud Heufke Kantelaar','Jeroen van Kins',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444415,'Nico van Veen','Wally Hovens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444415,'Rob Molier','René Bousie',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 5' and ssn_id like '2014%'),444416,'Hogewoerd 4','SNOOKERIJ 3',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444416,'Piotr Nerka','Pim Monteba',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444416,'Ilja Steenhorst','Paul Verbaken',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444416,'Thomas Janmaat','Arjen Joosten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444416,'Piotr Nerka','Paul Verbaken',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444416,'Ilja Steenhorst','Arjen Joosten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444416,'Thomas Janmaat','Pim Monteba',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444416,'Thomas Janmaat','Paul Verbaken',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444416,'Ilja Steenhorst','Pim Monteba',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444416,'Piotr Nerka','Arjen Joosten',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 5' and ssn_id like '2014%'),444417,'Jumbo 11','SNOOKERIJ 9',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444417,'Matthijs Maandag','Martijn Scholten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444417,'Teije Blauw','Wilco Smit',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444417,'Peter Terhorst','Patrick van der Hoorn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444417,'Matthijs Maandag','Wilco Smit',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444417,'Teije Blauw','Patrick van der Hoorn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444417,'Peter Terhorst','Martijn Scholten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444417,'Peter Terhorst','Wilco Smit',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444417,'Teije Blauw','Martijn Scholten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444417,'Matthijs Maandag','Patrick van der Hoorn',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('30-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 5' and ssn_id like '2014%'),448195,'Jumbo 11','Hogewoerd 4',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448195,'Matthijs Maandag','Thomas Janmaat',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448195,'Teije Blauw','Ilja Steenhorst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448195,'Peter Terhorst','Laurens Steernberg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448195,'Matthijs Maandag','Ilja Steenhorst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448195,'Teije Blauw','Laurens Steernberg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448195,'Peter Terhorst','Thomas Janmaat',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448195,'Peter Terhorst','Ilja Steenhorst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448195,'Teije Blauw','Thomas Janmaat',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448195,'Matthijs Maandag','Laurens Steernberg',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 5' and ssn_id like '2014%'),444418,'SNOOKERIJ 3','NNPV',1,8);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 5' and ssn_id like '2014%'),444419,'SNOOKERIJ 4','Jumbo 11',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444419,'Hans van der Meijden','Teije Blauw',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444419,'René Bousie','Matthijs Maandag',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444419,'Jeroen van Kins','Peter Terhorst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444419,'Hans van der Meijden','Matthijs Maandag',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444419,'René Bousie','Peter Terhorst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444419,'Jeroen van Kins','Teije Blauw',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444419,'Jeroen van Kins','Matthijs Maandag',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444419,'René Bousie','Teije Blauw',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444419,'Hans van der Meijden','Peter Terhorst',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 5' and ssn_id like '2014%'),444422,'SNOOKERIJ 9','SNOOKERIJ 4',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444422,'Bert van Hogeloon','Wally Hovens',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444422,'Wilco Smit','Jeroen van Kins',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444422,'Patrick van der Hoorn','Hans van der Meijden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444422,'Bert van Hogeloon','Jeroen van Kins',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444422,'Wilco Smit','Hans van der Meijden',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444422,'Patrick van der Hoorn','Wally Hovens',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444422,'Patrick van der Hoorn','Jeroen van Kins',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444422,'Wilco Smit','Wally Hovens',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444422,'Bert van Hogeloon','Hans van der Meijden',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 5' and ssn_id like '2014%'),444423,'Jumbo 11','SNOOKERIJ 3',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444423,'Teije Blauw','Pim Monteba',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444423,'Peter Terhorst','Peter Stoute',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444423,'Daniël Alferink','John van Ruiten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444423,'Teije Blauw','Peter Stoute',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444423,'Peter Terhorst','John van Ruiten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444423,'Daniël Alferink','Pim Monteba',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444423,'Daniël Alferink','Peter Stoute',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444423,'Peter Terhorst','Pim Monteba',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444423,'Teije Blauw','John van Ruiten',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 5' and ssn_id like '2014%'),444424,'NNPV','Hogewoerd 4',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 5' and ssn_id like '2014%'),444425,'SNOOKERIJ 9','SNOOKERIJ 3',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444425,'Bert van Hogeloon','Arjen Joosten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444425,'Wilco Smit','Peter Stoute',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444425,'Patrick van der Hoorn','Pim Monteba',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444425,'Bert van Hogeloon','Peter Stoute',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444425,'Wilco Smit','Pim Monteba',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444425,'Patrick van der Hoorn','Arjen Joosten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444425,'Patrick van der Hoorn','Peter Stoute',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444425,'Wilco Smit','Arjen Joosten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444425,'Bert van Hogeloon','Pim Monteba',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('25-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 5' and ssn_id like '2014%'),444427,'Hogewoerd 4','Jumbo 11',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444427,'Laurens Steernberg','Peter Terhorst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444427,'Thomas Janmaat','Matthijs Maandag',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444427,'Emiel van der Hart','Teije Blauw',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444427,'Laurens Steernberg','Matthijs Maandag',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444427,'Thomas Janmaat','Teije Blauw',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444427,'Emiel van der Hart','Peter Terhorst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444427,'Emiel van der Hart','Matthijs Maandag',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444427,'Thomas Janmaat','Peter Terhorst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444427,'Laurens Steernberg','Teije Blauw',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('25-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 5' and ssn_id like '2014%'),444428,'SNOOKERIJ 3','SNOOKERIJ 4',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444428,'Pim Monteba','Aat Smits',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444428,'Peter Stoute','Wally Hovens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444428,'John van Ruiten','Hans van der Meijden',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444428,'Pim Monteba','Wally Hovens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444428,'Peter Stoute','Hans van der Meijden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444428,'John van Ruiten','Aat Smits',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444428,'John van Ruiten','Wally Hovens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444428,'Peter Stoute','Aat Smits',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444428,'Pim Monteba','Hans van der Meijden',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 5' and ssn_id like '2014%'),444431,'SNOOKERIJ 9','Hogewoerd 4',1,8);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 5' and ssn_id like '2014%'),444432,'Jumbo 11','NNPV',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444432,'Daniël Alferink','Mark Molier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444432,'Fedde Cadee','Nico van Veen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444432,'Matthijs Maandag','Marco Roeleveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444432,'Daniël Alferink','Nico van Veen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444432,'Fedde Cadee','Marco Roeleveld',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444432,'Matthijs Maandag','Mark Molier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444432,'Matthijs Maandag','Nico van Veen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444432,'Fedde Cadee','Mark Molier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444432,'Daniël Alferink','Marco Roeleveld',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 5' and ssn_id like '2014%'),444433,'NNPV','SNOOKERIJ 9',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 5' and ssn_id like '2014%'),444434,'Hogewoerd 4','SNOOKERIJ 4',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444434,'Emiel van der Hart','Aat Smits',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444434,'Piotr Nerka','Wally Hovens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444434,'Ilja Steenhorst','Hans van der Meijden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444434,'Emiel van der Hart','Wally Hovens',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444434,'Piotr Nerka','Hans van der Meijden',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444434,'Ilja Steenhorst','Aat Smits',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444434,'Ilja Steenhorst','Wally Hovens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444434,'Piotr Nerka','Aat Smits',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444434,'Emiel van der Hart','Hans van der Meijden',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 5' and ssn_id like '2014%'),444438,'SNOOKERIJ 9','Jumbo 11',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444438,'Bert van Hogeloon','Peter Terhorst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444438,'Wilco Smit','Daniël Alferink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444438,'Patrick van der Hoorn','Teije Blauw',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444438,'Bert van Hogeloon','Daniël Alferink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444438,'Wilco Smit','Teije Blauw',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444438,'Patrick van der Hoorn','Peter Terhorst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444438,'Patrick van der Hoorn','Daniël Alferink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444438,'Wilco Smit','Peter Terhorst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444438,'Bert van Hogeloon','Teije Blauw',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 5' and ssn_id like '2014%'),444437,'SNOOKERIJ 4','NNPV',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 5' and ssn_id like '2014%'),448455,'SNOOKERIJ 3','Hogewoerd 4',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448455,'John van Ruiten','Ilja Steenhorst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448455,'Peter Stoute','Emiel van der Hart',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448455,'Pim Monteba','Piotr Nerka',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448455,'John van Ruiten','Emiel van der Hart',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448455,'Peter Stoute','Piotr Nerka',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448455,'Pim Monteba','Ilja Steenhorst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448455,'Pim Monteba','Emiel van der Hart',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448455,'Peter Stoute','Ilja Steenhorst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448455,'John van Ruiten','Piotr Nerka',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 5' and ssn_id like '2014%'),444439,'NNPV','SNOOKERIJ 3',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444439,'Mark Molier','Pim Monteba',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444439,'Rob Molier','Peter Stoute',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444439,'Ruud Heufke Kantelaar','John van Ruiten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444439,'Mark Molier','Peter Stoute',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444439,'Rob Molier','John van Ruiten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444439,'Ruud Heufke Kantelaar','Pim Monteba',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444439,'Ruud Heufke Kantelaar','Peter Stoute',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444439,'Rob Molier','Pim Monteba',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444439,'Mark Molier','John van Ruiten',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 5' and ssn_id like '2014%'),444441,'Jumbo 11','SNOOKERIJ 4',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444441,'Matthijs Maandag','Aat Smits',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444441,'Peter Terhorst','Jeroen van Kins',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444441,'Fedde Cadee','Hans van der Meijden',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444441,'Matthijs Maandag','Jeroen van Kins',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444441,'Peter Terhorst','Hans van der Meijden',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444441,'Fedde Cadee','Aat Smits',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444441,'Fedde Cadee','Jeroen van Kins',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444441,'Peter Terhorst','Aat Smits',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444441,'Matthijs Maandag','Hans van der Meijden',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 5' and ssn_id like '2014%'),444442,'SNOOKERIJ 3','Jumbo 11',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444442,'Pim Monteba','Peter Terhorst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444442,'John van Ruiten','Matthijs Maandag',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444442,'Peter Stoute','Teije Blauw',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444442,'Pim Monteba','Matthijs Maandag',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444442,'John van Ruiten','Teije Blauw',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444442,'Peter Stoute','Peter Terhorst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444442,'Peter Stoute','Matthijs Maandag',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444442,'John van Ruiten','Peter Terhorst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444442,'Pim Monteba','Teije Blauw',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 5' and ssn_id like '2014%'),444443,'SNOOKERIJ 4','SNOOKERIJ 9',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444443,'René Bousie','Wilco Smit',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444443,'Hans van der Meijden','Patrick van der Hoorn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444443,'Wally Hovens','Martijn Scholten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444443,'René Bousie','Patrick van der Hoorn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444443,'Hans van der Meijden','Martijn Scholten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444443,'Wally Hovens','Wilco Smit',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444443,'Wally Hovens','Patrick van der Hoorn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444443,'Hans van der Meijden','Wilco Smit',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444443,'René Bousie','Martijn Scholten',1,0);
