delete from cm_match_details where game_id in (select game_id from cm_matches where cpn_id = (select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 2' and ssn_id like '2014%'));
delete from cm_matches where cpn_id = (select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 2' and ssn_id like '2014%');
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-09-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 2' and ssn_id like '2014%'),443981,'SNOOKERIJ 1','SNOOKERIJ 5',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443981,'Jeffrey Laterveer','Jan van Amsterdam',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443981,'Hans van Ommeren','Pascal Hendrikse',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443981,'Aad Wijsman','Robert van Nieuwkoop',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443981,'Jeffrey Laterveer','Pascal Hendrikse',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443981,'Hans van Ommeren','Robert van Nieuwkoop',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443981,'Aad Wijsman','Jan van Amsterdam',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443981,'Aad Wijsman','Pascal Hendrikse',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443981,'Hans van Ommeren','Jan van Amsterdam',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443981,'Jeffrey Laterveer','Robert van Nieuwkoop',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-09-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 2' and ssn_id like '2014%'),443982,'Snooker Utrecht I','HOGEWOERD 1',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443982,'Django den Hartog','Akhi Kalicharan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443982,'Jasha Kiers','Shiraz Nasrullah',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443982,'Mark Koppert','Parkash Kalicharan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443982,'Django den Hartog','Shiraz Nasrullah',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443982,'Jasha Kiers','Parkash Kalicharan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443982,'Mark Koppert','Akhi Kalicharan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443982,'Mark Koppert','Shiraz Nasrullah',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443982,'Jasha Kiers','Akhi Kalicharan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443982,'Django den Hartog','Parkash Kalicharan',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-09-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 2' and ssn_id like '2014%'),443984,'Hippo 1','Final Touch 3',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443984,'Ruud de Wit','Sten van Schaik',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443984,'Marco Eisinga','Dion Meuwsen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443984,'Ruud de Wit','Michel Knol',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443984,'Marco Eisinga','Sten van Schaik',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443984,'Marco Eisinga','Michel Knol',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443984,'Ruud de Wit','Dion Meuwsen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('29-09-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 2' and ssn_id like '2014%'),443985,'Final Touch 3','Snooker Utrecht I',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443985,'Albert Papot','Pierre Linschoten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443985,'Wouter Kager','Mark Koppert',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443985,'Dion Meuwsen','Michel de Sain',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443985,'Albert Papot','Mark Koppert',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443985,'Wouter Kager','Michel de Sain',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443985,'Dion Meuwsen','Pierre Linschoten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443985,'Dion Meuwsen','Mark Koppert',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443985,'Wouter Kager','Pierre Linschoten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443985,'Albert Papot','Michel de Sain',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('30-09-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 2' and ssn_id like '2014%'),443987,'HOGEWOERD 1','JUMBO 3',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443987,'André Vuijk','Rob Oudshoorn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443987,'Shiraz Nasrullah','Frank de Rooij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443987,'Parkash Kalicharan','Frank de Rooij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443987,'Shiraz Nasrullah','Rob Oudshoorn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443987,'Parkash Kalicharan','Rob Oudshoorn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443987,'André Vuijk','Frank de Rooij',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 2' and ssn_id like '2014%'),443988,'SNOOKERIJ 5','Hippo 1',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 2' and ssn_id like '2014%'),443989,'SNOOKERIJ 1','HOGEWOERD 1',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 2' and ssn_id like '2014%'),443990,'Final Touch 3','SNOOKERIJ 5',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443990,'Wouter Kager','Pascal Hendrikse',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443990,'Michel Knol','Joris Scharpff',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443990,'Sten van Schaik','Pascal Hendrikse',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443990,'Wouter Kager','Joris Scharpff',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443990,'Michel Knol','Pascal Hendrikse',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443990,'Sten van Schaik','Joris Scharpff',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 2' and ssn_id like '2014%'),443995,'JUMBO 3','SNOOKERIJ 1',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 2' and ssn_id like '2014%'),443996,'SNOOKERIJ 5','Snooker Utrecht I',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 2' and ssn_id like '2014%'),443998,'Snooker Utrecht I','SNOOKERIJ 1',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443998,'Django den Hartog','Hans van Ommeren',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443998,'Pierre Linschoten','Coen Drejer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443998,'Mark Koppert','Hans de Heer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443998,'Django den Hartog','Coen Drejer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443998,'Pierre Linschoten','Hans de Heer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443998,'Mark Koppert','Hans van Ommeren',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443998,'Mark Koppert','Coen Drejer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443998,'Pierre Linschoten','Hans van Ommeren',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443998,'Django den Hartog','Hans de Heer',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 2' and ssn_id like '2014%'),444000,'Hippo 1','JUMBO 3',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444000,'Olivier Hensing','Frank de Rooij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444000,'Marco Eisinga','Frank de Rooij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444000,'Ruud de Wit','Frank de Rooij',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 2' and ssn_id like '2014%'),448229,'Final Touch 3','HOGEWOERD 1',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448229,'Wouter Kager','André Vuijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448229,'Dion Meuwsen','Shiraz Nasrullah',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448229,'Michel Knol','Parkash Kalicharan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448229,'Wouter Kager','Shiraz Nasrullah',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448229,'Dion Meuwsen','Parkash Kalicharan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448229,'Michel Knol','André Vuijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448229,'Michel Knol','Shiraz Nasrullah',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448229,'Dion Meuwsen','André Vuijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448229,'Wouter Kager','Parkash Kalicharan',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 2' and ssn_id like '2014%'),444001,'SNOOKERIJ 1','Hippo 1',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 2' and ssn_id like '2014%'),444003,'HOGEWOERD 1','SNOOKERIJ 5',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444003,'Shiraz Nasrullah','Joris Scharpff',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444003,'Parkash Kalicharan','Pascal Hendrikse',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444003,'André Vuijk','Aram Raken',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444003,'Shiraz Nasrullah','Pascal Hendrikse',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444003,'Parkash Kalicharan','Aram Raken',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444003,'André Vuijk','Joris Scharpff',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444003,'André Vuijk','Pascal Hendrikse',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444003,'Parkash Kalicharan','Joris Scharpff',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444003,'Shiraz Nasrullah','Aram Raken',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 2' and ssn_id like '2014%'),444004,'JUMBO 3','Final Touch 3',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444004,'Frank de Rooij','Dion Meuwsen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444004,'Rob Oudshoorn','Sten van Schaik',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444004,'Frank de Rooij','Sten van Schaik',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444004,'Rob Oudshoorn','Tens Tensen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444004,'Rob Oudshoorn','Dion Meuwsen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444004,'Frank de Rooij','Tens Tensen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 2' and ssn_id like '2014%'),444005,'Final Touch 3','SNOOKERIJ 1',0,9);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 2' and ssn_id like '2014%'),444008,'SNOOKERIJ 5','JUMBO 3',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 2' and ssn_id like '2014%'),444009,'Final Touch 3','Hippo 1',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444009,'Sten van Schaik','Marco Eisinga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444009,'Davis Wong','Ruud de Wit',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444009,'Michel Knol','Olivier Hensing',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444009,'Sten van Schaik','Ruud de Wit',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444009,'Davis Wong','Olivier Hensing',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444009,'Michel Knol','Marco Eisinga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444009,'Michel Knol','Ruud de Wit',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444009,'Davis Wong','Marco Eisinga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444009,'Sten van Schaik','Olivier Hensing',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 2' and ssn_id like '2014%'),444011,'HOGEWOERD 1','Snooker Utrecht I',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 2' and ssn_id like '2014%'),444012,'SNOOKERIJ 5','SNOOKERIJ 1',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('25-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 2' and ssn_id like '2014%'),444014,'Snooker Utrecht I','Final Touch 3',9,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444014,'Mark Koppert','Wouter Kager',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444014,'Pierre Linschoten','Michel Knol',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444014,'Django den Hartog','Sten van Schaik',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444014,'Mark Koppert','Michel Knol',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444014,'Pierre Linschoten','Sten van Schaik',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444014,'Django den Hartog','Wouter Kager',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444014,'Django den Hartog','Michel Knol',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444014,'Pierre Linschoten','Wouter Kager',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444014,'Mark Koppert','Sten van Schaik',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('26-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 2' and ssn_id like '2014%'),444015,'JUMBO 3','HOGEWOERD 1',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('28-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 2' and ssn_id like '2014%'),444016,'Hippo 1','SNOOKERIJ 5',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 2' and ssn_id like '2014%'),444018,'HOGEWOERD 1','SNOOKERIJ 1',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444018,'Shiraz Nasrullah','Jeffrey Laterveer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444018,'Parkash Kalicharan','Aad Wijsman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444018,'André Vuijk','Coen Drejer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444018,'Shiraz Nasrullah','Aad Wijsman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444018,'Parkash Kalicharan','Coen Drejer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444018,'André Vuijk','Jeffrey Laterveer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444018,'André Vuijk','Aad Wijsman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444018,'Parkash Kalicharan','Jeffrey Laterveer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444018,'Shiraz Nasrullah','Coen Drejer',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 2' and ssn_id like '2014%'),444019,'JUMBO 3','Snooker Utrecht I',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444019,'Rob Oudshoorn','Mark Koppert',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444019,'Rob Oudshoorn','Michel de Sain',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444019,'Rob Oudshoorn','Django den Hartog',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 2' and ssn_id like '2014%'),444020,'SNOOKERIJ 5','Final Touch 3',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 2' and ssn_id like '2014%'),444021,'SNOOKERIJ 1','JUMBO 3',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444021,'Hans de Heer','Frank de Rooij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444021,'Aad Wijsman','Rob Oudshoorn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444021,'Coen Drejer','Rob Oudshoorn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444021,'Aad Wijsman','Frank de Rooij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444021,'Coen Drejer','Frank de Rooij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444021,'Hans de Heer','Rob Oudshoorn',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 2' and ssn_id like '2014%'),444023,'Snooker Utrecht I','SNOOKERIJ 5',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444023,'Thomas Verheij','Joris Scharpff',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444023,'Django den Hartog','Pascal Hendrikse',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444023,'Pierre Linschoten','Jan van Amsterdam',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444023,'Thomas Verheij','Pascal Hendrikse',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444023,'Django den Hartog','Jan van Amsterdam',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444023,'Pierre Linschoten','Joris Scharpff',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444023,'Pierre Linschoten','Pascal Hendrikse',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444023,'Django den Hartog','Joris Scharpff',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444023,'Thomas Verheij','Jan van Amsterdam',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 2' and ssn_id like '2014%'),444024,'Hippo 1','HOGEWOERD 1',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444024,'Ruud de Wit','Akhi Kalicharan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444024,'Benno Lier','Parkash Kalicharan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444024,'Naut Bruns','Parkash Kalicharan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444024,'Benno Lier','Akhi Kalicharan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444024,'Naut Bruns','Akhi Kalicharan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444024,'Ruud de Wit','Parkash Kalicharan',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 2' and ssn_id like '2014%'),444025,'SNOOKERIJ 1','Snooker Utrecht I',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444025,'Aad Wijsman','Michel de Sain',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444025,'Hans van Ommeren','Mark Koppert',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444025,'Michel Noorduin','Pierre Linschoten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444025,'Aad Wijsman','Mark Koppert',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444025,'Hans van Ommeren','Pierre Linschoten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444025,'Michel Noorduin','Michel de Sain',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444025,'Michel Noorduin','Mark Koppert',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444025,'Hans van Ommeren','Michel de Sain',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444025,'Aad Wijsman','Pierre Linschoten',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 2' and ssn_id like '2014%'),448425,'Snooker Utrecht I','Hippo 1',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448425,'Django den Hartog','Ruud de Wit',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448425,'Pierre Linschoten','Olivier Hensing',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448425,'Django den Hartog','Olivier Hensing',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448425,'Mark Koppert','Ruud de Wit',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448425,'Mark Koppert','Olivier Hensing',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448425,'Pierre Linschoten','Ruud de Wit',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 2' and ssn_id like '2014%'),444027,'HOGEWOERD 1','Final Touch 3',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 2' and ssn_id like '2014%'),444028,'JUMBO 3','Hippo 1',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 2' and ssn_id like '2014%'),448424,'Snooker Utrecht I','JUMBO 3',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448424,'Django den Hartog','Rob Oudshoorn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448424,'Mark Koppert','Frank de Rooij',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448424,'Mark Koppert','Rob Oudshoorn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448424,'Django den Hartog','Frank de Rooij',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 2' and ssn_id like '2014%'),448480,'HOGEWOERD 1','Hippo 1',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448480,'Shiraz Nasrullah','Marco Eisinga',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448480,'Parkash Kalicharan','Maurits Engelen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448480,'André Vuijk','Ruud de Wit',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448480,'Shiraz Nasrullah','Maurits Engelen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448480,'Parkash Kalicharan','Ruud de Wit',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448480,'André Vuijk','Marco Eisinga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448480,'André Vuijk','Maurits Engelen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448480,'Parkash Kalicharan','Marco Eisinga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448480,'Shiraz Nasrullah','Ruud de Wit',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 2' and ssn_id like '2014%'),444029,'Final Touch 3','JUMBO 3',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 2' and ssn_id like '2014%'),444031,'SNOOKERIJ 5','HOGEWOERD 1',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 2' and ssn_id like '2014%'),444032,'Hippo 1','SNOOKERIJ 1',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444032,'Ruud de Wit','Aad Wijsman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444032,'Olivier Hensing','Coen Drejer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444032,'Marco Eisinga','Hans de Heer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444032,'Ruud de Wit','Coen Drejer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444032,'Olivier Hensing','Hans de Heer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444032,'Marco Eisinga','Aad Wijsman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444032,'Marco Eisinga','Coen Drejer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444032,'Olivier Hensing','Aad Wijsman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444032,'Ruud de Wit','Hans de Heer',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 2' and ssn_id like '2014%'),444033,'SNOOKERIJ 1','Final Touch 3',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 2' and ssn_id like '2014%'),444035,'JUMBO 3','SNOOKERIJ 5',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 2' and ssn_id like '2014%'),444036,'Hippo 1','Snooker Utrecht I',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444036,'Marco Eisinga','Pierre Linschoten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444036,'Naut Bruns','Mark Koppert',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444036,'Ruud de Wit','Jasha Kiers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444036,'Marco Eisinga','Mark Koppert',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444036,'Naut Bruns','Jasha Kiers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444036,'Ruud de Wit','Pierre Linschoten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444036,'Ruud de Wit','Mark Koppert',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444036,'Naut Bruns','Pierre Linschoten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444036,'Marco Eisinga','Jasha Kiers',1,0);
