delete from cm_match_details where game_id in (select game_id from cm_matches where cpn_id = (select id from cm_competitions where name = 'Combi Hoofdklasse-1e klasse poule 1' and ssn_id like '2014%'));
delete from cm_matches where cpn_id = (select id from cm_competitions where name = 'Combi Hoofdklasse-1e klasse poule 1' and ssn_id like '2014%');
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-09-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e klasse poule 1' and ssn_id like '2014%'),443925,'Sloten 1','Alkmaar 4',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443925,'Bobby Jahangir','Sjoerd Blondeel Timmerman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443925,'Norman Nowrozy','Eric van der Zwan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443925,'Chi Kwong Wu','Laurens van Deijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443925,'Bobby Jahangir','Eric van der Zwan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443925,'Norman Nowrozy','Laurens van Deijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443925,'Chi Kwong Wu','Sjoerd Blondeel Timmerman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443925,'Chi Kwong Wu','Eric van der Zwan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443925,'Norman Nowrozy','Sjoerd Blondeel Timmerman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443925,'Bobby Jahangir','Laurens van Deijk',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('01-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e klasse poule 1' and ssn_id like '2014%'),443929,'Koetshuys 1','Sloten 1',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443929,'Marco Kuperus','Norman Nowrozy',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443929,'Sander Nijssen','Adrie Voskuil',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443929,'Hans Reijerkerk','Peter Rath',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443929,'Marco Kuperus','Adrie Voskuil',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443929,'Sander Nijssen','Peter Rath',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443929,'Hans Reijerkerk','Norman Nowrozy',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443929,'Hans Reijerkerk','Adrie Voskuil',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443929,'Sander Nijssen','Norman Nowrozy',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443929,'Marco Kuperus','Peter Rath',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e klasse poule 1' and ssn_id like '2014%'),443930,'Alkmaar 4','Tasmanian Devils',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e klasse poule 1' and ssn_id like '2014%'),443931,'Sneeuwwitje e/d 7 dwergen','Westend 2',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443931,'Ronald Peeters','Wellington Lie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443931,'Robert Tump','Kim Fai Sung',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443931,'Richard van Leeuwen','Simon Reuter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443931,'Ronald Peeters','Kim Fai Sung',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443931,'Robert Tump','Simon Reuter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443931,'Richard van Leeuwen','Wellington Lie',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443931,'Richard van Leeuwen','Kim Fai Sung',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443931,'Robert Tump','Wellington Lie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443931,'Ronald Peeters','Simon Reuter',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e klasse poule 1' and ssn_id like '2014%'),443933,'Sloten 1','Tasmanian Devils',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443933,'Bobby Jahangir','Ronald Rennen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443933,'Chi Kwong Wu','Davith Denes Hiwat',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443933,'Peter Rath','Hilbrand Barkema',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443933,'Bobby Jahangir','Davith Denes Hiwat',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443933,'Chi Kwong Wu','Hilbrand Barkema',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443933,'Peter Rath','Ronald Rennen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443933,'Peter Rath','Davith Denes Hiwat',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443933,'Chi Kwong Wu','Ronald Rennen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443933,'Bobby Jahangir','Hilbrand Barkema',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e klasse poule 1' and ssn_id like '2014%'),443935,'FINAL TOUCH 2','Sneeuwwitje e/d 7 dwergen',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443935,'David Lucieer','Ronald Peeters',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443935,'Albert Pronk','René Verheyden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443935,'Martijn Lesterhuis','Rob Kanninga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443935,'David Lucieer','René Verheyden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443935,'Albert Pronk','Rob Kanninga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443935,'Martijn Lesterhuis','Ronald Peeters',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443935,'Martijn Lesterhuis','René Verheyden',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443935,'Albert Pronk','Ronald Peeters',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443935,'David Lucieer','Rob Kanninga',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e klasse poule 1' and ssn_id like '2014%'),443936,'Westend 2','Alkmaar 4',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443936,'Simon Reuter','Rick van Houten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443936,'Henk van Hooff','Eric van der Zwan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443936,'Marc Nieuweboer','Sjoerd Blondeel Timmerman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443936,'Simon Reuter','Eric van der Zwan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443936,'Henk van Hooff','Sjoerd Blondeel Timmerman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443936,'Marc Nieuweboer','Rick van Houten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443936,'Marc Nieuweboer','Eric van der Zwan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443936,'Henk van Hooff','Rick van Houten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443936,'Simon Reuter','Sjoerd Blondeel Timmerman',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e klasse poule 1' and ssn_id like '2014%'),443937,'Alkmaar 4','FINAL TOUCH 2',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e klasse poule 1' and ssn_id like '2014%'),443938,'Sneeuwwitje e/d 7 dwergen','Koetshuys 1',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443938,'René Verheyden','Marco Kuperus',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443938,'Robert Tump','Hans Reijerkerk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443938,'Rob Kanninga','Richard Kiljan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443938,'René Verheyden','Hans Reijerkerk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443938,'Robert Tump','Richard Kiljan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443938,'Rob Kanninga','Marco Kuperus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443938,'Rob Kanninga','Hans Reijerkerk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443938,'Robert Tump','Marco Kuperus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443938,'René Verheyden','Richard Kiljan',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e klasse poule 1' and ssn_id like '2014%'),443940,'Tasmanian Devils','Westend 2',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443940,'Rik van Winsum','Kim Fai Sung',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443940,'Ben Harvey','Marc Nieuweboer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443940,'Ronald Rennen','Wellington Lie',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443940,'Rik van Winsum','Marc Nieuweboer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443940,'Ben Harvey','Wellington Lie',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443940,'Ronald Rennen','Kim Fai Sung',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443940,'Ronald Rennen','Marc Nieuweboer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443940,'Ben Harvey','Kim Fai Sung',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443940,'Rik van Winsum','Wellington Lie',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e klasse poule 1' and ssn_id like '2014%'),443941,'Sloten 1','Westend 2',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443941,'Bobby Jahangir','Simon Reuter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443941,'Norman Nowrozy','Kim Fai Sung',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443941,'Peter Rath','Marc Nieuweboer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443941,'Bobby Jahangir','Kim Fai Sung',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443941,'Norman Nowrozy','Marc Nieuweboer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443941,'Peter Rath','Simon Reuter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443941,'Peter Rath','Kim Fai Sung',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443941,'Norman Nowrozy','Simon Reuter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443941,'Bobby Jahangir','Marc Nieuweboer',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e klasse poule 1' and ssn_id like '2014%'),443942,'Koetshuys 1','Alkmaar 4',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443942,'Sander Nijssen','Rick van Houten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443942,'Richard Kiljan','Eric van der Zwan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443942,'Hans Reijerkerk','Sjoerd Blondeel Timmerman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443942,'Sander Nijssen','Eric van der Zwan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443942,'Richard Kiljan','Sjoerd Blondeel Timmerman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443942,'Hans Reijerkerk','Rick van Houten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443942,'Hans Reijerkerk','Eric van der Zwan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443942,'Richard Kiljan','Rick van Houten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443942,'Sander Nijssen','Sjoerd Blondeel Timmerman',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e klasse poule 1' and ssn_id like '2014%'),443943,'FINAL TOUCH 2','Tasmanian Devils',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443943,'Albert Pronk','Davith Denes Hiwat',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443943,'David Lucieer','Ronald Rennen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443943,'Eric van Lokven','Kevin Slotboom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443943,'Albert Pronk','Ronald Rennen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443943,'David Lucieer','Kevin Slotboom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443943,'Eric van Lokven','Davith Denes Hiwat',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443943,'Eric van Lokven','Ronald Rennen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443943,'David Lucieer','Davith Denes Hiwat',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443943,'Albert Pronk','Kevin Slotboom',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('30-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e klasse poule 1' and ssn_id like '2014%'),448226,'FINAL TOUCH 2','Koetshuys 1',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448226,'Eric van Lokven','Richard Kiljan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448226,'Arnoud de la Mar','Marco Kuperus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448226,'David Lucieer','Hans Reijerkerk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448226,'Eric van Lokven','Marco Kuperus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448226,'Arnoud de la Mar','Hans Reijerkerk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448226,'David Lucieer','Richard Kiljan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448226,'David Lucieer','Marco Kuperus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448226,'Arnoud de la Mar','Richard Kiljan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448226,'Eric van Lokven','Hans Reijerkerk',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('01-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e klasse poule 1' and ssn_id like '2014%'),448216,'Tasmanian Devils','Sneeuwwitje e/d 7 dwergen',0,9);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448216,'Ben Harvey','Hennie van Houten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448216,'Raphael Murray','René Verheyden',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448216,'Ronald Rennen','Ronald Peeters',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448216,'Ben Harvey','René Verheyden',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448216,'Raphael Murray','Ronald Peeters',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448216,'Ronald Rennen','Hennie van Houten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448216,'Ronald Rennen','René Verheyden',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448216,'Raphael Murray','Hennie van Houten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448216,'Ben Harvey','Ronald Peeters',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e klasse poule 1' and ssn_id like '2014%'),443945,'Westend 2','FINAL TOUCH 2',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443945,'Simon Reuter','Martijn Lesterhuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443945,'Marc Nieuweboer','Eric van Lokven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443945,'Kim Fai Sung','Arnoud de la Mar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443945,'Simon Reuter','Eric van Lokven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443945,'Marc Nieuweboer','Arnoud de la Mar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443945,'Kim Fai Sung','Martijn Lesterhuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443945,'Kim Fai Sung','Eric van Lokven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443945,'Marc Nieuweboer','Martijn Lesterhuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443945,'Simon Reuter','Arnoud de la Mar',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e klasse poule 1' and ssn_id like '2014%'),443947,'Sneeuwwitje e/d 7 dwergen','Sloten 1',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443947,'René Verheyden','Peter Rath',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443947,'Ronald Peeters','Norman Nowrozy',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443947,'Robert Tump','Bobby Jahangir',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443947,'René Verheyden','Norman Nowrozy',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443947,'Ronald Peeters','Bobby Jahangir',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443947,'Robert Tump','Peter Rath',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443947,'Robert Tump','Norman Nowrozy',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443947,'Ronald Peeters','Peter Rath',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443947,'René Verheyden','Bobby Jahangir',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e klasse poule 1' and ssn_id like '2014%'),443948,'Tasmanian Devils','Koetshuys 1',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443948,'Kevin Slotboom','Sander Nijssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443948,'Ben Harvey','Marco Kuperus',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443948,'Ronald Rennen','Hans Reijerkerk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443948,'Kevin Slotboom','Marco Kuperus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443948,'Ben Harvey','Hans Reijerkerk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443948,'Ronald Rennen','Sander Nijssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443948,'Ronald Rennen','Marco Kuperus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443948,'Ben Harvey','Sander Nijssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443948,'Kevin Slotboom','Hans Reijerkerk',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e klasse poule 1' and ssn_id like '2014%'),443949,'Sloten 1','FINAL TOUCH 2',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443949,'Adrie Voskuil','Arnoud de la Mar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443949,'Bobby Jahangir','David Lucieer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443949,'Peter Rath','Albert Pronk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443949,'Adrie Voskuil','David Lucieer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443949,'Bobby Jahangir','Albert Pronk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443949,'Peter Rath','Arnoud de la Mar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443949,'Peter Rath','David Lucieer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443949,'Bobby Jahangir','Arnoud de la Mar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443949,'Adrie Voskuil','Albert Pronk',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e klasse poule 1' and ssn_id like '2014%'),443951,'Sneeuwwitje e/d 7 dwergen','Alkmaar 4',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e klasse poule 1' and ssn_id like '2014%'),448335,'Koetshuys 1','Westend 2',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448335,'Marco Kuperus','Marc Nieuweboer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448335,'Sander Nijssen','Simon Reuter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448335,'Hans Reijerkerk','Wellington Lie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448335,'Marco Kuperus','Simon Reuter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448335,'Sander Nijssen','Wellington Lie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448335,'Hans Reijerkerk','Marc Nieuweboer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448335,'Hans Reijerkerk','Simon Reuter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448335,'Sander Nijssen','Marc Nieuweboer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448335,'Marco Kuperus','Wellington Lie',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e klasse poule 1' and ssn_id like '2014%'),443954,'Alkmaar 4','Sloten 1',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443954,'Eric van der Zwan','Bobby Jahangir',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443954,'Laurens van Deijk','Peter Rath',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443954,'Sjoerd Blondeel Timmerman','Adrie Voskuil',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443954,'Eric van der Zwan','Peter Rath',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443954,'Laurens van Deijk','Adrie Voskuil',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443954,'Sjoerd Blondeel Timmerman','Bobby Jahangir',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443954,'Sjoerd Blondeel Timmerman','Peter Rath',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443954,'Laurens van Deijk','Bobby Jahangir',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443954,'Eric van der Zwan','Adrie Voskuil',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('25-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e klasse poule 1' and ssn_id like '2014%'),443957,'Sloten 1','Koetshuys 1',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443957,'Adrie Voskuil','Marco Kuperus',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443957,'Norman Nowrozy','Hans Reijerkerk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443957,'Peter Rath','Richard Kiljan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443957,'Adrie Voskuil','Hans Reijerkerk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443957,'Norman Nowrozy','Richard Kiljan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443957,'Peter Rath','Marco Kuperus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443957,'Peter Rath','Hans Reijerkerk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443957,'Norman Nowrozy','Marco Kuperus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443957,'Adrie Voskuil','Richard Kiljan',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e klasse poule 1' and ssn_id like '2014%'),443959,'Westend 2','Sneeuwwitje e/d 7 dwergen',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443959,'Simon Reuter','Rob Kanninga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443959,'Kim Fai Sung','René Verheyden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443959,'Marc Nieuweboer','Robert Tump',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443959,'Simon Reuter','René Verheyden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443959,'Kim Fai Sung','Robert Tump',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443959,'Marc Nieuweboer','Rob Kanninga',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443959,'Marc Nieuweboer','René Verheyden',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443959,'Kim Fai Sung','Rob Kanninga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443959,'Simon Reuter','Robert Tump',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e klasse poule 1' and ssn_id like '2014%'),443961,'Alkmaar 4','Westend 2',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443961,'Sjoerd Blondeel Timmerman','Marc Nieuweboer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443961,'Rick van Houten','Louis Leijdekker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443961,'Eric van der Zwan','Simon Reuter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443961,'Sjoerd Blondeel Timmerman','Louis Leijdekker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443961,'Rick van Houten','Simon Reuter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443961,'Eric van der Zwan','Marc Nieuweboer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443961,'Eric van der Zwan','Louis Leijdekker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443961,'Rick van Houten','Marc Nieuweboer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443961,'Sjoerd Blondeel Timmerman','Simon Reuter',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e klasse poule 1' and ssn_id like '2014%'),443964,'Tasmanian Devils','Sloten 1',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443964,'Davith Denes Hiwat','Bobby Jahangir',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443964,'Ronald Rennen','Peter Rath',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443964,'Kevin Slotboom','Adrie Voskuil',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443964,'Davith Denes Hiwat','Peter Rath',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443964,'Ronald Rennen','Adrie Voskuil',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443964,'Kevin Slotboom','Bobby Jahangir',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443964,'Kevin Slotboom','Peter Rath',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443964,'Ronald Rennen','Bobby Jahangir',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443964,'Davith Denes Hiwat','Adrie Voskuil',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e klasse poule 1' and ssn_id like '2014%'),443966,'Koetshuys 1','Sneeuwwitje e/d 7 dwergen',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443966,'Marco Kuperus','Robert Tump',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443966,'Richard Kiljan','Ronald Peeters',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443966,'Hans Reijerkerk','Rob Kanninga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443966,'Marco Kuperus','Ronald Peeters',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443966,'Richard Kiljan','Rob Kanninga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443966,'Hans Reijerkerk','Robert Tump',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443966,'Hans Reijerkerk','Ronald Peeters',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443966,'Richard Kiljan','Robert Tump',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443966,'Marco Kuperus','Rob Kanninga',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e klasse poule 1' and ssn_id like '2014%'),443967,'FINAL TOUCH 2','Alkmaar 4',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443967,'Albert Pronk','Rick van Houten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443967,'David Lucieer','Eric van der Zwan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443967,'Eric van Lokven','Sjoerd Blondeel Timmerman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443967,'Albert Pronk','Eric van der Zwan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443967,'David Lucieer','Sjoerd Blondeel Timmerman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443967,'Eric van Lokven','Rick van Houten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443967,'Eric van Lokven','Eric van der Zwan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443967,'David Lucieer','Rick van Houten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443967,'Albert Pronk','Sjoerd Blondeel Timmerman',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e klasse poule 1' and ssn_id like '2014%'),443969,'Westend 2','Sloten 1',9,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443969,'Marc Nieuweboer','Norman Nowrozy',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443969,'Kim Fai Sung','Peter Rath',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443969,'Wellington Lie','Bobby Jahangir',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443969,'Marc Nieuweboer','Peter Rath',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443969,'Kim Fai Sung','Bobby Jahangir',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443969,'Wellington Lie','Norman Nowrozy',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443969,'Wellington Lie','Peter Rath',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443969,'Kim Fai Sung','Norman Nowrozy',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443969,'Marc Nieuweboer','Bobby Jahangir',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e klasse poule 1' and ssn_id like '2014%'),443970,'Alkmaar 4','Koetshuys 1',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443970,'Sjoerd Blondeel Timmerman','Richard Kiljan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443970,'Laurens van Deijk','Hans Reijerkerk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443970,'Rick van Houten','Sander Nijssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443970,'Sjoerd Blondeel Timmerman','Hans Reijerkerk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443970,'Laurens van Deijk','Sander Nijssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443970,'Rick van Houten','Richard Kiljan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443970,'Rick van Houten','Hans Reijerkerk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443970,'Laurens van Deijk','Richard Kiljan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443970,'Sjoerd Blondeel Timmerman','Sander Nijssen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e klasse poule 1' and ssn_id like '2014%'),448419,'Koetshuys 1','FINAL TOUCH 2',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448419,'Marco Kuperus','Davis Wong',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448419,'Sander Nijssen','Martijn Lesterhuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448419,'Hans Reijerkerk','Albert Pronk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448419,'Marco Kuperus','Martijn Lesterhuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448419,'Sander Nijssen','Albert Pronk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448419,'Hans Reijerkerk','Davis Wong',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448419,'Hans Reijerkerk','Martijn Lesterhuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448419,'Sander Nijssen','Davis Wong',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448419,'Marco Kuperus','Albert Pronk',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e klasse poule 1' and ssn_id like '2014%'),448422,'Sneeuwwitje e/d 7 dwergen','FINAL TOUCH 2',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448422,'Richard van Leeuwen','David Lucieer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448422,'Rob Kanninga','Martijn Lesterhuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448422,'Ronald Peeters','Eric van Lokven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448422,'Richard van Leeuwen','Martijn Lesterhuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448422,'Rob Kanninga','Eric van Lokven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448422,'Ronald Peeters','David Lucieer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448422,'Ronald Peeters','Martijn Lesterhuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448422,'Rob Kanninga','David Lucieer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448422,'Richard van Leeuwen','Eric van Lokven',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e klasse poule 1' and ssn_id like '2014%'),448386,'Sneeuwwitje e/d 7 dwergen','Tasmanian Devils',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448386,'Rob Kanninga','Rik van Winsum',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448386,'Ronald Peeters','Davith Denes Hiwat',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448386,'René Verheyden','Ronald Rennen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448386,'Rob Kanninga','Davith Denes Hiwat',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448386,'Ronald Peeters','Ronald Rennen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448386,'René Verheyden','Rik van Winsum',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448386,'René Verheyden','Davith Denes Hiwat',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448386,'Ronald Peeters','Rik van Winsum',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448386,'Rob Kanninga','Ronald Rennen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e klasse poule 1' and ssn_id like '2014%'),443973,'Sloten 1','Sneeuwwitje e/d 7 dwergen',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443973,'Bobby Jahangir','Ronald Peeters',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443973,'Norman Nowrozy','Rob Kanninga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443973,'Peter Rath','René Verheyden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443973,'Bobby Jahangir','Rob Kanninga',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443973,'Norman Nowrozy','René Verheyden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443973,'Peter Rath','Ronald Peeters',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443973,'Peter Rath','Rob Kanninga',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443973,'Norman Nowrozy','Ronald Peeters',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443973,'Bobby Jahangir','René Verheyden',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e klasse poule 1' and ssn_id like '2014%'),443975,'FINAL TOUCH 2','Westend 2',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443975,'Albert Pronk','Marc Nieuweboer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443975,'David Lucieer','Louis Leijdekker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443975,'Martijn Lesterhuis','Simon Reuter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443975,'Albert Pronk','Louis Leijdekker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443975,'David Lucieer','Simon Reuter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443975,'Martijn Lesterhuis','Marc Nieuweboer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443975,'Martijn Lesterhuis','Louis Leijdekker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443975,'David Lucieer','Marc Nieuweboer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443975,'Albert Pronk','Simon Reuter',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e klasse poule 1' and ssn_id like '2014%'),448505,'Koetshuys 1','Tasmanian Devils',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448505,'Sander Nijssen','Kevin Slotboom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448505,'Marco Kuperus','Davith Denes Hiwat',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448505,'Hans Reijerkerk','Ronald Rennen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448505,'Sander Nijssen','Davith Denes Hiwat',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448505,'Marco Kuperus','Ronald Rennen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448505,'Hans Reijerkerk','Kevin Slotboom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448505,'Hans Reijerkerk','Davith Denes Hiwat',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448505,'Marco Kuperus','Kevin Slotboom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448505,'Sander Nijssen','Ronald Rennen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e klasse poule 1' and ssn_id like '2014%'),443977,'FINAL TOUCH 2','Sloten 1',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443977,'Albert Pronk','Bobby Jahangir',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443977,'Eric van Lokven','Peter Rath',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443977,'Martijn Lesterhuis','Adrie Voskuil',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443977,'Albert Pronk','Peter Rath',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443977,'Eric van Lokven','Adrie Voskuil',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443977,'Martijn Lesterhuis','Bobby Jahangir',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443977,'Martijn Lesterhuis','Peter Rath',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443977,'Eric van Lokven','Bobby Jahangir',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443977,'Albert Pronk','Adrie Voskuil',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e klasse poule 1' and ssn_id like '2014%'),443978,'Westend 2','Koetshuys 1',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443978,'Marco Haverkotte','Sander Nijssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443978,'Simon Reuter','Hans Reijerkerk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443978,'Marc Nieuweboer','Richard Kiljan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443978,'Marco Haverkotte','Hans Reijerkerk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443978,'Simon Reuter','Richard Kiljan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443978,'Marc Nieuweboer','Sander Nijssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443978,'Marc Nieuweboer','Hans Reijerkerk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443978,'Simon Reuter','Sander Nijssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(443978,'Marco Haverkotte','Richard Kiljan',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e klasse poule 1' and ssn_id like '2014%'),443979,'Alkmaar 4','Sneeuwwitje e/d 7 dwergen',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('01-02-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e klasse poule 1' and ssn_id like '2014%'),448510,'Tasmanian Devils','Alkmaar 4',5,4);
