delete from cm_match_details where game_id in (select game_id from cm_matches where cpn_id = (select id from cm_competitions where name = 'Combi 2e-3e klasse poule 2' and ssn_id like '2014%'));
delete from cm_matches where cpn_id = (select id from cm_competitions where name = 'Combi 2e-3e klasse poule 2' and ssn_id like '2014%');
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-09-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 2' and ssn_id like '2014%'),444277,'Snooker Utrecht 2','Dicksie Chicks',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444277,'Justin van Emstede','Eva Groen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444277,'Rene Bos','Tens Tensen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444277,'Justin van Emstede','Tens Tensen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444277,'Rene Bos','Ruud van Mierlo',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444277,'Rene Bos','Eva Groen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444277,'Justin van Emstede','Ruud van Mierlo',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-09-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 2' and ssn_id like '2014%'),444278,'CUE GENIUS 2','DE BILJARTMAKERS 2',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444278,'Ronald Rave','Dick Roskamp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444278,'Harry de Boer','Gerard Bocxe',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444278,'Ronald Brouwer','Lex Franssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444278,'Ronald Rave','Gerard Bocxe',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444278,'Harry de Boer','Lex Franssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444278,'Ronald Brouwer','Dick Roskamp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444278,'Ronald Brouwer','Gerard Bocxe',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444278,'Harry de Boer','Dick Roskamp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444278,'Ronald Rave','Lex Franssen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-09-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 2' and ssn_id like '2014%'),444279,'OZEBI 3','Sloten 2',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('01-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 2' and ssn_id like '2014%'),444280,'Sloten 2','Snooker Utrecht 2',8,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 2' and ssn_id like '2014%'),444281,'DE BILJARTMAKERS 1','OZEBI 3',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444281,'Edwin Stokkermans','René Kerkhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444281,'Michael Salentijn','Kees Reijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444281,'Erik de Ruiter','Robert Rodenburg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444281,'Edwin Stokkermans','Kees Reijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444281,'Michael Salentijn','Robert Rodenburg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444281,'Erik de Ruiter','René Kerkhoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444281,'Erik de Ruiter','Kees Reijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444281,'Michael Salentijn','René Kerkhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444281,'Edwin Stokkermans','Robert Rodenburg',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 2' and ssn_id like '2014%'),444282,'Dicksie Chicks','CUE GENIUS 2',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444282,'Lisette de Groot','Harry de Boer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444282,'Ruud van Mierlo','Ronald Brouwer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444282,'Karen Flore','Ronald Rave',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444282,'Lisette de Groot','Ronald Brouwer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444282,'Ruud van Mierlo','Ronald Rave',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444282,'Karen Flore','Harry de Boer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444282,'Karen Flore','Ronald Brouwer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444282,'Ruud van Mierlo','Harry de Boer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444282,'Lisette de Groot','Ronald Rave',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 2' and ssn_id like '2014%'),444283,'Snooker Utrecht 2','DE BILJARTMAKERS 1',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444283,'Michiel Vlootman','Edwin Stokkermans',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444283,'Rene Bos','Erik de Ruiter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444283,'John Zom','Michael Salentijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444283,'Michiel Vlootman','Erik de Ruiter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444283,'Rene Bos','Michael Salentijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444283,'John Zom','Edwin Stokkermans',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444283,'John Zom','Erik de Ruiter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444283,'Rene Bos','Edwin Stokkermans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444283,'Michiel Vlootman','Michael Salentijn',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 2' and ssn_id like '2014%'),444284,'CUE GENIUS 2','Sloten 2',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444284,'Ronald Rave','Alex van Hensbergen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444284,'Ronald Brouwer','Kilian Steen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444284,'Harry de Boer','Chi Kwong Wu',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444284,'Ronald Rave','Kilian Steen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444284,'Ronald Brouwer','Chi Kwong Wu',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444284,'Harry de Boer','Alex van Hensbergen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444284,'Harry de Boer','Kilian Steen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444284,'Ronald Brouwer','Alex van Hensbergen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444284,'Ronald Rave','Chi Kwong Wu',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 2' and ssn_id like '2014%'),444285,'DE BILJARTMAKERS 2','Dicksie Chicks',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444285,'Gerard Bocxe','Karen Flore',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444285,'Dick Roskamp','Ruud van Mierlo',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444285,'Lex Franssen','Tens Tensen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444285,'Gerard Bocxe','Ruud van Mierlo',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444285,'Dick Roskamp','Tens Tensen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444285,'Lex Franssen','Karen Flore',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444285,'Lex Franssen','Ruud van Mierlo',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444285,'Dick Roskamp','Karen Flore',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444285,'Gerard Bocxe','Tens Tensen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 2' and ssn_id like '2014%'),444286,'Sloten 2','DE BILJARTMAKERS 2',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444286,'Kilian Steen','Dick Roskamp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444286,'Alex van Hensbergen','Gerard Bocxe',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444286,'Chi Kwong Wu','Lex Franssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444286,'Kilian Steen','Gerard Bocxe',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444286,'Alex van Hensbergen','Lex Franssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444286,'Chi Kwong Wu','Dick Roskamp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444286,'Chi Kwong Wu','Gerard Bocxe',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444286,'Alex van Hensbergen','Dick Roskamp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444286,'Kilian Steen','Lex Franssen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 2' and ssn_id like '2014%'),444287,'OZEBI 3','Snooker Utrecht 2',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 2' and ssn_id like '2014%'),444288,'DE BILJARTMAKERS 1','CUE GENIUS 2',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444288,'Michael Salentijn','Ronald Rave',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444288,'Edwin Stokkermans','Harry de Boer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444288,'Erik de Ruiter','Ronald Brouwer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444288,'Michael Salentijn','Harry de Boer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444288,'Edwin Stokkermans','Ronald Brouwer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444288,'Erik de Ruiter','Ronald Rave',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444288,'Erik de Ruiter','Harry de Boer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444288,'Edwin Stokkermans','Ronald Rave',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444288,'Michael Salentijn','Ronald Brouwer',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 2' and ssn_id like '2014%'),444289,'CUE GENIUS 2','OZEBI 3',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 2' and ssn_id like '2014%'),444291,'Dicksie Chicks','Sloten 2',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('29-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 2' and ssn_id like '2014%'),448169,'Sloten 2','DE BILJARTMAKERS 1',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448169,'Chi Kwong Wu','Edwin Stokkermans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448169,'Alex van Hensbergen','Erik de Ruiter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448169,'Kilian Steen','Michael Salentijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448169,'Chi Kwong Wu','Erik de Ruiter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448169,'Alex van Hensbergen','Michael Salentijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448169,'Kilian Steen','Edwin Stokkermans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448169,'Kilian Steen','Erik de Ruiter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448169,'Alex van Hensbergen','Edwin Stokkermans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448169,'Chi Kwong Wu','Michael Salentijn',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('30-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 2' and ssn_id like '2014%'),448174,'DE BILJARTMAKERS 1','Dicksie Chicks',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448174,'Michael Salentijn','Ruud van Mierlo',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448174,'Edwin Stokkermans','Karen Flore',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448174,'Erik de Ruiter','Tens Tensen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448174,'Michael Salentijn','Karen Flore',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448174,'Edwin Stokkermans','Tens Tensen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448174,'Erik de Ruiter','Ruud van Mierlo',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448174,'Erik de Ruiter','Karen Flore',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448174,'Edwin Stokkermans','Ruud van Mierlo',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448174,'Michael Salentijn','Tens Tensen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 2' and ssn_id like '2014%'),444292,'Snooker Utrecht 2','CUE GENIUS 2',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444292,'Rene Bos','Harry de Boer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444292,'Justin van Emstede','Ronald Brouwer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444292,'Wouter Teensma','Bas Wittgen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444292,'Rene Bos','Ronald Brouwer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444292,'Justin van Emstede','Bas Wittgen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444292,'Wouter Teensma','Harry de Boer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444292,'Wouter Teensma','Ronald Brouwer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444292,'Justin van Emstede','Harry de Boer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444292,'Rene Bos','Bas Wittgen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 2' and ssn_id like '2014%'),444293,'OZEBI 3','DE BILJARTMAKERS 2',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444293,'Kees Reijn','Dick Roskamp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444293,'Marijn Sloots','Gerard Bocxe',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444293,'Jeroen Sloots','Lex Franssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444293,'Kees Reijn','Gerard Bocxe',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444293,'Marijn Sloots','Lex Franssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444293,'Jeroen Sloots','Dick Roskamp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444293,'Jeroen Sloots','Gerard Bocxe',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444293,'Marijn Sloots','Dick Roskamp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444293,'Kees Reijn','Lex Franssen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 2' and ssn_id like '2014%'),444296,'DE BILJARTMAKERS 2','Snooker Utrecht 2',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444296,'Gerard Bocxe','John Zom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444296,'Lex Franssen','Michiel Vlootman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444296,'Dick Roskamp','Wouter Teensma',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444296,'Gerard Bocxe','Michiel Vlootman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444296,'Lex Franssen','Wouter Teensma',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444296,'Dick Roskamp','John Zom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444296,'Dick Roskamp','Michiel Vlootman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444296,'Lex Franssen','John Zom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444296,'Gerard Bocxe','Wouter Teensma',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 2' and ssn_id like '2014%'),444297,'Dicksie Chicks','OZEBI 3',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444297,'Lisette de Groot','Kees Reijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444297,'Eva Groen','René Kerkhoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444297,'Karen Flore','Robert Rodenburg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444297,'Lisette de Groot','René Kerkhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444297,'Eva Groen','Robert Rodenburg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444297,'Karen Flore','Kees Reijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444297,'Karen Flore','René Kerkhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444297,'Eva Groen','Kees Reijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444297,'Lisette de Groot','Robert Rodenburg',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 2' and ssn_id like '2014%'),448331,'CUE GENIUS 2','DE BILJARTMAKERS 1',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448331,'Harry de Boer','Edwin Stokkermans',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448331,'Ronald Brouwer','Erik de Ruiter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448331,'Bas Wittgen','Michael Salentijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448331,'Harry de Boer','Erik de Ruiter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448331,'Ronald Brouwer','Michael Salentijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448331,'Bas Wittgen','Edwin Stokkermans',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448331,'Bas Wittgen','Erik de Ruiter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448331,'Ronald Brouwer','Edwin Stokkermans',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448331,'Harry de Boer','Michael Salentijn',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 2' and ssn_id like '2014%'),444298,'Sloten 2','OZEBI 3',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444298,'Chi Kwong Wu','René Kerkhoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444298,'Alex van Hensbergen','Kees Reijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444298,'Kilian Steen','Marijn Sloots',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444298,'Chi Kwong Wu','Kees Reijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444298,'Alex van Hensbergen','Marijn Sloots',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444298,'Kilian Steen','René Kerkhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444298,'Kilian Steen','Kees Reijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444298,'Alex van Hensbergen','René Kerkhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444298,'Chi Kwong Wu','Marijn Sloots',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 2' and ssn_id like '2014%'),444299,'DE BILJARTMAKERS 2','CUE GENIUS 2',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444299,'Gerard Bocxe','Ronald Brouwer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444299,'Lex Franssen','Ronald Rave',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444299,'Gerard Bocxe','Ronald Rave',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444299,'Lex Franssen','Harry de Boer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444299,'Lex Franssen','Ronald Brouwer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444299,'Gerard Bocxe','Harry de Boer',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 2' and ssn_id like '2014%'),444300,'Dicksie Chicks','Snooker Utrecht 2',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444300,'Lisette de Groot','Debabrata Panja',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444300,'Karen Flore','Justin van Emstede',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444300,'Tens Tensen','Wouter Teensma',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444300,'Lisette de Groot','Justin van Emstede',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444300,'Karen Flore','Wouter Teensma',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444300,'Tens Tensen','Debabrata Panja',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444300,'Tens Tensen','Justin van Emstede',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444300,'Karen Flore','Debabrata Panja',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444300,'Lisette de Groot','Wouter Teensma',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 2' and ssn_id like '2014%'),444301,'Snooker Utrecht 2','Sloten 2',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444301,'John Zom','Alex van Hensbergen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444301,'Debabrata Panja','Chi Kwong Wu',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444301,'Rene Bos','Kilian Steen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444301,'John Zom','Chi Kwong Wu',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444301,'Debabrata Panja','Kilian Steen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444301,'Rene Bos','Alex van Hensbergen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444301,'Rene Bos','Chi Kwong Wu',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444301,'Debabrata Panja','Alex van Hensbergen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444301,'John Zom','Kilian Steen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('25-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 2' and ssn_id like '2014%'),444302,'CUE GENIUS 2','Dicksie Chicks',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444302,'Ronald Rave','Ruud van Mierlo',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444302,'Harry de Boer','Tens Tensen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444302,'Ronald Brouwer','Karen Flore',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444302,'Ronald Rave','Tens Tensen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444302,'Harry de Boer','Karen Flore',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444302,'Ronald Brouwer','Ruud van Mierlo',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444302,'Ronald Brouwer','Tens Tensen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444302,'Harry de Boer','Ruud van Mierlo',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444302,'Ronald Rave','Karen Flore',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 2' and ssn_id like '2014%'),444303,'OZEBI 3','DE BILJARTMAKERS 1',9,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444303,'Kees Reijn','Edwin Stokkermans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444303,'Jeroen Sloots','Erik de Ruiter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444303,'René Kerkhoven','Michael Salentijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444303,'Kees Reijn','Erik de Ruiter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444303,'Jeroen Sloots','Michael Salentijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444303,'René Kerkhoven','Edwin Stokkermans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444303,'René Kerkhoven','Erik de Ruiter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444303,'Jeroen Sloots','Edwin Stokkermans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444303,'Kees Reijn','Michael Salentijn',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 2' and ssn_id like '2014%'),444304,'Sloten 2','CUE GENIUS 2',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444304,'Alex van Hensbergen','Bas Wittgen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444304,'Chi Kwong Wu','Ronald Rave',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444304,'Roy Steinraht','Ronald Brouwer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444304,'Alex van Hensbergen','Ronald Rave',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444304,'Chi Kwong Wu','Ronald Brouwer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444304,'Roy Steinraht','Bas Wittgen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444304,'Roy Steinraht','Ronald Rave',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444304,'Chi Kwong Wu','Bas Wittgen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444304,'Alex van Hensbergen','Ronald Brouwer',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 2' and ssn_id like '2014%'),444305,'DE BILJARTMAKERS 1','Snooker Utrecht 2',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444305,'Edwin Stokkermans','Rene Bos',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444305,'Michael Salentijn','John Zom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444305,'Edwin Stokkermans','John Zom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444305,'Erik de Ruiter','Rene Bos',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444305,'Erik de Ruiter','John Zom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444305,'Michael Salentijn','Rene Bos',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 2' and ssn_id like '2014%'),444306,'Dicksie Chicks','DE BILJARTMAKERS 2',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444306,'Karen Flore','Dick Roskamp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444306,'Ruud van Mierlo','Gerard Bocxe',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444306,'Lisette de Groot','Lex Franssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444306,'Karen Flore','Gerard Bocxe',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444306,'Ruud van Mierlo','Lex Franssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444306,'Lisette de Groot','Dick Roskamp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444306,'Lisette de Groot','Gerard Bocxe',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444306,'Ruud van Mierlo','Dick Roskamp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444306,'Karen Flore','Lex Franssen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 2' and ssn_id like '2014%'),444307,'Snooker Utrecht 2','OZEBI 3',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 2' and ssn_id like '2014%'),444309,'DE BILJARTMAKERS 2','Sloten 2',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444309,'Gerard Bocxe','Chi Kwong Wu',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444309,'Dick Roskamp','Roy Steinraht',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444309,'Lex Franssen','Kilian Steen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444309,'Gerard Bocxe','Roy Steinraht',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444309,'Dick Roskamp','Kilian Steen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444309,'Lex Franssen','Chi Kwong Wu',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444309,'Lex Franssen','Roy Steinraht',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444309,'Dick Roskamp','Chi Kwong Wu',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444309,'Gerard Bocxe','Kilian Steen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 2' and ssn_id like '2014%'),444310,'Sloten 2','Dicksie Chicks',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444310,'Kilian Steen','Eva Groen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444310,'Alex van Hensbergen','Tens Tensen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444310,'Chi Kwong Wu','Ruud van Mierlo',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444310,'Kilian Steen','Tens Tensen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444310,'Alex van Hensbergen','Ruud van Mierlo',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444310,'Chi Kwong Wu','Eva Groen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444310,'Chi Kwong Wu','Tens Tensen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444310,'Alex van Hensbergen','Eva Groen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444310,'Kilian Steen','Ruud van Mierlo',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 2' and ssn_id like '2014%'),444312,'DE BILJARTMAKERS 1','DE BILJARTMAKERS 2',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444312,'Michael Salentijn','Dick Roskamp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444312,'Edwin Stokkermans','Gerard Bocxe',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444312,'Erik de Ruiter','Lex Franssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444312,'Michael Salentijn','Gerard Bocxe',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444312,'Edwin Stokkermans','Lex Franssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444312,'Erik de Ruiter','Dick Roskamp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444312,'Erik de Ruiter','Gerard Bocxe',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444312,'Edwin Stokkermans','Dick Roskamp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444312,'Michael Salentijn','Lex Franssen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 2' and ssn_id like '2014%'),448484,'DE BILJARTMAKERS 2','DE BILJARTMAKERS 1',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 2' and ssn_id like '2014%'),444313,'CUE GENIUS 2','Snooker Utrecht 2',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 2' and ssn_id like '2014%'),444314,'DE BILJARTMAKERS 2','OZEBI 3',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444314,'Lex Franssen','Kees Reijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444314,'Dick Roskamp','Marijn Sloots',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444314,'Gerard Bocxe','Robert Rodenburg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444314,'Lex Franssen','Marijn Sloots',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444314,'Dick Roskamp','Robert Rodenburg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444314,'Gerard Bocxe','Kees Reijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444314,'Gerard Bocxe','Marijn Sloots',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444314,'Dick Roskamp','Kees Reijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444314,'Lex Franssen','Robert Rodenburg',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 2' and ssn_id like '2014%'),444315,'Dicksie Chicks','DE BILJARTMAKERS 1',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444315,'Ruud van Mierlo','Michael Salentijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444315,'Karen Flore','Erik de Ruiter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444315,'Lisette de Groot','Edwin Stokkermans',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444315,'Ruud van Mierlo','Erik de Ruiter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444315,'Karen Flore','Edwin Stokkermans',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444315,'Lisette de Groot','Michael Salentijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444315,'Lisette de Groot','Erik de Ruiter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444315,'Karen Flore','Michael Salentijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444315,'Ruud van Mierlo','Edwin Stokkermans',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 2' and ssn_id like '2014%'),444316,'Snooker Utrecht 2','DE BILJARTMAKERS 2',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444316,'John Zom','Dick Roskamp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444316,'Debabrata Panja','Gerard Bocxe',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444316,'Justin van Emstede','Lex Franssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444316,'John Zom','Gerard Bocxe',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444316,'Debabrata Panja','Lex Franssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444316,'Justin van Emstede','Dick Roskamp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444316,'Justin van Emstede','Gerard Bocxe',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444316,'Debabrata Panja','Dick Roskamp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444316,'John Zom','Lex Franssen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 2' and ssn_id like '2014%'),444317,'OZEBI 3','Dicksie Chicks',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444317,'Kees Reijn','Ruud van Mierlo',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444317,'Jeroen Sloots','Eva Groen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444317,'René Kerkhoven','Lisette de Groot',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444317,'Kees Reijn','Eva Groen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444317,'Jeroen Sloots','Lisette de Groot',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444317,'René Kerkhoven','Ruud van Mierlo',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444317,'René Kerkhoven','Eva Groen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444317,'Jeroen Sloots','Ruud van Mierlo',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444317,'Kees Reijn','Lisette de Groot',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 2' and ssn_id like '2014%'),444318,'DE BILJARTMAKERS 1','Sloten 2',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444318,'Michael Salentijn','Alex van Hensbergen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444318,'Edwin Stokkermans','Roy Steinraht',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444318,'Erik de Ruiter','Kilian Steen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444318,'Michael Salentijn','Roy Steinraht',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444318,'Edwin Stokkermans','Kilian Steen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444318,'Erik de Ruiter','Alex van Hensbergen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444318,'Erik de Ruiter','Roy Steinraht',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444318,'Edwin Stokkermans','Alex van Hensbergen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444318,'Michael Salentijn','Kilian Steen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('29-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 2' and ssn_id like '2014%'),448570,'OZEBI 3','CUE GENIUS 2',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448570,'Kees Reijn','Ronald Rave',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448570,'Jeroen Sloots','Harry de Boer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448570,'René Kerkhoven','Bas Wittgen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448570,'Kees Reijn','Harry de Boer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448570,'Jeroen Sloots','Bas Wittgen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448570,'René Kerkhoven','Ronald Rave',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448570,'René Kerkhoven','Harry de Boer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448570,'Jeroen Sloots','Ronald Rave',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448570,'Kees Reijn','Bas Wittgen',1,0);
