delete from cm_match_details where game_id in (select game_id from cm_matches where cpn_id = (select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 5' and ssn_id like '2014%'));
delete from cm_matches where cpn_id = (select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 5' and ssn_id like '2014%');
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-09-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 5' and ssn_id like '2014%'),444149,'AVVL','VEGHEL 2',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444149,'Raymond Ruesink','René van Bavel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444149,'Sicco Vollema','Pieter van Driel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444149,'Herman van Deutekom','Gertjan Huiskes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444149,'Raymond Ruesink','Pieter van Driel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444149,'Sicco Vollema','Gertjan Huiskes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444149,'Herman van Deutekom','René van Bavel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444149,'Herman van Deutekom','Pieter van Driel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444149,'Sicco Vollema','René van Bavel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444149,'Raymond Ruesink','Gertjan Huiskes',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-09-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 5' and ssn_id like '2014%'),444151,'VINK 1','Back in the Pack 2.0',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444151,'Wingho Li','Willem de Koning',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444151,'Hijlko Soepboer','Luuk Buys',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444151,'Danny Flendrie','Leon van de Laak',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444151,'Wingho Li','Luuk Buys',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444151,'Hijlko Soepboer','Leon van de Laak',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444151,'Danny Flendrie','Willem de Koning',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444151,'Danny Flendrie','Luuk Buys',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444151,'Hijlko Soepboer','Willem de Koning',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444151,'Wingho Li','Leon van de Laak',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-09-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 5' and ssn_id like '2014%'),444153,'The Chokers','AVVL',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444153,'Gert Jan Niels','Sicco Vollema',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444153,'Geert Dutman','Herman van Deutekom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444153,'Michiel Ronhaar','Raymond Ruesink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444153,'Gert Jan Niels','Herman van Deutekom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444153,'Geert Dutman','Raymond Ruesink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444153,'Michiel Ronhaar','Sicco Vollema',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444153,'Michiel Ronhaar','Herman van Deutekom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444153,'Geert Dutman','Sicco Vollema',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444153,'Gert Jan Niels','Raymond Ruesink',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('25-09-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 5' and ssn_id like '2014%'),444156,'Back in the Pack 2.0','DE DIEZE 2 / HIAB',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444156,'Roel Koks','Mario Veltman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444156,'Willem de Koning','Juriaan van den Nieuwenhuizen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444156,'Luuk Buys','Mario Veltman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444156,'Roel Koks','Juriaan van den Nieuwenhuizen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444156,'Willem de Koning','Mario Veltman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444156,'Luuk Buys','Juriaan van den Nieuwenhuizen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 5' and ssn_id like '2014%'),444159,'VINK 1','VEGHEL 2',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444159,'Peter Kok','René van Bavel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444159,'Danny Flendrie','Sebastiaan Henstra',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444159,'Erik Kerkhoven','Peter Koopmans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444159,'Peter Kok','Sebastiaan Henstra',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444159,'Danny Flendrie','Peter Koopmans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444159,'Erik Kerkhoven','René van Bavel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444159,'Erik Kerkhoven','Sebastiaan Henstra',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444159,'Danny Flendrie','René van Bavel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444159,'Peter Kok','Peter Koopmans',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 5' and ssn_id like '2014%'),444160,'DE DIEZE 2 / HIAB','Ames 2  De Zwervers',9,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444160,'Mario Veltman','Math van der Linden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444160,'Juriaan van den Nieuwenhuizen','Hans Moerkerk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444160,'Jeroen van Driel','Ko de Ruijter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444160,'Mario Veltman','Hans Moerkerk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444160,'Juriaan van den Nieuwenhuizen','Ko de Ruijter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444160,'Jeroen van Driel','Math van der Linden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444160,'Jeroen van Driel','Hans Moerkerk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444160,'Juriaan van den Nieuwenhuizen','Math van der Linden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444160,'Mario Veltman','Ko de Ruijter',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 5' and ssn_id like '2014%'),444162,'The Chokers','VINK 1',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444162,'Gert Jan Niels','Danny Flendrie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444162,'Nienke Reijntjes','Erik Kerkhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444162,'Marieke Kamies','Peter Kok',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444162,'Gert Jan Niels','Erik Kerkhoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444162,'Nienke Reijntjes','Peter Kok',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444162,'Marieke Kamies','Danny Flendrie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444162,'Marieke Kamies','Erik Kerkhoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444162,'Nienke Reijntjes','Danny Flendrie',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444162,'Gert Jan Niels','Peter Kok',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 5' and ssn_id like '2014%'),444166,'Back in the Pack 2.0','Ames 2  De Zwervers',9,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444166,'Willem de Koning','Wim Manders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444166,'Roel Koks','Frans van Poppel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444166,'Peter Bertens','Anthony Bisschops',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444166,'Willem de Koning','Frans van Poppel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444166,'Roel Koks','Anthony Bisschops',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444166,'Peter Bertens','Wim Manders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444166,'Peter Bertens','Frans van Poppel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444166,'Roel Koks','Wim Manders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444166,'Willem de Koning','Anthony Bisschops',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 5' and ssn_id like '2014%'),444167,'VINK 1','AVVL',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444167,'Wingho Li','Sicco Vollema',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444167,'Peter Kok','Herman van Deutekom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444167,'Erik Kerkhoven','Raymond Ruesink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444167,'Wingho Li','Herman van Deutekom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444167,'Peter Kok','Raymond Ruesink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444167,'Erik Kerkhoven','Sicco Vollema',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444167,'Erik Kerkhoven','Herman van Deutekom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444167,'Peter Kok','Sicco Vollema',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444167,'Wingho Li','Raymond Ruesink',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 5' and ssn_id like '2014%'),444172,'VEGHEL 2','Back in the Pack 2.0',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444172,'Sebastiaan Henstra','Roel Koks',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444172,'Pieter van Driel','Peter Bertens',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444172,'Theo van den Anker','Willem de Koning',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444172,'Sebastiaan Henstra','Peter Bertens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444172,'Pieter van Driel','Willem de Koning',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444172,'Theo van den Anker','Roel Koks',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444172,'Theo van den Anker','Peter Bertens',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444172,'Pieter van Driel','Roel Koks',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444172,'Sebastiaan Henstra','Willem de Koning',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 5' and ssn_id like '2014%'),448178,'DE DIEZE 2 / HIAB','The Chokers',9,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448178,'Marcel Roza','Geert Dutman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448178,'Jeroen van Driel','Gert Jan Niels',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448178,'Juriaan van den Nieuwenhuizen','Michiel Ronhaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448178,'Marcel Roza','Gert Jan Niels',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448178,'Jeroen van Driel','Michiel Ronhaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448178,'Juriaan van den Nieuwenhuizen','Geert Dutman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448178,'Juriaan van den Nieuwenhuizen','Gert Jan Niels',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448178,'Jeroen van Driel','Geert Dutman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448178,'Marcel Roza','Michiel Ronhaar',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('29-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 5' and ssn_id like '2014%'),444173,'Ames 2  De Zwervers','VEGHEL 2',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444173,'Anthony Bisschops','Jacques Willem van Melis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444173,'Ko de Ruijter','René van Bavel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444173,'Hans Moerkerk','Gertjan Huiskes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444173,'Anthony Bisschops','René van Bavel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444173,'Ko de Ruijter','Gertjan Huiskes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444173,'Hans Moerkerk','Jacques Willem van Melis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444173,'Hans Moerkerk','René van Bavel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444173,'Ko de Ruijter','Jacques Willem van Melis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444173,'Anthony Bisschops','Gertjan Huiskes',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('30-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 5' and ssn_id like '2014%'),444175,'Back in the Pack 2.0','The Chokers',9,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444175,'Willem de Koning','Geert Dutman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444175,'Roel Koks','Eddy Takkenkamp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444175,'Peter Bertens','Louis Leurs',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444175,'Willem de Koning','Eddy Takkenkamp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444175,'Roel Koks','Louis Leurs',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444175,'Peter Bertens','Geert Dutman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444175,'Peter Bertens','Eddy Takkenkamp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444175,'Roel Koks','Geert Dutman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444175,'Willem de Koning','Louis Leurs',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 5' and ssn_id like '2014%'),444177,'AVVL','Back in the Pack 2.0',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444177,'Raymond Ruesink','Roel Koks',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444177,'Herman van Deutekom','Leon van de Laak',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444177,'Sicco Vollema','Willem de Koning',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444177,'Raymond Ruesink','Leon van de Laak',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444177,'Herman van Deutekom','Willem de Koning',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444177,'Sicco Vollema','Roel Koks',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444177,'Sicco Vollema','Leon van de Laak',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444177,'Herman van Deutekom','Roel Koks',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444177,'Raymond Ruesink','Willem de Koning',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 5' and ssn_id like '2014%'),444178,'The Chokers','Ames 2  De Zwervers',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444178,'Nienke Reijntjes','Anthony Bisschops',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444178,'Marieke Kamies','Frans van Poppel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444178,'Gert Jan Niels','Ko de Ruijter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444178,'Nienke Reijntjes','Frans van Poppel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444178,'Marieke Kamies','Ko de Ruijter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444178,'Gert Jan Niels','Anthony Bisschops',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444178,'Gert Jan Niels','Frans van Poppel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444178,'Marieke Kamies','Anthony Bisschops',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444178,'Nienke Reijntjes','Ko de Ruijter',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 5' and ssn_id like '2014%'),444180,'VINK 1','DE DIEZE 2 / HIAB',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444180,'Wingho Li','Mario Veltman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444180,'Hijlko Soepboer','Jorick Blokx',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444180,'Erik Kerkhoven','Juriaan van den Nieuwenhuizen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444180,'Wingho Li','Jorick Blokx',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444180,'Hijlko Soepboer','Juriaan van den Nieuwenhuizen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444180,'Erik Kerkhoven','Mario Veltman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444180,'Erik Kerkhoven','Jorick Blokx',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444180,'Hijlko Soepboer','Mario Veltman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444180,'Wingho Li','Juriaan van den Nieuwenhuizen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 5' and ssn_id like '2014%'),444181,'Ames 2  De Zwervers','AVVL',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444181,'Anthony Bisschops','Raymond Ruesink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444181,'Frans van Poppel','Herman van Deutekom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444181,'Wim Manders','Sicco Vollema',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444181,'Anthony Bisschops','Herman van Deutekom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444181,'Frans van Poppel','Sicco Vollema',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444181,'Wim Manders','Raymond Ruesink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444181,'Wim Manders','Herman van Deutekom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444181,'Frans van Poppel','Raymond Ruesink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444181,'Anthony Bisschops','Sicco Vollema',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 5' and ssn_id like '2014%'),448247,'Ames 2  De Zwervers','VINK 1',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448247,'Wim Manders','Erik Kerkhoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448247,'Ko de Ruijter','Hijlko Soepboer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448247,'Frans van Poppel','Peter Kok',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448247,'Wim Manders','Hijlko Soepboer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448247,'Ko de Ruijter','Peter Kok',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448247,'Frans van Poppel','Erik Kerkhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448247,'Frans van Poppel','Hijlko Soepboer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448247,'Ko de Ruijter','Erik Kerkhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448247,'Wim Manders','Peter Kok',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 5' and ssn_id like '2014%'),448287,'AVVL','DE DIEZE 2 / HIAB',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448287,'Herman van Deutekom','Jorick Blokx',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448287,'Sicco Vollema','Juriaan van den Nieuwenhuizen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448287,'Raymond Ruesink','Marcel Roza',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448287,'Herman van Deutekom','Juriaan van den Nieuwenhuizen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448287,'Sicco Vollema','Marcel Roza',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448287,'Raymond Ruesink','Jorick Blokx',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448287,'Raymond Ruesink','Juriaan van den Nieuwenhuizen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448287,'Sicco Vollema','Jorick Blokx',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448287,'Herman van Deutekom','Marcel Roza',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 5' and ssn_id like '2014%'),444187,'Back in the Pack 2.0','VINK 1',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444187,'Luuk Buys','Jan van Domselaar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444187,'Peter Bertens','Erik Kerkhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444187,'Willem de Koning','Hijlko Soepboer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444187,'Luuk Buys','Erik Kerkhoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444187,'Peter Bertens','Hijlko Soepboer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444187,'Willem de Koning','Jan van Domselaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444187,'Willem de Koning','Erik Kerkhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444187,'Peter Bertens','Jan van Domselaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444187,'Luuk Buys','Hijlko Soepboer',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 5' and ssn_id like '2014%'),444188,'VEGHEL 2','AVVL',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444188,'Pieter van Driel','Sicco Vollema',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444188,'Theo van den Anker','Herman van Deutekom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444188,'Sebastiaan Henstra','Raymond Ruesink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444188,'Pieter van Driel','Herman van Deutekom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444188,'Theo van den Anker','Raymond Ruesink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444188,'Sebastiaan Henstra','Sicco Vollema',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444188,'Sebastiaan Henstra','Herman van Deutekom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444188,'Theo van den Anker','Sicco Vollema',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444188,'Pieter van Driel','Raymond Ruesink',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('25-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 5' and ssn_id like '2014%'),444189,'AVVL','The Chokers',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444189,'Raymond Ruesink','Eddy Takkenkamp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444189,'Sicco Vollema','Nienke Reijntjes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444189,'Herman van Deutekom','Geert Dutman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444189,'Raymond Ruesink','Nienke Reijntjes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444189,'Sicco Vollema','Geert Dutman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444189,'Herman van Deutekom','Eddy Takkenkamp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444189,'Herman van Deutekom','Nienke Reijntjes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444189,'Sicco Vollema','Eddy Takkenkamp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444189,'Raymond Ruesink','Geert Dutman',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 5' and ssn_id like '2014%'),444191,'VINK 1','Ames 2  De Zwervers',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444191,'Wingho Li','Anthony Bisschops',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444191,'Hijlko Soepboer','Wim Manders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444191,'Danny Flendrie','Ko de Ruijter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444191,'Wingho Li','Wim Manders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444191,'Hijlko Soepboer','Ko de Ruijter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444191,'Danny Flendrie','Anthony Bisschops',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444191,'Danny Flendrie','Wim Manders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444191,'Hijlko Soepboer','Anthony Bisschops',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444191,'Wingho Li','Ko de Ruijter',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('28-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 5' and ssn_id like '2014%'),444192,'DE DIEZE 2 / HIAB','Back in the Pack 2.0',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444192,'Jeroen van Driel','Luuk Buys',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444192,'Mario Veltman','Willem de Koning',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444192,'Juriaan van den Nieuwenhuizen','Roel Koks',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444192,'Jeroen van Driel','Willem de Koning',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444192,'Mario Veltman','Roel Koks',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444192,'Juriaan van den Nieuwenhuizen','Luuk Buys',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444192,'Juriaan van den Nieuwenhuizen','Willem de Koning',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444192,'Mario Veltman','Luuk Buys',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444192,'Jeroen van Driel','Roel Koks',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 5' and ssn_id like '2014%'),444194,'Ames 2  De Zwervers','DE DIEZE 2 / HIAB',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444194,'Wim Manders','Jorick Blokx',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444194,'Frans van Poppel','Juriaan van den Nieuwenhuizen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444194,'Anthony Bisschops','Wiljan van Sommeren',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444194,'Wim Manders','Juriaan van den Nieuwenhuizen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444194,'Frans van Poppel','Wiljan van Sommeren',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444194,'Anthony Bisschops','Jorick Blokx',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444194,'Anthony Bisschops','Juriaan van den Nieuwenhuizen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444194,'Frans van Poppel','Jorick Blokx',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444194,'Wim Manders','Wiljan van Sommeren',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 5' and ssn_id like '2014%'),444196,'VEGHEL 2','VINK 1',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444196,'Pieter van Driel','Peter Kok',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444196,'Gertjan Huiskes','Hijlko Soepboer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444196,'Pieter Anne van Melis','Danny Flendrie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444196,'Pieter van Driel','Hijlko Soepboer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444196,'Gertjan Huiskes','Danny Flendrie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444196,'Pieter Anne van Melis','Peter Kok',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444196,'Pieter Anne van Melis','Hijlko Soepboer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444196,'Gertjan Huiskes','Peter Kok',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444196,'Pieter van Driel','Danny Flendrie',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 5' and ssn_id like '2014%'),444199,'VINK 1','The Chokers',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444199,'Peter Kok','Michiel Ronhaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444199,'Hijlko Soepboer','Geert Dutman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444199,'Erik Kerkhoven','Gert Jan Niels',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444199,'Peter Kok','Geert Dutman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444199,'Hijlko Soepboer','Gert Jan Niels',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444199,'Erik Kerkhoven','Michiel Ronhaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444199,'Erik Kerkhoven','Geert Dutman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444199,'Hijlko Soepboer','Michiel Ronhaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444199,'Peter Kok','Gert Jan Niels',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 5' and ssn_id like '2014%'),444200,'DE DIEZE 2 / HIAB','VEGHEL 2',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444200,'Wiljan van Sommeren','René van Bavel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444200,'Marcel Roza','Theo van den Anker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444200,'Juriaan van den Nieuwenhuizen','Gertjan Huiskes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444200,'Wiljan van Sommeren','Theo van den Anker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444200,'Marcel Roza','Gertjan Huiskes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444200,'Juriaan van den Nieuwenhuizen','René van Bavel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444200,'Juriaan van den Nieuwenhuizen','Theo van den Anker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444200,'Marcel Roza','René van Bavel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444200,'Wiljan van Sommeren','Gertjan Huiskes',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 5' and ssn_id like '2014%'),448428,'VEGHEL 2','The Chokers',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 5' and ssn_id like '2014%'),444201,'The Chokers','DE DIEZE 2 / HIAB',0,9);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444201,'Gert Jan Niels','Jorick Blokx',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444201,'Nienke Reijntjes','Juriaan van den Nieuwenhuizen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444201,'Michiel Ronhaar','Marcel Roza',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444201,'Gert Jan Niels','Juriaan van den Nieuwenhuizen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444201,'Nienke Reijntjes','Marcel Roza',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444201,'Michiel Ronhaar','Jorick Blokx',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444201,'Michiel Ronhaar','Juriaan van den Nieuwenhuizen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444201,'Nienke Reijntjes','Jorick Blokx',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444201,'Gert Jan Niels','Marcel Roza',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 5' and ssn_id like '2014%'),444203,'Ames 2  De Zwervers','Back in the Pack 2.0',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444203,'Anthony Bisschops','Willem de Koning',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444203,'Frans van Poppel','Peter Bertens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444203,'Hans Moerkerk','Luuk Buys',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444203,'Anthony Bisschops','Peter Bertens',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444203,'Frans van Poppel','Luuk Buys',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444203,'Hans Moerkerk','Willem de Koning',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444203,'Hans Moerkerk','Peter Bertens',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444203,'Frans van Poppel','Willem de Koning',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444203,'Anthony Bisschops','Luuk Buys',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 5' and ssn_id like '2014%'),448465,'AVVL','VINK 1',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448465,'Raymond Ruesink','Danny Flendrie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448465,'Sicco Vollema','Erik Kerkhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448465,'Herman van Deutekom','Wingho Li',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448465,'Raymond Ruesink','Erik Kerkhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448465,'Sicco Vollema','Wingho Li',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448465,'Herman van Deutekom','Danny Flendrie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448465,'Herman van Deutekom','Erik Kerkhoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448465,'Sicco Vollema','Danny Flendrie',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448465,'Raymond Ruesink','Wingho Li',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 5' and ssn_id like '2014%'),444207,'Back in the Pack 2.0','VEGHEL 2',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444207,'Willem de Koning','Gertjan Huiskes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444207,'Luuk Buys','Theo van den Anker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444207,'Roel Koks','René van Bavel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444207,'Willem de Koning','Theo van den Anker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444207,'Luuk Buys','René van Bavel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444207,'Roel Koks','Gertjan Huiskes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444207,'Roel Koks','Theo van den Anker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444207,'Luuk Buys','Gertjan Huiskes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444207,'Willem de Koning','René van Bavel',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 5' and ssn_id like '2014%'),444208,'DE DIEZE 2 / HIAB','AVVL',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444208,'Mario Veltman','Herman van Deutekom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444208,'Juriaan van den Nieuwenhuizen','Sicco Vollema',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444208,'Mario Veltman','Raymond Ruesink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444208,'Juriaan van den Nieuwenhuizen','Herman van Deutekom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444208,'Juriaan van den Nieuwenhuizen','Raymond Ruesink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444208,'Mario Veltman','Sicco Vollema',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 5' and ssn_id like '2014%'),444209,'The Chokers','Back in the Pack 2.0',0,9);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444209,'Nienke Reijntjes','Luuk Buys',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444209,'Marieke Kamies','Roel Koks',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444209,'Eddy Takkenkamp','Willem de Koning',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444209,'Nienke Reijntjes','Roel Koks',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444209,'Marieke Kamies','Willem de Koning',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444209,'Eddy Takkenkamp','Luuk Buys',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444209,'Eddy Takkenkamp','Roel Koks',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444209,'Marieke Kamies','Luuk Buys',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444209,'Nienke Reijntjes','Willem de Koning',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 5' and ssn_id like '2014%'),444212,'VEGHEL 2','Ames 2  De Zwervers',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444212,'René van Bavel','Anthony Bisschops',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444212,'Pieter Anne van Melis','Frans van Poppel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444212,'Gertjan Huiskes','Ko de Ruijter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444212,'René van Bavel','Frans van Poppel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444212,'Pieter Anne van Melis','Ko de Ruijter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444212,'Gertjan Huiskes','Anthony Bisschops',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444212,'Gertjan Huiskes','Frans van Poppel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444212,'Pieter Anne van Melis','Anthony Bisschops',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444212,'René van Bavel','Ko de Ruijter',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 5' and ssn_id like '2014%'),448427,'VEGHEL 2','DE DIEZE 2 / HIAB',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448427,'Theo van den Anker','Wiljan van Sommeren',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448427,'Gertjan Huiskes','Marcel Roza',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448427,'Pieter Anne van Melis','Jorick Blokx',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448427,'Theo van den Anker','Marcel Roza',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448427,'Gertjan Huiskes','Jorick Blokx',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448427,'Pieter Anne van Melis','Wiljan van Sommeren',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448427,'Pieter Anne van Melis','Marcel Roza',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448427,'Gertjan Huiskes','Wiljan van Sommeren',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448427,'Theo van den Anker','Jorick Blokx',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 5' and ssn_id like '2014%'),444214,'Ames 2  De Zwervers','The Chokers',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444214,'Wim Manders','Michiel Ronhaar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444214,'Hans Moerkerk','Nienke Reijntjes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444214,'Frans van Poppel','Gert Jan Niels',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444214,'Wim Manders','Nienke Reijntjes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444214,'Hans Moerkerk','Gert Jan Niels',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444214,'Frans van Poppel','Michiel Ronhaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444214,'Frans van Poppel','Nienke Reijntjes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444214,'Hans Moerkerk','Michiel Ronhaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444214,'Wim Manders','Gert Jan Niels',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 5' and ssn_id like '2014%'),444215,'Back in the Pack 2.0','AVVL',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444215,'Luuk Buys','Herman van Deutekom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444215,'Willem de Koning','Sicco Vollema',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444215,'Peter Bertens','Raymond Ruesink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444215,'Luuk Buys','Sicco Vollema',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444215,'Willem de Koning','Raymond Ruesink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444215,'Peter Bertens','Herman van Deutekom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444215,'Peter Bertens','Sicco Vollema',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444215,'Willem de Koning','Herman van Deutekom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444215,'Luuk Buys','Raymond Ruesink',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 5' and ssn_id like '2014%'),444216,'DE DIEZE 2 / HIAB','VINK 1',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444216,'Mario Veltman','Danny Flendrie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444216,'Jorick Blokx','Erik Kerkhoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444216,'Juriaan van den Nieuwenhuizen','Peter Kok',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444216,'Mario Veltman','Erik Kerkhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444216,'Jorick Blokx','Peter Kok',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444216,'Juriaan van den Nieuwenhuizen','Danny Flendrie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444216,'Juriaan van den Nieuwenhuizen','Erik Kerkhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444216,'Jorick Blokx','Danny Flendrie',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444216,'Mario Veltman','Peter Kok',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 5' and ssn_id like '2014%'),444217,'The Chokers','VEGHEL 2',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444217,'Marieke Kamies','Gertjan Huiskes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444217,'Gert Jan Niels','Sebastiaan Henstra',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444217,'Michiel Ronhaar','Jacques Willem van Melis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444217,'Marieke Kamies','Sebastiaan Henstra',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444217,'Gert Jan Niels','Jacques Willem van Melis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444217,'Michiel Ronhaar','Gertjan Huiskes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444217,'Michiel Ronhaar','Sebastiaan Henstra',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444217,'Gert Jan Niels','Gertjan Huiskes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444217,'Marieke Kamies','Jacques Willem van Melis',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi Hoofdklasse-1e Klasse poule 5' and ssn_id like '2014%'),444218,'AVVL','Ames 2  De Zwervers',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444218,'Raymond Ruesink','Hans Moerkerk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444218,'Sicco Vollema','Frans van Poppel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444218,'Herman van Deutekom','Wim Manders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444218,'Raymond Ruesink','Frans van Poppel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444218,'Sicco Vollema','Wim Manders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444218,'Herman van Deutekom','Hans Moerkerk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444218,'Herman van Deutekom','Frans van Poppel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444218,'Sicco Vollema','Hans Moerkerk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444218,'Raymond Ruesink','Wim Manders',1,0);
