delete from cm_match_details where game_id in (select game_id from cm_matches where cpn_id = (select id from cm_competitions where name = 'Combi 2e-3e klasse poule 1' and ssn_id like '2014%'));
delete from cm_matches where cpn_id = (select id from cm_competitions where name = 'Combi 2e-3e klasse poule 1' and ssn_id like '2014%');
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-09-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 1' and ssn_id like '2014%'),444223,'De Biljartmakers 3','Fluke je snooker',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444223,'Maurijn Maas','Danny van der Werff',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444223,'Fred Ensel','Dim Gerven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444223,'Wim Koudstaal','Anton Geschev',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444223,'Maurijn Maas','Dim Gerven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444223,'Fred Ensel','Anton Geschev',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444223,'Wim Koudstaal','Danny van der Werff',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444223,'Wim Koudstaal','Dim Gerven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444223,'Fred Ensel','Danny van der Werff',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444223,'Maurijn Maas','Anton Geschev',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('30-09-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 1' and ssn_id like '2014%'),444226,'THE FIFTH PLANET 5','De Biljartmakers 3',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444226,'Edwin van Vugt','Maurijn Maas',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444226,'Peter Fokker','Hans Slier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444226,'Edwin van Vugt','Nico Soeren',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444226,'Peter Fokker','Maurijn Maas',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444226,'Peter Fokker','Nico Soeren',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444226,'Edwin van Vugt','Hans Slier',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 1' and ssn_id like '2014%'),447355,'Spaernehuis 1','THE FIFTH PLANET 5',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(447355,'Jonas de Vries','Peter Fokker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(447355,'Anton Kerstholt','Edwin van Vugt',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(447355,'Barry Lambers','Edwin van Vugt',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(447355,'Anton Kerstholt','Peter Fokker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(447355,'Barry Lambers','Peter Fokker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(447355,'Jonas de Vries','Edwin van Vugt',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 1' and ssn_id like '2014%'),444231,'Amsterdams onwettige zonen','Fluke je snooker',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444231,'Rahman Azimi','Stefan van Lieshout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444231,'Ali Soeleman','Anton Geschev',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444231,'Stephan Schmidt','Dim Gerven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444231,'Rahman Azimi','Anton Geschev',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444231,'Ali Soeleman','Dim Gerven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444231,'Stephan Schmidt','Stefan van Lieshout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444231,'Stephan Schmidt','Anton Geschev',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444231,'Ali Soeleman','Stefan van Lieshout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444231,'Rahman Azimi','Dim Gerven',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 1' and ssn_id like '2014%'),444232,'Spaernehuis 1','De Biljartmakers 3',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444232,'David Prins','Hans Slier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444232,'Anton Kerstholt','Fred Ensel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444232,'Barry Lambers','Nico Soeren',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444232,'David Prins','Fred Ensel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444232,'Anton Kerstholt','Nico Soeren',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444232,'Barry Lambers','Hans Slier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444232,'Barry Lambers','Fred Ensel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444232,'Anton Kerstholt','Hans Slier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444232,'David Prins','Nico Soeren',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 1' and ssn_id like '2014%'),444234,'THE FIFTH PLANET 5','Amsterdams onwettige zonen',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444234,'Edwin van Vugt','Jeroen van der Linde',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444234,'Fred Wurtz','Gethin Davies',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444234,'Peter Fokker','Etienne Verheem',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444234,'Edwin van Vugt','Gethin Davies',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444234,'Fred Wurtz','Etienne Verheem',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444234,'Peter Fokker','Jeroen van der Linde',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444234,'Peter Fokker','Gethin Davies',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444234,'Fred Wurtz','Jeroen van der Linde',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444234,'Edwin van Vugt','Etienne Verheem',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-10-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 1' and ssn_id like '2014%'),444238,'Amsterdams onwettige zonen','De Biljartmakers 3',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 1' and ssn_id like '2014%'),444242,'Fluke je snooker','Spaernehuis 1',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 1' and ssn_id like '2014%'),444245,'Fluke je snooker','THE FIFTH PLANET 5',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444245,'Niels van Lieshout','Peter Fokker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444245,'Martin van Zeelt','Fred Wurtz',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444245,'Niels van Lieshout','Fred Wurtz',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444245,'Martin van Zeelt','Edwin van Vugt',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444245,'Martin van Zeelt','Peter Fokker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444245,'Niels van Lieshout','Edwin van Vugt',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 1' and ssn_id like '2014%'),444248,'Spaernehuis 1','Amsterdams onwettige zonen',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444248,'Jonas de Vries','Ali Soeleman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444248,'David Prins','Stephan Schmidt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444248,'Barry Lambers','Etienne Verheem',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444248,'Jonas de Vries','Stephan Schmidt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444248,'David Prins','Etienne Verheem',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444248,'Barry Lambers','Ali Soeleman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444248,'Barry Lambers','Stephan Schmidt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444248,'David Prins','Ali Soeleman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444248,'Jonas de Vries','Etienne Verheem',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 1' and ssn_id like '2014%'),444249,'Fluke je snooker','De Biljartmakers 3',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('26-11-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 1' and ssn_id like '2014%'),444255,'De Biljartmakers 3','THE FIFTH PLANET 5',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444255,'Wim Koudstaal','Edwin van Vugt',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444255,'Nico Soeren','Fred Wurtz',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444255,'Wim Koudstaal','Fred Wurtz',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444255,'Wil van Vliet','Edwin van Vugt',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444255,'Wil van Vliet','Fred Wurtz',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444255,'Nico Soeren','Edwin van Vugt',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('01-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 1' and ssn_id like '2014%'),444257,'Fluke je snooker','Amsterdams onwettige zonen',1,8);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 1' and ssn_id like '2014%'),444259,'De Biljartmakers 3','Spaernehuis 1',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444259,'Nico Soeren','David Prins',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444259,'Hans Slier','Anton Kerstholt',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444259,'Wim Koudstaal','Jonas de Vries',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444259,'Nico Soeren','Anton Kerstholt',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444259,'Hans Slier','Jonas de Vries',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444259,'Wim Koudstaal','David Prins',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444259,'Wim Koudstaal','Anton Kerstholt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444259,'Hans Slier','David Prins',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444259,'Nico Soeren','Jonas de Vries',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-12-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 1' and ssn_id like '2014%'),444268,'De Biljartmakers 3','Amsterdams onwettige zonen',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444268,'Maurijn Maas','Stephan Schmidt',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444268,'Wim Koudstaal','Etienne Verheem',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444268,'Nico Soeren','Rahman Azimi',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444268,'Maurijn Maas','Etienne Verheem',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444268,'Wim Koudstaal','Rahman Azimi',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444268,'Nico Soeren','Stephan Schmidt',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444268,'Nico Soeren','Etienne Verheem',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444268,'Wim Koudstaal','Stephan Schmidt',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444268,'Maurijn Maas','Rahman Azimi',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 1' and ssn_id like '2014%'),448332,'THE FIFTH PLANET 5','Spaernehuis 1',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 1' and ssn_id like '2014%'),448426,'Amsterdams onwettige zonen','THE FIFTH PLANET 5',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448426,'Gethin Davies','Peter Fokker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448426,'Stephan Schmidt','Edwin van Vugt',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448426,'Etienne Verheem','Peter Fokker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448426,'Gethin Davies','Edwin van Vugt',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448426,'Stephan Schmidt','Peter Fokker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(448426,'Etienne Verheem','Edwin van Vugt',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 1' and ssn_id like '2014%'),444272,'Spaernehuis 1','Fluke je snooker',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444272,'Anton Kerstholt','Anton Geschev',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444272,'David Prins','Niels van Lieshout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444272,'Barry Lambers','Dim Gerven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444272,'Anton Kerstholt','Niels van Lieshout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444272,'David Prins','Dim Gerven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444272,'Barry Lambers','Anton Geschev',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444272,'Barry Lambers','Niels van Lieshout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444272,'David Prins','Anton Geschev',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(444272,'Anton Kerstholt','Dim Gerven',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 1' and ssn_id like '2014%'),444274,'THE FIFTH PLANET 5','Fluke je snooker',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-01-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Combi 2e-3e klasse poule 1' and ssn_id like '2014%'),444275,'Amsterdams onwettige zonen','Spaernehuis 1',5,4);
