delete from cm_match_details where game_id in (select game_id from cm_matches where cpn_id = (select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2014%'));
delete from cm_matches where cpn_id = (select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2014%');
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2014%'),449390,'Snooker Utrecht 2','De Biljartmakers 3',9,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2014%'),449436,'Jumbo 11','THE GREEN SENSATIONS',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449436,'Teije Blauw','Jeroen Gode',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449436,'Peter Terhorst','Dennis van der Marel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449436,'Fedde Cadee','Roland van der Wulp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449436,'Teije Blauw','Dennis van der Marel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449436,'Peter Terhorst','Roland van der Wulp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449436,'Fedde Cadee','Jeroen Gode',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449436,'Fedde Cadee','Dennis van der Marel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449436,'Peter Terhorst','Jeroen Gode',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449436,'Teije Blauw','Roland van der Wulp',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2014%'),449392,'De Biljartmakers 3','OLD REBELS',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449392,'Nico Soeren','John Rodrigues Garcia',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449392,'Fred Ensel','Ed van den Berg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449392,'Wim Koudstaal','Jef Raber',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449392,'Nico Soeren','Ed van den Berg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449392,'Fred Ensel','Jef Raber',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449392,'Wim Koudstaal','John Rodrigues Garcia',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449392,'Wim Koudstaal','Ed van den Berg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449392,'Fred Ensel','John Rodrigues Garcia',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449392,'Nico Soeren','Jef Raber',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2014%'),449393,'THE GREEN SENSATIONS','Snooker Utrecht 2',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449393,'Dennis van der Marel','Wouter Teensma',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449393,'Jeffrey de Wijs','Rene Bos',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449393,'Roland van der Wulp','Michiel Vlootman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449393,'Dennis van der Marel','Rene Bos',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449393,'Jeffrey de Wijs','Michiel Vlootman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449393,'Roland van der Wulp','Wouter Teensma',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449393,'Roland van der Wulp','Rene Bos',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449393,'Jeffrey de Wijs','Wouter Teensma',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449393,'Dennis van der Marel','Michiel Vlootman',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2014%'),449437,'SPIJKENISSE 9','Jumbo 11',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2014%'),449394,'OLD REBELS','THE GREEN SENSATIONS',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449394,'Jef Raber','Michael van der Wulp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449394,'John Rodrigues Garcia','Roland van der Wulp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449394,'Ed van den Berg','Jeroen Gode',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449394,'Jef Raber','Roland van der Wulp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449394,'John Rodrigues Garcia','Jeroen Gode',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449394,'Ed van den Berg','Michael van der Wulp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449394,'Ed van den Berg','Roland van der Wulp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449394,'John Rodrigues Garcia','Michael van der Wulp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449394,'Jef Raber','Jeroen Gode',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2014%'),449395,'SPIJKENISSE 9','De Biljartmakers 3',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449395,'Arie van den Houwen','Maurijn Maas',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449395,'Remco van Brenkelen','Hans Slier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449395,'Anton Scharloo','Nico Soeren',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449395,'Arie van den Houwen','Hans Slier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449395,'Remco van Brenkelen','Nico Soeren',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449395,'Anton Scharloo','Maurijn Maas',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449395,'Anton Scharloo','Hans Slier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449395,'Remco van Brenkelen','Maurijn Maas',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449395,'Arie van den Houwen','Nico Soeren',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2014%'),449438,'Jumbo 11','Snooker Utrecht 2',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('30-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2014%'),449396,'Snooker Utrecht 2','OLD REBELS',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('01-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2014%'),449439,'De Biljartmakers 3','Jumbo 11',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449439,'Wim Koudstaal','Daniël Alferink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449439,'Fred Ensel','Matthijs Maandag',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449439,'Nico Soeren','Peter Terhorst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449439,'Wim Koudstaal','Matthijs Maandag',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449439,'Fred Ensel','Peter Terhorst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449439,'Nico Soeren','Daniël Alferink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449439,'Nico Soeren','Matthijs Maandag',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449439,'Fred Ensel','Daniël Alferink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449439,'Wim Koudstaal','Peter Terhorst',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2014%'),449397,'THE GREEN SENSATIONS','SPIJKENISSE 9',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449397,'Dennis van der Marel','Arie Beljaars',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449397,'Michael van der Wulp','Arie van den Houwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449397,'Jeroen Gode','Anton Scharloo',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449397,'Dennis van der Marel','Arie van den Houwen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449397,'Michael van der Wulp','Anton Scharloo',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449397,'Jeroen Gode','Arie Beljaars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449397,'Jeroen Gode','Arie van den Houwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449397,'Michael van der Wulp','Arie Beljaars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449397,'Dennis van der Marel','Anton Scharloo',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2014%'),449398,'De Biljartmakers 3','THE GREEN SENSATIONS',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449398,'Nico Soeren','Jeroen Gode',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449398,'Wim Koudstaal','Jeroen Hofmeester',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449398,'Maurijn Maas','Dennis van der Marel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449398,'Nico Soeren','Jeroen Hofmeester',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449398,'Wim Koudstaal','Dennis van der Marel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449398,'Maurijn Maas','Jeroen Gode',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449398,'Maurijn Maas','Jeroen Hofmeester',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449398,'Wim Koudstaal','Jeroen Gode',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449398,'Nico Soeren','Dennis van der Marel',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2014%'),449440,'Jumbo 11','OLD REBELS',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2014%'),449400,'De Biljartmakers 3','Snooker Utrecht 2',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449400,'Wim Koudstaal','John Zom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449400,'Wil van Vliet','Wouter Teensma',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449400,'Fred Ensel','Wouter Teensma',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449400,'Wil van Vliet','John Zom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449400,'Fred Ensel','John Zom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449400,'Wim Koudstaal','Wouter Teensma',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2014%'),449401,'SPIJKENISSE 9','OLD REBELS',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449401,'Arie van den Houwen','Jef Raber',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449401,'Arie Beljaars','Ed van den Berg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449401,'Anton Scharloo','John Rodrigues Garcia',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449401,'Arie van den Houwen','Ed van den Berg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449401,'Arie Beljaars','John Rodrigues Garcia',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449401,'Anton Scharloo','Jef Raber',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449401,'Anton Scharloo','Ed van den Berg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449401,'Arie Beljaars','Jef Raber',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449401,'Arie van den Houwen','John Rodrigues Garcia',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2014%'),449441,'THE GREEN SENSATIONS','Jumbo 11',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449441,'Jeroen Gode','Peter Terhorst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449441,'Roland van der Wulp','Matthijs Maandag',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449441,'Michael van der Wulp','Fedde Cadee',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449441,'Jeroen Gode','Matthijs Maandag',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449441,'Roland van der Wulp','Fedde Cadee',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449441,'Michael van der Wulp','Peter Terhorst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449441,'Michael van der Wulp','Matthijs Maandag',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449441,'Roland van der Wulp','Peter Terhorst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449441,'Jeroen Gode','Fedde Cadee',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('30-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2014%'),449638,'SPIJKENISSE 9','Snooker Utrecht 2',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449638,'Anton Scharloo','Wouter Teensma',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449638,'Arie van den Houwen','John Zom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449638,'Arie Beljaars','Debabrata Panja',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449638,'Anton Scharloo','John Zom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449638,'Arie van den Houwen','Debabrata Panja',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449638,'Arie Beljaars','Wouter Teensma',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449638,'Arie Beljaars','John Zom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449638,'Arie van den Houwen','Wouter Teensma',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449638,'Anton Scharloo','Debabrata Panja',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2014%'),449402,'Snooker Utrecht 2','THE GREEN SENSATIONS',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449402,'Justin van Emstede','Jeroen Gode',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449402,'Rene Bos','Dennis van der Marel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449402,'Justin van Emstede','Jeroen Hofmeester',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449402,'Rene Bos','Jeroen Gode',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449402,'Rene Bos','Jeroen Hofmeester',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449402,'Justin van Emstede','Dennis van der Marel',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2014%'),449403,'OLD REBELS','De Biljartmakers 3',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449403,'Eric Feteridge','Nico Soeren',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449403,'John Rodrigues Garcia','Maurijn Maas',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449403,'Jef Raber','Wim Koudstaal',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449403,'Eric Feteridge','Maurijn Maas',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449403,'John Rodrigues Garcia','Wim Koudstaal',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449403,'Jef Raber','Nico Soeren',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449403,'Jef Raber','Maurijn Maas',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449403,'John Rodrigues Garcia','Nico Soeren',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449403,'Eric Feteridge','Wim Koudstaal',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2014%'),449442,'Jumbo 11','SPIJKENISSE 9',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449442,'Peter Terhorst','Arie Beljaars',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449442,'Fedde Cadee','Arie van den Houwen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449442,'Matthijs Maandag','Anton Scharloo',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449442,'Peter Terhorst','Arie van den Houwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449442,'Fedde Cadee','Anton Scharloo',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449442,'Matthijs Maandag','Arie Beljaars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449442,'Matthijs Maandag','Arie van den Houwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449442,'Fedde Cadee','Arie Beljaars',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449442,'Peter Terhorst','Anton Scharloo',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2014%'),449443,'Snooker Utrecht 2','Jumbo 11',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449443,'John Zom','Fedde Cadee',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449443,'Rene Bos','Matthijs Maandag',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449443,'Wouter Teensma','Teije Blauw',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449443,'John Zom','Matthijs Maandag',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449443,'Rene Bos','Teije Blauw',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449443,'Wouter Teensma','Fedde Cadee',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449443,'Wouter Teensma','Matthijs Maandag',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449443,'Rene Bos','Fedde Cadee',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449443,'John Zom','Teije Blauw',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2014%'),449404,'De Biljartmakers 3','SPIJKENISSE 9',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449404,'Wim Koudstaal','Anton Scharloo',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449404,'Nico Soeren','Arie Beljaars',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449404,'Wil van Vliet','Arie van den Houwen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449404,'Wim Koudstaal','Arie Beljaars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449404,'Nico Soeren','Arie van den Houwen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449404,'Wil van Vliet','Anton Scharloo',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449404,'Wil van Vliet','Arie Beljaars',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449404,'Nico Soeren','Anton Scharloo',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449404,'Wim Koudstaal','Arie van den Houwen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2014%'),449405,'THE GREEN SENSATIONS','OLD REBELS',9,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449405,'Jeffrey de Wijs','Eric Feteridge',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449405,'Michael van der Wulp','Ed van den Berg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449405,'Roland van der Wulp','Jef Raber',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449405,'Jeffrey de Wijs','Ed van den Berg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449405,'Michael van der Wulp','Jef Raber',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449405,'Roland van der Wulp','Eric Feteridge',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449405,'Roland van der Wulp','Ed van den Berg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449405,'Michael van der Wulp','Eric Feteridge',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449405,'Jeffrey de Wijs','Jef Raber',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2014%'),449406,'OLD REBELS','Snooker Utrecht 2',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449406,'Eric Feteridge','John Zom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449406,'John Rodrigues Garcia','Debabrata Panja',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449406,'Eric Feteridge','Debabrata Panja',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449406,'Jef Raber','John Zom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449406,'Jef Raber','Debabrata Panja',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449406,'John Rodrigues Garcia','John Zom',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2014%'),449407,'SPIJKENISSE 9','THE GREEN SENSATIONS',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449407,'Anton Scharloo','Jeffrey de Wijs',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449407,'Arie Beljaars','Roland van der Wulp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449407,'Remco van Brenkelen','Dennis van der Marel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449407,'Anton Scharloo','Roland van der Wulp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449407,'Arie Beljaars','Dennis van der Marel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449407,'Remco van Brenkelen','Jeffrey de Wijs',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449407,'Remco van Brenkelen','Roland van der Wulp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449407,'Arie Beljaars','Jeffrey de Wijs',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449407,'Anton Scharloo','Dennis van der Marel',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2014%'),449444,'Jumbo 11','De Biljartmakers 3',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449444,'Peter Terhorst','Nico Soeren',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449444,'Teije Blauw','Wil van Vliet',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449444,'Matthijs Maandag','Wim Koudstaal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449444,'Peter Terhorst','Wil van Vliet',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449444,'Teije Blauw','Wim Koudstaal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449444,'Matthijs Maandag','Nico Soeren',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449444,'Matthijs Maandag','Wil van Vliet',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449444,'Teije Blauw','Nico Soeren',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449444,'Peter Terhorst','Wim Koudstaal',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('25-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2014%'),449408,'Snooker Utrecht 2','SPIJKENISSE 9',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('26-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2014%'),449445,'OLD REBELS','Jumbo 11',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449445,'Eric Feteridge','Peter Terhorst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449445,'John Rodrigues Garcia','Daniël Alferink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449445,'Jef Raber','Teije Blauw',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449445,'Eric Feteridge','Daniël Alferink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449445,'John Rodrigues Garcia','Teije Blauw',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449445,'Jef Raber','Peter Terhorst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449445,'Jef Raber','Daniël Alferink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449445,'John Rodrigues Garcia','Peter Terhorst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449445,'Eric Feteridge','Teije Blauw',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('28-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2014%'),449409,'THE GREEN SENSATIONS','De Biljartmakers 3',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449409,'Dennis van der Marel','Wim Koudstaal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449409,'Michael van der Wulp','Fred Ensel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449409,'Roland van der Wulp','Maurijn Maas',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449409,'Dennis van der Marel','Fred Ensel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449409,'Michael van der Wulp','Maurijn Maas',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449409,'Roland van der Wulp','Wim Koudstaal',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449409,'Roland van der Wulp','Fred Ensel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449409,'Michael van der Wulp','Wim Koudstaal',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449409,'Dennis van der Marel','Maurijn Maas',0,1);
