delete from cm_match_details where game_id in (select game_id from cm_matches where cpn_id = (select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'));
delete from cm_matches where cpn_id = (select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%');
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-09-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351144,'Fluke je snooker','Chicks With Sticks',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-09-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351147,'Spaernehuis 1','Jumbo 11',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351147,'Andrew Smales','Fedde Cadee',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351147,'Anton Kerstholt','Matthijs Maandag',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351147,'Barry Lambers','Matthijs Maandag',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351147,'Anton Kerstholt','Fedde Cadee',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351147,'Barry Lambers','Fedde Cadee',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351147,'Andrew Smales','Matthijs Maandag',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-09-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351150,'Trickshot','CUE GENIUS 2',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-09-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351151,'OP HERHALING','Well John...',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351151,'Henk Leegwater','Edwin Horlings',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351151,'Rob van den Berg','Wouter Moes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351151,'Peter Schuddeboom','Jean Paul Kievit',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351151,'Henk Leegwater','Wouter Moes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351151,'Rob van den Berg','Jean Paul Kievit',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351151,'Peter Schuddeboom','Edwin Horlings',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351151,'Peter Schuddeboom','Wouter Moes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351151,'Rob van den Berg','Edwin Horlings',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351151,'Henk Leegwater','Jean Paul Kievit',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-09-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351153,'Chicks With Sticks','Spaernehuis 1',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351153,'Lisette de Groot','Barry Lambers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351153,'Eva Groen','Andrew Smales',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351153,'Tens Tensen','Anton Kerstholt',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351153,'Lisette de Groot','Andrew Smales',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351153,'Eva Groen','Anton Kerstholt',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351153,'Tens Tensen','Barry Lambers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351153,'Tens Tensen','Andrew Smales',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351153,'Eva Groen','Barry Lambers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351153,'Lisette de Groot','Anton Kerstholt',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-09-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),359044,'Well John...','Trickshot',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-10-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351155,'CUE GENIUS 2','OP HERHALING',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351155,'Ronald Brouwer','Henk Leegwater',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351155,'Ronald Rave','Peter Schuddeboom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351155,'Harry de Boer','Willem Visser',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351155,'Ronald Brouwer','Peter Schuddeboom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351155,'Ronald Rave','Willem Visser',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351155,'Harry de Boer','Henk Leegwater',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351155,'Harry de Boer','Peter Schuddeboom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351155,'Ronald Rave','Henk Leegwater',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351155,'Ronald Brouwer','Willem Visser',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-10-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351157,'Fluke je snooker 2','Trickshot',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-10-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351158,'Jumbo 11','Chicks With Sticks',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351158,'Fedde Cadee','Lisette de Groot',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351158,'Teije Blauw','Tens Tensen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351158,'Dick Potharst','Eva Groen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351158,'Fedde Cadee','Tens Tensen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351158,'Teije Blauw','Eva Groen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351158,'Dick Potharst','Lisette de Groot',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351158,'Dick Potharst','Tens Tensen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351158,'Teije Blauw','Lisette de Groot',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351158,'Fedde Cadee','Eva Groen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-10-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351159,'Well John...','CUE GENIUS 2',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-10-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351161,'Trickshot','Fluke je snooker',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-10-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351162,'OP HERHALING','Fluke je snooker 2',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-10-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351164,'Fluke je snooker','OP HERHALING',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-10-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351165,'Spaernehuis 1','Trickshot',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351165,'Anton Kerstholt','Ruud Docter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351165,'Andrew Smales','John Zoontjes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351165,'David Prins','Henk Visser',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351165,'Anton Kerstholt','John Zoontjes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351165,'Andrew Smales','Henk Visser',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351165,'David Prins','Ruud Docter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351165,'David Prins','John Zoontjes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351165,'Andrew Smales','Ruud Docter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351165,'Anton Kerstholt','Henk Visser',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-10-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351166,'Fluke je snooker 2','Well John...',1,8);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('29-10-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351169,'Well John...','Fluke je snooker',9,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('30-10-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351171,'CUE GENIUS 2','Fluke je snooker 2',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('30-10-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351172,'Trickshot','Jumbo 11',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('31-10-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351173,'OP HERHALING','Spaernehuis 1',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351173,'Henk Leegwater','Barry Lambers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351173,'Rob van den Berg','Andrew Smales',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351173,'Peter Schuddeboom','Anton Kerstholt',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351173,'Henk Leegwater','Andrew Smales',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351173,'Rob van den Berg','Anton Kerstholt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351173,'Peter Schuddeboom','Barry Lambers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351173,'Peter Schuddeboom','Andrew Smales',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351173,'Rob van den Berg','Barry Lambers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351173,'Henk Leegwater','Anton Kerstholt',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-11-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351174,'Fluke je snooker','CUE GENIUS 2',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-11-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351175,'Spaernehuis 1','Well John...',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-11-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351177,'Chicks With Sticks','Trickshot',0,9);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('26-11-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351179,'Well John...','Jumbo 11',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-11-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351180,'CUE GENIUS 2','Spaernehuis 1',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351180,'Harry de Boer','Barry Lambers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351180,'Ronald Rave','David Prins',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351180,'Ronald Brouwer','Andrew Smales',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351180,'Harry de Boer','David Prins',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351180,'Ronald Rave','Andrew Smales',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351180,'Ronald Brouwer','Barry Lambers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351180,'Ronald Brouwer','David Prins',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351180,'Ronald Rave','Barry Lambers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351180,'Harry de Boer','Andrew Smales',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('28-11-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351182,'Fluke je snooker 2','Fluke je snooker',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('28-11-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351183,'OP HERHALING','Chicks With Sticks',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-12-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351187,'Well John...','Chicks With Sticks',8,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-12-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351188,'Jumbo 11','CUE GENIUS 2',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-12-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351189,'Fluke je snooker','Spaernehuis 1',0,9);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-12-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351191,'CUE GENIUS 2','Chicks With Sticks',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351191,'Harry de Boer','Tens Tensen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351191,'Ronald Rave','Lisette de Groot',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351191,'Ronald Brouwer','Eva Groen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351191,'Harry de Boer','Lisette de Groot',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351191,'Ronald Rave','Eva Groen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351191,'Ronald Brouwer','Tens Tensen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351191,'Ronald Brouwer','Lisette de Groot',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351191,'Ronald Rave','Tens Tensen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351191,'Harry de Boer','Eva Groen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-12-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351192,'Fluke je snooker 2','Jumbo 11',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-12-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),364090,'Spaernehuis 1','Fluke je snooker 2',9,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(364090,'Anton Kerstholt','Niels van Lieshout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(364090,'Andrew Smales','Peter Afink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(364090,'Barry Lambers','Gino van den Berg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(364090,'Anton Kerstholt','Peter Afink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(364090,'Andrew Smales','Gino van den Berg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(364090,'Barry Lambers','Niels van Lieshout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(364090,'Barry Lambers','Peter Afink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(364090,'Andrew Smales','Niels van Lieshout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(364090,'Anton Kerstholt','Gino van den Berg',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-01-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351197,'Fluke je snooker 2','Chicks With Sticks',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-01-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351198,'Jumbo 11','Fluke je snooker',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('31-01-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351202,'Chicks With Sticks','Fluke je snooker',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-02-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351205,'Well John...','OP HERHALING',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-02-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351206,'CUE GENIUS 2','Trickshot',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-02-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351207,'Spaernehuis 1','Chicks With Sticks',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351207,'Anton Kerstholt','Tens Tensen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351207,'Andrew Smales','Lisette de Groot',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351207,'Barry Lambers','Eva Groen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351207,'Anton Kerstholt','Lisette de Groot',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351207,'Andrew Smales','Eva Groen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351207,'Barry Lambers','Tens Tensen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351207,'Barry Lambers','Lisette de Groot',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351207,'Andrew Smales','Tens Tensen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351207,'Anton Kerstholt','Eva Groen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-02-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351210,'Trickshot','Fluke je snooker 2',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-02-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351211,'OP HERHALING','CUE GENIUS 2',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-02-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351213,'Chicks With Sticks','Jumbo 11',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351213,'Lisette de Groot','Fedde Cadee',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351213,'Eva Groen','Peter Terhorst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351213,'Tens Tensen','Teije Blauw',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351213,'Lisette de Groot','Peter Terhorst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351213,'Eva Groen','Teije Blauw',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351213,'Tens Tensen','Fedde Cadee',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351213,'Tens Tensen','Peter Terhorst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351213,'Eva Groen','Fedde Cadee',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351213,'Lisette de Groot','Teije Blauw',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-02-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351217,'Fluke je snooker 2','OP HERHALING',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-03-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),364838,'Trickshot','OP HERHALING',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-03-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351219,'Well John...','Fluke je snooker 2',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-03-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351221,'Trickshot','Spaernehuis 1',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-03-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351222,'OP HERHALING','Fluke je snooker',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351222,'Rob van den Berg','Frank Hus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351222,'Peter Schuddeboom','Anton Geschev',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351222,'Willem Visser','Stefan van Lieshout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351222,'Rob van den Berg','Anton Geschev',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351222,'Peter Schuddeboom','Stefan van Lieshout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351222,'Willem Visser','Frank Hus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351222,'Willem Visser','Anton Geschev',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351222,'Peter Schuddeboom','Frank Hus',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351222,'Rob van den Berg','Stefan van Lieshout',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-03-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),365453,'CUE GENIUS 2','Well John...',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-03-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),364983,'Trickshot','Well John...',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('25-03-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351224,'Fluke je snooker','Well John...',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-03-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351225,'Spaernehuis 1','OP HERHALING',9,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-03-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351226,'Fluke je snooker 2','CUE GENIUS 2',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('28-03-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351228,'Jumbo 11','Trickshot',1,8);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('01-04-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351229,'Well John...','Spaernehuis 1',1,8);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-04-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351231,'CUE GENIUS 2','Fluke je snooker',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-04-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351233,'OP HERHALING','Jumbo 11',8,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-04-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351234,'Fluke je snooker','Fluke je snooker 2',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-04-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351235,'Spaernehuis 1','CUE GENIUS 2',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351235,'David Prins','Ronald Rave',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351235,'Andrew Smales','Ronald Brouwer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351235,'Barry Lambers','Harry de Boer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351235,'David Prins','Ronald Brouwer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351235,'Andrew Smales','Harry de Boer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351235,'Barry Lambers','Ronald Rave',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351235,'Barry Lambers','Ronald Brouwer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351235,'Andrew Smales','Ronald Rave',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351235,'David Prins','Harry de Boer',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-04-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351237,'Chicks With Sticks','OP HERHALING',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-04-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351238,'Jumbo 11','Well John...',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-04-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),366130,'Trickshot','Chicks With Sticks',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-04-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),365988,'Fluke je snooker','Trickshot',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-04-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351240,'CUE GENIUS 2','Jumbo 11',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-04-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351242,'Fluke je snooker 2','Spaernehuis 1',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('25-04-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351239,'Chicks With Sticks','Well John...',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351239,'Tens Tensen','Wouter Moes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351239,'Lisette de Groot','Edwin Horlings',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351239,'Eva Groen','Marc Koene',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351239,'Tens Tensen','Edwin Horlings',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351239,'Lisette de Groot','Marc Koene',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351239,'Eva Groen','Wouter Moes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351239,'Eva Groen','Edwin Horlings',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351239,'Lisette de Groot','Wouter Moes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351239,'Tens Tensen','Marc Koene',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('01-05-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351245,'Spaernehuis 1','Fluke je snooker',9,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351245,'Anton Kerstholt','Anne Duivis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351245,'Barry Lambers','Frank Hus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351245,'David Prins','Dim Gerven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351245,'Anton Kerstholt','Frank Hus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351245,'Barry Lambers','Dim Gerven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351245,'David Prins','Anne Duivis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351245,'David Prins','Frank Hus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351245,'Barry Lambers','Anne Duivis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351245,'Anton Kerstholt','Dim Gerven',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-05-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351247,'Chicks With Sticks','CUE GENIUS 2',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351247,'Lisette de Groot','Harry de Boer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351247,'Eva Groen','Ronald Rave',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351247,'Tens Tensen','Ronald Brouwer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351247,'Lisette de Groot','Ronald Rave',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351247,'Eva Groen','Ronald Brouwer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351247,'Tens Tensen','Harry de Boer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351247,'Tens Tensen','Ronald Rave',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351247,'Eva Groen','Harry de Boer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351247,'Lisette de Groot','Ronald Brouwer',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-05-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351248,'Jumbo 11','Fluke je snooker 2',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-05-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351249,'Fluke je snooker','Jumbo 11',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-05-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351253,'OP HERHALING','Trickshot',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-05-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),351252,'Chicks With Sticks','Fluke je snooker 2',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351252,'Lisette de Groot','Rob van den Berg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351252,'Eva Groen','Niels van Lieshout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351252,'Tens Tensen','Peter Afink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351252,'Lisette de Groot','Niels van Lieshout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351252,'Eva Groen','Peter Afink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351252,'Tens Tensen','Rob van den Berg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351252,'Tens Tensen','Niels van Lieshout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351252,'Eva Groen','Rob van den Berg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351252,'Lisette de Groot','Peter Afink',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-05-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde divisie poule 1' and ssn_id like '2012%'),366745,'Jumbo 11','Spaernehuis 1',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366745,'Matthijs Maandag','Andrew Smales',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366745,'Fedde Cadee','Anton Kerstholt',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366745,'Peter Terhorst','Barry Lambers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366745,'Matthijs Maandag','Anton Kerstholt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366745,'Fedde Cadee','Barry Lambers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366745,'Peter Terhorst','Andrew Smales',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366745,'Peter Terhorst','Anton Kerstholt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366745,'Fedde Cadee','Andrew Smales',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366745,'Matthijs Maandag','Barry Lambers',1,0);
