delete from cm_match_details where game_id in (select game_id from cm_matches where cpn_id = (select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2011%'));
delete from cm_matches where cpn_id = (select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2011%');
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-09-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2011%'),294357,'Hoogewoerd 4','SPIJKENISSE 9',1,8);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-09-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2011%'),294360,'SNOOKERIJ 4','Snookerij 69',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294360,'Henk Buls','Joost Elfering',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294360,'Wally Hovens','Peter Stoute',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294360,'Jeroen van Kins','Arjen Joosten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294360,'Henk Buls','Peter Stoute',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294360,'Wally Hovens','Arjen Joosten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294360,'Jeroen van Kins','Joost Elfering',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294360,'Jeroen van Kins','Peter Stoute',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294360,'Wally Hovens','Joost Elfering',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294360,'Henk Buls','Arjen Joosten',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-09-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2011%'),294361,'Snookerij 69','Capelle Vaaf',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294361,'Joost Elfering','Jan Rouw',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294361,'Arjen Joosten','Richard Mostert',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294361,'Peter Stoute','David Uljee',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294361,'Joost Elfering','Richard Mostert',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294361,'Arjen Joosten','David Uljee',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294361,'Peter Stoute','Jan Rouw',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294361,'Peter Stoute','Richard Mostert',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294361,'Arjen Joosten','Jan Rouw',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294361,'Joost Elfering','David Uljee',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('29-09-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2011%'),294364,'SPIJKENISSE 9','Jumbo 11',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294364,'Patrick Beljaars','Matthijs Maandag',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294364,'Arie Beljaars','Peter Terhorst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294364,'Remco van Brenkelen','Teije Blauw',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294364,'Patrick Beljaars','Peter Terhorst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294364,'Arie Beljaars','Teije Blauw',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294364,'Remco van Brenkelen','Matthijs Maandag',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294364,'Remco van Brenkelen','Peter Terhorst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294364,'Arie Beljaars','Matthijs Maandag',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294364,'Patrick Beljaars','Teije Blauw',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-10-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2011%'),294365,'Hoogewoerd 4','Snookerij 69',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294365,'Emiel van der Hart','Joost Elfering',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294365,'Leander Arkenau','Arjen Joosten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294365,'Laurens Steernberg','Peter Stoute',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294365,'Emiel van der Hart','Arjen Joosten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294365,'Leander Arkenau','Peter Stoute',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294365,'Laurens Steernberg','Joost Elfering',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294365,'Laurens Steernberg','Arjen Joosten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294365,'Leander Arkenau','Joost Elfering',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294365,'Emiel van der Hart','Peter Stoute',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-10-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2011%'),294368,'SNOOKERIJ 4','Capelle Vaaf',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294368,'Jeroen van Kins','Kevin Jansen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294368,'Marcel de Jong','Richard Mostert',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294368,'Aat Smits','Martijn Loot',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294368,'Jeroen van Kins','Richard Mostert',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294368,'Marcel de Jong','Martijn Loot',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294368,'Aat Smits','Kevin Jansen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294368,'Aat Smits','Richard Mostert',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294368,'Marcel de Jong','Kevin Jansen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294368,'Jeroen van Kins','Martijn Loot',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-10-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2011%'),294369,'Snookerij 69','Jumbo 11',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-10-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2011%'),294371,'Capelle Vaaf','Hoogewoerd 4',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294371,'René van Lier','Laurens Steernberg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294371,'Kevin Jansen','Ilja Steenhorst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294371,'René van Lier','Tjebbe Borggreve',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294371,'Kevin Jansen','Laurens Steernberg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294371,'Kevin Jansen','Tjebbe Borggreve',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294371,'René van Lier','Ilja Steenhorst',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-10-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2011%'),294372,'SPIJKENISSE 9','SNOOKERIJ 4',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294372,'Patrick Beljaars','Marcel de Jong',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294372,'Arie Beljaars','Aat Smits',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294372,'Arie van den Houwen','Wally Hovens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294372,'Patrick Beljaars','Aat Smits',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294372,'Arie Beljaars','Wally Hovens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294372,'Arie van den Houwen','Marcel de Jong',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294372,'Arie van den Houwen','Aat Smits',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294372,'Arie Beljaars','Marcel de Jong',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294372,'Patrick Beljaars','Wally Hovens',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2011%'),294374,'Jumbo 11','Capelle Vaaf',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294374,'Dick Potharst','Martijn Loot',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294374,'Matthijs Maandag','David Uljee',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294374,'Teije Blauw','Jan Rouw',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294374,'Dick Potharst','David Uljee',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294374,'Matthijs Maandag','Jan Rouw',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294374,'Teije Blauw','Martijn Loot',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294374,'Teije Blauw','David Uljee',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294374,'Matthijs Maandag','Martijn Loot',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294374,'Dick Potharst','Jan Rouw',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2011%'),294376,'SNOOKERIJ 4','Hoogewoerd 4',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294376,'Jeroen van Kins','Laurens Steernberg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294376,'Henk Buls','Emiel van der Hart',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294376,'Marcel de Jong','Ilja Steenhorst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294376,'Jeroen van Kins','Emiel van der Hart',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294376,'Henk Buls','Ilja Steenhorst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294376,'Marcel de Jong','Laurens Steernberg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294376,'Marcel de Jong','Emiel van der Hart',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294376,'Henk Buls','Laurens Steernberg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294376,'Jeroen van Kins','Ilja Steenhorst',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2011%'),294377,'Hoogewoerd 4','Jumbo 11',0,9);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294377,'Emiel van der Hart','Teije Blauw',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294377,'Leander Arkenau','Dick Potharst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294377,'Laurens Steernberg','Peter Terhorst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294377,'Emiel van der Hart','Dick Potharst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294377,'Leander Arkenau','Peter Terhorst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294377,'Laurens Steernberg','Teije Blauw',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294377,'Laurens Steernberg','Dick Potharst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294377,'Leander Arkenau','Teije Blauw',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294377,'Emiel van der Hart','Peter Terhorst',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2011%'),294378,'Snookerij 69','SPIJKENISSE 9',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('25-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2011%'),294384,'SNOOKERIJ 4','Jumbo 11',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294384,'Jeroen van Kins','Matthijs Maandag',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294384,'Marcel de Jong','Teije Blauw',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294384,'Aat Smits','Peter Terhorst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294384,'Jeroen van Kins','Teije Blauw',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294384,'Marcel de Jong','Peter Terhorst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294384,'Aat Smits','Matthijs Maandag',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294384,'Aat Smits','Teije Blauw',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294384,'Marcel de Jong','Matthijs Maandag',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294384,'Jeroen van Kins','Peter Terhorst',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('29-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2011%'),294385,'Snookerij 69','SNOOKERIJ 4',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('01-12-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2011%'),294388,'SPIJKENISSE 9','Hoogewoerd 4',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294388,'Patrick Beljaars','Laurens Steernberg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294388,'Arie Beljaars','Tjebbe Borggreve',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294388,'Arie van den Houwen','Leander Arkenau',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294388,'Patrick Beljaars','Tjebbe Borggreve',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294388,'Arie Beljaars','Leander Arkenau',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294388,'Arie van den Houwen','Laurens Steernberg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294388,'Arie van den Houwen','Tjebbe Borggreve',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294388,'Arie Beljaars','Laurens Steernberg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294388,'Patrick Beljaars','Leander Arkenau',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-12-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2011%'),294390,'Jumbo 11','SPIJKENISSE 9',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294390,'Teije Blauw','Arie Beljaars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294390,'Matthijs Maandag','Patrick Beljaars',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294390,'Peter Terhorst','Arie van den Houwen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294390,'Teije Blauw','Patrick Beljaars',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294390,'Matthijs Maandag','Arie van den Houwen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294390,'Peter Terhorst','Arie Beljaars',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294390,'Peter Terhorst','Patrick Beljaars',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294390,'Matthijs Maandag','Arie Beljaars',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294390,'Teije Blauw','Arie van den Houwen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2011%'),294393,'Snookerij 69','Hoogewoerd 4',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294393,'Arjen Joosten','Emiel van der Hart',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294393,'Joost Elfering','Laurens Steernberg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294393,'Peter Stoute','Ilja Steenhorst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294393,'Arjen Joosten','Laurens Steernberg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294393,'Joost Elfering','Ilja Steenhorst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294393,'Peter Stoute','Emiel van der Hart',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294393,'Peter Stoute','Laurens Steernberg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294393,'Joost Elfering','Emiel van der Hart',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294393,'Arjen Joosten','Ilja Steenhorst',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2011%'),308123,'SPIJKENISSE 9','Capelle Vaaf',0,9);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308123,'Arie van den Houwen','René van Lier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308123,'Patrick Beljaars','Kevin Jansen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308123,'Arie Beljaars','Jan Rouw',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308123,'Arie van den Houwen','Kevin Jansen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308123,'Patrick Beljaars','Jan Rouw',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308123,'Arie Beljaars','René van Lier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308123,'Arie Beljaars','Kevin Jansen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308123,'Patrick Beljaars','René van Lier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308123,'Arie van den Houwen','Jan Rouw',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2011%'),294395,'Capelle Vaaf','SNOOKERIJ 4',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294395,'Richard Mostert','Aat Smits',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294395,'Jan Rouw','Marcel de Jong',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294395,'Kevin Jansen','Jeroen van Kins',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294395,'Richard Mostert','Marcel de Jong',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294395,'Jan Rouw','Jeroen van Kins',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294395,'Kevin Jansen','Aat Smits',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294395,'Kevin Jansen','Marcel de Jong',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294395,'Jan Rouw','Aat Smits',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294395,'Richard Mostert','Jeroen van Kins',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2011%'),294399,'Jumbo 11','Snookerij 69',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2011%'),294400,'SNOOKERIJ 4','SPIJKENISSE 9',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294400,'Henk Buls','Patrick Beljaars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294400,'Wally Hovens','Arie Beljaars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294400,'Jeroen van Kins','Remco van Brenkelen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294400,'Henk Buls','Arie Beljaars',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294400,'Wally Hovens','Remco van Brenkelen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294400,'Jeroen van Kins','Patrick Beljaars',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294400,'Jeroen van Kins','Arie Beljaars',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294400,'Wally Hovens','Patrick Beljaars',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294400,'Henk Buls','Remco van Brenkelen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2011%'),294401,'Hoogewoerd 4','SNOOKERIJ 4',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('26-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2011%'),308327,'Capelle Vaaf','Snookerij 69',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308327,'David Uljee','Arjen Joosten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308327,'Kevin Jansen','Peter Stoute',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308327,'Richard Mostert','Joost Elfering',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308327,'David Uljee','Peter Stoute',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308327,'Kevin Jansen','Joost Elfering',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308327,'Richard Mostert','Arjen Joosten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308327,'Richard Mostert','Peter Stoute',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308327,'Kevin Jansen','Arjen Joosten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308327,'David Uljee','Joost Elfering',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('26-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2011%'),294404,'Capelle Vaaf','Jumbo 11',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-02-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2011%'),294407,'SPIJKENISSE 9','Snookerij 69',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294407,'Patrick Beljaars','Joost Elfering',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294407,'Arie Beljaars','Peter Stoute',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294407,'Remco van Brenkelen','Arjen Joosten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294407,'Patrick Beljaars','Peter Stoute',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294407,'Arie Beljaars','Arjen Joosten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294407,'Remco van Brenkelen','Joost Elfering',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294407,'Remco van Brenkelen','Peter Stoute',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294407,'Arie Beljaars','Joost Elfering',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294407,'Patrick Beljaars','Arjen Joosten',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-02-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2011%'),308181,'Hoogewoerd 4','Capelle Vaaf',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308181,'Ilja Steenhorst','René van Lier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308181,'Leander Arkenau','Jan Rouw',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308181,'Laurens Steernberg','Kevin Jansen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308181,'Ilja Steenhorst','Jan Rouw',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308181,'Leander Arkenau','Kevin Jansen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308181,'Laurens Steernberg','René van Lier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308181,'Laurens Steernberg','Jan Rouw',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308181,'Leander Arkenau','René van Lier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308181,'Ilja Steenhorst','Kevin Jansen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-02-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2011%'),294411,'Jumbo 11','SNOOKERIJ 4',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294411,'Peter Terhorst','Aat Smits',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294411,'Matthijs Maandag','Marcel de Jong',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294411,'Teije Blauw','Jeroen van Kins',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294411,'Peter Terhorst','Marcel de Jong',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294411,'Matthijs Maandag','Jeroen van Kins',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294411,'Teije Blauw','Aat Smits',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294411,'Teije Blauw','Marcel de Jong',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294411,'Matthijs Maandag','Aat Smits',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294411,'Peter Terhorst','Jeroen van Kins',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-02-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2011%'),294412,'Capelle Vaaf','SPIJKENISSE 9',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294412,'Richard Mostert','Arie Beljaars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294412,'Jan Rouw','Patrick Beljaars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294412,'Kevin Jansen','Arie van den Houwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294412,'Richard Mostert','Patrick Beljaars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294412,'Jan Rouw','Arie van den Houwen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294412,'Kevin Jansen','Arie Beljaars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294412,'Kevin Jansen','Patrick Beljaars',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294412,'Jan Rouw','Arie Beljaars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294412,'Richard Mostert','Arie van den Houwen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('28-02-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2011%'),294413,'Hoogewoerd 4','SPIJKENISSE 9',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294413,'Ilja Steenhorst','Arie Beljaars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294413,'Tjebbe Borggreve','Arie van den Houwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294413,'Emiel van der Hart','Patrick Beljaars',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294413,'Ilja Steenhorst','Arie van den Houwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294413,'Tjebbe Borggreve','Patrick Beljaars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294413,'Emiel van der Hart','Arie Beljaars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294413,'Emiel van der Hart','Arie van den Houwen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294413,'Tjebbe Borggreve','Arie Beljaars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294413,'Ilja Steenhorst','Patrick Beljaars',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-03-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2011%'),294416,'SNOOKERIJ 4','Snookerij 69',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294416,'Jeroen van Kins','Joost Elfering',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294416,'Wally Hovens','Peter Stoute',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294416,'Aat Smits','Arjen Joosten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294416,'Jeroen van Kins','Peter Stoute',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294416,'Wally Hovens','Arjen Joosten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294416,'Aat Smits','Joost Elfering',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294416,'Aat Smits','Peter Stoute',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294416,'Wally Hovens','Joost Elfering',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294416,'Jeroen van Kins','Arjen Joosten',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-03-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2011%'),294417,'Snookerij 69','Capelle Vaaf',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294417,'Peter Stoute','René van Lier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294417,'Joost Elfering','Jan Rouw',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294417,'Arjen Joosten','Richard Mostert',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294417,'Peter Stoute','Jan Rouw',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294417,'Joost Elfering','Richard Mostert',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294417,'Arjen Joosten','René van Lier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294417,'Arjen Joosten','Jan Rouw',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294417,'Joost Elfering','René van Lier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294417,'Peter Stoute','Richard Mostert',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('29-03-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2011%'),294420,'SPIJKENISSE 9','Jumbo 11',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-04-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2011%'),294421,'Hoogewoerd 4','Snookerij 69',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-04-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2011%'),294424,'SNOOKERIJ 4','Capelle Vaaf',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294424,'Jeroen van Kins','Martijn Loot',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294424,'Wally Hovens','Jan Rouw',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294424,'Henk Buls','Kevin Jansen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294424,'Jeroen van Kins','Jan Rouw',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294424,'Wally Hovens','Kevin Jansen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294424,'Henk Buls','Martijn Loot',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294424,'Henk Buls','Jan Rouw',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294424,'Wally Hovens','Martijn Loot',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294424,'Jeroen van Kins','Kevin Jansen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-04-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2011%'),294425,'Snookerij 69','Jumbo 11',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-04-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2011%'),294427,'Capelle Vaaf','Hoogewoerd 4',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294427,'Jan Rouw','Laurens Steernberg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294427,'Martijn Loot','Leander Arkenau',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294427,'Kevin Jansen','Emiel van der Hart',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294427,'Jan Rouw','Leander Arkenau',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294427,'Martijn Loot','Emiel van der Hart',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294427,'Kevin Jansen','Laurens Steernberg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294427,'Kevin Jansen','Leander Arkenau',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294427,'Martijn Loot','Laurens Steernberg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294427,'Jan Rouw','Emiel van der Hart',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-04-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2011%'),294428,'SPIJKENISSE 9','SNOOKERIJ 4',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294428,'Remco van Brenkelen','Marcel de Jong',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294428,'Patrick Beljaars','Aat Smits',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294428,'Arie Beljaars','Wally Hovens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294428,'Remco van Brenkelen','Aat Smits',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294428,'Patrick Beljaars','Wally Hovens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294428,'Arie Beljaars','Marcel de Jong',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294428,'Arie Beljaars','Aat Smits',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294428,'Patrick Beljaars','Marcel de Jong',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294428,'Remco van Brenkelen','Wally Hovens',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-04-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2011%'),294430,'Jumbo 11','Capelle Vaaf',0,9);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294430,'Dick Potharst','René van Lier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294430,'Matthijs Maandag','Kevin Jansen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294430,'Teije Blauw','Jan Rouw',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294430,'Dick Potharst','Kevin Jansen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294430,'Matthijs Maandag','Jan Rouw',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294430,'Teije Blauw','René van Lier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294430,'Teije Blauw','Kevin Jansen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294430,'Matthijs Maandag','René van Lier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294430,'Dick Potharst','Jan Rouw',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-04-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2011%'),294432,'SNOOKERIJ 4','Hoogewoerd 4',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294432,'Jeroen van Kins','Ilja Steenhorst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294432,'Henk Buls','Leander Arkenau',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294432,'Marcel de Jong','Laurens Steernberg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294432,'Jeroen van Kins','Leander Arkenau',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294432,'Henk Buls','Laurens Steernberg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294432,'Marcel de Jong','Ilja Steenhorst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294432,'Marcel de Jong','Leander Arkenau',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294432,'Henk Buls','Ilja Steenhorst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294432,'Jeroen van Kins','Laurens Steernberg',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2011%'),294434,'Snookerij 69','SPIJKENISSE 9',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294434,'Arjen Joosten','Arie Beljaars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294434,'Joost Elfering','Arie van den Houwen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294434,'Peter Stoute','Patrick Beljaars',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294434,'Arjen Joosten','Arie van den Houwen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294434,'Joost Elfering','Patrick Beljaars',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294434,'Peter Stoute','Arie Beljaars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294434,'Peter Stoute','Arie van den Houwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294434,'Joost Elfering','Arie Beljaars',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294434,'Arjen Joosten','Patrick Beljaars',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2011%'),294439,'SPIJKENISSE 9','Capelle Vaaf',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294439,'Arie Beljaars','Martijn Loot',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294439,'Patrick Beljaars','Kevin Jansen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294439,'Arie van den Houwen','René van Lier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294439,'Arie Beljaars','Kevin Jansen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294439,'Patrick Beljaars','René van Lier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294439,'Arie van den Houwen','Martijn Loot',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294439,'Arie van den Houwen','Kevin Jansen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294439,'Patrick Beljaars','Martijn Loot',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294439,'Arie Beljaars','René van Lier',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('25-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 3' and ssn_id like '2011%'),294440,'SNOOKERIJ 4','Jumbo 11',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294440,'Jeroen van Kins','Teije Blauw',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294440,'Henk Buls','Matthijs Maandag',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294440,'Wally Hovens','Matthijs Maandag',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294440,'Henk Buls','Teije Blauw',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294440,'Wally Hovens','Teije Blauw',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294440,'Jeroen van Kins','Matthijs Maandag',0,1);
