delete from cm_match_details where game_id in (select game_id from cm_matches where cpn_id = (select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'));
delete from cm_matches where cpn_id = (select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%');
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-09-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294201,'Fluke je snooker','The Blue Men',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-09-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294203,'Amsterdams onwettige zonen','Greenball',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294203,'Ali Soeleman','Martin van Zeelt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294203,'Chaka Sanichar','Ton Oud',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294203,'Fredo Lekkerkerker','Frans Gemser',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294203,'Ali Soeleman','Ton Oud',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294203,'Chaka Sanichar','Frans Gemser',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294203,'Fredo Lekkerkerker','Martin van Zeelt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294203,'Fredo Lekkerkerker','Ton Oud',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294203,'Chaka Sanichar','Martin van Zeelt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294203,'Ali Soeleman','Frans Gemser',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-09-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294204,'Chicks With Sticks','CUE GENIUS 2',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('26-09-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294205,'Greenball','Fluke je snooker 2',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-09-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294206,'CUE GENIUS 2','Fluke je snooker',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('28-09-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),299942,'Fluke je snooker 2','Triickshot',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('30-09-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294208,'The Blue Men','Amsterdams onwettige zonen',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-10-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294209,'Fluke je snooker','OP HERHALING',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-10-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294210,'Triickshot','Greenball',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-10-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294211,'Fluke je snooker 2','The Blue Men',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-10-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294212,'Amsterdams onwettige zonen','CUE GENIUS 2',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294212,'Gilliano Smit','Peter Eurlings',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294212,'Ali Soeleman','Harry de Boer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294212,'Jeroen Carolus','Ronald Rave',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294212,'Gilliano Smit','Harry de Boer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294212,'Ali Soeleman','Ronald Rave',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294212,'Jeroen Carolus','Peter Eurlings',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294212,'Jeroen Carolus','Harry de Boer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294212,'Ali Soeleman','Peter Eurlings',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294212,'Gilliano Smit','Ronald Rave',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-10-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),306510,'OP HERHALING','Chicks With Sticks',9,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('01-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294213,'CUE GENIUS 2','Fluke je snooker 2',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294213,'Ronald Rave','Gino van den Berg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294213,'Harry de Boer','Jeroen de Jong',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294213,'Ronald Brouwer','Gino van den Berg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294213,'Ronald Rave','Jeroen de Jong',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294213,'Harry de Boer','Gino van den Berg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294213,'Ronald Brouwer','Jeroen de Jong',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294215,'Chicks With Sticks','Fluke je snooker',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294215,'Tens Tensen','Stefan van Lieshout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294215,'Lisette de Groot','Anton Geschev',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294215,'Eva Groen','Lester Noom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294215,'Tens Tensen','Anton Geschev',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294215,'Lisette de Groot','Lester Noom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294215,'Eva Groen','Stefan van Lieshout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294215,'Eva Groen','Anton Geschev',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294215,'Lisette de Groot','Stefan van Lieshout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294215,'Tens Tensen','Lester Noom',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),306987,'OP HERHALING','Amsterdams onwettige zonen',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(306987,'Rob van den Berg','Jeroen Carolus',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(306987,'Willem Visser','Ali Soeleman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(306987,'Peter Schuddeboom','Fredo Lekkerkerker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(306987,'Rob van den Berg','Ali Soeleman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(306987,'Willem Visser','Fredo Lekkerkerker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(306987,'Peter Schuddeboom','Jeroen Carolus',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(306987,'Peter Schuddeboom','Ali Soeleman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(306987,'Willem Visser','Jeroen Carolus',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(306987,'Rob van den Berg','Fredo Lekkerkerker',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294217,'Greenball','The Blue Men',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294218,'Triickshot','CUE GENIUS 2',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294219,'Fluke je snooker 2','OP HERHALING',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294220,'Amsterdams onwettige zonen','Chicks With Sticks',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294220,'Ali Soeleman','Lisette de Groot',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294220,'Fredo Lekkerkerker','Tens Tensen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294220,'Jeroen Carolus','Eva Groen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294220,'Ali Soeleman','Tens Tensen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294220,'Fredo Lekkerkerker','Eva Groen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294220,'Jeroen Carolus','Lisette de Groot',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294220,'Jeroen Carolus','Tens Tensen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294220,'Fredo Lekkerkerker','Lisette de Groot',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294220,'Ali Soeleman','Eva Groen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294221,'Fluke je snooker','Amsterdams onwettige zonen',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294222,'CUE GENIUS 2','Greenball',9,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294222,'Harry de Boer','Frans Gemser',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294222,'Ronald Brouwer','Wouter Oosterveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294222,'Ronald Rave','Ton Oud',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294222,'Harry de Boer','Wouter Oosterveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294222,'Ronald Brouwer','Ton Oud',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294222,'Ronald Rave','Frans Gemser',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294222,'Ronald Rave','Wouter Oosterveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294222,'Ronald Brouwer','Frans Gemser',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294222,'Harry de Boer','Ton Oud',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294223,'OP HERHALING','Triickshot',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294224,'Chicks With Sticks','Fluke je snooker 2',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-12-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294225,'Greenball','OP HERHALING',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294225,'Ton Oud','Henk Leegwater',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294225,'Frans Gemser','Rob van den Berg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294225,'Vincent Leegwater','Peter Schuddeboom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294225,'Ton Oud','Rob van den Berg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294225,'Frans Gemser','Peter Schuddeboom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294225,'Vincent Leegwater','Henk Leegwater',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294225,'Vincent Leegwater','Rob van den Berg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294225,'Frans Gemser','Henk Leegwater',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294225,'Ton Oud','Peter Schuddeboom',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-12-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294226,'Triickshot','Chicks With Sticks',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294226,'Henk Visser','Eva Groen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294226,'Frank Oudshoorn','Tens Tensen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294226,'Ruud Docter','Tens Tensen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294226,'Frank Oudshoorn','Eva Groen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294226,'Ruud Docter','Eva Groen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294226,'Henk Visser','Tens Tensen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-12-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294227,'Fluke je snooker 2','Fluke je snooker',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-12-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294228,'The Blue Men','CUE GENIUS 2',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-12-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294229,'Fluke je snooker','Triickshot',1,8);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-12-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294231,'OP HERHALING','The Blue Men',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-12-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294232,'Chicks With Sticks','Greenball',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),307724,'Amsterdams onwettige zonen','Fluke je snooker 2',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(307724,'Ali Soeleman','Niels van Lieshout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(307724,'Fredo Lekkerkerker','Gino van den Berg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(307724,'Chaka Sanichar','Gino van den Berg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(307724,'Fredo Lekkerkerker','Niels van Lieshout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(307724,'Chaka Sanichar','Niels van Lieshout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(307724,'Ali Soeleman','Gino van den Berg',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294233,'Greenball','Fluke je snooker',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294234,'CUE GENIUS 2','OP HERHALING',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294234,'Ronald Brouwer','Willem Visser',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294234,'Ronald Rave','Henk Leegwater',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294234,'Harry de Boer','Peter Schuddeboom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294234,'Ronald Brouwer','Henk Leegwater',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294234,'Ronald Rave','Peter Schuddeboom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294234,'Harry de Boer','Willem Visser',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294234,'Harry de Boer','Henk Leegwater',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294234,'Ronald Rave','Willem Visser',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294234,'Ronald Brouwer','Peter Schuddeboom',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294235,'Triickshot','Amsterdams onwettige zonen',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294235,'Frank Oudshoorn','Fredo Lekkerkerker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294235,'Hans Visser','Ali Soeleman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294235,'John Zoontjes','Jeroen Carolus',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294235,'Frank Oudshoorn','Ali Soeleman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294235,'Hans Visser','Jeroen Carolus',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294235,'John Zoontjes','Fredo Lekkerkerker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294235,'John Zoontjes','Ali Soeleman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294235,'Hans Visser','Fredo Lekkerkerker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294235,'Frank Oudshoorn','Jeroen Carolus',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294236,'The Blue Men','Chicks With Sticks',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294237,'Greenball','Amsterdams onwettige zonen',0,9);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294238,'CUE GENIUS 2','Chicks With Sticks',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294239,'Triickshot','Fluke je snooker 2',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294240,'The Blue Men','Fluke je snooker',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-02-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),307663,'The Blue Men','Triickshot',9,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-02-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294241,'Fluke je snooker','CUE GENIUS 2',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-02-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294242,'Fluke je snooker 2','Greenball',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-02-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294243,'Amsterdams onwettige zonen','The Blue Men',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294243,'Ali Soeleman','Kim Pothof',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294243,'Gilliano Smit','Walter Kramer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294243,'Ali Soeleman','Walter Kramer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294243,'Jeroen Carolus','Kim Pothof',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294243,'Jeroen Carolus','Walter Kramer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294243,'Gilliano Smit','Kim Pothof',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-02-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294244,'Chicks With Sticks','OP HERHALING',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-02-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294246,'CUE GENIUS 2','Amsterdams onwettige zonen',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294246,'Harry de Boer','Fredo Lekkerkerker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294246,'Ronald Brouwer','Gilliano Smit',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294246,'Ronald Rave','Ali Soeleman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294246,'Harry de Boer','Gilliano Smit',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294246,'Ronald Brouwer','Ali Soeleman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294246,'Ronald Rave','Fredo Lekkerkerker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294246,'Ronald Rave','Gilliano Smit',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294246,'Ronald Brouwer','Fredo Lekkerkerker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294246,'Harry de Boer','Ali Soeleman',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-02-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294247,'OP HERHALING','Fluke je snooker',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-03-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),308751,'Greenball','Triickshot',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308751,'Ton Oud','John Zoontjes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308751,'Martin van Zeelt','Henk Visser',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308751,'Frans Gemser','Frank Oudshoorn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308751,'Ton Oud','Henk Visser',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308751,'Martin van Zeelt','Frank Oudshoorn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308751,'Frans Gemser','John Zoontjes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308751,'Frans Gemser','Henk Visser',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308751,'Martin van Zeelt','John Zoontjes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308751,'Ton Oud','Frank Oudshoorn',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-03-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294249,'Fluke je snooker','Chicks With Sticks',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-03-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294250,'Triickshot','The Blue Men',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294250,'Frank Oudshoorn','Kim Pothof',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294250,'Ruud Docter','Walter Kramer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294250,'Henk Visser','Walter Kramer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294250,'Ruud Docter','Kim Pothof',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294250,'Henk Visser','Kim Pothof',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294250,'Frank Oudshoorn','Walter Kramer',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-03-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294251,'Fluke je snooker 2','CUE GENIUS 2',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-03-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294252,'Amsterdams onwettige zonen','OP HERHALING',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294252,'Ali Soeleman','Willem Visser',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294252,'Fredo Lekkerkerker','Rob van den Berg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294252,'Gilliano Smit','Henk Leegwater',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294252,'Ali Soeleman','Rob van den Berg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294252,'Fredo Lekkerkerker','Henk Leegwater',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294252,'Gilliano Smit','Willem Visser',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294252,'Gilliano Smit','Rob van den Berg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294252,'Fredo Lekkerkerker','Willem Visser',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294252,'Ali Soeleman','Henk Leegwater',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-03-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294253,'CUE GENIUS 2','Triickshot',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('28-03-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294254,'OP HERHALING','Fluke je snooker 2',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('29-03-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294255,'Chicks With Sticks','Amsterdams onwettige zonen',0,9);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('30-03-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294256,'The Blue Men','Greenball',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-04-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294258,'Triickshot','OP HERHALING',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294258,'John Zoontjes','Peter Schuddeboom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294258,'Henk Visser','Rob van den Berg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294258,'Ruud Docter','Henk Leegwater',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294258,'John Zoontjes','Rob van den Berg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294258,'Henk Visser','Henk Leegwater',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294258,'Ruud Docter','Peter Schuddeboom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294258,'Ruud Docter','Rob van den Berg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294258,'Henk Visser','Peter Schuddeboom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294258,'John Zoontjes','Henk Leegwater',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-04-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294259,'Fluke je snooker 2','Chicks With Sticks',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-04-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294260,'Amsterdams onwettige zonen','Fluke je snooker',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294260,'Ali Soeleman','Stefan van Lieshout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294260,'Fredo Lekkerkerker','Lester Noom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294260,'Chaka Sanichar','Lester Noom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294260,'Fredo Lekkerkerker','Stefan van Lieshout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294260,'Chaka Sanichar','Stefan van Lieshout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294260,'Ali Soeleman','Lester Noom',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-04-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294261,'Fluke je snooker','Fluke je snooker 2',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-04-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294262,'CUE GENIUS 2','The Blue Men',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-04-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),309453,'Greenball','CUE GENIUS 2',1,8);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),309499,'OP HERHALING','Greenball',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309499,'Willem Visser','Ton Oud',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309499,'Rob van den Berg','Martin van Zeelt',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309499,'Peter Schuddeboom','Vincent Leegwater',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309499,'Willem Visser','Martin van Zeelt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309499,'Rob van den Berg','Vincent Leegwater',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309499,'Peter Schuddeboom','Ton Oud',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309499,'Peter Schuddeboom','Martin van Zeelt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309499,'Rob van den Berg','Ton Oud',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309499,'Willem Visser','Vincent Leegwater',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),309500,'Chicks With Sticks','Triickshot',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),309643,'The Blue Men','Fluke je snooker 2',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294265,'Greenball','Chicks With Sticks',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294266,'Triickshot','Fluke je snooker',8,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294267,'Fluke je snooker 2','Amsterdams onwettige zonen',0,9);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294268,'The Blue Men','OP HERHALING',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294269,'Fluke je snooker','Greenball',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294270,'Amsterdams onwettige zonen','Triickshot',9,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294270,'Ali Soeleman','John Zoontjes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294270,'Chaka Sanichar','Ruud Docter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294270,'Gilliano Smit','Hans Visser',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294270,'Ali Soeleman','Ruud Docter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294270,'Chaka Sanichar','Hans Visser',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294270,'Gilliano Smit','John Zoontjes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294270,'Gilliano Smit','Ruud Docter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294270,'Chaka Sanichar','John Zoontjes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294270,'Ali Soeleman','Hans Visser',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),294272,'Chicks With Sticks','The Blue Men',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('29-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2011%'),309935,'OP HERHALING','CUE GENIUS 2',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309935,'Willem Visser','Ronald Brouwer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309935,'Henk Leegwater','Harry de Boer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309935,'Peter Schuddeboom','Ronald Rave',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309935,'Willem Visser','Harry de Boer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309935,'Henk Leegwater','Ronald Rave',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309935,'Peter Schuddeboom','Ronald Brouwer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309935,'Peter Schuddeboom','Harry de Boer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309935,'Henk Leegwater','Ronald Brouwer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309935,'Willem Visser','Ronald Rave',1,0);
