delete from cm_match_details where game_id in (select game_id from cm_matches where cpn_id = (select id from cm_competitions where name = 'Derde klasse A' and ssn_id like '2013%'));
delete from cm_matches where cpn_id = (select id from cm_competitions where name = 'Derde klasse A' and ssn_id like '2013%');
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-09-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse A' and ssn_id like '2013%'),424551,'Fluke je snooker','Dicksie Chicks',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-09-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse A' and ssn_id like '2013%'),424554,'CUE GENIUS 2','Fluke je snooker 2',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-09-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse A' and ssn_id like '2013%'),424557,'Fluke je snooker','CUE GENIUS 2',1,8);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('01-10-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse A' and ssn_id like '2013%'),424560,'CUE GENIUS 2','Trickshot',9,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-10-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse A' and ssn_id like '2013%'),424561,'Fluke je snooker 2','Fluke je snooker',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-10-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse A' and ssn_id like '2013%'),430401,'Trickshot','Dicksie Chicks',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-10-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse A' and ssn_id like '2013%'),424564,'Trickshot','Fluke je snooker 2',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-10-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse A' and ssn_id like '2013%'),424566,'Fluke je snooker','Trickshot',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-10-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse A' and ssn_id like '2013%'),424567,'CUE GENIUS 2','Dicksie Chicks',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424567,'Ronald Brouwer','Tens Tensen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424567,'Harry de Boer','Boris van der Kloor',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424567,'Ronald Rave','Lisette de Groot',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424567,'Ronald Brouwer','Boris van der Kloor',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424567,'Harry de Boer','Lisette de Groot',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424567,'Ronald Rave','Tens Tensen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424567,'Ronald Rave','Boris van der Kloor',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424567,'Harry de Boer','Tens Tensen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424567,'Ronald Brouwer','Lisette de Groot',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('31-10-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse A' and ssn_id like '2013%'),424571,'Dicksie Chicks','Fluke je snooker 2',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-11-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse A' and ssn_id like '2013%'),424574,'Dicksie Chicks','Fluke je snooker',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-11-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse A' and ssn_id like '2013%'),424577,'Fluke je snooker 2','CUE GENIUS 2',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-11-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse A' and ssn_id like '2013%'),430402,'Dicksie Chicks','Trickshot',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('26-11-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse A' and ssn_id like '2013%'),424578,'CUE GENIUS 2','Fluke je snooker',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424578,'Harry de Boer','Dim Gerven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424578,'Ronald Rave','Anne Duivis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424578,'Ronald Brouwer','Frank Hus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424578,'Harry de Boer','Anne Duivis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424578,'Ronald Rave','Frank Hus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424578,'Ronald Brouwer','Dim Gerven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424578,'Ronald Brouwer','Anne Duivis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424578,'Ronald Rave','Dim Gerven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424578,'Harry de Boer','Frank Hus',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-12-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse A' and ssn_id like '2013%'),424581,'Fluke je snooker','Fluke je snooker 2',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424581,'Frank Hus','Gino van den Berg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424581,'Lester Noom','Niels van Lieshout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424581,'Stefan van Lieshout','Niels van Lieshout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424581,'Lester Noom','Gino van den Berg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424581,'Stefan van Lieshout','Gino van den Berg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424581,'Frank Hus','Niels van Lieshout',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-12-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse A' and ssn_id like '2013%'),424586,'Fluke je snooker 2','Trickshot',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-12-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse A' and ssn_id like '2013%'),424587,'Trickshot','Fluke je snooker',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-12-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse A' and ssn_id like '2013%'),424589,'Dicksie Chicks','CUE GENIUS 2',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424589,'Boris van der Kloor','Ronald Brouwer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424589,'Eva Groen','Ronald Rave',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424589,'Karen Flore','Harry de Boer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424589,'Boris van der Kloor','Ronald Rave',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424589,'Eva Groen','Harry de Boer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424589,'Karen Flore','Ronald Brouwer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424589,'Karen Flore','Ronald Rave',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424589,'Eva Groen','Ronald Brouwer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424589,'Boris van der Kloor','Harry de Boer',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-01-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse A' and ssn_id like '2013%'),424592,'Fluke je snooker 2','Dicksie Chicks',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-01-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse A' and ssn_id like '2013%'),424593,'Fluke je snooker','Dicksie Chicks',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-01-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse A' and ssn_id like '2013%'),424596,'CUE GENIUS 2','Fluke je snooker 2',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-02-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse A' and ssn_id like '2013%'),433536,'Trickshot','CUE GENIUS 2',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-02-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse A' and ssn_id like '2013%'),424599,'Fluke je snooker','CUE GENIUS 2',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-03-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse A' and ssn_id like '2013%'),424602,'CUE GENIUS 2','Trickshot',9,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424602,'Harry de Boer','Frank Oudshoorn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424602,'Ronald Brouwer','Henk Visser',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424602,'Ronald Rave','Ruud Docter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424602,'Harry de Boer','Henk Visser',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424602,'Ronald Brouwer','Ruud Docter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424602,'Ronald Rave','Frank Oudshoorn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424602,'Ronald Rave','Henk Visser',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424602,'Ronald Brouwer','Frank Oudshoorn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424602,'Harry de Boer','Ruud Docter',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-03-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse A' and ssn_id like '2013%'),424603,'Fluke je snooker 2','Fluke je snooker',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424603,'Martin van Zeelt','Stefan van Lieshout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424603,'Peter Afink','Lester Noom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424603,'Niels van Lieshout','Frank Hus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424603,'Martin van Zeelt','Lester Noom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424603,'Peter Afink','Frank Hus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424603,'Niels van Lieshout','Stefan van Lieshout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424603,'Niels van Lieshout','Lester Noom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424603,'Peter Afink','Stefan van Lieshout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424603,'Martin van Zeelt','Frank Hus',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-03-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse A' and ssn_id like '2013%'),424605,'Trickshot','Fluke je snooker 2',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-03-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse A' and ssn_id like '2013%'),424608,'Fluke je snooker','Trickshot',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-03-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse A' and ssn_id like '2013%'),424609,'CUE GENIUS 2','Dicksie Chicks',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424609,'Ronald Rave','Tens Tensen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424609,'Harry de Boer','Boris van der Kloor',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424609,'Ronald Brouwer','Karen Flore',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424609,'Ronald Rave','Boris van der Kloor',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424609,'Harry de Boer','Karen Flore',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424609,'Ronald Brouwer','Tens Tensen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424609,'Ronald Brouwer','Boris van der Kloor',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424609,'Harry de Boer','Tens Tensen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424609,'Ronald Rave','Karen Flore',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-03-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse A' and ssn_id like '2013%'),434009,'Dicksie Chicks','Trickshot',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434009,'Eva Groen','Henk Visser',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434009,'Tens Tensen','John Zoontjes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434009,'Karen Flore','Frank Oudshoorn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434009,'Eva Groen','John Zoontjes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434009,'Tens Tensen','Frank Oudshoorn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434009,'Karen Flore','Henk Visser',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434009,'Karen Flore','John Zoontjes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434009,'Tens Tensen','Henk Visser',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434009,'Eva Groen','Frank Oudshoorn',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-04-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse A' and ssn_id like '2013%'),424613,'Dicksie Chicks','Fluke je snooker 2',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-04-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse A' and ssn_id like '2013%'),424618,'Trickshot','Dicksie Chicks',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-04-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse A' and ssn_id like '2013%'),424619,'Fluke je snooker 2','CUE GENIUS 2',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-04-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse A' and ssn_id like '2013%'),424620,'CUE GENIUS 2','Fluke je snooker',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-05-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse A' and ssn_id like '2013%'),434613,'Dicksie Chicks','Fluke je snooker',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434613,'Tens Tensen','Anton Geschev',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434613,'Sten van Schaik','Frank Hus',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434613,'Lisette de Groot','Dim Gerven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434613,'Tens Tensen','Frank Hus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434613,'Sten van Schaik','Dim Gerven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434613,'Lisette de Groot','Anton Geschev',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434613,'Lisette de Groot','Frank Hus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434613,'Sten van Schaik','Anton Geschev',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434613,'Tens Tensen','Dim Gerven',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-05-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse A' and ssn_id like '2013%'),424623,'Fluke je snooker','Fluke je snooker 2',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-05-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse A' and ssn_id like '2013%'),424624,'Trickshot','CUE GENIUS 2',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-05-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse A' and ssn_id like '2013%'),424628,'Fluke je snooker 2','Trickshot',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-05-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse A' and ssn_id like '2013%'),424629,'Trickshot','Fluke je snooker',8,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('28-05-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse A' and ssn_id like '2013%'),424634,'Fluke je snooker 2','Dicksie Chicks',2,7);
