delete from cm_match_details where game_id in (select game_id from cm_matches where cpn_id = (select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2014%'));
delete from cm_matches where cpn_id = (select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2014%');
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2014%'),449331,'CUE GENIUS 2','Fluke je snooker',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449331,'Harry de Boer','Stefan van Lieshout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449331,'Ronald Rave','Anton Geschev',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449331,'Ronald Brouwer','Stefan van Lieshout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449331,'Harry de Boer','Anton Geschev',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449331,'Ronald Rave','Stefan van Lieshout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449331,'Ronald Brouwer','Anton Geschev',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2014%'),449333,'Dicksie Chicks','CUE GENIUS 2',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449333,'Karen Flore','Harry de Boer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449333,'Tens Tensen','Bas Wittgen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449333,'Ruud van Mierlo','Ronald Brouwer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449333,'Karen Flore','Bas Wittgen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449333,'Tens Tensen','Ronald Brouwer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449333,'Ruud van Mierlo','Harry de Boer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449333,'Ruud van Mierlo','Bas Wittgen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449333,'Tens Tensen','Harry de Boer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449333,'Karen Flore','Ronald Brouwer',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('30-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2014%'),449334,'Fluke je snooker','Dicksie Chicks',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449334,'Danny van der Werff','Karen Flore',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449334,'Stefan van Lieshout','Tens Tensen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449334,'Anton Geschev','Lisette de Groot',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449334,'Danny van der Werff','Tens Tensen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449334,'Stefan van Lieshout','Lisette de Groot',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449334,'Anton Geschev','Karen Flore',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449334,'Anton Geschev','Tens Tensen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449334,'Stefan van Lieshout','Karen Flore',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449334,'Danny van der Werff','Lisette de Groot',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2014%'),449340,'Fluke je snooker','CUE GENIUS 2',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449340,'Niels van Lieshout','Ronald Rave',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449340,'Dim Gerven','Bas Wittgen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449340,'Danny van der Werff','Ronald Brouwer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449340,'Niels van Lieshout','Bas Wittgen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449340,'Dim Gerven','Ronald Brouwer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449340,'Danny van der Werff','Ronald Rave',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449340,'Danny van der Werff','Bas Wittgen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449340,'Dim Gerven','Ronald Rave',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449340,'Niels van Lieshout','Ronald Brouwer',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2014%'),449343,'CUE GENIUS 2','Dicksie Chicks',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449343,'Ronald Brouwer','Ruud van Mierlo',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449343,'Harry de Boer','Karen Flore',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449343,'Ronald Rave','Tens Tensen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449343,'Ronald Brouwer','Karen Flore',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449343,'Harry de Boer','Tens Tensen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449343,'Ronald Rave','Ruud van Mierlo',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449343,'Ronald Rave','Karen Flore',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449343,'Harry de Boer','Ruud van Mierlo',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449343,'Ronald Brouwer','Tens Tensen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Derde klasse poule 1' and ssn_id like '2014%'),449345,'Dicksie Chicks','Fluke je snooker',3,6);
