delete from cm_match_details where game_id in (select game_id from cm_matches where cpn_id = (select id from cm_competitions where name = 'Eerste klasse poule 2' and ssn_id like '2014%'));
delete from cm_matches where cpn_id = (select id from cm_competitions where name = 'Eerste klasse poule 2' and ssn_id like '2014%');
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Eerste klasse poule 2' and ssn_id like '2014%'),449179,'Koetshuys 1','JUMBO 3',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449179,'Marco Kuperus','Frank de Rooij',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449179,'Hans Reijerkerk','Rob Oudshoorn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449179,'Sander Nijssen','Frank de Rooij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449179,'Marco Kuperus','Rob Oudshoorn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449179,'Hans Reijerkerk','Frank de Rooij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449179,'Sander Nijssen','Rob Oudshoorn',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Eerste klasse poule 2' and ssn_id like '2014%'),449180,'JUMBO 3','HOGEWOERD 1',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Eerste klasse poule 2' and ssn_id like '2014%'),449181,'SNOOKERIJ 6','Koetshuys 1',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449181,'Hans Wolvers','Marco Kuperus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449181,'Namir Khoury','Hans Reijerkerk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449181,'Roger Planje','Sander Nijssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449181,'Hans Wolvers','Hans Reijerkerk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449181,'Namir Khoury','Sander Nijssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449181,'Roger Planje','Marco Kuperus',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449181,'Roger Planje','Hans Reijerkerk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449181,'Namir Khoury','Marco Kuperus',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449181,'Hans Wolvers','Sander Nijssen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Eerste klasse poule 2' and ssn_id like '2014%'),449183,'HOGEWOERD 1','SNOOKERIJ 6',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449183,'Shiraz Nasrullah','Gennaro Cannavacciuolo',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449183,'Parkash Kalicharan','Roger Planje',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449183,'André Vuijk','John van de Zwart',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449183,'Shiraz Nasrullah','Roger Planje',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449183,'Parkash Kalicharan','John van de Zwart',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449183,'André Vuijk','Gennaro Cannavacciuolo',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449183,'André Vuijk','Roger Planje',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449183,'Parkash Kalicharan','Gennaro Cannavacciuolo',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449183,'Shiraz Nasrullah','John van de Zwart',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('01-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Eerste klasse poule 2' and ssn_id like '2014%'),449184,'Koetshuys 1','HOGEWOERD 1',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449184,'Richard Kiljan','Parkash Kalicharan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449184,'Sander Nijssen','André Vuijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449184,'Marco Kuperus','Shiraz Nasrullah',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449184,'Richard Kiljan','André Vuijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449184,'Sander Nijssen','Shiraz Nasrullah',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449184,'Marco Kuperus','Parkash Kalicharan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449184,'Marco Kuperus','André Vuijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449184,'Sander Nijssen','Parkash Kalicharan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449184,'Richard Kiljan','Shiraz Nasrullah',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Eerste klasse poule 2' and ssn_id like '2014%'),449187,'JUMBO 3','SNOOKERIJ 6',9,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Eerste klasse poule 2' and ssn_id like '2014%'),449189,'JUMBO 3','Koetshuys 1',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Eerste klasse poule 2' and ssn_id like '2014%'),449190,'HOGEWOERD 1','JUMBO 3',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Eerste klasse poule 2' and ssn_id like '2014%'),449191,'Koetshuys 1','SNOOKERIJ 6',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449191,'Sander Nijssen','Roger Planje',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449191,'Richard Kiljan','Namir Khoury',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449191,'Hans Reijerkerk','Gennaro Cannavacciuolo',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449191,'Sander Nijssen','Namir Khoury',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449191,'Richard Kiljan','Gennaro Cannavacciuolo',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449191,'Hans Reijerkerk','Roger Planje',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449191,'Hans Reijerkerk','Namir Khoury',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449191,'Richard Kiljan','Roger Planje',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449191,'Sander Nijssen','Gennaro Cannavacciuolo',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Eerste klasse poule 2' and ssn_id like '2014%'),449195,'HOGEWOERD 1','Koetshuys 1',9,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('29-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Eerste klasse poule 2' and ssn_id like '2014%'),449197,'SNOOKERIJ 6','JUMBO 3',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449197,'Hans Wolvers','Rob Oudshoorn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449197,'Job Bavelaar','Frank de Rooij',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449197,'Roger Planje','Frank de Rooij',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449197,'Job Bavelaar','Rob Oudshoorn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449197,'Roger Planje','Rob Oudshoorn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449197,'Hans Wolvers','Frank de Rooij',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-06-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Eerste klasse poule 2' and ssn_id like '2014%'),449835,'SNOOKERIJ 6','HOGEWOERD 1',4,5);
