delete from cm_match_details where game_id in (select game_id from cm_matches where cpn_id = (select id from cm_competitions where name = 'Eerste klasse poule 5' and ssn_id like '2014%'));
delete from cm_matches where cpn_id = (select id from cm_competitions where name = 'Eerste klasse poule 5' and ssn_id like '2014%');
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Eerste klasse poule 5' and ssn_id like '2014%'),449238,'La Carambole','SC Capelle 1',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449238,'Paul Wisse','John Prinsen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449238,'Patrick Beeres','Fausto Salis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449238,'Anton Vogelaar','Rien Baak',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449238,'Paul Wisse','Fausto Salis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449238,'Patrick Beeres','Rien Baak',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449238,'Anton Vogelaar','John Prinsen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449238,'Anton Vogelaar','Fausto Salis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449238,'Patrick Beeres','John Prinsen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449238,'Paul Wisse','Rien Baak',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Eerste klasse poule 5' and ssn_id like '2014%'),449240,'SNOOKERPALACE PUTTE','De Loods 147.1',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449240,'David Smeekens','Melvin Reese',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449240,'Peter de Brie','Pascal de Smit',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449240,'Ward van Doren','Pascal de Smit',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449240,'Peter de Brie','Melvin Reese',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449240,'Ward van Doren','Melvin Reese',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449240,'David Smeekens','Pascal de Smit',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Eerste klasse poule 5' and ssn_id like '2014%'),449242,'La Carambole','SNOOKERPALACE PUTTE',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449242,'Anton Vogelaar','David Smeekens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449242,'Ad Roverts','Peter de Brie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449242,'Martin Jansen','Peter van Someren',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449242,'Anton Vogelaar','Peter de Brie',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449242,'Ad Roverts','Peter van Someren',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449242,'Martin Jansen','David Smeekens',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449242,'Martin Jansen','Peter de Brie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449242,'Ad Roverts','David Smeekens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449242,'Anton Vogelaar','Peter van Someren',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Eerste klasse poule 5' and ssn_id like '2014%'),449245,'De Loods 147.1','La Carambole',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449245,'Melvin Reese','Edwin Roverts',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449245,'Pascal de Smit','Ad Roverts',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449245,'Kevin Chan','Paul Wisse',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449245,'Melvin Reese','Ad Roverts',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449245,'Pascal de Smit','Paul Wisse',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449245,'Kevin Chan','Edwin Roverts',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449245,'Kevin Chan','Ad Roverts',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449245,'Pascal de Smit','Edwin Roverts',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449245,'Melvin Reese','Paul Wisse',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Eerste klasse poule 5' and ssn_id like '2014%'),449247,'SC Capelle 1','De Loods 147.1',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449247,'Rien Baak','Melvin Reese',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449247,'Rene Boers','Kevin Chan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449247,'Fausto Salis','Ray Westdijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449247,'Rien Baak','Kevin Chan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449247,'Rene Boers','Ray Westdijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449247,'Fausto Salis','Melvin Reese',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449247,'Fausto Salis','Kevin Chan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449247,'Rene Boers','Melvin Reese',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449247,'Rien Baak','Ray Westdijk',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Eerste klasse poule 5' and ssn_id like '2014%'),449249,'SC Capelle 1','La Carambole',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449249,'Fausto Salis','Edwin Roverts',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449249,'Rene Boers','Anton Vogelaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449249,'Rien Baak','Patrick Beeres',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449249,'Fausto Salis','Anton Vogelaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449249,'Rene Boers','Patrick Beeres',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449249,'Rien Baak','Edwin Roverts',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449249,'Rien Baak','Anton Vogelaar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449249,'Rene Boers','Edwin Roverts',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449249,'Fausto Salis','Patrick Beeres',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('28-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Eerste klasse poule 5' and ssn_id like '2014%'),449616,'SNOOKERPALACE PUTTE','SC Capelle 1',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449616,'Peter van Someren','John Prinsen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449616,'Ward van Doren','Rene Boers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449616,'David Smeekens','Fausto Salis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449616,'Peter van Someren','Rene Boers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449616,'Ward van Doren','Fausto Salis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449616,'David Smeekens','John Prinsen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449616,'David Smeekens','Rene Boers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449616,'Ward van Doren','John Prinsen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449616,'Peter van Someren','Fausto Salis',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Eerste klasse poule 5' and ssn_id like '2014%'),449252,'SNOOKERPALACE PUTTE','La Carambole',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449252,'Peter van Someren','Martin Jansen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449252,'Ward van Doren','Edwin Roverts',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449252,'Peter de Brie','Patrick Beeres',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449252,'Peter van Someren','Edwin Roverts',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449252,'Ward van Doren','Patrick Beeres',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449252,'Peter de Brie','Martin Jansen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449252,'Peter de Brie','Edwin Roverts',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449252,'Ward van Doren','Martin Jansen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449252,'Peter van Someren','Patrick Beeres',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Eerste klasse poule 5' and ssn_id like '2014%'),449255,'SC Capelle 1','SNOOKERPALACE PUTTE',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449255,'Rien Baak','Peter de Brie',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449255,'John Prinsen','Adrie Stoffels',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449255,'Fausto Salis','Peter van Someren',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449255,'Rien Baak','Adrie Stoffels',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449255,'John Prinsen','Peter van Someren',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449255,'Fausto Salis','Peter de Brie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449255,'Fausto Salis','Adrie Stoffels',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449255,'John Prinsen','Peter de Brie',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449255,'Rien Baak','Peter van Someren',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('29-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Eerste klasse poule 5' and ssn_id like '2014%'),449257,'De Loods 147.1','SC Capelle 1',0,9);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449257,'Kevin Chan','John Prinsen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449257,'Kevin Chan','Fausto Salis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449257,'Kevin Chan','Rien Baak',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-06-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Eerste klasse poule 5' and ssn_id like '2014%'),449847,'De Loods 147.1','SNOOKERPALACE PUTTE',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449847,'Jimmy Worung','Ward van Doren',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449847,'Melvin Reese','Peter van Someren',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449847,'Melvin Reese','Ward van Doren',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449847,'Jimmy Worung','Peter van Someren',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-06-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Eerste klasse poule 5' and ssn_id like '2014%'),449848,'La Carambole','De Loods 147.1',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449848,'Edwin Roverts','Pascal de Smit',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449848,'Ad Roverts','Melvin Reese',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449848,'Anton Vogelaar','Jimmy Worung',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449848,'Edwin Roverts','Melvin Reese',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449848,'Ad Roverts','Jimmy Worung',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449848,'Anton Vogelaar','Pascal de Smit',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449848,'Anton Vogelaar','Melvin Reese',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449848,'Ad Roverts','Pascal de Smit',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449848,'Edwin Roverts','Jimmy Worung',0,1);
