delete from cm_match_details where game_id in (select game_id from cm_matches where cpn_id = (select id from cm_competitions where name = 'Eerste klasse poule 1' and ssn_id like '2014%'));
delete from cm_matches where cpn_id = (select id from cm_competitions where name = 'Eerste klasse poule 1' and ssn_id like '2014%');
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Eerste klasse poule 1' and ssn_id like '2014%'),449158,'Final Touch 3','Westend 2',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449158,'Tens Tensen','Simon Reuter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449158,'Dion Meuwsen','Louis Leijdekker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449158,'Sten van Schaik','Kim Fai Sung',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449158,'Tens Tensen','Louis Leijdekker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449158,'Dion Meuwsen','Kim Fai Sung',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449158,'Sten van Schaik','Simon Reuter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449158,'Sten van Schaik','Louis Leijdekker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449158,'Dion Meuwsen','Simon Reuter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449158,'Tens Tensen','Kim Fai Sung',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Eerste klasse poule 1' and ssn_id like '2014%'),449162,'Final Touch 3','Sloten 1',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449162,'Sten van Schaik','Peter Rath',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449162,'Dion Meuwsen','Norman Nowrozy',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449162,'Michel Knol','Adrie Voskuil',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449162,'Sten van Schaik','Norman Nowrozy',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449162,'Dion Meuwsen','Adrie Voskuil',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449162,'Michel Knol','Peter Rath',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449162,'Michel Knol','Norman Nowrozy',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449162,'Dion Meuwsen','Peter Rath',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449162,'Sten van Schaik','Adrie Voskuil',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Eerste klasse poule 1' and ssn_id like '2014%'),449163,'Westend 2','Tasmanian Devils',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449163,'Simon Reuter','Ronald Rennen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449163,'Louis Leijdekker','Davith Denes Hiwat',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449163,'Marc Nieuweboer','Rik van Winsum',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449163,'Simon Reuter','Davith Denes Hiwat',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449163,'Louis Leijdekker','Rik van Winsum',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449163,'Marc Nieuweboer','Ronald Rennen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449163,'Marc Nieuweboer','Davith Denes Hiwat',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449163,'Louis Leijdekker','Ronald Rennen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449163,'Simon Reuter','Rik van Winsum',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('28-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Eerste klasse poule 1' and ssn_id like '2014%'),449587,'Tasmanian Devils','Final Touch 3',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449587,'Rik van Winsum','Sten van Schaik',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449587,'Davith Denes Hiwat','Michel Knol',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449587,'Ronald Rennen','Wouter Kager',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449587,'Rik van Winsum','Michel Knol',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449587,'Davith Denes Hiwat','Wouter Kager',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449587,'Ronald Rennen','Sten van Schaik',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449587,'Ronald Rennen','Michel Knol',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449587,'Davith Denes Hiwat','Sten van Schaik',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449587,'Rik van Winsum','Wouter Kager',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('31-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Eerste klasse poule 1' and ssn_id like '2014%'),449164,'Sloten 1','Westend 2',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449164,'Bobby Jahangir','Marco Haverkotte',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449164,'Norman Nowrozy','Simon Reuter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449164,'Peter Rath','Louis Leijdekker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449164,'Bobby Jahangir','Simon Reuter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449164,'Norman Nowrozy','Louis Leijdekker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449164,'Peter Rath','Marco Haverkotte',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449164,'Peter Rath','Simon Reuter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449164,'Norman Nowrozy','Marco Haverkotte',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449164,'Bobby Jahangir','Louis Leijdekker',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Eerste klasse poule 1' and ssn_id like '2014%'),449167,'Tasmanian Devils','Sloten 1',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449167,'Rik van Winsum','Bobby Jahangir',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449167,'Ronald Rennen','Peter Rath',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449167,'Kevin Slotboom','Adrie Voskuil',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449167,'Rik van Winsum','Peter Rath',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449167,'Ronald Rennen','Adrie Voskuil',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449167,'Kevin Slotboom','Bobby Jahangir',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449167,'Kevin Slotboom','Peter Rath',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449167,'Ronald Rennen','Bobby Jahangir',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449167,'Rik van Winsum','Adrie Voskuil',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Eerste klasse poule 1' and ssn_id like '2014%'),449168,'Westend 2','Final Touch 3',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449168,'Marc Nieuweboer','Davis Wong',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449168,'Wellington Lie','Michel Knol',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449168,'Kim Fai Sung','Dion Meuwsen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449168,'Marc Nieuweboer','Michel Knol',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449168,'Wellington Lie','Dion Meuwsen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449168,'Kim Fai Sung','Davis Wong',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449168,'Kim Fai Sung','Michel Knol',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449168,'Wellington Lie','Davis Wong',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449168,'Marc Nieuweboer','Dion Meuwsen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Eerste klasse poule 1' and ssn_id like '2014%'),449170,'Final Touch 3','Tasmanian Devils',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Eerste klasse poule 1' and ssn_id like '2014%'),449172,'Sloten 1','Final Touch 3',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449172,'Adrie Voskuil','Dion Meuwsen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449172,'Norman Nowrozy','Wouter Kager',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449172,'Peter Rath','Sten van Schaik',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449172,'Adrie Voskuil','Wouter Kager',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449172,'Norman Nowrozy','Sten van Schaik',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449172,'Peter Rath','Dion Meuwsen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449172,'Peter Rath','Wouter Kager',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449172,'Norman Nowrozy','Dion Meuwsen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449172,'Adrie Voskuil','Sten van Schaik',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Eerste klasse poule 1' and ssn_id like '2014%'),449173,'Tasmanian Devils','Westend 2',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449173,'Davith Denes Hiwat','Simon Reuter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449173,'Kevin Slotboom','Louis Leijdekker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449173,'Rik van Winsum','Marco Haverkotte',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449173,'Davith Denes Hiwat','Louis Leijdekker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449173,'Kevin Slotboom','Marco Haverkotte',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449173,'Rik van Winsum','Simon Reuter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449173,'Rik van Winsum','Louis Leijdekker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449173,'Kevin Slotboom','Simon Reuter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449173,'Davith Denes Hiwat','Marco Haverkotte',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Eerste klasse poule 1' and ssn_id like '2014%'),449175,'Westend 2','Sloten 1',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449175,'Kim Fai Sung','Bobby Jahangir',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449175,'Marc Nieuweboer','Norman Nowrozy',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449175,'Wellington Lie','Peter Rath',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449175,'Kim Fai Sung','Norman Nowrozy',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449175,'Marc Nieuweboer','Peter Rath',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449175,'Wellington Lie','Bobby Jahangir',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449175,'Wellington Lie','Norman Nowrozy',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449175,'Marc Nieuweboer','Bobby Jahangir',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449175,'Kim Fai Sung','Peter Rath',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('31-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Eerste klasse poule 1' and ssn_id like '2014%'),449842,'Sloten 1','Tasmanian Devils',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449842,'Adrie Voskuil','Rik van Winsum',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449842,'Bobby Jahangir','Ronald Rennen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449842,'Peter Rath','Davith Denes Hiwat',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449842,'Adrie Voskuil','Ronald Rennen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449842,'Bobby Jahangir','Davith Denes Hiwat',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449842,'Peter Rath','Rik van Winsum',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449842,'Peter Rath','Ronald Rennen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449842,'Bobby Jahangir','Rik van Winsum',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449842,'Adrie Voskuil','Davith Denes Hiwat',1,0);
