delete from cm_match_details where game_id in (select game_id from cm_matches where cpn_id = (select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'));
delete from cm_matches where cpn_id = (select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%');
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-09-2010','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213599,'Snooker Academy','Alkmaar 4',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213599,'Jan Willem Kweldam','Rick van Houten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213599,'Rob Admiraal','Sjoerd Blondeel Timmerman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213599,'Ron Fortgens','Guy van den Ende',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213599,'Jan Willem Kweldam','Sjoerd Blondeel Timmerman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213599,'Rob Admiraal','Guy van den Ende',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213599,'Ron Fortgens','Rick van Houten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213599,'Ron Fortgens','Sjoerd Blondeel Timmerman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213599,'Rob Admiraal','Rick van Houten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213599,'Jan Willem Kweldam','Guy van den Ende',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-09-2010','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213601,'BREAKTHROUGH','FINAL TOUCH 1',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('29-09-2010','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213602,'Final Touch 3','Snooker Academy',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213602,'Egon Grinwis','Rob Admiraal',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213602,'Peter de Vries','Arjen Timmers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213602,'Dean Mitchell','Jan Willem Kweldam',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213602,'Egon Grinwis','Arjen Timmers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213602,'Peter de Vries','Jan Willem Kweldam',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213602,'Dean Mitchell','Rob Admiraal',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213602,'Dean Mitchell','Arjen Timmers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213602,'Peter de Vries','Rob Admiraal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213602,'Egon Grinwis','Jan Willem Kweldam',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('30-09-2010','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213603,'Alkmaar 4','BREAKTHROUGH',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213603,'Guy van den Ende','Henk van Hooff',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213603,'Rick van Houten','George Wijte',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213603,'Eric van der Zwan','Raymond Selhorst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213603,'Guy van den Ende','George Wijte',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213603,'Rick van Houten','Raymond Selhorst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213603,'Eric van der Zwan','Henk van Hooff',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213603,'Eric van der Zwan','George Wijte',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213603,'Rick van Houten','Henk van Hooff',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213603,'Guy van den Ende','Raymond Selhorst',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('30-09-2010','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213604,'FINAL TOUCH 1','PURMEREND 1',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213604,'Frans Veling','Marco Haverkotte',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213604,'Wessel Tit','Louis Leijdekker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213604,'Peter de Kamper','Patrick Tijssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213604,'Frans Veling','Louis Leijdekker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213604,'Wessel Tit','Patrick Tijssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213604,'Peter de Kamper','Marco Haverkotte',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213604,'Peter de Kamper','Louis Leijdekker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213604,'Wessel Tit','Marco Haverkotte',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213604,'Frans Veling','Patrick Tijssen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-10-2010','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213606,'PURMEREND 1','Alkmaar 4',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-10-2010','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213607,'BREAKTHROUGH','Final Touch 3',9,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-10-2010','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213608,'Snooker Academy','BREAKTHROUGH',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213608,'Jan Willem Kweldam','Marco Glorie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213608,'Rob Admiraal','Lennert Duijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213608,'Ron Fortgens','Henk van Hooff',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213608,'Jan Willem Kweldam','Lennert Duijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213608,'Rob Admiraal','Henk van Hooff',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213608,'Ron Fortgens','Marco Glorie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213608,'Ron Fortgens','Lennert Duijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213608,'Rob Admiraal','Marco Glorie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213608,'Jan Willem Kweldam','Henk van Hooff',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-10-2010','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213609,'Final Touch 3','PURMEREND 1',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213609,'Peter de Vries','Marco Haverkotte',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213609,'Edwin Horlings','Rick Mulder',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213609,'Reitse Jonkman','Patrick Tijssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213609,'Peter de Vries','Rick Mulder',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213609,'Edwin Horlings','Patrick Tijssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213609,'Reitse Jonkman','Marco Haverkotte',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213609,'Reitse Jonkman','Rick Mulder',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213609,'Edwin Horlings','Marco Haverkotte',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213609,'Peter de Vries','Patrick Tijssen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-10-2010','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213610,'Alkmaar 4','SU 1 De Balluh',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('01-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213611,'SU 1 De Balluh','Final Touch 3',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213612,'PURMEREND 1','Snooker Academy',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213612,'Louis Leijdekker','Ron Fortgens',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213612,'Rick Mulder','Jan Willem Kweldam',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213612,'Patrick Tijssen','Rob Admiraal',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213612,'Louis Leijdekker','Jan Willem Kweldam',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213612,'Rick Mulder','Rob Admiraal',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213612,'Patrick Tijssen','Ron Fortgens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213612,'Patrick Tijssen','Jan Willem Kweldam',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213612,'Rick Mulder','Ron Fortgens',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213612,'Louis Leijdekker','Rob Admiraal',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213613,'FINAL TOUCH 1','Alkmaar 4',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213614,'Snooker Academy','SU 1 De Balluh',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213614,'Rob Admiraal','Maarten Evertzen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213614,'Ron Fortgens','Michel de Sain',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213614,'Arjen Timmers','Mark Koppert',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213614,'Rob Admiraal','Michel de Sain',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213614,'Ron Fortgens','Mark Koppert',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213614,'Arjen Timmers','Maarten Evertzen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213614,'Arjen Timmers','Michel de Sain',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213614,'Ron Fortgens','Maarten Evertzen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213614,'Rob Admiraal','Mark Koppert',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213615,'Final Touch 3','FINAL TOUCH 1',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213616,'BREAKTHROUGH','PURMEREND 1',8,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213617,'SU 1 De Balluh','BREAKTHROUGH',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213617,'Pierre Linschoten','Lennert Duijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213617,'Richard Beers','Simon Reuter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213617,'Michel de Sain','Henk van Hooff',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213617,'Pierre Linschoten','Simon Reuter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213617,'Richard Beers','Henk van Hooff',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213617,'Michel de Sain','Lennert Duijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213617,'Michel de Sain','Simon Reuter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213617,'Richard Beers','Lennert Duijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213617,'Pierre Linschoten','Henk van Hooff',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('25-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213618,'Alkmaar 4','Final Touch 3',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213618,'Guy van den Ende','Dean Mitchell',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213618,'Eric van der Zwan','Edwin Horlings',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213618,'Rick van Houten','Edwin Horlings',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213618,'Eric van der Zwan','Dean Mitchell',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213618,'Rick van Houten','Dean Mitchell',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213618,'Guy van den Ende','Edwin Horlings',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('25-11-2010','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213619,'FINAL TOUCH 1','Snooker Academy',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-12-2010','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213622,'FINAL TOUCH 1','BREAKTHROUGH',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213622,'Frans Veling','Marco Glorie',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213622,'Willem Swager','Lennert Duijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213622,'Albert Pronk','Henk van Hooff',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213622,'Frans Veling','Lennert Duijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213622,'Willem Swager','Henk van Hooff',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213622,'Albert Pronk','Marco Glorie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213622,'Albert Pronk','Lennert Duijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213622,'Willem Swager','Marco Glorie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213622,'Frans Veling','Henk van Hooff',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-12-2010','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),231439,'SU 1 De Balluh','PURMEREND 1',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(231439,'Maarten Evertzen','Rick Mulder',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(231439,'Pierre Linschoten','Louis Leijdekker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(231439,'Eddie Bongers','Patrick Tijssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(231439,'Maarten Evertzen','Louis Leijdekker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(231439,'Pierre Linschoten','Patrick Tijssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(231439,'Eddie Bongers','Rick Mulder',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(231439,'Eddie Bongers','Louis Leijdekker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(231439,'Pierre Linschoten','Rick Mulder',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(231439,'Maarten Evertzen','Patrick Tijssen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-12-2010','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213623,'Snooker Academy','Final Touch 3',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213623,'Arjen Timmers','Albert Papot',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213623,'Jan Willem Kweldam','Egon Grinwis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213623,'Rob Admiraal','Reitse Jonkman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213623,'Arjen Timmers','Egon Grinwis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213623,'Jan Willem Kweldam','Reitse Jonkman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213623,'Rob Admiraal','Albert Papot',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213623,'Rob Admiraal','Egon Grinwis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213623,'Jan Willem Kweldam','Albert Papot',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213623,'Arjen Timmers','Reitse Jonkman',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-12-2010','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213624,'PURMEREND 1','FINAL TOUCH 1',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-12-2010','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213625,'BREAKTHROUGH','Alkmaar 4',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213625,'Raymond Selhorst','Rick van Houten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213625,'Marco Glorie','Sjoerd Blondeel Timmerman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213625,'Lennert Duijn','Guy van den Ende',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213625,'Raymond Selhorst','Sjoerd Blondeel Timmerman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213625,'Marco Glorie','Guy van den Ende',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213625,'Lennert Duijn','Rick van Houten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213625,'Lennert Duijn','Sjoerd Blondeel Timmerman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213625,'Marco Glorie','Rick van Houten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213625,'Raymond Selhorst','Guy van den Ende',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-01-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213626,'Final Touch 3','BREAKTHROUGH',1,8);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-01-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213627,'Alkmaar 4','PURMEREND 1',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213627,'Guy van den Ende','Marco Haverkotte',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213627,'Rick van Houten','Rick Mulder',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213627,'Eric van der Zwan','Louis Leijdekker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213627,'Guy van den Ende','Rick Mulder',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213627,'Rick van Houten','Louis Leijdekker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213627,'Eric van der Zwan','Marco Haverkotte',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213627,'Eric van der Zwan','Rick Mulder',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213627,'Rick van Houten','Marco Haverkotte',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213627,'Guy van den Ende','Louis Leijdekker',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-01-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213629,'SU 1 De Balluh','Alkmaar 4',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213629,'Michel de Sain','Jan de Wit',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213629,'Pierre Linschoten','Sjoerd Blondeel Timmerman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213629,'Eddie Bongers','Guy van den Ende',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213629,'Michel de Sain','Sjoerd Blondeel Timmerman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213629,'Pierre Linschoten','Guy van den Ende',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213629,'Eddie Bongers','Jan de Wit',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213629,'Eddie Bongers','Sjoerd Blondeel Timmerman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213629,'Pierre Linschoten','Jan de Wit',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213629,'Michel de Sain','Guy van den Ende',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-01-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213630,'PURMEREND 1','Final Touch 3',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-01-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213631,'BREAKTHROUGH','Snooker Academy',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213631,'Raymond Selhorst','Jan Willem Kweldam',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213631,'Marco Glorie','Ron Fortgens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213631,'Henk van Hooff','Rob Admiraal',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213631,'Raymond Selhorst','Ron Fortgens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213631,'Marco Glorie','Rob Admiraal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213631,'Henk van Hooff','Jan Willem Kweldam',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213631,'Henk van Hooff','Ron Fortgens',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213631,'Marco Glorie','Jan Willem Kweldam',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213631,'Raymond Selhorst','Rob Admiraal',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-01-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213632,'Snooker Academy','PURMEREND 1',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213632,'Jan Willem Kweldam','Rick Mulder',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213632,'Rob Admiraal','Louis Leijdekker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213632,'Ron Fortgens','Marco Haverkotte',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213632,'Jan Willem Kweldam','Louis Leijdekker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213632,'Rob Admiraal','Marco Haverkotte',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213632,'Ron Fortgens','Rick Mulder',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213632,'Ron Fortgens','Louis Leijdekker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213632,'Rob Admiraal','Rick Mulder',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213632,'Jan Willem Kweldam','Marco Haverkotte',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-01-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213633,'Final Touch 3','SU 1 De Balluh',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213633,'Peter de Vries','Michel de Sain',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213633,'Egon Grinwis','Mark Koppert',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213633,'Dean Mitchell','Maarten Evertzen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213633,'Peter de Vries','Mark Koppert',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213633,'Egon Grinwis','Maarten Evertzen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213633,'Dean Mitchell','Michel de Sain',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213633,'Dean Mitchell','Mark Koppert',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213633,'Egon Grinwis','Michel de Sain',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213633,'Peter de Vries','Maarten Evertzen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-01-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213634,'Alkmaar 4','FINAL TOUCH 1',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213634,'Sjoerd Blondeel Timmerman','Albert Pronk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213634,'Guy van den Ende','Willem Swager',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213634,'Eric van der Zwan','Frans Veling',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213634,'Sjoerd Blondeel Timmerman','Willem Swager',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213634,'Guy van den Ende','Frans Veling',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213634,'Eric van der Zwan','Albert Pronk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213634,'Eric van der Zwan','Willem Swager',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213634,'Guy van den Ende','Albert Pronk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213634,'Sjoerd Blondeel Timmerman','Frans Veling',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-01-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),232254,'Alkmaar 4','Snooker Academy',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232254,'Guy van den Ende','Rob Admiraal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232254,'Rick van Houten','Ron Fortgens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232254,'Eric van der Zwan','Jan Willem Kweldam',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232254,'Guy van den Ende','Ron Fortgens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232254,'Rick van Houten','Jan Willem Kweldam',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232254,'Eric van der Zwan','Rob Admiraal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232254,'Eric van der Zwan','Ron Fortgens',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232254,'Rick van Houten','Rob Admiraal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232254,'Guy van den Ende','Jan Willem Kweldam',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('31-01-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213635,'SU 1 De Balluh','Snooker Academy',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213635,'Maarten Evertzen','Ron Fortgens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213635,'Michel de Sain','Jan Willem Kweldam',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213635,'Pierre Linschoten','Rob Admiraal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213635,'Maarten Evertzen','Jan Willem Kweldam',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213635,'Michel de Sain','Rob Admiraal',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213635,'Pierre Linschoten','Ron Fortgens',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213635,'Pierre Linschoten','Jan Willem Kweldam',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213635,'Michel de Sain','Ron Fortgens',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213635,'Maarten Evertzen','Rob Admiraal',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-02-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),232557,'FINAL TOUCH 1','SU 1 De Balluh',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232557,'Willem Swager','Pierre Linschoten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232557,'Frans Veling','Erik van den Berg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232557,'Albert Pronk','Maarten Evertzen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232557,'Willem Swager','Erik van den Berg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232557,'Frans Veling','Maarten Evertzen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232557,'Albert Pronk','Pierre Linschoten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232557,'Albert Pronk','Erik van den Berg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232557,'Frans Veling','Pierre Linschoten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232557,'Willem Swager','Maarten Evertzen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-02-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213636,'PURMEREND 1','BREAKTHROUGH',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213636,'Patrick Tijssen','Henk van Hooff',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213636,'Marco Haverkotte','Lennert Duijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213636,'Rick Mulder','Raymond Selhorst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213636,'Patrick Tijssen','Lennert Duijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213636,'Marco Haverkotte','Raymond Selhorst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213636,'Rick Mulder','Henk van Hooff',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213636,'Rick Mulder','Lennert Duijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213636,'Marco Haverkotte','Henk van Hooff',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213636,'Patrick Tijssen','Raymond Selhorst',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-02-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213637,'FINAL TOUCH 1','Final Touch 3',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213637,'Wessel Tit','Dean Mitchell',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213637,'Frans Veling','Patrick Matthiessen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213637,'Albert Pronk','Egon Grinwis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213637,'Wessel Tit','Patrick Matthiessen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213637,'Frans Veling','Egon Grinwis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213637,'Albert Pronk','Dean Mitchell',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213637,'Albert Pronk','Patrick Matthiessen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213637,'Frans Veling','Dean Mitchell',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213637,'Wessel Tit','Egon Grinwis',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-02-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213638,'Snooker Academy','FINAL TOUCH 1',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213638,'Jan Willem Kweldam','Peter de Kamper',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213638,'Rob Admiraal','Willem Swager',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213638,'Ron Fortgens','Wessel Tit',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213638,'Jan Willem Kweldam','Willem Swager',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213638,'Rob Admiraal','Wessel Tit',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213638,'Ron Fortgens','Peter de Kamper',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213638,'Ron Fortgens','Willem Swager',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213638,'Rob Admiraal','Peter de Kamper',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213638,'Jan Willem Kweldam','Wessel Tit',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-02-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213639,'Final Touch 3','Alkmaar 4',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-02-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213640,'BREAKTHROUGH','SU 1 De Balluh',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213640,'Henk van Hooff','Erik van den Berg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213640,'Marco Glorie','Eddie Bongers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213640,'Lennert Duijn','Mark Koppert',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213640,'Henk van Hooff','Eddie Bongers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213640,'Marco Glorie','Mark Koppert',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213640,'Lennert Duijn','Erik van den Berg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213640,'Lennert Duijn','Eddie Bongers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213640,'Marco Glorie','Erik van den Berg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213640,'Henk van Hooff','Mark Koppert',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-02-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213641,'Snooker Academy','Alkmaar 4',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213641,'Jan Willem Kweldam','Sjoerd Blondeel Timmerman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213641,'Rob Admiraal','Rick van Houten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213641,'Ron Fortgens','Guy van den Ende',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213641,'Jan Willem Kweldam','Rick van Houten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213641,'Rob Admiraal','Guy van den Ende',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213641,'Ron Fortgens','Sjoerd Blondeel Timmerman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213641,'Ron Fortgens','Rick van Houten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213641,'Rob Admiraal','Sjoerd Blondeel Timmerman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213641,'Jan Willem Kweldam','Guy van den Ende',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-02-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),232765,'PURMEREND 1','SU 1 De Balluh',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232765,'Patrick Tijssen','Maarten Evertzen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232765,'Marco Haverkotte','Pierre Linschoten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232765,'Rick Mulder','Mark Koppert',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232765,'Patrick Tijssen','Pierre Linschoten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232765,'Marco Haverkotte','Mark Koppert',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232765,'Rick Mulder','Maarten Evertzen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232765,'Rick Mulder','Pierre Linschoten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232765,'Marco Haverkotte','Maarten Evertzen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(232765,'Patrick Tijssen','Mark Koppert',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-02-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213642,'PURMEREND 1','SU 1 De Balluh',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213642,'Patrick Tijssen','Mark Koppert',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213642,'Marco Haverkotte','Pierre Linschoten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213642,'Rick Mulder','Maarten Evertzen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213642,'Patrick Tijssen','Pierre Linschoten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213642,'Marco Haverkotte','Maarten Evertzen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213642,'Rick Mulder','Mark Koppert',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213642,'Rick Mulder','Pierre Linschoten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213642,'Marco Haverkotte','Mark Koppert',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213642,'Patrick Tijssen','Maarten Evertzen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-02-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213643,'BREAKTHROUGH','FINAL TOUCH 1',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213643,'Henk van Hooff','Albert Pronk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213643,'George Wijte','Willem Swager',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213643,'Raymond Selhorst','Frans Veling',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213643,'Henk van Hooff','Willem Swager',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213643,'George Wijte','Frans Veling',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213643,'Raymond Selhorst','Albert Pronk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213643,'Raymond Selhorst','Willem Swager',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213643,'George Wijte','Albert Pronk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213643,'Henk van Hooff','Frans Veling',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-03-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213644,'Final Touch 3','Snooker Academy',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213644,'Reitse Jonkman','Jan Willem Kweldam',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213644,'Edwin Horlings','Rob Admiraal',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213644,'Peter de Vries','Ron Fortgens',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213644,'Reitse Jonkman','Rob Admiraal',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213644,'Edwin Horlings','Ron Fortgens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213644,'Peter de Vries','Jan Willem Kweldam',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213644,'Peter de Vries','Rob Admiraal',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213644,'Edwin Horlings','Jan Willem Kweldam',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213644,'Reitse Jonkman','Ron Fortgens',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-03-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213645,'Alkmaar 4','BREAKTHROUGH',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213645,'Guy van den Ende','Lennert Duijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213645,'Sjoerd Blondeel Timmerman','Marco Glorie',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213645,'Eric van der Zwan','Henk van Hooff',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213645,'Guy van den Ende','Marco Glorie',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213645,'Sjoerd Blondeel Timmerman','Henk van Hooff',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213645,'Eric van der Zwan','Lennert Duijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213645,'Eric van der Zwan','Marco Glorie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213645,'Sjoerd Blondeel Timmerman','Lennert Duijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213645,'Guy van den Ende','Henk van Hooff',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-03-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213646,'FINAL TOUCH 1','PURMEREND 1',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213646,'Frans Veling','Patrick Tijssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213646,'Albert Pronk','Louis Leijdekker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213646,'Wessel Tit','Rick Mulder',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213646,'Frans Veling','Louis Leijdekker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213646,'Albert Pronk','Rick Mulder',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213646,'Wessel Tit','Patrick Tijssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213646,'Wessel Tit','Louis Leijdekker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213646,'Albert Pronk','Patrick Tijssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213646,'Frans Veling','Rick Mulder',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('28-03-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),233563,'SU 1 De Balluh','FINAL TOUCH 1',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233563,'Maarten Evertzen','Frans Veling',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233563,'Pierre Linschoten','Albert Pronk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233563,'Mark Koppert','Wessel Tit',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233563,'Maarten Evertzen','Albert Pronk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233563,'Pierre Linschoten','Wessel Tit',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233563,'Mark Koppert','Frans Veling',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233563,'Mark Koppert','Albert Pronk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233563,'Pierre Linschoten','Frans Veling',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233563,'Maarten Evertzen','Wessel Tit',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('28-03-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213647,'SU 1 De Balluh','FINAL TOUCH 1',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213647,'Maarten Evertzen','Frans Veling',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213647,'Pierre Linschoten','Albert Pronk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213647,'Mark Koppert','Wessel Tit',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213647,'Maarten Evertzen','Albert Pronk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213647,'Pierre Linschoten','Wessel Tit',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213647,'Mark Koppert','Frans Veling',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213647,'Mark Koppert','Albert Pronk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213647,'Pierre Linschoten','Frans Veling',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213647,'Maarten Evertzen','Wessel Tit',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('31-03-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213648,'PURMEREND 1','Alkmaar 4',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213648,'Louis Leijdekker','Eric van der Zwan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213648,'Patrick Tijssen','Jan de Wit',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213648,'Marco Haverkotte','Rick van Houten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213648,'Louis Leijdekker','Jan de Wit',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213648,'Patrick Tijssen','Rick van Houten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213648,'Marco Haverkotte','Eric van der Zwan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213648,'Marco Haverkotte','Jan de Wit',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213648,'Patrick Tijssen','Eric van der Zwan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213648,'Louis Leijdekker','Rick van Houten',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('31-03-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213649,'BREAKTHROUGH','Final Touch 3',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213649,'Henk van Hooff','Patrick Matthiessen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213649,'Michel Grapendaal','Reitse Jonkman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213649,'Marco Glorie','Edwin Horlings',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213649,'Henk van Hooff','Reitse Jonkman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213649,'Michel Grapendaal','Edwin Horlings',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213649,'Marco Glorie','Patrick Matthiessen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213649,'Marco Glorie','Reitse Jonkman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213649,'Michel Grapendaal','Patrick Matthiessen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213649,'Henk van Hooff','Edwin Horlings',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-04-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213650,'Snooker Academy','BREAKTHROUGH',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213650,'Ron Fortgens','George Wijte',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213650,'Rob Admiraal','Henk van Hooff',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213650,'Jan Willem Kweldam','Marco Glorie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213650,'Ron Fortgens','Henk van Hooff',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213650,'Rob Admiraal','Marco Glorie',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213650,'Jan Willem Kweldam','George Wijte',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213650,'Jan Willem Kweldam','Henk van Hooff',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213650,'Rob Admiraal','George Wijte',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213650,'Ron Fortgens','Marco Glorie',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-04-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213651,'Final Touch 3','PURMEREND 1',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213651,'Peter de Vries','Marco Haverkotte',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213651,'Albert Papot','Patrick Tijssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213651,'Dean Mitchell','Rick Mulder',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213651,'Peter de Vries','Patrick Tijssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213651,'Albert Papot','Rick Mulder',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213651,'Dean Mitchell','Marco Haverkotte',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213651,'Dean Mitchell','Patrick Tijssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213651,'Albert Papot','Marco Haverkotte',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213651,'Peter de Vries','Rick Mulder',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-04-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213653,'SU 1 De Balluh','Final Touch 3',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213653,'Mark Koppert','Egon Grinwis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213653,'Michel de Sain','Reitse Jonkman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213653,'Pierre Linschoten','Albert Papot',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213653,'Mark Koppert','Reitse Jonkman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213653,'Michel de Sain','Albert Papot',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213653,'Pierre Linschoten','Egon Grinwis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213653,'Pierre Linschoten','Reitse Jonkman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213653,'Michel de Sain','Egon Grinwis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213653,'Mark Koppert','Albert Papot',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-04-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213654,'PURMEREND 1','Snooker Academy',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213654,'Patrick Tijssen','Jan Willem Kweldam',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213654,'Louis Leijdekker','Rob Admiraal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213654,'Marco Haverkotte','Ron Fortgens',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213654,'Patrick Tijssen','Rob Admiraal',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213654,'Louis Leijdekker','Ron Fortgens',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213654,'Marco Haverkotte','Jan Willem Kweldam',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213654,'Marco Haverkotte','Rob Admiraal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213654,'Louis Leijdekker','Jan Willem Kweldam',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213654,'Patrick Tijssen','Ron Fortgens',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-04-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213655,'FINAL TOUCH 1','Alkmaar 4',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-05-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213656,'Snooker Academy','SU 1 De Balluh',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213656,'Ron Fortgens','Michel de Sain',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213656,'Rob Admiraal','Mark Koppert',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213656,'Jan Willem Kweldam','Maarten Evertzen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213656,'Ron Fortgens','Mark Koppert',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213656,'Rob Admiraal','Maarten Evertzen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213656,'Jan Willem Kweldam','Michel de Sain',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213656,'Jan Willem Kweldam','Mark Koppert',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213656,'Rob Admiraal','Michel de Sain',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213656,'Ron Fortgens','Maarten Evertzen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-05-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213657,'Final Touch 3','FINAL TOUCH 1',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-05-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213658,'BREAKTHROUGH','PURMEREND 1',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213658,'Henk van Hooff','Rick Mulder',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213658,'Raymond Selhorst','Louis Leijdekker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213658,'Marco Glorie','Marco Haverkotte',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213658,'Henk van Hooff','Louis Leijdekker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213658,'Raymond Selhorst','Marco Haverkotte',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213658,'Marco Glorie','Rick Mulder',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213658,'Marco Glorie','Louis Leijdekker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213658,'Raymond Selhorst','Rick Mulder',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(213658,'Henk van Hooff','Marco Haverkotte',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-05-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213660,'Alkmaar 4','Final Touch 3',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-05-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),213661,'FINAL TOUCH 1','Snooker Academy',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-05-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),233991,'SU 1 De Balluh','BREAKTHROUGH',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233991,'Mark Koppert','Henk van Hooff',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233991,'Michel de Sain','Raymond Selhorst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233991,'Pierre Linschoten','Marco Glorie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233991,'Mark Koppert','Raymond Selhorst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233991,'Michel de Sain','Marco Glorie',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233991,'Pierre Linschoten','Henk van Hooff',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233991,'Pierre Linschoten','Raymond Selhorst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233991,'Michel de Sain','Henk van Hooff',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233991,'Mark Koppert','Marco Glorie',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('25-05-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2010%'),233915,'Alkmaar 4','SU 1 De Balluh',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233915,'Guy van den Ende','Michel de Sain',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233915,'Eric van der Zwan','Mark Koppert',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233915,'Sjoerd Blondeel Timmerman','Eddie Bongers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233915,'Guy van den Ende','Mark Koppert',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233915,'Eric van der Zwan','Eddie Bongers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233915,'Sjoerd Blondeel Timmerman','Michel de Sain',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233915,'Sjoerd Blondeel Timmerman','Mark Koppert',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233915,'Eric van der Zwan','Michel de Sain',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(233915,'Guy van den Ende','Eddie Bongers',0,1);
