delete from cm_match_details where game_id in (select game_id from cm_matches where cpn_id = (select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'));
delete from cm_matches where cpn_id = (select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%');
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-09-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),423688,'FINAL TOUCH 2','Snooker Society 1',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423688,'Eric van Lokven','Pascal Sars',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423688,'Dean Mitchell','Pieter Kodde',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423688,'Willem Swager','Martijn Woonings',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423688,'Eric van Lokven','Pieter Kodde',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423688,'Dean Mitchell','Martijn Woonings',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423688,'Willem Swager','Pascal Sars',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423688,'Willem Swager','Pieter Kodde',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423688,'Dean Mitchell','Pascal Sars',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423688,'Eric van Lokven','Martijn Woonings',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-09-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),423691,'Alkmaar 4','Hippo 1',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-09-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),423694,'HVTC/OZEBI','Alkmaar 4',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423694,'Emile van den Heuvel','Rick van Houten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423694,'Peter Kooij','Sjoerd Blondeel Timmerman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423694,'Berry Roelofs','Eric van der Zwan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423694,'Emile van den Heuvel','Sjoerd Blondeel Timmerman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423694,'Peter Kooij','Eric van der Zwan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423694,'Berry Roelofs','Rick van Houten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423694,'Berry Roelofs','Sjoerd Blondeel Timmerman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423694,'Peter Kooij','Rick van Houten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423694,'Emile van den Heuvel','Eric van der Zwan',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-09-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),423695,'VINK 1','FINAL TOUCH 2',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423695,'Erik Kerkhoven','Albert Pronk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423695,'Hijlko Soepboer','Willem Swager',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423695,'Peter Kok','Laurens van Deijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423695,'Erik Kerkhoven','Willem Swager',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423695,'Hijlko Soepboer','Laurens van Deijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423695,'Peter Kok','Albert Pronk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423695,'Peter Kok','Willem Swager',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423695,'Hijlko Soepboer','Albert Pronk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423695,'Erik Kerkhoven','Laurens van Deijk',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-09-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),423696,'Snooker Society 1','Tasmanian Devils',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423696,'Sietse Oukes','Davith Denes Hiwat',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423696,'Pascal Sars','Kevin Slotboom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423696,'Pieter Kodde','Rik van Winsum',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423696,'Sietse Oukes','Kevin Slotboom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423696,'Pascal Sars','Rik van Winsum',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423696,'Pieter Kodde','Davith Denes Hiwat',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423696,'Pieter Kodde','Kevin Slotboom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423696,'Pascal Sars','Davith Denes Hiwat',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423696,'Sietse Oukes','Rik van Winsum',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-10-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),423699,'Snooker Society 1','VINK 1',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423699,'Martijn Woonings','Roelan Derks',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423699,'Pascal Sars','Ruud de Jong',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423699,'Pieter Kodde','Danny Flendrie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423699,'Martijn Woonings','Ruud de Jong',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423699,'Pascal Sars','Danny Flendrie',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423699,'Pieter Kodde','Roelan Derks',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423699,'Pieter Kodde','Ruud de Jong',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423699,'Pascal Sars','Roelan Derks',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423699,'Martijn Woonings','Danny Flendrie',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-10-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),423700,'FINAL TOUCH 2','Hippo 1',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423700,'Eric van Lokven','Ruud de Wit',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423700,'Laurens van Deijk','Marco Eisinga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423700,'Dean Mitchell','Marco Eisinga',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423700,'Laurens van Deijk','Ruud de Wit',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423700,'Dean Mitchell','Ruud de Wit',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423700,'Eric van Lokven','Marco Eisinga',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-10-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),423701,'Alkmaar 4','SU 1 De Balluh',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423701,'Rick van Houten','Patrick Terlou',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423701,'Guy van den Ende','Mark Koppert',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423701,'Sjoerd Blondeel Timmerman','Thomas Verheij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423701,'Rick van Houten','Mark Koppert',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423701,'Guy van den Ende','Thomas Verheij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423701,'Sjoerd Blondeel Timmerman','Patrick Terlou',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423701,'Sjoerd Blondeel Timmerman','Mark Koppert',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423701,'Guy van den Ende','Patrick Terlou',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423701,'Rick van Houten','Thomas Verheij',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-10-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),423704,'HVTC/OZEBI','FINAL TOUCH 2',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423704,'Peter Kooij','Albert Pronk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423704,'Peter Kooij','Laurens van Deijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423704,'Peter Kooij','Arnoud de la Mar',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-10-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),423706,'VINK 1','Tasmanian Devils',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-11-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),430404,'Tasmanian Devils','SU 1 De Balluh',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(430404,'Rik van Winsum','Michel de Sain',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(430404,'Ronald Rennen','Patrick Terlou',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(430404,'Rik van Winsum','Patrick Terlou',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(430404,'Ronald Rennen','Thomas Verheij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(430404,'Ronald Rennen','Michel de Sain',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(430404,'Rik van Winsum','Thomas Verheij',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-11-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),423709,'VINK 1','Hippo 1',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423709,'Danny Flendrie','Ruud de Wit',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423709,'Roelan Derks','Marco Eisinga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423709,'Hijlko Soepboer','Olivier Hensing',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423709,'Danny Flendrie','Marco Eisinga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423709,'Roelan Derks','Olivier Hensing',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423709,'Hijlko Soepboer','Ruud de Wit',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423709,'Hijlko Soepboer','Marco Eisinga',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423709,'Roelan Derks','Ruud de Wit',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423709,'Danny Flendrie','Olivier Hensing',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-11-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),423710,'Snooker Society 1','HVTC/OZEBI',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423710,'Martijn Woonings','Michel Woudenberg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423710,'Sietse Oukes','Michael Koren',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423710,'Pascal Sars','Eddie Bongers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423710,'Martijn Woonings','Michael Koren',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423710,'Sietse Oukes','Eddie Bongers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423710,'Pascal Sars','Michel Woudenberg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423710,'Pascal Sars','Michael Koren',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423710,'Sietse Oukes','Michel Woudenberg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423710,'Martijn Woonings','Eddie Bongers',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-11-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),423712,'FINAL TOUCH 2','SU 1 De Balluh',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423712,'Eric van Lokven','Thomas Verheij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423712,'Martijn Lesterhuis','Patrick Terlou',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423712,'Dean Mitchell','Mark Koppert',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423712,'Eric van Lokven','Patrick Terlou',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423712,'Martijn Lesterhuis','Mark Koppert',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423712,'Dean Mitchell','Thomas Verheij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423712,'Dean Mitchell','Patrick Terlou',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423712,'Martijn Lesterhuis','Thomas Verheij',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423712,'Eric van Lokven','Mark Koppert',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-11-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),431615,'Hippo 1','Snooker Society 1',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431615,'Ruud de Wit','Sietse Oukes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431615,'Benno Lier','Martijn Woonings',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431615,'Ruud de Wit','Martijn Woonings',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431615,'Benno Lier','Pascal Sars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431615,'Benno Lier','Sietse Oukes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431615,'Ruud de Wit','Pascal Sars',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-11-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),423714,'HVTC/OZEBI','VINK 1',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423714,'Michael Koren','Peter Kok',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423714,'Michel Woudenberg','Danny Flendrie',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423714,'Eddie Bongers','Roelan Derks',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423714,'Michael Koren','Danny Flendrie',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423714,'Michel Woudenberg','Roelan Derks',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423714,'Eddie Bongers','Peter Kok',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423714,'Eddie Bongers','Danny Flendrie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423714,'Michel Woudenberg','Peter Kok',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423714,'Michael Koren','Roelan Derks',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-11-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),432133,'SU 1 De Balluh','Snooker Society 1',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(432133,'Thomas Verheij','Pascal Sars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(432133,'Patrick Terlou','Pieter Kodde',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(432133,'Mark Koppert','Martijn Woonings',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(432133,'Thomas Verheij','Pieter Kodde',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(432133,'Patrick Terlou','Martijn Woonings',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(432133,'Mark Koppert','Pascal Sars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(432133,'Mark Koppert','Pieter Kodde',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(432133,'Patrick Terlou','Pascal Sars',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(432133,'Thomas Verheij','Martijn Woonings',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-11-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),423717,'Hippo 1','Tasmanian Devils',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423717,'Olivier Hensing','Bas Capelle',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423717,'Naut Bruns','Davith Denes Hiwat',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423717,'Marco Eisinga','Freddie de Grooth',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423717,'Olivier Hensing','Davith Denes Hiwat',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423717,'Naut Bruns','Freddie de Grooth',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423717,'Marco Eisinga','Bas Capelle',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423717,'Marco Eisinga','Davith Denes Hiwat',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423717,'Naut Bruns','Bas Capelle',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423717,'Olivier Hensing','Freddie de Grooth',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-12-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),423718,'VINK 1','SU 1 De Balluh',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423718,'Danny Flendrie','Thomas Verheij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423718,'Roelan Derks','Patrick Terlou',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423718,'Erik Kerkhoven','Mark Koppert',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423718,'Danny Flendrie','Patrick Terlou',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423718,'Roelan Derks','Mark Koppert',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423718,'Erik Kerkhoven','Thomas Verheij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423718,'Erik Kerkhoven','Patrick Terlou',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423718,'Roelan Derks','Thomas Verheij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423718,'Danny Flendrie','Mark Koppert',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-12-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),423721,'Hippo 1','HVTC/OZEBI',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423721,'Marco Eisinga','Michel Woudenberg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423721,'Benno Lier','Berry Roelofs',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423721,'Marco Eisinga','Berry Roelofs',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423721,'Benno Lier','Peter Kooij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423721,'Benno Lier','Michel Woudenberg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423721,'Marco Eisinga','Peter Kooij',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-12-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),423724,'SU 1 De Balluh','Hippo 1',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423724,'Patrick Terlou','Ruud de Wit',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423724,'Mark Koppert','Benno Lier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423724,'Michel de Sain','Ruud de Wit',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423724,'Patrick Terlou','Benno Lier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423724,'Mark Koppert','Ruud de Wit',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423724,'Michel de Sain','Benno Lier',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-12-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),423725,'HVTC/OZEBI','Tasmanian Devils',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-12-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),432753,'FINAL TOUCH 2','Alkmaar 4',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(432753,'Eric van Lokven','Rick van Houten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(432753,'Willem Swager','Guy van den Ende',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(432753,'Laurens van Deijk','Eric van der Zwan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(432753,'Eric van Lokven','Guy van den Ende',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(432753,'Willem Swager','Eric van der Zwan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(432753,'Laurens van Deijk','Rick van Houten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(432753,'Laurens van Deijk','Guy van den Ende',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(432753,'Willem Swager','Rick van Houten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(432753,'Eric van Lokven','Eric van der Zwan',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-12-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),423727,'Alkmaar 4','Snooker Society 1',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-01-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),423728,'HVTC/OZEBI','SU 1 De Balluh',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423728,'Michael Koren','Patrick Terlou',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423728,'Michel Woudenberg','Mark Koppert',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423728,'Berry Roelofs','Michel de Sain',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423728,'Michael Koren','Mark Koppert',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423728,'Michel Woudenberg','Michel de Sain',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423728,'Berry Roelofs','Patrick Terlou',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423728,'Berry Roelofs','Mark Koppert',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423728,'Michel Woudenberg','Patrick Terlou',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423728,'Michael Koren','Michel de Sain',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-01-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),423729,'VINK 1','Alkmaar 4',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423729,'Roelan Derks','Rick van Houten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423729,'Erik Kerkhoven','Guy van den Ende',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423729,'Ruud de Jong','Eric van der Zwan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423729,'Roelan Derks','Guy van den Ende',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423729,'Erik Kerkhoven','Eric van der Zwan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423729,'Ruud de Jong','Rick van Houten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423729,'Ruud de Jong','Guy van den Ende',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423729,'Erik Kerkhoven','Rick van Houten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423729,'Roelan Derks','Eric van der Zwan',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-01-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),423732,'Tasmanian Devils','FINAL TOUCH 2',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423732,'Rik van Winsum','Eric van Lokven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423732,'Ronald Rennen','Willem Swager',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423732,'Kevin Slotboom','Laurens van Deijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423732,'Rik van Winsum','Willem Swager',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423732,'Ronald Rennen','Laurens van Deijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423732,'Kevin Slotboom','Eric van Lokven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423732,'Kevin Slotboom','Willem Swager',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423732,'Ronald Rennen','Eric van Lokven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423732,'Rik van Winsum','Laurens van Deijk',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-01-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),433084,'Tasmanian Devils','Alkmaar 4',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433084,'Rik van Winsum','Eric van der Zwan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433084,'Ronald Rennen','Rick van Houten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433084,'Kevin Slotboom','Guy van den Ende',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433084,'Rik van Winsum','Rick van Houten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433084,'Ronald Rennen','Guy van den Ende',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433084,'Kevin Slotboom','Eric van der Zwan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433084,'Kevin Slotboom','Rick van Houten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433084,'Ronald Rennen','Eric van der Zwan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433084,'Rik van Winsum','Guy van den Ende',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-01-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),423737,'Hippo 1','Alkmaar 4',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423737,'Ruud de Wit','Sjoerd Blondeel Timmerman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423737,'Marco Eisinga','Eric van der Zwan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423737,'Naut Bruns','Guy van den Ende',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423737,'Ruud de Wit','Eric van der Zwan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423737,'Marco Eisinga','Guy van den Ende',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423737,'Naut Bruns','Sjoerd Blondeel Timmerman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423737,'Naut Bruns','Eric van der Zwan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423737,'Marco Eisinga','Sjoerd Blondeel Timmerman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423737,'Ruud de Wit','Guy van den Ende',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('25-01-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),433416,'SU 1 De Balluh','Tasmanian Devils',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433416,'Eddie Bongers','Freddie de Grooth',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433416,'Thomas Verheij','Ronald Rennen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433416,'Patrick Terlou','Davith Denes Hiwat',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433416,'Eddie Bongers','Ronald Rennen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433416,'Thomas Verheij','Davith Denes Hiwat',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433416,'Patrick Terlou','Freddie de Grooth',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433416,'Patrick Terlou','Ronald Rennen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433416,'Thomas Verheij','Freddie de Grooth',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433416,'Eddie Bongers','Davith Denes Hiwat',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('28-01-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),433249,'Snooker Society 1','FINAL TOUCH 2',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433249,'Pascal Sars','Eric van Lokven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433249,'Martijn Woonings','Laurens van Deijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433249,'Sietse Oukes','Arnoud de la Mar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433249,'Pascal Sars','Laurens van Deijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433249,'Martijn Woonings','Arnoud de la Mar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433249,'Sietse Oukes','Eric van Lokven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433249,'Sietse Oukes','Laurens van Deijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433249,'Martijn Woonings','Eric van Lokven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433249,'Pascal Sars','Arnoud de la Mar',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-02-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),423740,'FINAL TOUCH 2','VINK 1',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423740,'Martijn Lesterhuis','Ruud de Jong',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423740,'Willem Swager','Hijlko Soepboer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423740,'Albert Pronk','Roelan Derks',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423740,'Martijn Lesterhuis','Hijlko Soepboer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423740,'Willem Swager','Roelan Derks',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423740,'Albert Pronk','Ruud de Jong',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423740,'Albert Pronk','Hijlko Soepboer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423740,'Willem Swager','Ruud de Jong',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423740,'Martijn Lesterhuis','Roelan Derks',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-02-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),423741,'Alkmaar 4','HVTC/OZEBI',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('01-03-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),423742,'Tasmanian Devils','Snooker Society 1',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423742,'Davith Denes Hiwat','Pieter Kodde',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423742,'Ronald Rennen','Martijn Woonings',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423742,'Kevin Slotboom','Pascal Sars',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423742,'Davith Denes Hiwat','Martijn Woonings',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423742,'Ronald Rennen','Pascal Sars',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423742,'Kevin Slotboom','Pieter Kodde',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423742,'Kevin Slotboom','Martijn Woonings',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423742,'Ronald Rennen','Pieter Kodde',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423742,'Davith Denes Hiwat','Pascal Sars',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-03-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),423746,'VINK 1','Snooker Society 1',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423746,'Danny Flendrie','Pieter Kodde',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423746,'Peter Kok','Pascal Sars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423746,'Ruud de Jong','Martijn Woonings',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423746,'Danny Flendrie','Pascal Sars',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423746,'Peter Kok','Martijn Woonings',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423746,'Ruud de Jong','Pieter Kodde',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423746,'Ruud de Jong','Pascal Sars',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423746,'Peter Kok','Pieter Kodde',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423746,'Danny Flendrie','Martijn Woonings',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-03-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),423747,'Hippo 1','FINAL TOUCH 2',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-03-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),423749,'Snooker Society 1','Hippo 1',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423749,'Pascal Sars','Ruud de Wit',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423749,'Martijn Woonings','Benno Lier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423749,'Pieter Kodde','Olivier Hensing',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423749,'Pascal Sars','Benno Lier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423749,'Martijn Woonings','Olivier Hensing',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423749,'Pieter Kodde','Ruud de Wit',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423749,'Pieter Kodde','Benno Lier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423749,'Martijn Woonings','Ruud de Wit',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423749,'Pascal Sars','Olivier Hensing',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-03-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),423750,'FINAL TOUCH 2','HVTC/OZEBI',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423750,'Eric van Lokven','Peter Kooij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423750,'Martijn Lesterhuis','Michel Woudenberg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423750,'Laurens van Deijk','Michael Koren',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423750,'Eric van Lokven','Michel Woudenberg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423750,'Martijn Lesterhuis','Michael Koren',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423750,'Laurens van Deijk','Peter Kooij',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423750,'Laurens van Deijk','Michel Woudenberg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423750,'Martijn Lesterhuis','Peter Kooij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423750,'Eric van Lokven','Michael Koren',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-03-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),423752,'Tasmanian Devils','VINK 1',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-04-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),423753,'SU 1 De Balluh','FINAL TOUCH 2',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423753,'Thomas Verheij','Martijn Lesterhuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423753,'Michel de Sain','Albert Pronk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423753,'Patrick Terlou','Eric van Lokven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423753,'Thomas Verheij','Albert Pronk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423753,'Michel de Sain','Eric van Lokven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423753,'Patrick Terlou','Martijn Lesterhuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423753,'Patrick Terlou','Albert Pronk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423753,'Michel de Sain','Martijn Lesterhuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423753,'Thomas Verheij','Eric van Lokven',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-04-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),423754,'HVTC/OZEBI','Snooker Society 1',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423754,'Peter Kooij','Pascal Sars',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423754,'Berry Roelofs','Sietse Oukes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423754,'Eddie Bongers','Martijn Woonings',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423754,'Peter Kooij','Sietse Oukes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423754,'Berry Roelofs','Martijn Woonings',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423754,'Eddie Bongers','Pascal Sars',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423754,'Eddie Bongers','Sietse Oukes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423754,'Berry Roelofs','Pascal Sars',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423754,'Peter Kooij','Martijn Woonings',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-04-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),423756,'Alkmaar 4','Tasmanian Devils',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-04-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),423757,'Hippo 1','VINK 1',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-04-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),423759,'VINK 1','HVTC/OZEBI',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423759,'Peter Kok','Eddie Bongers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423759,'Erik Kerkhoven','Michael Koren',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423759,'Hijlko Soepboer','Michel Woudenberg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423759,'Peter Kok','Michael Koren',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423759,'Erik Kerkhoven','Michel Woudenberg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423759,'Hijlko Soepboer','Eddie Bongers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423759,'Hijlko Soepboer','Michael Koren',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423759,'Erik Kerkhoven','Eddie Bongers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423759,'Peter Kok','Michel Woudenberg',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-04-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),423760,'Snooker Society 1','SU 1 De Balluh',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423760,'Pascal Sars','Mark Koppert',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423760,'Martijn Woonings','Patrick Terlou',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423760,'Pieter Kodde','Michel de Sain',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423760,'Pascal Sars','Patrick Terlou',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423760,'Martijn Woonings','Michel de Sain',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423760,'Pieter Kodde','Mark Koppert',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423760,'Pieter Kodde','Patrick Terlou',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423760,'Martijn Woonings','Mark Koppert',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423760,'Pascal Sars','Michel de Sain',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-04-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),423762,'Tasmanian Devils','Hippo 1',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-05-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),423764,'SU 1 De Balluh','VINK 1',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423764,'Michel de Sain','Peter Kok',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423764,'Mark Koppert','Danny Flendrie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423764,'Patrick Terlou','Danny Flendrie',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423764,'Mark Koppert','Peter Kok',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423764,'Patrick Terlou','Peter Kok',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423764,'Michel de Sain','Danny Flendrie',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-05-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),423767,'Alkmaar 4','FINAL TOUCH 2',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-05-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),435079,'HVTC/OZEBI','Hippo 1',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435079,'Emile van den Heuvel','Marco Eisinga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435079,'Michael Koren','Ruud de Wit',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435079,'Michel Woudenberg','Olivier Hensing',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435079,'Emile van den Heuvel','Ruud de Wit',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435079,'Michael Koren','Olivier Hensing',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435079,'Michel Woudenberg','Marco Eisinga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435079,'Michel Woudenberg','Ruud de Wit',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435079,'Michael Koren','Marco Eisinga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435079,'Emile van den Heuvel','Olivier Hensing',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-05-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),423769,'Snooker Society 1','Alkmaar 4',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423769,'Martijn Woonings','Rick van Houten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423769,'Pascal Sars','Sjoerd Blondeel Timmerman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423769,'Pieter Kodde','Eric van der Zwan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423769,'Martijn Woonings','Sjoerd Blondeel Timmerman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423769,'Pascal Sars','Eric van der Zwan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423769,'Pieter Kodde','Rick van Houten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423769,'Pieter Kodde','Sjoerd Blondeel Timmerman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423769,'Pascal Sars','Rick van Houten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423769,'Martijn Woonings','Eric van der Zwan',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-05-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),423772,'Tasmanian Devils','HVTC/OZEBI',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('26-05-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),423774,'SU 1 De Balluh','HVTC/OZEBI',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423774,'Mark Koppert','Peter Kooij',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423774,'Thomas Verheij','Eddie Bongers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423774,'Michel de Sain','Michael Koren',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423774,'Mark Koppert','Eddie Bongers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423774,'Thomas Verheij','Michael Koren',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423774,'Michel de Sain','Peter Kooij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423774,'Michel de Sain','Eddie Bongers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423774,'Thomas Verheij','Peter Kooij',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423774,'Mark Koppert','Michael Koren',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('28-05-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),435202,'SU 1 De Balluh','Alkmaar 4',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435202,'Michel de Sain','Guy van den Ende',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435202,'Patrick Terlou','Sjoerd Blondeel Timmerman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435202,'Mark Koppert','Eric van der Zwan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435202,'Michel de Sain','Sjoerd Blondeel Timmerman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435202,'Patrick Terlou','Eric van der Zwan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435202,'Mark Koppert','Guy van den Ende',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435202,'Mark Koppert','Sjoerd Blondeel Timmerman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435202,'Patrick Terlou','Guy van den Ende',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435202,'Michel de Sain','Eric van der Zwan',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('29-05-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),423776,'FINAL TOUCH 2','Tasmanian Devils',8,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('29-05-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),423777,'Alkmaar 4','VINK 1',8,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-06-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse A' and ssn_id like '2013%'),435226,'Hippo 1','SU 1 De Balluh',0,9);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435226,'Naut Bruns','Patrick Terlou',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435226,'Marco Eisinga','Mark Koppert',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435226,'Benno Lier','Michel de Sain',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435226,'Naut Bruns','Mark Koppert',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435226,'Marco Eisinga','Michel de Sain',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435226,'Benno Lier','Patrick Terlou',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435226,'Benno Lier','Mark Koppert',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435226,'Marco Eisinga','Patrick Terlou',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435226,'Naut Bruns','Michel de Sain',0,1);
