delete from cm_match_details where game_id in (select game_id from cm_matches where cpn_id = (select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'));
delete from cm_matches where cpn_id = (select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%');
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-09-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),423778,'Thurston Snooker 1','Blaak',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423778,'Jimmy Worung','Donny van Oosterhout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423778,'Hoa Nguyen','Raemon Sluiter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423778,'OC Chan','Stefan Wernke',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423778,'Jimmy Worung','Raemon Sluiter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423778,'Hoa Nguyen','Stefan Wernke',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423778,'OC Chan','Donny van Oosterhout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423778,'OC Chan','Raemon Sluiter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423778,'Hoa Nguyen','Donny van Oosterhout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423778,'Jimmy Worung','Stefan Wernke',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-09-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),423781,'Snookerij 0','Pompadour 2',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423781,'Wim Monfils','Niki Lin',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423781,'Coen Drejer','Tim De Ruyter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423781,'Martijn Verzaal','Corné Kuijpers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423781,'Wim Monfils','Tim De Ruyter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423781,'Coen Drejer','Corné Kuijpers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423781,'Martijn Verzaal','Niki Lin',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423781,'Martijn Verzaal','Tim De Ruyter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423781,'Coen Drejer','Niki Lin',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423781,'Wim Monfils','Corné Kuijpers',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-09-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),423782,'Pompadour 2','Thurston Snooker 1',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423782,'Tim De Ruyter','Anthony Cheung',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423782,'Maurice Rijk','Hugo Leung',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423782,'Patrick Tijssen','Jimmy Worung',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423782,'Tim De Ruyter','Hugo Leung',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423782,'Maurice Rijk','Jimmy Worung',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423782,'Patrick Tijssen','Anthony Cheung',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423782,'Patrick Tijssen','Hugo Leung',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423782,'Maurice Rijk','Anthony Cheung',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423782,'Tim De Ruyter','Jimmy Worung',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-09-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),423783,'Blaak','De Loods 1',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423783,'Laslo Batis','Roeland Melief',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423783,'Marcel Streef','Alexander van den Doel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423783,'Donny van Oosterhout','Hans van Velde',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423783,'Laslo Batis','Alexander van den Doel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423783,'Marcel Streef','Hans van Velde',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423783,'Donny van Oosterhout','Roeland Melief',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423783,'Donny van Oosterhout','Alexander van den Doel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423783,'Marcel Streef','Roeland Melief',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423783,'Laslo Batis','Hans van Velde',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('26-09-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),423785,'SC Capelle 1','Back in the Pack 2.0',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423785,'Rien Baak','Willem de Koning',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423785,'Fausto Salis','Leon van de Laak',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423785,'Rene Boers','Peter Bertens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423785,'Rien Baak','Leon van de Laak',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423785,'Fausto Salis','Peter Bertens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423785,'Rene Boers','Willem de Koning',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423785,'Rene Boers','Leon van de Laak',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423785,'Fausto Salis','Willem de Koning',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423785,'Rien Baak','Peter Bertens',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-10-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),423788,'De Loods 1','Pompadour 2',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423788,'Hans van Velde','Tim De Ruyter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423788,'Alexander van den Doel','Philippe van den Broeke',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423788,'Roeland Melief','Patrick Tijssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423788,'Hans van Velde','Philippe van den Broeke',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423788,'Alexander van den Doel','Patrick Tijssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423788,'Roeland Melief','Tim De Ruyter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423788,'Roeland Melief','Philippe van den Broeke',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423788,'Alexander van den Doel','Tim De Ruyter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423788,'Hans van Velde','Patrick Tijssen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-10-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),431349,'Zeekant','SC Capelle 1',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431349,'Raymond Huisman','Edwin Heinsman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431349,'Ben Vermeer','Rene Boers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431349,'Jarl Hinfelaar','Sjaak Hofman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431349,'Raymond Huisman','Rene Boers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431349,'Ben Vermeer','Sjaak Hofman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431349,'Jarl Hinfelaar','Edwin Heinsman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431349,'Jarl Hinfelaar','Rene Boers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431349,'Ben Vermeer','Edwin Heinsman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431349,'Raymond Huisman','Sjaak Hofman',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-10-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),423790,'Back in the Pack 2.0','Blaak',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423790,'Roel Koks','Benjamin Hamburger',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423790,'Leon van de Laak','Tim van der Zanden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423790,'Peter Bertens','Donny van Oosterhout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423790,'Roel Koks','Tim van der Zanden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423790,'Leon van de Laak','Donny van Oosterhout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423790,'Peter Bertens','Benjamin Hamburger',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423790,'Peter Bertens','Tim van der Zanden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423790,'Leon van de Laak','Benjamin Hamburger',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423790,'Roel Koks','Donny van Oosterhout',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-10-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),423792,'Snookerij 0','Thurston Snooker 1',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423792,'Wim Monfils','Anthony Cheung',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423792,'Coen Drejer','OC Chan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423792,'Kevin Vermeiren','Jimmy Worung',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423792,'Wim Monfils','OC Chan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423792,'Coen Drejer','Jimmy Worung',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423792,'Kevin Vermeiren','Anthony Cheung',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423792,'Kevin Vermeiren','OC Chan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423792,'Coen Drejer','Anthony Cheung',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423792,'Wim Monfils','Jimmy Worung',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-10-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),423794,'Pompadour 2','Back in the Pack 2.0',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423794,'Maurice Rijk','Leon van de Laak',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423794,'Niki Lin','Willem de Koning',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423794,'Philippe van den Broeke','Roel Koks',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423794,'Maurice Rijk','Willem de Koning',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423794,'Niki Lin','Roel Koks',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423794,'Philippe van den Broeke','Leon van de Laak',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423794,'Philippe van den Broeke','Willem de Koning',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423794,'Niki Lin','Leon van de Laak',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423794,'Maurice Rijk','Roel Koks',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-10-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),423795,'Blaak','Zeekant',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423795,'Tim van der Zanden','Raymond Huisman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423795,'Benjamin Hamburger','Maurice Kempeneers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423795,'Marcel Streef','Marcel Scholtes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423795,'Tim van der Zanden','Maurice Kempeneers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423795,'Benjamin Hamburger','Marcel Scholtes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423795,'Marcel Streef','Raymond Huisman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423795,'Marcel Streef','Maurice Kempeneers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423795,'Benjamin Hamburger','Raymond Huisman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423795,'Tim van der Zanden','Marcel Scholtes',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('28-10-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),431327,'Thurston Snooker 1','De Loods 1',9,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431327,'Anthony Cheung','Hans van Velde',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431327,'Raymond Fabrie','Roeland Melief',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431327,'Huidji See','Alexander van den Doel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431327,'Anthony Cheung','Roeland Melief',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431327,'Raymond Fabrie','Alexander van den Doel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431327,'Huidji See','Hans van Velde',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431327,'Huidji See','Roeland Melief',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431327,'Raymond Fabrie','Hans van Velde',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431327,'Anthony Cheung','Alexander van den Doel',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('29-10-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),431367,'De Loods 1','SC Capelle 1',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431367,'Alexander van den Doel','Rien Baak',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431367,'Hans van Velde','Rene Boers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431367,'Roeland Melief','Fausto Salis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431367,'Alexander van den Doel','Rene Boers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431367,'Hans van Velde','Fausto Salis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431367,'Roeland Melief','Rien Baak',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431367,'Roeland Melief','Rene Boers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431367,'Hans van Velde','Rien Baak',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431367,'Alexander van den Doel','Fausto Salis',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-11-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),423799,'Zeekant','Pompadour 2',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423799,'Jarl Hinfelaar','Maurice Rijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423799,'Ben Vermeer','Tim De Ruyter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423799,'Marcel Scholtes','Niki Lin',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423799,'Jarl Hinfelaar','Tim De Ruyter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423799,'Ben Vermeer','Niki Lin',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423799,'Marcel Scholtes','Maurice Rijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423799,'Marcel Scholtes','Tim De Ruyter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423799,'Ben Vermeer','Maurice Rijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423799,'Jarl Hinfelaar','Niki Lin',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-11-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),423800,'Back in the Pack 2.0','Thurston Snooker 1',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423800,'Roel Koks','Anthony Cheung',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423800,'Peter Bertens','Hoa Nguyen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423800,'Roel Koks','Hoa Nguyen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423800,'Peter Bertens','Jimmy Worung',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423800,'Peter Bertens','Anthony Cheung',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423800,'Roel Koks','Jimmy Worung',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-11-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),423802,'Snookerij 0','De Loods 1',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423802,'Wim Monfils','Hans van Velde',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423802,'Kevin Vermeiren','Roeland Melief',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423802,'Martijn Verzaal','Alexander van den Doel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423802,'Wim Monfils','Roeland Melief',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423802,'Kevin Vermeiren','Alexander van den Doel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423802,'Martijn Verzaal','Hans van Velde',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423802,'Martijn Verzaal','Roeland Melief',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423802,'Kevin Vermeiren','Hans van Velde',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423802,'Wim Monfils','Alexander van den Doel',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-11-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),423803,'Blaak','Snookerij 0',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-11-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),431368,'De Loods 1','Back in the Pack 2.0',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431368,'Alexander van den Doel','Willem de Koning',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431368,'Roeland Melief','Roel Koks',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431368,'Hans van Velde','Roel Koks',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431368,'Roeland Melief','Willem de Koning',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431368,'Hans van Velde','Willem de Koning',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431368,'Alexander van den Doel','Roel Koks',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-11-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),423804,'Thurston Snooker 1','Zeekant',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423804,'Jimmy Worung','Jarl Hinfelaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423804,'Anthony Cheung','Raymond Huisman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423804,'Raymond Fabrie','Marcel Scholtes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423804,'Jimmy Worung','Raymond Huisman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423804,'Anthony Cheung','Marcel Scholtes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423804,'Raymond Fabrie','Jarl Hinfelaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423804,'Raymond Fabrie','Raymond Huisman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423804,'Anthony Cheung','Jarl Hinfelaar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423804,'Jimmy Worung','Marcel Scholtes',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-11-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),423807,'SC Capelle 1','Snookerij 0',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423807,'Edwin Heinsman','Björn Matheijssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423807,'Rene Boers','Martijn Verzaal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423807,'Fausto Salis','Martijn Verzaal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423807,'Rene Boers','Björn Matheijssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423807,'Fausto Salis','Björn Matheijssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423807,'Edwin Heinsman','Martijn Verzaal',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('29-11-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),431819,'Snookerij 0','Back in the Pack 2.0',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431819,'Wim Monfils','Leon van de Laak',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431819,'Coen Drejer','Willem de Koning',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431819,'Martijn Verzaal','Roel Koks',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431819,'Wim Monfils','Willem de Koning',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431819,'Coen Drejer','Roel Koks',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431819,'Martijn Verzaal','Leon van de Laak',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431819,'Martijn Verzaal','Willem de Koning',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431819,'Coen Drejer','Leon van de Laak',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431819,'Wim Monfils','Roel Koks',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-12-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),432382,'SC Capelle 1','Blaak',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(432382,'Edwin Heinsman','Tim van der Zanden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(432382,'Fausto Salis','Benjamin Hamburger',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(432382,'Rien Baak','Marcel Streef',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(432382,'Edwin Heinsman','Benjamin Hamburger',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(432382,'Fausto Salis','Marcel Streef',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(432382,'Rien Baak','Tim van der Zanden',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(432382,'Rien Baak','Benjamin Hamburger',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(432382,'Fausto Salis','Tim van der Zanden',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(432382,'Edwin Heinsman','Marcel Streef',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-12-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),423814,'Pompadour 2','SC Capelle 1',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423814,'Niki Lin','Rien Baak',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423814,'Patrick Tijssen','Rene Boers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423814,'Tim De Ruyter','Fausto Salis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423814,'Niki Lin','Rene Boers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423814,'Patrick Tijssen','Fausto Salis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423814,'Tim De Ruyter','Rien Baak',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423814,'Tim De Ruyter','Rene Boers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423814,'Patrick Tijssen','Rien Baak',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423814,'Niki Lin','Fausto Salis',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-12-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),423816,'Back in the Pack 2.0','Zeekant',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423816,'Willem de Koning','Ben Vermeer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423816,'Peter Bertens','Marcel Scholtes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423816,'Roel Koks','Jarl Hinfelaar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423816,'Willem de Koning','Marcel Scholtes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423816,'Peter Bertens','Jarl Hinfelaar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423816,'Roel Koks','Ben Vermeer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423816,'Roel Koks','Marcel Scholtes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423816,'Peter Bertens','Ben Vermeer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423816,'Willem de Koning','Jarl Hinfelaar',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-12-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),431958,'Zeekant','De Loods 1',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431958,'Ben Vermeer','Hans van Velde',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431958,'Marcel Scholtes','Roeland Melief',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431958,'Maurice Kempeneers','Alexander van den Doel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431958,'Ben Vermeer','Roeland Melief',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431958,'Marcel Scholtes','Alexander van den Doel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431958,'Maurice Kempeneers','Hans van Velde',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431958,'Maurice Kempeneers','Roeland Melief',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431958,'Marcel Scholtes','Hans van Velde',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431958,'Ben Vermeer','Alexander van den Doel',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-01-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),423819,'SC Capelle 1','Thurston Snooker 1',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423819,'Fausto Salis','Huidji See',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423819,'Rene Boers','Jimmy Worung',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423819,'Rien Baak','Jimmy Worung',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423819,'Rene Boers','Huidji See',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423819,'Rien Baak','Huidji See',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423819,'Fausto Salis','Jimmy Worung',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-01-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),423821,'Snookerij 0','Zeekant',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423821,'Wim Monfils','Marcel Scholtes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423821,'Wim Monfils','Raymond Huisman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423821,'Wim Monfils','Ben Vermeer',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-01-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),423822,'Pompadour 2','Snookerij 0',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423822,'Michaël Kuijpers','Björn Matheijssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423822,'Corné Kuijpers','Wim Monfils',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423822,'Corné Kuijpers','Björn Matheijssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423822,'Michaël Kuijpers','Wim Monfils',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-01-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),423823,'Blaak','Thurston Snooker 1',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423823,'Benjamin Hamburger','OC Chan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423823,'Marcel Streef','Hoa Nguyen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423823,'Tim van der Zanden','Anthony Cheung',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423823,'Benjamin Hamburger','Hoa Nguyen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423823,'Marcel Streef','Anthony Cheung',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423823,'Tim van der Zanden','OC Chan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423823,'Tim van der Zanden','Hoa Nguyen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423823,'Marcel Streef','OC Chan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423823,'Benjamin Hamburger','Anthony Cheung',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-01-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),423825,'SC Capelle 1','De Loods 1',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423825,'Edwin Heinsman','Hans van Velde',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423825,'Rien Baak','Roeland Melief',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423825,'Rene Boers','Alexander van den Doel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423825,'Edwin Heinsman','Roeland Melief',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423825,'Rien Baak','Alexander van den Doel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423825,'Rene Boers','Hans van Velde',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423825,'Rene Boers','Roeland Melief',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423825,'Rien Baak','Hans van Velde',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423825,'Edwin Heinsman','Alexander van den Doel',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-01-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),423827,'Blaak','Pompadour 2',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423827,'Donny van Oosterhout','Corné Kuijpers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423827,'Tim van der Zanden','Niki Lin',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423827,'Marcel Streef','Patrick Tijssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423827,'Donny van Oosterhout','Niki Lin',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423827,'Tim van der Zanden','Patrick Tijssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423827,'Marcel Streef','Corné Kuijpers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423827,'Marcel Streef','Niki Lin',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423827,'Tim van der Zanden','Corné Kuijpers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423827,'Donny van Oosterhout','Patrick Tijssen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-02-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),423829,'Thurston Snooker 1','Pompadour 2',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423829,'Huidji See','Maurice Rijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423829,'Raymond Fabrie','Patrick Tijssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423829,'Anthony Cheung','Tim De Ruyter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423829,'Huidji See','Patrick Tijssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423829,'Raymond Fabrie','Tim De Ruyter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423829,'Anthony Cheung','Maurice Rijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423829,'Anthony Cheung','Patrick Tijssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423829,'Raymond Fabrie','Maurice Rijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423829,'Huidji See','Tim De Ruyter',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-02-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),423832,'Back in the Pack 2.0','SC Capelle 1',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423832,'Roel Koks','Fausto Salis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423832,'Willem de Koning','Rien Baak',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423832,'Roel Koks','Rien Baak',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423832,'Willem de Koning','Edwin Heinsman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423832,'Willem de Koning','Fausto Salis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423832,'Roel Koks','Edwin Heinsman',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-03-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),433269,'De Loods 1','Blaak',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433269,'Hans van Velde','Benjamin Hamburger',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433269,'Alexander van den Doel','Tim van der Zanden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433269,'Roeland Melief','Donny van Oosterhout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433269,'Hans van Velde','Tim van der Zanden',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433269,'Alexander van den Doel','Donny van Oosterhout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433269,'Roeland Melief','Benjamin Hamburger',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433269,'Roeland Melief','Tim van der Zanden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433269,'Alexander van den Doel','Benjamin Hamburger',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433269,'Hans van Velde','Donny van Oosterhout',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-03-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),434131,'SC Capelle 1','Zeekant',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434131,'Rien Baak','Jarl Hinfelaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434131,'Rene Boers','Ben Vermeer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434131,'Edwin Heinsman','Raymond Huisman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434131,'Rien Baak','Ben Vermeer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434131,'Rene Boers','Raymond Huisman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434131,'Edwin Heinsman','Jarl Hinfelaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434131,'Edwin Heinsman','Ben Vermeer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434131,'Rene Boers','Jarl Hinfelaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434131,'Rien Baak','Raymond Huisman',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-03-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),423834,'Thurston Snooker 1','Snookerij 0',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423834,'Jimmy Worung','Wim Monfils',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423834,'Raymond Fabrie','Coen Drejer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423834,'Huidji See','Martijn Verzaal',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423834,'Jimmy Worung','Coen Drejer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423834,'Raymond Fabrie','Martijn Verzaal',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423834,'Huidji See','Wim Monfils',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423834,'Huidji See','Coen Drejer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423834,'Raymond Fabrie','Wim Monfils',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423834,'Jimmy Worung','Martijn Verzaal',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-03-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),423835,'Pompadour 2','De Loods 1',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423835,'Michaël Kuijpers','Hans van Velde',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423835,'Niki Lin','Roeland Melief',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423835,'Tim De Ruyter','Alexander van den Doel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423835,'Michaël Kuijpers','Roeland Melief',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423835,'Niki Lin','Alexander van den Doel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423835,'Tim De Ruyter','Hans van Velde',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423835,'Tim De Ruyter','Roeland Melief',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423835,'Niki Lin','Hans van Velde',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423835,'Michaël Kuijpers','Alexander van den Doel',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-03-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),423836,'Blaak','Back in the Pack 2.0',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-03-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),423838,'De Loods 1','Thurston Snooker 1',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-03-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),423839,'Zeekant','Blaak',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423839,'Jarl Hinfelaar','Donny van Oosterhout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423839,'Marcel Scholtes','Tim van der Zanden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423839,'Maurice Kempeneers','Benjamin Hamburger',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423839,'Jarl Hinfelaar','Tim van der Zanden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423839,'Marcel Scholtes','Benjamin Hamburger',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423839,'Maurice Kempeneers','Donny van Oosterhout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423839,'Maurice Kempeneers','Tim van der Zanden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423839,'Marcel Scholtes','Donny van Oosterhout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423839,'Jarl Hinfelaar','Benjamin Hamburger',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-04-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),423843,'Thurston Snooker 1','Back in the Pack 2.0',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423843,'OC Chan','Willem de Koning',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423843,'Jimmy Worung','Roel Koks',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423843,'OC Chan','Roel Koks',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423843,'Jimmy Worung','Leon van de Laak',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423843,'Jimmy Worung','Willem de Koning',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423843,'OC Chan','Leon van de Laak',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-04-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),423844,'Pompadour 2','Zeekant',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-04-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),423846,'De Loods 1','Snookerij 0',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423846,'Hans van Velde','Björn Matheijssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423846,'Alexander van den Doel','Wim Monfils',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423846,'Roeland Melief','Martijn Verzaal',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423846,'Hans van Velde','Wim Monfils',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423846,'Alexander van den Doel','Martijn Verzaal',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423846,'Roeland Melief','Björn Matheijssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423846,'Roeland Melief','Wim Monfils',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423846,'Alexander van den Doel','Björn Matheijssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423846,'Hans van Velde','Martijn Verzaal',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-04-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),423850,'Back in the Pack 2.0','De Loods 1',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423850,'Willem de Koning','Hans van Velde',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423850,'Roel Koks','Roeland Melief',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423850,'Leon van de Laak','Alexander van den Doel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423850,'Willem de Koning','Roeland Melief',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423850,'Roel Koks','Alexander van den Doel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423850,'Leon van de Laak','Hans van Velde',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423850,'Leon van de Laak','Roeland Melief',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423850,'Roel Koks','Hans van Velde',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423850,'Willem de Koning','Alexander van den Doel',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-04-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),423852,'Snookerij 0','SC Capelle 1',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('28-04-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),434780,'Zeekant','Thurston Snooker 1',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434780,'Jarl Hinfelaar','Anthony Cheung',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434780,'Ben Vermeer','Hugo Leung',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434780,'Raymond Huisman','Raymond Fabrie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434780,'Jarl Hinfelaar','Hugo Leung',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434780,'Ben Vermeer','Raymond Fabrie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434780,'Raymond Huisman','Anthony Cheung',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434780,'Raymond Huisman','Hugo Leung',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434780,'Ben Vermeer','Anthony Cheung',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434780,'Jarl Hinfelaar','Raymond Fabrie',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('01-05-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),434601,'Back in the Pack 2.0','Pompadour 2',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434601,'Willem de Koning','Corné Kuijpers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434601,'Roel Koks','Michaël Kuijpers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434601,'Willem de Koning','Michaël Kuijpers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434601,'Roel Koks','Niki Lin',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434601,'Roel Koks','Corné Kuijpers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434601,'Willem de Koning','Niki Lin',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-05-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),423855,'Blaak','SC Capelle 1',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423855,'Benjamin Hamburger','Edwin Heinsman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423855,'Tim van der Zanden','Edwin Heinsman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423855,'Donny van Oosterhout','Edwin Heinsman',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-05-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),423856,'De Loods 1','Zeekant',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423856,'Alexander van den Doel','Jarl Hinfelaar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423856,'Hans van Velde','Marcel Scholtes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423856,'Roeland Melief','Ben Vermeer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423856,'Alexander van den Doel','Marcel Scholtes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423856,'Hans van Velde','Ben Vermeer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423856,'Roeland Melief','Jarl Hinfelaar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423856,'Roeland Melief','Marcel Scholtes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423856,'Hans van Velde','Jarl Hinfelaar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423856,'Alexander van den Doel','Ben Vermeer',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-05-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),423857,'Back in the Pack 2.0','Snookerij 0',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423857,'Roel Koks','Björn Matheijssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423857,'Peter Bertens','Martijn Verzaal',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423857,'Willem de Koning','Wim Monfils',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423857,'Roel Koks','Martijn Verzaal',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423857,'Peter Bertens','Wim Monfils',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423857,'Willem de Koning','Björn Matheijssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423857,'Willem de Koning','Martijn Verzaal',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423857,'Peter Bertens','Björn Matheijssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423857,'Roel Koks','Wim Monfils',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-05-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),423859,'Zeekant','Back in the Pack 2.0',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423859,'Ben Vermeer','Peter Bertens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423859,'Jarl Hinfelaar','Willem de Koning',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423859,'Raymond Huisman','Leon van de Laak',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423859,'Ben Vermeer','Willem de Koning',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423859,'Jarl Hinfelaar','Leon van de Laak',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423859,'Raymond Huisman','Peter Bertens',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423859,'Raymond Huisman','Willem de Koning',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423859,'Jarl Hinfelaar','Peter Bertens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(423859,'Ben Vermeer','Leon van de Laak',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-05-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),423862,'Snookerij 0','Blaak',8,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('26-05-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),423863,'Thurston Snooker 1','SC Capelle 1',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('29-05-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),435085,'SC Capelle 1','Pompadour 2',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-06-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),435194,'Pompadour 2','Blaak',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-06-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse B' and ssn_id like '2013%'),435113,'Zeekant','Snookerij 0',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435113,'Jarl Hinfelaar','Coen Drejer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435113,'Ben Vermeer','Martijn Verzaal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435113,'Raymond Huisman','Wim Monfils',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435113,'Jarl Hinfelaar','Martijn Verzaal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435113,'Ben Vermeer','Wim Monfils',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435113,'Raymond Huisman','Coen Drejer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435113,'Raymond Huisman','Martijn Verzaal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435113,'Ben Vermeer','Coen Drejer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435113,'Jarl Hinfelaar','Wim Monfils',0,1);
