delete from cm_match_details where game_id in (select game_id from cm_matches where cpn_id = (select id from cm_competitions where name = 'Hoofdklasse poule 3' and ssn_id like '2014%'));
delete from cm_matches where cpn_id = (select id from cm_competitions where name = 'Hoofdklasse poule 3' and ssn_id like '2014%');
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 3' and ssn_id like '2014%'),449139,'Snooker Utrecht I','AVVL',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449139,'Mark Koppert','Sicco Vollema',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449139,'Django den Hartog','Herman van Deutekom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449139,'Pierre Linschoten','Raymond Ruesink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449139,'Mark Koppert','Herman van Deutekom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449139,'Django den Hartog','Raymond Ruesink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449139,'Pierre Linschoten','Sicco Vollema',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449139,'Pierre Linschoten','Herman van Deutekom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449139,'Django den Hartog','Sicco Vollema',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449139,'Mark Koppert','Raymond Ruesink',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 3' and ssn_id like '2014%'),449138,'DE DIEZE 2 / HIAB','Back in the Pack 2.0',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449138,'Juriaan van den Nieuwenhuizen','Luuk Buys',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449138,'Jorick Blokx','Peter Bertens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449138,'Marcel Roza','Willem de Koning',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449138,'Juriaan van den Nieuwenhuizen','Peter Bertens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449138,'Jorick Blokx','Willem de Koning',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449138,'Marcel Roza','Luuk Buys',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449138,'Marcel Roza','Peter Bertens',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449138,'Jorick Blokx','Luuk Buys',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449138,'Juriaan van den Nieuwenhuizen','Willem de Koning',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 3' and ssn_id like '2014%'),449140,'AVVL','DE DIEZE 2 / HIAB',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449140,'Raymond Ruesink','Juriaan van den Nieuwenhuizen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449140,'Herman van Deutekom','Wiljan van Sommeren',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449140,'Sicco Vollema','Jorick Blokx',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449140,'Raymond Ruesink','Wiljan van Sommeren',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449140,'Herman van Deutekom','Jorick Blokx',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449140,'Sicco Vollema','Juriaan van den Nieuwenhuizen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449140,'Sicco Vollema','Wiljan van Sommeren',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449140,'Herman van Deutekom','Juriaan van den Nieuwenhuizen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449140,'Raymond Ruesink','Jorick Blokx',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 3' and ssn_id like '2014%'),449141,'VINK 1','Snooker Utrecht I',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449141,'Hijlko Soepboer','Django den Hartog',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449141,'Wingho Li','Thomas Verheij',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449141,'Erik Kerkhoven','Mark Koppert',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449141,'Hijlko Soepboer','Thomas Verheij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449141,'Wingho Li','Mark Koppert',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449141,'Erik Kerkhoven','Django den Hartog',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449141,'Erik Kerkhoven','Thomas Verheij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449141,'Wingho Li','Django den Hartog',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449141,'Hijlko Soepboer','Mark Koppert',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('25-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 3' and ssn_id like '2014%'),449538,'DE DIEZE 2 / HIAB','VINK 1',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449538,'Mario Veltman','Danny Flendrie',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449538,'Marcel Roza','Jan van Domselaar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449538,'Juriaan van den Nieuwenhuizen','Erik Kerkhoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449538,'Mario Veltman','Jan van Domselaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449538,'Marcel Roza','Erik Kerkhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449538,'Juriaan van den Nieuwenhuizen','Danny Flendrie',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449538,'Juriaan van den Nieuwenhuizen','Jan van Domselaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449538,'Marcel Roza','Danny Flendrie',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449538,'Mario Veltman','Erik Kerkhoven',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('31-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 3' and ssn_id like '2014%'),449144,'Snooker Utrecht I','DE DIEZE 2 / HIAB',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449144,'Thomas Verheij','Jorick Blokx',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449144,'Mark Koppert','Juriaan van den Nieuwenhuizen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449144,'Jasha Kiers','Mario Veltman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449144,'Thomas Verheij','Juriaan van den Nieuwenhuizen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449144,'Mark Koppert','Mario Veltman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449144,'Jasha Kiers','Jorick Blokx',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449144,'Jasha Kiers','Juriaan van den Nieuwenhuizen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449144,'Mark Koppert','Jorick Blokx',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449144,'Thomas Verheij','Mario Veltman',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 3' and ssn_id like '2014%'),449147,'Back in the Pack 2.0','Snooker Utrecht I',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449147,'Roel Koks','Mark Koppert',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449147,'Luuk Buys','Thomas Verheij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449147,'Willem de Koning','Django den Hartog',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449147,'Roel Koks','Thomas Verheij',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449147,'Luuk Buys','Django den Hartog',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449147,'Willem de Koning','Mark Koppert',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449147,'Willem de Koning','Thomas Verheij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449147,'Luuk Buys','Mark Koppert',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449147,'Roel Koks','Django den Hartog',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 3' and ssn_id like '2014%'),449148,'AVVL','Snooker Utrecht I',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449148,'Raymond Ruesink','Michel de Sain',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449148,'Sicco Vollema','Django den Hartog',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449148,'Herman van Deutekom','Mark Koppert',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449148,'Raymond Ruesink','Django den Hartog',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449148,'Sicco Vollema','Mark Koppert',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449148,'Herman van Deutekom','Michel de Sain',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449148,'Herman van Deutekom','Django den Hartog',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449148,'Sicco Vollema','Michel de Sain',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449148,'Raymond Ruesink','Mark Koppert',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 3' and ssn_id like '2014%'),449149,'Back in the Pack 2.0','DE DIEZE 2 / HIAB',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449149,'Willem de Koning','Jorick Blokx',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449149,'Luuk Buys','Wiljan van Sommeren',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449149,'Peter Bertens','Juriaan van den Nieuwenhuizen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449149,'Willem de Koning','Wiljan van Sommeren',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449149,'Luuk Buys','Juriaan van den Nieuwenhuizen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449149,'Peter Bertens','Jorick Blokx',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449149,'Peter Bertens','Wiljan van Sommeren',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449149,'Luuk Buys','Jorick Blokx',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449149,'Willem de Koning','Juriaan van den Nieuwenhuizen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 3' and ssn_id like '2014%'),449631,'Back in the Pack 2.0','AVVL',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449631,'Willem de Koning','Sicco Vollema',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449631,'Roel Koks','Herman van Deutekom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449631,'Peter Bertens','Raymond Ruesink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449631,'Willem de Koning','Herman van Deutekom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449631,'Roel Koks','Raymond Ruesink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449631,'Peter Bertens','Sicco Vollema',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449631,'Peter Bertens','Herman van Deutekom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449631,'Roel Koks','Sicco Vollema',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449631,'Willem de Koning','Raymond Ruesink',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 3' and ssn_id like '2014%'),449723,'Snooker Utrecht I','VINK 1',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449723,'Mark Koppert','Peter Kok',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449723,'Django den Hartog','Jan van Domselaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449723,'Pierre Linschoten','Wingho Li',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449723,'Mark Koppert','Jan van Domselaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449723,'Django den Hartog','Wingho Li',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449723,'Pierre Linschoten','Peter Kok',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449723,'Pierre Linschoten','Jan van Domselaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449723,'Django den Hartog','Peter Kok',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449723,'Mark Koppert','Wingho Li',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('28-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 3' and ssn_id like '2014%'),449637,'AVVL','VINK 1',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449637,'Raymond Ruesink','Hijlko Soepboer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449637,'Sicco Vollema','Erik Kerkhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449637,'Herman van Deutekom','Peter Kok',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449637,'Raymond Ruesink','Erik Kerkhoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449637,'Sicco Vollema','Peter Kok',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449637,'Herman van Deutekom','Hijlko Soepboer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449637,'Herman van Deutekom','Erik Kerkhoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449637,'Sicco Vollema','Hijlko Soepboer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449637,'Raymond Ruesink','Peter Kok',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('30-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 3' and ssn_id like '2014%'),449710,'VINK 1','Back in the Pack 2.0',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449710,'Hijlko Soepboer','Roel Koks',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449710,'Erik Kerkhoven','Willem de Koning',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449710,'Peter Kok','Luuk Buys',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449710,'Hijlko Soepboer','Willem de Koning',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449710,'Erik Kerkhoven','Luuk Buys',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449710,'Peter Kok','Roel Koks',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449710,'Peter Kok','Willem de Koning',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449710,'Erik Kerkhoven','Roel Koks',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449710,'Hijlko Soepboer','Luuk Buys',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 3' and ssn_id like '2014%'),449150,'DE DIEZE 2 / HIAB','AVVL',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449150,'Wiljan van Sommeren','Raymond Ruesink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449150,'Jorick Blokx','Herman van Deutekom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449150,'Juriaan van den Nieuwenhuizen','Sicco Vollema',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449150,'Wiljan van Sommeren','Herman van Deutekom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449150,'Jorick Blokx','Sicco Vollema',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449150,'Juriaan van den Nieuwenhuizen','Raymond Ruesink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449150,'Juriaan van den Nieuwenhuizen','Herman van Deutekom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449150,'Jorick Blokx','Raymond Ruesink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449150,'Wiljan van Sommeren','Sicco Vollema',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 3' and ssn_id like '2014%'),449596,'VINK 1','DE DIEZE 2 / HIAB',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449596,'Erik Kerkhoven','Jorick Blokx',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449596,'Hijlko Soepboer','Juriaan van den Nieuwenhuizen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449596,'Jan van Domselaar','Mario Veltman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449596,'Erik Kerkhoven','Juriaan van den Nieuwenhuizen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449596,'Hijlko Soepboer','Mario Veltman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449596,'Jan van Domselaar','Jorick Blokx',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449596,'Jan van Domselaar','Juriaan van den Nieuwenhuizen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449596,'Hijlko Soepboer','Jorick Blokx',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449596,'Erik Kerkhoven','Mario Veltman',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 3' and ssn_id like '2014%'),449152,'AVVL','Back in the Pack 2.0',0,9);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449152,'Raymond Ruesink','Willem de Koning',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449152,'Sicco Vollema','Roel Koks',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449152,'Herman van Deutekom','Luuk Buys',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449152,'Raymond Ruesink','Roel Koks',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449152,'Sicco Vollema','Luuk Buys',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449152,'Herman van Deutekom','Willem de Koning',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449152,'Herman van Deutekom','Roel Koks',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449152,'Sicco Vollema','Willem de Koning',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449152,'Raymond Ruesink','Luuk Buys',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 3' and ssn_id like '2014%'),449154,'DE DIEZE 2 / HIAB','Snooker Utrecht I',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449154,'Marcel Roza','Django den Hartog',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449154,'Mario Veltman','Michel de Sain',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449154,'Juriaan van den Nieuwenhuizen','Mark Koppert',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449154,'Marcel Roza','Michel de Sain',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449154,'Mario Veltman','Mark Koppert',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449154,'Juriaan van den Nieuwenhuizen','Django den Hartog',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449154,'Juriaan van den Nieuwenhuizen','Michel de Sain',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449154,'Mario Veltman','Django den Hartog',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449154,'Marcel Roza','Mark Koppert',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 3' and ssn_id like '2014%'),449155,'Back in the Pack 2.0','VINK 1',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449155,'Luuk Buys','Erik Kerkhoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449155,'Willem de Koning','Hijlko Soepboer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449155,'Roel Koks','Danny Flendrie',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449155,'Luuk Buys','Hijlko Soepboer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449155,'Willem de Koning','Danny Flendrie',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449155,'Roel Koks','Erik Kerkhoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449155,'Roel Koks','Hijlko Soepboer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449155,'Willem de Koning','Erik Kerkhoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449155,'Luuk Buys','Danny Flendrie',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('26-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 3' and ssn_id like '2014%'),449156,'Snooker Utrecht I','Back in the Pack 2.0',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449156,'Thomas Verheij','Willem de Koning',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449156,'Django den Hartog','Luuk Buys',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449156,'Mark Koppert','Leon van de Laak',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449156,'Thomas Verheij','Luuk Buys',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449156,'Django den Hartog','Leon van de Laak',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449156,'Mark Koppert','Willem de Koning',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449156,'Mark Koppert','Luuk Buys',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449156,'Django den Hartog','Willem de Koning',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449156,'Thomas Verheij','Leon van de Laak',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('28-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 3' and ssn_id like '2014%'),449157,'VINK 1','AVVL',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449157,'Wingho Li','Sicco Vollema',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449157,'Hijlko Soepboer','Herman van Deutekom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449157,'Danny Flendrie','Raymond Ruesink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449157,'Wingho Li','Herman van Deutekom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449157,'Hijlko Soepboer','Raymond Ruesink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449157,'Danny Flendrie','Sicco Vollema',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449157,'Danny Flendrie','Herman van Deutekom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449157,'Hijlko Soepboer','Sicco Vollema',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449157,'Wingho Li','Raymond Ruesink',0,1);
