delete from cm_match_details where game_id in (select game_id from cm_matches where cpn_id = (select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2011%'));
delete from cm_matches where cpn_id = (select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2011%');
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-09-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2011%'),293353,'BREAKTHROUGH','Snooker Academy',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293353,'Simon Reuter','Jan Willem Kweldam',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293353,'Lennert Duijn','Ron Fortgens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293353,'George Wijte','Rob Admiraal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293353,'Simon Reuter','Ron Fortgens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293353,'Lennert Duijn','Rob Admiraal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293353,'George Wijte','Jan Willem Kweldam',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293353,'George Wijte','Ron Fortgens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293353,'Lennert Duijn','Jan Willem Kweldam',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293353,'Simon Reuter','Rob Admiraal',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-09-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2011%'),301254,'Level Two','HIPPONUV',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('29-09-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2011%'),293358,'PURMEREND 1','Alkmaar 4',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293358,'Marco Haverkotte','Rick van Houten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293358,'Rick Mulder','Eric van der Zwan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293358,'Patrick Tijssen','Guy van den Ende',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293358,'Marco Haverkotte','Eric van der Zwan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293358,'Rick Mulder','Guy van den Ende',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293358,'Patrick Tijssen','Rick van Houten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293358,'Patrick Tijssen','Eric van der Zwan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293358,'Rick Mulder','Rick van Houten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293358,'Marco Haverkotte','Guy van den Ende',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('29-09-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2011%'),293359,'FINAL TOUCH 1','BREAKTHROUGH',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293359,'Dean Mitchell','Henk van Hooff',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293359,'Albert Pronk','Michel Grapendaal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293359,'Willem Swager','Lennert Duijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293359,'Dean Mitchell','Michel Grapendaal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293359,'Albert Pronk','Lennert Duijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293359,'Willem Swager','Henk van Hooff',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293359,'Willem Swager','Michel Grapendaal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293359,'Albert Pronk','Henk van Hooff',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293359,'Dean Mitchell','Lennert Duijn',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-10-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2011%'),293361,'Snooker Academy','FINAL TOUCH 1',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293361,'Jan Willem Kweldam','David Lucieer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293361,'Ron Fortgens','Willem Swager',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293361,'Rob Admiraal','Wessel Tit',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293361,'Jan Willem Kweldam','Willem Swager',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293361,'Ron Fortgens','Wessel Tit',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293361,'Rob Admiraal','David Lucieer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293361,'Rob Admiraal','Willem Swager',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293361,'Ron Fortgens','David Lucieer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293361,'Jan Willem Kweldam','Wessel Tit',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-10-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2011%'),293362,'BREAKTHROUGH','HIPPONUV',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293362,'Henk van Hooff','Marco Eisinga',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293362,'Marco Glorie','Jeremy Gaasenbeek',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293362,'George Wijte','Martijn Lesterhuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293362,'Henk van Hooff','Jeremy Gaasenbeek',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293362,'Marco Glorie','Martijn Lesterhuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293362,'George Wijte','Marco Eisinga',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293362,'George Wijte','Jeremy Gaasenbeek',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293362,'Marco Glorie','Marco Eisinga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293362,'Henk van Hooff','Martijn Lesterhuis',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-10-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2011%'),293363,'Level Two','PURMEREND 1',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293363,'Remco van Dortmond','Rick Mulder',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293363,'Steven Wong','Louis Leijdekker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293363,'Jimmy Cai','Patrick Tijssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293363,'Remco van Dortmond','Louis Leijdekker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293363,'Steven Wong','Patrick Tijssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293363,'Jimmy Cai','Rick Mulder',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293363,'Jimmy Cai','Louis Leijdekker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293363,'Steven Wong','Rick Mulder',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293363,'Remco van Dortmond','Patrick Tijssen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('31-10-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2011%'),293365,'HIPPONUV','Snooker Academy',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293365,'Martijn Lesterhuis','Rob Admiraal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293365,'Ruud de Wit','Ron Fortgens',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293365,'Naut Bruns','Jan Willem Kweldam',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293365,'Martijn Lesterhuis','Ron Fortgens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293365,'Ruud de Wit','Jan Willem Kweldam',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293365,'Naut Bruns','Rob Admiraal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293365,'Naut Bruns','Ron Fortgens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293365,'Ruud de Wit','Rob Admiraal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293365,'Martijn Lesterhuis','Jan Willem Kweldam',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2011%'),293366,'Alkmaar 4','Level Two',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293366,'Sjoerd Blondeel Timmerman','Jimmy Cai',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293366,'Guy van den Ende','Erwin van Faassen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293366,'Eric van der Zwan','Remco van Dortmond',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293366,'Sjoerd Blondeel Timmerman','Erwin van Faassen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293366,'Guy van den Ende','Remco van Dortmond',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293366,'Eric van der Zwan','Jimmy Cai',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293366,'Eric van der Zwan','Erwin van Faassen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293366,'Guy van den Ende','Jimmy Cai',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293366,'Sjoerd Blondeel Timmerman','Remco van Dortmond',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2011%'),293370,'BREAKTHROUGH','PURMEREND 1',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293370,'Raymond Selhorst','Marco Haverkotte',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293370,'Henk van Hooff','Louis Leijdekker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293370,'Marco Glorie','Patrick Tijssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293370,'Raymond Selhorst','Louis Leijdekker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293370,'Henk van Hooff','Patrick Tijssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293370,'Marco Glorie','Marco Haverkotte',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293370,'Marco Glorie','Louis Leijdekker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293370,'Henk van Hooff','Marco Haverkotte',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293370,'Raymond Selhorst','Patrick Tijssen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2011%'),293371,'FINAL TOUCH 1','HIPPONUV',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293371,'David Lucieer','Ruud de Wit',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293371,'Willem Swager','Martijn Lesterhuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293371,'Albert Pronk','Jeremy Gaasenbeek',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293371,'David Lucieer','Martijn Lesterhuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293371,'Willem Swager','Jeremy Gaasenbeek',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293371,'Albert Pronk','Ruud de Wit',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293371,'Albert Pronk','Martijn Lesterhuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293371,'Willem Swager','Ruud de Wit',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293371,'David Lucieer','Jeremy Gaasenbeek',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2011%'),293374,'Alkmaar 4','BREAKTHROUGH',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293374,'Sjoerd Blondeel Timmerman','Simon Reuter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293374,'Guy van den Ende','George Wijte',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293374,'Rick van Houten','Raymond Selhorst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293374,'Sjoerd Blondeel Timmerman','George Wijte',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293374,'Guy van den Ende','Raymond Selhorst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293374,'Rick van Houten','Simon Reuter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293374,'Rick van Houten','George Wijte',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293374,'Guy van den Ende','Simon Reuter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293374,'Sjoerd Blondeel Timmerman','Raymond Selhorst',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2011%'),293375,'PURMEREND 1','Snooker Academy',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293375,'Louis Leijdekker','Rob Admiraal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293375,'Marco Haverkotte','Ron Fortgens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293375,'Rick Mulder','Jan Willem Kweldam',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293375,'Louis Leijdekker','Ron Fortgens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293375,'Marco Haverkotte','Jan Willem Kweldam',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293375,'Rick Mulder','Rob Admiraal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293375,'Rick Mulder','Ron Fortgens',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293375,'Marco Haverkotte','Rob Admiraal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293375,'Louis Leijdekker','Jan Willem Kweldam',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-12-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2011%'),293377,'Snooker Academy','Alkmaar 4',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293377,'Ron Fortgens','Rick van Houten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293377,'Rob Admiraal','Eric van der Zwan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293377,'Jan Willem Kweldam','Sjoerd Blondeel Timmerman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293377,'Ron Fortgens','Eric van der Zwan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293377,'Rob Admiraal','Sjoerd Blondeel Timmerman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293377,'Jan Willem Kweldam','Rick van Houten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293377,'Jan Willem Kweldam','Eric van der Zwan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293377,'Rob Admiraal','Rick van Houten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293377,'Ron Fortgens','Sjoerd Blondeel Timmerman',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-12-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2011%'),293378,'BREAKTHROUGH','Level Two',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293378,'Michel Grapendaal','Chi Chui',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293378,'Lennert Duijn','Steven Wong',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293378,'Henk van Hooff','Jimmy Cai',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293378,'Michel Grapendaal','Steven Wong',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293378,'Lennert Duijn','Jimmy Cai',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293378,'Henk van Hooff','Chi Chui',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293378,'Henk van Hooff','Steven Wong',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293378,'Lennert Duijn','Chi Chui',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293378,'Michel Grapendaal','Jimmy Cai',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-12-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2011%'),293379,'FINAL TOUCH 1','PURMEREND 1',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293379,'David Lucieer','Patrick Tijssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293379,'Wessel Tit','Marco Haverkotte',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293379,'Arnoud de la Mar','Rick Mulder',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293379,'David Lucieer','Marco Haverkotte',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293379,'Wessel Tit','Rick Mulder',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293379,'Arnoud de la Mar','Patrick Tijssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293379,'Arnoud de la Mar','Marco Haverkotte',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293379,'Wessel Tit','Patrick Tijssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293379,'David Lucieer','Rick Mulder',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-12-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2011%'),293381,'Level Two','Snooker Academy',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293381,'Erwin van Faassen','Rob Admiraal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293381,'Remco van Dortmond','Ron Fortgens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293381,'Steven Wong','Jan Willem Kweldam',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293381,'Erwin van Faassen','Ron Fortgens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293381,'Remco van Dortmond','Jan Willem Kweldam',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293381,'Steven Wong','Rob Admiraal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293381,'Steven Wong','Ron Fortgens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293381,'Remco van Dortmond','Rob Admiraal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293381,'Erwin van Faassen','Jan Willem Kweldam',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2011%'),308098,'PURMEREND 1','HIPPONUV',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2011%'),293384,'BREAKTHROUGH','FINAL TOUCH 1',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293384,'Raymond Selhorst','Albert Pronk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293384,'Henk van Hooff','Willem Swager',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293384,'Marco Glorie','Dean Mitchell',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293384,'Raymond Selhorst','Willem Swager',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293384,'Henk van Hooff','Dean Mitchell',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293384,'Marco Glorie','Albert Pronk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293384,'Marco Glorie','Willem Swager',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293384,'Henk van Hooff','Albert Pronk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293384,'Raymond Selhorst','Dean Mitchell',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2011%'),293386,'HIPPONUV','Alkmaar 4',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293386,'Jeremy Gaasenbeek','Guy van den Ende',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293386,'Martijn Lesterhuis','Rick van Houten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293386,'Marco Eisinga','Sjoerd Blondeel Timmerman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293386,'Jeremy Gaasenbeek','Rick van Houten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293386,'Martijn Lesterhuis','Sjoerd Blondeel Timmerman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293386,'Marco Eisinga','Guy van den Ende',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293386,'Marco Eisinga','Rick van Houten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293386,'Martijn Lesterhuis','Guy van den Ende',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293386,'Jeremy Gaasenbeek','Sjoerd Blondeel Timmerman',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2011%'),293388,'FINAL TOUCH 1','Level Two',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293388,'Arnoud de la Mar','Remco van Dortmond',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293388,'David Lucieer','Jimmy Cai',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293388,'Wessel Tit','Erwin van Faassen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293388,'Arnoud de la Mar','Jimmy Cai',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293388,'David Lucieer','Erwin van Faassen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293388,'Wessel Tit','Remco van Dortmond',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293388,'Wessel Tit','Jimmy Cai',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293388,'David Lucieer','Remco van Dortmond',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293388,'Arnoud de la Mar','Erwin van Faassen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-02-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2011%'),293395,'Alkmaar 4','PURMEREND 1',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-02-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2011%'),293397,'HIPPONUV','BREAKTHROUGH',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293397,'Martijn Lesterhuis','Simon Reuter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293397,'Jan Willem Koppenberg','Lennert Duijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293397,'Marco Eisinga','Michel Grapendaal',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293397,'Martijn Lesterhuis','Lennert Duijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293397,'Jan Willem Koppenberg','Michel Grapendaal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293397,'Marco Eisinga','Simon Reuter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293397,'Marco Eisinga','Lennert Duijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293397,'Jan Willem Koppenberg','Simon Reuter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293397,'Martijn Lesterhuis','Michel Grapendaal',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-02-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2011%'),293398,'PURMEREND 1','Level Two',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('28-02-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2011%'),308793,'Snooker Academy','BREAKTHROUGH',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308793,'Ron Fortgens','Raymond Selhorst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308793,'Rob Admiraal','Henk van Hooff',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308793,'Jan Willem Kweldam','Marco Glorie',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308793,'Ron Fortgens','Henk van Hooff',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308793,'Rob Admiraal','Marco Glorie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308793,'Jan Willem Kweldam','Raymond Selhorst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308793,'Jan Willem Kweldam','Henk van Hooff',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308793,'Rob Admiraal','Raymond Selhorst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308793,'Ron Fortgens','Marco Glorie',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('01-03-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2011%'),308794,'FINAL TOUCH 1','Snooker Academy',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308794,'Willem Swager','Ron Fortgens',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308794,'Albert Pronk','Jan Willem Kweldam',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308794,'David Lucieer','Rob Admiraal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308794,'Willem Swager','Jan Willem Kweldam',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308794,'Albert Pronk','Rob Admiraal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308794,'David Lucieer','Ron Fortgens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308794,'David Lucieer','Jan Willem Kweldam',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308794,'Albert Pronk','Ron Fortgens',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308794,'Willem Swager','Rob Admiraal',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-03-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2011%'),308856,'HIPPONUV','Level Two',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-03-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2011%'),293403,'Level Two','Alkmaar 4',9,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293403,'Jimmy Cai','Guy van den Ende',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293403,'Erwin van Faassen','Eric van der Zwan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293403,'Steven Wong','Sjoerd Blondeel Timmerman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293403,'Jimmy Cai','Eric van der Zwan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293403,'Erwin van Faassen','Sjoerd Blondeel Timmerman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293403,'Steven Wong','Guy van den Ende',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293403,'Steven Wong','Eric van der Zwan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293403,'Erwin van Faassen','Guy van den Ende',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293403,'Jimmy Cai','Sjoerd Blondeel Timmerman',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-03-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2011%'),308983,'Alkmaar 4','FINAL TOUCH 1',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('26-03-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2011%'),293405,'HIPPONUV','FINAL TOUCH 1',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293405,'Martijn Lesterhuis','David Lucieer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293405,'Jan Willem Koppenberg','Wessel Tit',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293405,'Naut Bruns','Arnoud de la Mar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293405,'Martijn Lesterhuis','Wessel Tit',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293405,'Jan Willem Koppenberg','Arnoud de la Mar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293405,'Naut Bruns','David Lucieer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293405,'Naut Bruns','Wessel Tit',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293405,'Jan Willem Koppenberg','David Lucieer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293405,'Martijn Lesterhuis','Arnoud de la Mar',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('29-03-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2011%'),293407,'PURMEREND 1','BREAKTHROUGH',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293407,'Marco Haverkotte','Michel Grapendaal',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293407,'Rick Mulder','Lennert Duijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293407,'Louis Leijdekker','George Wijte',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293407,'Marco Haverkotte','Lennert Duijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293407,'Rick Mulder','George Wijte',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293407,'Louis Leijdekker','Michel Grapendaal',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293407,'Louis Leijdekker','Lennert Duijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293407,'Rick Mulder','Michel Grapendaal',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293407,'Marco Haverkotte','George Wijte',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-04-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2011%'),293409,'Snooker Academy','PURMEREND 1',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293409,'Jan Willem Kweldam','Patrick Tijssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293409,'Rob Admiraal','Louis Leijdekker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293409,'Ron Fortgens','Marco Haverkotte',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293409,'Jan Willem Kweldam','Louis Leijdekker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293409,'Rob Admiraal','Marco Haverkotte',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293409,'Ron Fortgens','Patrick Tijssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293409,'Ron Fortgens','Louis Leijdekker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293409,'Rob Admiraal','Patrick Tijssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293409,'Jan Willem Kweldam','Marco Haverkotte',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-04-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2011%'),293410,'BREAKTHROUGH','Alkmaar 4',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293410,'Simon Reuter','Guy van den Ende',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293410,'Henk van Hooff','Rick van Houten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293410,'Marco Glorie','Sjoerd Blondeel Timmerman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293410,'Simon Reuter','Rick van Houten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293410,'Henk van Hooff','Sjoerd Blondeel Timmerman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293410,'Marco Glorie','Guy van den Ende',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293410,'Marco Glorie','Rick van Houten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293410,'Henk van Hooff','Guy van den Ende',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293410,'Simon Reuter','Sjoerd Blondeel Timmerman',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-04-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2011%'),293413,'Level Two','BREAKTHROUGH',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293413,'Jimmy Cai','Henk van Hooff',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293413,'Remco van Dortmond','Michel Grapendaal',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293413,'Erwin van Faassen','Michel Grapendaal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293413,'Remco van Dortmond','Henk van Hooff',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293413,'Erwin van Faassen','Henk van Hooff',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293413,'Jimmy Cai','Michel Grapendaal',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-04-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2011%'),293414,'Alkmaar 4','Snooker Academy',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293414,'Rick van Houten','Ron Fortgens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293414,'Sjoerd Blondeel Timmerman','Rob Admiraal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293414,'Eric van der Zwan','Jan Willem Kweldam',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293414,'Rick van Houten','Rob Admiraal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293414,'Sjoerd Blondeel Timmerman','Jan Willem Kweldam',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293414,'Eric van der Zwan','Ron Fortgens',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293414,'Eric van der Zwan','Rob Admiraal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293414,'Sjoerd Blondeel Timmerman','Ron Fortgens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293414,'Rick van Houten','Jan Willem Kweldam',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2011%'),309577,'PURMEREND 1','FINAL TOUCH 1',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309577,'Marco Haverkotte','Wessel Tit',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309577,'Rick Mulder','David Lucieer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309577,'Patrick Tijssen','Arnoud de la Mar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309577,'Marco Haverkotte','David Lucieer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309577,'Rick Mulder','Arnoud de la Mar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309577,'Patrick Tijssen','Wessel Tit',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309577,'Patrick Tijssen','David Lucieer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309577,'Rick Mulder','Wessel Tit',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309577,'Marco Haverkotte','Arnoud de la Mar',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2011%'),309443,'Snooker Academy','HIPPONUV',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309443,'Rob Admiraal','Martijn Lesterhuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309443,'Ron Fortgens','Marco Eisinga',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309443,'Jan Willem Kweldam','Jan Willem Koppenberg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309443,'Rob Admiraal','Marco Eisinga',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309443,'Ron Fortgens','Jan Willem Koppenberg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309443,'Jan Willem Kweldam','Martijn Lesterhuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309443,'Jan Willem Kweldam','Marco Eisinga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309443,'Ron Fortgens','Martijn Lesterhuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309443,'Rob Admiraal','Jan Willem Koppenberg',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2011%'),293416,'HIPPONUV','PURMEREND 1',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293416,'Marco Eisinga','Rick Mulder',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293416,'Martijn Lesterhuis','Patrick Tijssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293416,'Jan Willem Koppenberg','Louis Leijdekker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293416,'Marco Eisinga','Patrick Tijssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293416,'Martijn Lesterhuis','Louis Leijdekker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293416,'Jan Willem Koppenberg','Rick Mulder',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293416,'Jan Willem Koppenberg','Patrick Tijssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293416,'Martijn Lesterhuis','Rick Mulder',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293416,'Marco Eisinga','Louis Leijdekker',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2011%'),293417,'Snooker Academy','Level Two',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293417,'Rob Admiraal','Erwin van Faassen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293417,'Ron Fortgens','Remco van Dortmond',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293417,'Jan Willem Kweldam','Jimmy Cai',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293417,'Rob Admiraal','Remco van Dortmond',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293417,'Ron Fortgens','Jimmy Cai',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293417,'Jan Willem Kweldam','Erwin van Faassen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293417,'Jan Willem Kweldam','Remco van Dortmond',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293417,'Ron Fortgens','Erwin van Faassen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293417,'Rob Admiraal','Jimmy Cai',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2011%'),293421,'Level Two','FINAL TOUCH 1',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2011%'),293422,'Alkmaar 4','HIPPONUV',3,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('31-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 1' and ssn_id like '2011%'),309936,'FINAL TOUCH 1','Alkmaar 4',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309936,'Arnoud de la Mar','Guy van den Ende',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309936,'Dean Mitchell','Sjoerd Blondeel Timmerman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309936,'Albert Pronk','Eric van der Zwan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309936,'Arnoud de la Mar','Sjoerd Blondeel Timmerman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309936,'Dean Mitchell','Eric van der Zwan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309936,'Albert Pronk','Guy van den Ende',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309936,'Albert Pronk','Sjoerd Blondeel Timmerman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309936,'Dean Mitchell','Guy van den Ende',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309936,'Arnoud de la Mar','Eric van der Zwan',0,1);
