delete from cm_match_details where game_id in (select game_id from cm_matches where cpn_id = (select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'));
delete from cm_matches where cpn_id = (select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%');
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-09-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350417,'DUH BALLUH','VLAARDINGEN 1',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350417,'Bas Hendrickx','Martin Hazewinkel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350417,'Luuk Buys','René Tinge',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350417,'Jurgen Coolen','René Tinge',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350417,'Luuk Buys','Martin Hazewinkel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350417,'Jurgen Coolen','Martin Hazewinkel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350417,'Bas Hendrickx','René Tinge',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-09-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350418,'Zeekant par 3','SC Capelle 1',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350418,'Marcel Scholtes','Fausto Salis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350418,'Ron Schul','Rien Baak',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350418,'Raymond Huisman','Edwin Heinsman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350418,'Marcel Scholtes','Rien Baak',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350418,'Ron Schul','Edwin Heinsman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350418,'Raymond Huisman','Fausto Salis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350418,'Raymond Huisman','Rien Baak',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350418,'Ron Schul','Fausto Salis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350418,'Marcel Scholtes','Edwin Heinsman',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-09-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350419,'Snookerij 0','Back in the Pack 2.0',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350419,'Job Bavelaar','Willem de Koning',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350419,'Coen Drejer','Peter Bertens',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350419,'Björn Matheijssen','Leon van de Laak',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350419,'Job Bavelaar','Peter Bertens',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350419,'Coen Drejer','Leon van de Laak',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350419,'Björn Matheijssen','Willem de Koning',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350419,'Björn Matheijssen','Peter Bertens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350419,'Coen Drejer','Willem de Koning',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350419,'Job Bavelaar','Leon van de Laak',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-09-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),359099,'VLAARDINGEN 1','Zeekantje',9,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(359099,'Marco de Graaff','Jarl Hinfelaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(359099,'Bo Speyer','Menno Bussink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(359099,'Marco de Graaff','Menno Bussink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(359099,'Bo Speyer','Fred Jansen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(359099,'Bo Speyer','Jarl Hinfelaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(359099,'Marco de Graaff','Fred Jansen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-09-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350421,'SC Capelle 1','Snookerij 0',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350421,'Fausto Salis','Kevin Vermeiren',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350421,'Edwin Heinsman','Coen Drejer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350421,'Rien Baak','John van de Zwart',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350421,'Fausto Salis','Coen Drejer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350421,'Edwin Heinsman','John van de Zwart',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350421,'Rien Baak','Kevin Vermeiren',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350421,'Rien Baak','Coen Drejer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350421,'Edwin Heinsman','Kevin Vermeiren',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350421,'Fausto Salis','John van de Zwart',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-09-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350422,'Back in the Pack 2.0','DUH BALLUH',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350422,'Willem de Koning','Keesjan Coenraad',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350422,'Leon van de Laak','John van Gorp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350422,'Roel Koks','Luuk Buys',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350422,'Willem de Koning','John van Gorp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350422,'Leon van de Laak','Luuk Buys',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350422,'Roel Koks','Keesjan Coenraad',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350422,'Roel Koks','John van Gorp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350422,'Leon van de Laak','Keesjan Coenraad',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350422,'Willem de Koning','Luuk Buys',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-10-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350425,'Zeekantje','Back in the Pack 2.0',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350425,'Menno Bussink','Peter Bertens',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350425,'Jarl Hinfelaar','Leon van de Laak',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350425,'Jannes Gout','Willem de Koning',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350425,'Menno Bussink','Leon van de Laak',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350425,'Jarl Hinfelaar','Willem de Koning',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350425,'Jannes Gout','Peter Bertens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350425,'Jannes Gout','Leon van de Laak',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350425,'Jarl Hinfelaar','Peter Bertens',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350425,'Menno Bussink','Willem de Koning',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-10-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350426,'DUH BALLUH','SC Capelle 1',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350426,'Bas Hendrickx','Edwin Heinsman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350426,'John van Gorp','Rien Baak',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350426,'Toine Oomens','Fausto Salis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350426,'Bas Hendrickx','Rien Baak',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350426,'John van Gorp','Fausto Salis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350426,'Toine Oomens','Edwin Heinsman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350426,'Toine Oomens','Rien Baak',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350426,'John van Gorp','Edwin Heinsman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350426,'Bas Hendrickx','Fausto Salis',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-10-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350427,'Zeekant par 3','Snookerij 0',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350427,'Marcel Scholtes','Job Bavelaar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350427,'Maurice Kempeneers','Björn Matheijssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350427,'Raymond Huisman','Coen Drejer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350427,'Marcel Scholtes','Björn Matheijssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350427,'Maurice Kempeneers','Coen Drejer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350427,'Raymond Huisman','Job Bavelaar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350427,'Raymond Huisman','Björn Matheijssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350427,'Maurice Kempeneers','Job Bavelaar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350427,'Marcel Scholtes','Coen Drejer',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-10-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350428,'SC Capelle 1','Zeekantje',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350428,'Rien Baak','Jarl Hinfelaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350428,'Edwin Heinsman','Johan Grootens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350428,'Fausto Salis','Menno Bussink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350428,'Rien Baak','Johan Grootens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350428,'Edwin Heinsman','Menno Bussink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350428,'Fausto Salis','Jarl Hinfelaar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350428,'Fausto Salis','Johan Grootens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350428,'Edwin Heinsman','Jarl Hinfelaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350428,'Rien Baak','Menno Bussink',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-10-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350430,'Snookerij 0','DUH BALLUH',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350430,'Kevin Vermeiren','John van Gorp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350430,'John van de Zwart','Luuk Buys',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350430,'Gennaro Cannavacciuolo','Bas Hendrickx',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350430,'Kevin Vermeiren','Luuk Buys',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350430,'John van de Zwart','Bas Hendrickx',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350430,'Gennaro Cannavacciuolo','John van Gorp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350430,'Gennaro Cannavacciuolo','Luuk Buys',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350430,'John van de Zwart','John van Gorp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350430,'Kevin Vermeiren','Bas Hendrickx',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-10-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),361625,'VLAARDINGEN 1','Zeekant par 3',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(361625,'René Tinge','Marcel Scholtes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(361625,'Marco de Graaff','Ben Vermeer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(361625,'René Tinge','Ron Schul',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(361625,'Marco de Graaff','Marcel Scholtes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(361625,'Marco de Graaff','Ron Schul',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(361625,'René Tinge','Ben Vermeer',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-10-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350433,'Zeekantje','Snookerij 0',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350433,'Menno Bussink','Björn Matheijssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350433,'Jarl Hinfelaar','Job Bavelaar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350433,'Fabian Rademaker','Coen Drejer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350433,'Menno Bussink','Job Bavelaar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350433,'Jarl Hinfelaar','Coen Drejer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350433,'Fabian Rademaker','Björn Matheijssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350433,'Fabian Rademaker','Job Bavelaar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350433,'Jarl Hinfelaar','Björn Matheijssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350433,'Menno Bussink','Coen Drejer',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('25-10-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350434,'Zeekant par 3','DUH BALLUH',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-11-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350437,'SC Capelle 1','VLAARDINGEN 1',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350437,'Rien Baak','Marko Reijers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350437,'Fausto Salis','Marco de Graaff',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350437,'Edwin Heinsman','René Tinge',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350437,'Rien Baak','Marco de Graaff',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350437,'Fausto Salis','René Tinge',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350437,'Edwin Heinsman','Marko Reijers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350437,'Edwin Heinsman','Marco de Graaff',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350437,'Fausto Salis','Marko Reijers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350437,'Rien Baak','René Tinge',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-11-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350438,'Back in the Pack 2.0','Zeekant par 3',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350438,'Willem de Koning','Marcel Scholtes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350438,'Peter Bertens','Raymond Huisman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350438,'Roel Koks','Ben Vermeer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350438,'Willem de Koning','Raymond Huisman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350438,'Peter Bertens','Ben Vermeer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350438,'Roel Koks','Marcel Scholtes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350438,'Roel Koks','Raymond Huisman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350438,'Peter Bertens','Marcel Scholtes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350438,'Willem de Koning','Ben Vermeer',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-11-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350443,'VLAARDINGEN 1','Snookerij 0',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350443,'René Tinge','Gennaro Cannavacciuolo',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350443,'Marco de Graaff','Kevin Vermeiren',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350443,'René Tinge','John van de Zwart',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350443,'Marco de Graaff','Gennaro Cannavacciuolo',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350443,'Marco de Graaff','John van de Zwart',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350443,'René Tinge','Kevin Vermeiren',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-11-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350441,'Back in the Pack 2.0','SC Capelle 1',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350441,'Willem de Koning','Fausto Salis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350441,'Leon van de Laak','Rien Baak',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350441,'Peter Bertens','Sjaak Hofman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350441,'Willem de Koning','Rien Baak',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350441,'Leon van de Laak','Sjaak Hofman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350441,'Peter Bertens','Fausto Salis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350441,'Peter Bertens','Rien Baak',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350441,'Leon van de Laak','Fausto Salis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350441,'Willem de Koning','Sjaak Hofman',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-11-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350442,'Zeekant par 3','Zeekantje',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('26-11-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350447,'VLAARDINGEN 1','DUH BALLUH',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350447,'Martin Hazewinkel','Jurgen Coolen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350447,'René Tinge','Luuk Buys',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350447,'Martin Hazewinkel','John van Gorp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350447,'René Tinge','Jurgen Coolen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350447,'René Tinge','John van Gorp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350447,'Martin Hazewinkel','Luuk Buys',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('29-11-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350446,'Back in the Pack 2.0','Snookerij 0',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350446,'Willem de Koning','John van de Zwart',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350446,'Leon van de Laak','Job Bavelaar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350446,'Peter Bertens','Coen Drejer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350446,'Willem de Koning','Job Bavelaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350446,'Leon van de Laak','Coen Drejer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350446,'Peter Bertens','John van de Zwart',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350446,'Peter Bertens','Job Bavelaar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350446,'Leon van de Laak','John van de Zwart',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350446,'Willem de Koning','Coen Drejer',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-12-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),363120,'SC Capelle 1','Zeekant par 3',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-12-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350448,'DUH BALLUH','Back in the Pack 2.0',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350448,'Luuk Buys','Peter Bertens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350448,'Keesjan Coenraad','Roel Koks',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350448,'John van Gorp','Willem de Koning',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350448,'Luuk Buys','Roel Koks',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350448,'Keesjan Coenraad','Willem de Koning',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350448,'John van Gorp','Peter Bertens',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350448,'John van Gorp','Roel Koks',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350448,'Keesjan Coenraad','Peter Bertens',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350448,'Luuk Buys','Willem de Koning',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-12-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350449,'Zeekantje','VLAARDINGEN 1',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350449,'Jarl Hinfelaar','Marko Reijers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350449,'Jannes Gout','Martin Hazewinkel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350449,'Menno Bussink','Marko Reijers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350449,'Jarl Hinfelaar','Martin Hazewinkel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350449,'Jannes Gout','Marko Reijers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350449,'Menno Bussink','Martin Hazewinkel',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-12-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350451,'Snookerij 0','SC Capelle 1',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350451,'Coen Drejer','Edwin Heinsman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350451,'John van de Zwart','Fausto Salis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350451,'Björn Matheijssen','Rien Baak',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350451,'Coen Drejer','Fausto Salis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350451,'John van de Zwart','Rien Baak',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350451,'Björn Matheijssen','Edwin Heinsman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350451,'Björn Matheijssen','Fausto Salis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350451,'John van de Zwart','Edwin Heinsman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350451,'Coen Drejer','Rien Baak',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-01-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350454,'Snookerij 0','Zeekant par 3',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350454,'Kevin Vermeiren','Marcel Scholtes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350454,'Björn Matheijssen','Maurice Kempeneers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350454,'Job Bavelaar','Ben Vermeer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350454,'Kevin Vermeiren','Maurice Kempeneers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350454,'Björn Matheijssen','Ben Vermeer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350454,'Job Bavelaar','Marcel Scholtes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350454,'Job Bavelaar','Maurice Kempeneers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350454,'Björn Matheijssen','Marcel Scholtes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350454,'Kevin Vermeiren','Ben Vermeer',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-01-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350457,'DUH BALLUH','Snookerij 0',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350457,'Bas Hendrickx','Björn Matheijssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350457,'Jurgen Coolen','Coen Drejer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350457,'Toine Oomens','Job Bavelaar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350457,'Bas Hendrickx','Coen Drejer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350457,'Jurgen Coolen','Job Bavelaar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350457,'Toine Oomens','Björn Matheijssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350457,'Toine Oomens','Coen Drejer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350457,'Jurgen Coolen','Björn Matheijssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350457,'Bas Hendrickx','Job Bavelaar',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-01-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350458,'Zeekantje','SC Capelle 1',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350458,'Jarl Hinfelaar','Rien Baak',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350458,'Jannes Gout','Fausto Salis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350458,'Ben Cicek','Edwin Heinsman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350458,'Jarl Hinfelaar','Fausto Salis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350458,'Jannes Gout','Edwin Heinsman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350458,'Ben Cicek','Rien Baak',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350458,'Ben Cicek','Fausto Salis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350458,'Jannes Gout','Rien Baak',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350458,'Jarl Hinfelaar','Edwin Heinsman',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-01-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350459,'Zeekant par 3','VLAARDINGEN 1',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350459,'Marcel Scholtes','Marco de Graaff',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350459,'Raymond Huisman','Martin Hazewinkel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350459,'Ben Vermeer','René Tinge',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350459,'Marcel Scholtes','Martin Hazewinkel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350459,'Raymond Huisman','René Tinge',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350459,'Ben Vermeer','Marco de Graaff',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350459,'Ben Vermeer','Martin Hazewinkel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350459,'Raymond Huisman','Marco de Graaff',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350459,'Marcel Scholtes','René Tinge',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('29-01-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350460,'DUH BALLUH','Zeekant par 3',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350460,'Bas Hendrickx','Marcel Scholtes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350460,'Luuk Buys','Ron Schul',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350460,'Toine Oomens','Ben Vermeer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350460,'Bas Hendrickx','Ron Schul',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350460,'Luuk Buys','Ben Vermeer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350460,'Toine Oomens','Marcel Scholtes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350460,'Toine Oomens','Ron Schul',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350460,'Luuk Buys','Marcel Scholtes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350460,'Bas Hendrickx','Ben Vermeer',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('31-01-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),364843,'VLAARDINGEN 1','Back in the Pack 2.0',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(364843,'Martin Hazewinkel','Peter Bertens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(364843,'René Tinge','Leon van de Laak',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(364843,'Marko Reijers','Willem de Koning',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(364843,'Martin Hazewinkel','Leon van de Laak',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(364843,'René Tinge','Willem de Koning',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(364843,'Marko Reijers','Peter Bertens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(364843,'Marko Reijers','Leon van de Laak',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(364843,'René Tinge','Peter Bertens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(364843,'Martin Hazewinkel','Willem de Koning',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('31-01-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350462,'Back in the Pack 2.0','VLAARDINGEN 1',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350462,'Willem de Koning','René Tinge',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350462,'Peter Bertens','Marko Reijers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350462,'Leon van de Laak','Martin Hazewinkel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350462,'Willem de Koning','Marko Reijers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350462,'Peter Bertens','Martin Hazewinkel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350462,'Leon van de Laak','René Tinge',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350462,'Leon van de Laak','Marko Reijers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350462,'Peter Bertens','René Tinge',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350462,'Willem de Koning','Martin Hazewinkel',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('01-02-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350463,'Snookerij 0','Zeekantje',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350463,'Kevin Vermeiren','Jannes Gout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350463,'John van de Zwart','Jarl Hinfelaar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350463,'Job Bavelaar','Menno Bussink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350463,'Kevin Vermeiren','Jarl Hinfelaar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350463,'John van de Zwart','Menno Bussink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350463,'Job Bavelaar','Jannes Gout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350463,'Job Bavelaar','Jarl Hinfelaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350463,'John van de Zwart','Jannes Gout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350463,'Kevin Vermeiren','Menno Bussink',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-02-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350467,'VLAARDINGEN 1','SC Capelle 1',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350467,'Martin Hazewinkel','Fausto Salis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350467,'Marco de Graaff','Edwin Heinsman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350467,'Martin Hazewinkel','Edwin Heinsman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350467,'Marco de Graaff','Sjaak Hofman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350467,'Marco de Graaff','Fausto Salis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350467,'Martin Hazewinkel','Sjaak Hofman',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-02-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350465,'Zeekantje','DUH BALLUH',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350465,'Jarl Hinfelaar','Bas Hendrickx',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350465,'Jannes Gout','John van Gorp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350465,'Fabian Rademaker','Toine Oomens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350465,'Jarl Hinfelaar','John van Gorp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350465,'Jannes Gout','Toine Oomens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350465,'Fabian Rademaker','Bas Hendrickx',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350465,'Fabian Rademaker','John van Gorp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350465,'Jannes Gout','Bas Hendrickx',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350465,'Jarl Hinfelaar','Toine Oomens',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-02-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350466,'Zeekant par 3','Back in the Pack 2.0',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350466,'Ben Vermeer','Peter Bertens',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350466,'Marcel Scholtes','Leon van de Laak',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350466,'Raymond Huisman','Willem de Koning',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350466,'Ben Vermeer','Leon van de Laak',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350466,'Marcel Scholtes','Willem de Koning',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350466,'Raymond Huisman','Peter Bertens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350466,'Raymond Huisman','Leon van de Laak',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350466,'Marcel Scholtes','Peter Bertens',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350466,'Ben Vermeer','Willem de Koning',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('26-02-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350469,'Zeekantje','Zeekant par 3',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350469,'Jarl Hinfelaar','Maurice Kempeneers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350469,'Fabian Rademaker','Ben Vermeer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350469,'Jannes Gout','Marcel Scholtes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350469,'Jarl Hinfelaar','Ben Vermeer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350469,'Fabian Rademaker','Marcel Scholtes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350469,'Jannes Gout','Maurice Kempeneers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350469,'Jannes Gout','Ben Vermeer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350469,'Fabian Rademaker','Maurice Kempeneers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350469,'Jarl Hinfelaar','Marcel Scholtes',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('01-03-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350471,'Snookerij 0','VLAARDINGEN 1',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350471,'Gennaro Cannavacciuolo','Marco de Graaff',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350471,'Björn Matheijssen','Marko Reijers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350471,'Coen Drejer','Martin Hazewinkel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350471,'Gennaro Cannavacciuolo','Marko Reijers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350471,'Björn Matheijssen','Martin Hazewinkel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350471,'Coen Drejer','Marco de Graaff',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350471,'Coen Drejer','Marko Reijers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350471,'Björn Matheijssen','Marco de Graaff',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350471,'Gennaro Cannavacciuolo','Martin Hazewinkel',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-03-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350473,'DUH BALLUH','VLAARDINGEN 1',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350473,'Bas Hendrickx','Martin Hazewinkel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350473,'John van Gorp','René Tinge',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350473,'Jurgen Coolen','René Tinge',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350473,'John van Gorp','Martin Hazewinkel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350473,'Jurgen Coolen','Martin Hazewinkel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350473,'Bas Hendrickx','René Tinge',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-03-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350474,'Zeekant par 3','SC Capelle 1',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350474,'Ben Vermeer','Sjaak Hofman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350474,'Raymond Huisman','Rien Baak',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350474,'Marcel Scholtes','Edwin Heinsman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350474,'Ben Vermeer','Rien Baak',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350474,'Raymond Huisman','Edwin Heinsman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350474,'Marcel Scholtes','Sjaak Hofman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350474,'Marcel Scholtes','Rien Baak',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350474,'Raymond Huisman','Sjaak Hofman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350474,'Ben Vermeer','Edwin Heinsman',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-03-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350475,'Snookerij 0','Back in the Pack 2.0',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350475,'Coen Drejer','Peter Bertens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350475,'Björn Matheijssen','Robert Stevenson',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350475,'Gennaro Cannavacciuolo','Willem de Koning',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350475,'Coen Drejer','Robert Stevenson',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350475,'Björn Matheijssen','Willem de Koning',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350475,'Gennaro Cannavacciuolo','Peter Bertens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350475,'Gennaro Cannavacciuolo','Robert Stevenson',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350475,'Björn Matheijssen','Peter Bertens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350475,'Coen Drejer','Willem de Koning',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-03-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),365407,'SC Capelle 1','DUH BALLUH',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365407,'Rien Baak','Keesjan Coenraad',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365407,'Sjaak Hofman','Luuk Buys',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365407,'Fausto Salis','John van Gorp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365407,'Rien Baak','Luuk Buys',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365407,'Sjaak Hofman','John van Gorp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365407,'Fausto Salis','Keesjan Coenraad',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365407,'Fausto Salis','Luuk Buys',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365407,'Sjaak Hofman','Keesjan Coenraad',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365407,'Rien Baak','John van Gorp',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('25-03-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350479,'VLAARDINGEN 1','Zeekantje',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350479,'Marco de Graaff','Johan Grootens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350479,'Marko Reijers','Jarl Hinfelaar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350479,'Marco de Graaff','Jarl Hinfelaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350479,'Marko Reijers','Ben Cicek',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350479,'Marko Reijers','Johan Grootens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350479,'Marco de Graaff','Ben Cicek',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('28-03-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350477,'SC Capelle 1','Snookerij 0',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350477,'Edwin Heinsman','Björn Matheijssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350477,'Rien Baak','Coen Drejer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350477,'Fausto Salis','Kevin Vermeiren',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350477,'Edwin Heinsman','Coen Drejer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350477,'Rien Baak','Kevin Vermeiren',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350477,'Fausto Salis','Björn Matheijssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350477,'Fausto Salis','Coen Drejer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350477,'Rien Baak','Björn Matheijssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350477,'Edwin Heinsman','Kevin Vermeiren',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('28-03-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350478,'Back in the Pack 2.0','DUH BALLUH',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350478,'Willem de Koning','Toine Oomens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350478,'Peter Bertens','Keesjan Coenraad',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350478,'Leon van de Laak','Jurgen Coolen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350478,'Willem de Koning','Keesjan Coenraad',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350478,'Peter Bertens','Jurgen Coolen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350478,'Leon van de Laak','Toine Oomens',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350478,'Leon van de Laak','Keesjan Coenraad',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350478,'Peter Bertens','Toine Oomens',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350478,'Willem de Koning','Jurgen Coolen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-04-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350481,'Zeekantje','Back in the Pack 2.0',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350481,'Jarl Hinfelaar','Peter Bertens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350481,'Fabian Rademaker','Leon van de Laak',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350481,'Jannes Gout','Willem de Koning',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350481,'Jarl Hinfelaar','Leon van de Laak',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350481,'Fabian Rademaker','Willem de Koning',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350481,'Jannes Gout','Peter Bertens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350481,'Jannes Gout','Leon van de Laak',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350481,'Fabian Rademaker','Peter Bertens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350481,'Jarl Hinfelaar','Willem de Koning',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-04-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350482,'DUH BALLUH','SC Capelle 1',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350482,'Bas Hendrickx','Rien Baak',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350482,'Keesjan Coenraad','Fausto Salis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350482,'Jurgen Coolen','Sjaak Hofman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350482,'Bas Hendrickx','Fausto Salis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350482,'Keesjan Coenraad','Sjaak Hofman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350482,'Jurgen Coolen','Rien Baak',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350482,'Jurgen Coolen','Fausto Salis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350482,'Keesjan Coenraad','Rien Baak',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350482,'Bas Hendrickx','Sjaak Hofman',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-04-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350483,'Zeekant par 3','Snookerij 0',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350483,'Ben Vermeer','Job Bavelaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350483,'Marcel Scholtes','Björn Matheijssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350483,'Raymond Huisman','Kevin Vermeiren',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350483,'Ben Vermeer','Björn Matheijssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350483,'Marcel Scholtes','Kevin Vermeiren',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350483,'Raymond Huisman','Job Bavelaar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350483,'Raymond Huisman','Björn Matheijssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350483,'Marcel Scholtes','Job Bavelaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350483,'Ben Vermeer','Kevin Vermeiren',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-04-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350487,'VLAARDINGEN 1','Zeekant par 3',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350487,'René Tinge','Marcel Scholtes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350487,'Marco de Graaff','Ron Schul',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350487,'Bo Speyer','Ben Vermeer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350487,'René Tinge','Ron Schul',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350487,'Marco de Graaff','Ben Vermeer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350487,'Bo Speyer','Marcel Scholtes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350487,'Bo Speyer','Ron Schul',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350487,'Marco de Graaff','Marcel Scholtes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350487,'René Tinge','Ben Vermeer',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-04-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),365906,'SC Capelle 1','Back in the Pack 2.0',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365906,'Rien Baak','Peter Bertens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365906,'Sjaak Hofman','Leon van de Laak',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365906,'Fausto Salis','Willem de Koning',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365906,'Rien Baak','Leon van de Laak',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365906,'Sjaak Hofman','Willem de Koning',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365906,'Fausto Salis','Peter Bertens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365906,'Fausto Salis','Leon van de Laak',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365906,'Sjaak Hofman','Peter Bertens',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365906,'Rien Baak','Willem de Koning',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-04-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350484,'SC Capelle 1','Zeekantje',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350484,'Fausto Salis','Jannes Gout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350484,'Rien Baak','Fabian Rademaker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350484,'Fausto Salis','Fabian Rademaker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350484,'Rien Baak','Johan Grootens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350484,'Rien Baak','Jannes Gout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350484,'Fausto Salis','Johan Grootens',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-04-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350486,'Snookerij 0','DUH BALLUH',9,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350486,'John van de Zwart','John van Gorp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350486,'Coen Drejer','Toine Oomens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350486,'Björn Matheijssen','Bas Hendrickx',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350486,'John van de Zwart','Toine Oomens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350486,'Coen Drejer','Bas Hendrickx',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350486,'Björn Matheijssen','John van Gorp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350486,'Björn Matheijssen','Toine Oomens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350486,'Coen Drejer','John van Gorp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350486,'John van de Zwart','Bas Hendrickx',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-04-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350491,'VLAARDINGEN 1','Back in the Pack 2.0',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350491,'Martin Hazewinkel','Willem de Koning',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350491,'Marco de Graaff','Hans Smulders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350491,'Martin Hazewinkel','Peter Bertens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350491,'Marco de Graaff','Willem de Koning',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350491,'Marco de Graaff','Peter Bertens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350491,'Martin Hazewinkel','Hans Smulders',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-04-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350489,'Zeekantje','Snookerij 0',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350489,'Jarl Hinfelaar','Björn Matheijssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350489,'Fabian Rademaker','Coen Drejer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350489,'Jannes Gout','Kevin Vermeiren',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350489,'Jarl Hinfelaar','Coen Drejer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350489,'Fabian Rademaker','Kevin Vermeiren',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350489,'Jannes Gout','Björn Matheijssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350489,'Jannes Gout','Coen Drejer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350489,'Fabian Rademaker','Björn Matheijssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350489,'Jarl Hinfelaar','Kevin Vermeiren',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('30-04-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350492,'DUH BALLUH','Zeekantje',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350492,'Bas Hendrickx','Fabian Rademaker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350492,'Keesjan Coenraad','Jarl Hinfelaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350492,'Toine Oomens','Jannes Gout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350492,'Bas Hendrickx','Jarl Hinfelaar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350492,'Keesjan Coenraad','Jannes Gout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350492,'Toine Oomens','Fabian Rademaker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350492,'Toine Oomens','Jarl Hinfelaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350492,'Keesjan Coenraad','Fabian Rademaker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350492,'Bas Hendrickx','Jannes Gout',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-05-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),366303,'DUH BALLUH','Zeekantje',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366303,'Keesjan Coenraad','Jarl Hinfelaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366303,'Toine Oomens','Jannes Gout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366303,'Jurgen Coolen','Fabian Rademaker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366303,'Keesjan Coenraad','Jannes Gout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366303,'Toine Oomens','Fabian Rademaker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366303,'Jurgen Coolen','Jarl Hinfelaar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366303,'Jurgen Coolen','Jannes Gout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366303,'Toine Oomens','Jarl Hinfelaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366303,'Keesjan Coenraad','Fabian Rademaker',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-05-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350493,'SC Capelle 1','VLAARDINGEN 1',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350493,'Rien Baak','Marco de Graaff',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350493,'Sjaak Hofman','Martin Hazewinkel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350493,'Fausto Salis','Marco de Graaff',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350493,'Rien Baak','Martin Hazewinkel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350493,'Sjaak Hofman','Marco de Graaff',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350493,'Fausto Salis','Martin Hazewinkel',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-05-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350494,'Back in the Pack 2.0','Zeekant par 3',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350494,'Willem de Koning','Marcel Scholtes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350494,'Peter Bertens','Raymond Hoogwater',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350494,'Leon van de Laak','Ben Vermeer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350494,'Willem de Koning','Raymond Hoogwater',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350494,'Peter Bertens','Ben Vermeer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350494,'Leon van de Laak','Marcel Scholtes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350494,'Leon van de Laak','Raymond Hoogwater',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350494,'Peter Bertens','Marcel Scholtes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350494,'Willem de Koning','Ben Vermeer',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-05-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350497,'Back in the Pack 2.0','SC Capelle 1',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350497,'Roel Koks','Rien Baak',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350497,'Willem de Koning','Fausto Salis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350497,'Peter Bertens','Edwin Heinsman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350497,'Roel Koks','Fausto Salis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350497,'Willem de Koning','Edwin Heinsman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350497,'Peter Bertens','Rien Baak',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350497,'Peter Bertens','Fausto Salis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350497,'Willem de Koning','Rien Baak',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350497,'Roel Koks','Edwin Heinsman',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-05-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),350498,'Zeekant par 3','Zeekantje',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350498,'Ben Vermeer','Fabian Rademaker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350498,'Marcel Scholtes','Johan Grootens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350498,'Maurice Kempeneers','Jannes Gout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350498,'Ben Vermeer','Johan Grootens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350498,'Marcel Scholtes','Jannes Gout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350498,'Maurice Kempeneers','Fabian Rademaker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350498,'Maurice Kempeneers','Johan Grootens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350498,'Marcel Scholtes','Fabian Rademaker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350498,'Ben Vermeer','Jannes Gout',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-05-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),366546,'VLAARDINGEN 1','Snookerij 0',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366546,'Martin Hazewinkel','Coen Drejer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366546,'Marco de Graaff','Björn Matheijssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366546,'Marco de Graaff','Coen Drejer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366546,'Martin Hazewinkel','Björn Matheijssen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-05-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),366545,'Zeekant par 3','DUH BALLUH',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366545,'Ben Vermeer','Jurgen Coolen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366545,'Maurice Kempeneers','John van Gorp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366545,'Raymond Huisman','Bas Hendrickx',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366545,'Ben Vermeer','John van Gorp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366545,'Maurice Kempeneers','Bas Hendrickx',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366545,'Raymond Huisman','Jurgen Coolen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366545,'Raymond Huisman','John van Gorp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366545,'Maurice Kempeneers','Jurgen Coolen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366545,'Ben Vermeer','Bas Hendrickx',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-05-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2012%'),366772,'Back in the Pack 2.0','Zeekantje',3,0);
