delete from cm_match_details where game_id in (select game_id from cm_matches where cpn_id = (select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2014%'));
delete from cm_matches where cpn_id = (select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2014%');
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2014%'),449118,'VLAARDINGEN 1','De Loods 1',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449118,'Marko Reijers','Roeland Melief',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449118,'Marco de Graaff','Alexander van den Doel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449118,'Marko Reijers','Alexander van den Doel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449118,'Marco de Graaff','Hans van Velde',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449118,'Marco de Graaff','Roeland Melief',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449118,'Marko Reijers','Hans van Velde',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2014%'),449457,'Capelle Vaaf','Pompadour 2',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449457,'Kaylash Persad','Corné Kuijpers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449457,'Kevin Jansen','Jurgen Gruson',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449457,'Kaylash Persad','Jurgen Gruson',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449457,'Kevin Jansen','Niki Lin',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449457,'Kevin Jansen','Corné Kuijpers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449457,'Kaylash Persad','Niki Lin',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2014%'),449120,'De Loods 1','Capelle Vaaf',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449120,'Alexander van den Doel','Kevin Jansen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449120,'Roeland Melief','Ho Bang Tang',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449120,'Hans van Velde','Kevin Jansen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449120,'Alexander van den Doel','Ho Bang Tang',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449120,'Roeland Melief','Kevin Jansen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449120,'Hans van Velde','Ho Bang Tang',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2014%'),449121,'Hippo 1','VLAARDINGEN 1',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2014%'),449458,'VLAARDINGEN 1','Capelle Vaaf',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2014%'),449125,'Hippo 1','Pompadour 2',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2014%'),449126,'De Loods 1','Hippo 1',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2014%'),449127,'Pompadour 2','VLAARDINGEN 1',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2014%'),449620,'Capelle Vaaf','Hippo 1',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2014%'),449537,'Pompadour 2','De Loods 1',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449537,'Anton Janssen','Alexander van den Doel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449537,'Niki Lin','Hans van Velde',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449537,'Corné Kuijpers','Roeland Melief',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449537,'Anton Janssen','Hans van Velde',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449537,'Niki Lin','Roeland Melief',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449537,'Corné Kuijpers','Alexander van den Doel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449537,'Corné Kuijpers','Hans van Velde',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449537,'Niki Lin','Alexander van den Doel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449537,'Anton Janssen','Roeland Melief',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('30-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2014%'),449732,'Pompadour 2','Capelle Vaaf',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449732,'Niki Lin','Kevin Jansen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449732,'Maurice Rijk','Kevin Jansen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449732,'Corné Kuijpers','Kevin Jansen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2014%'),449130,'VLAARDINGEN 1','Hippo 1',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2014%'),449733,'Hippo 1','Capelle Vaaf',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449733,'Benno Lier','Ho Bang Tang',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449733,'Marco Eisinga','Kevin Jansen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449733,'Olivier Hensing','Kevin Jansen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449733,'Marco Eisinga','Ho Bang Tang',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449733,'Olivier Hensing','Ho Bang Tang',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449733,'Benno Lier','Kevin Jansen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2014%'),449621,'Capelle Vaaf','De Loods 1',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449621,'Ho Bang Tang','Hans van Velde',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449621,'Kevin Jansen','Roeland Melief',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449621,'Ho Bang Tang','Roeland Melief',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449621,'Kevin Jansen','Alexander van den Doel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449621,'Kevin Jansen','Hans van Velde',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449621,'Ho Bang Tang','Alexander van den Doel',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2014%'),449135,'Capelle Vaaf','VLAARDINGEN 1',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449135,'Kaylash Persad','Marko Reijers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449135,'Ho Bang Tang','Marko Reijers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449135,'Kaylash Persad','René Tinge',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449135,'Ho Bang Tang','René Tinge',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2014%'),449134,'Pompadour 2','Hippo 1',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449134,'Jurgen Gruson','Marco Eisinga',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449134,'Anton Janssen','Olivier Hensing',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449134,'Jurgen Gruson','Olivier Hensing',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449134,'Corné Kuijpers','Marco Eisinga',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449134,'Corné Kuijpers','Olivier Hensing',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449134,'Anton Janssen','Marco Eisinga',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('25-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2014%'),449136,'VLAARDINGEN 1','Pompadour 2',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('26-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2014%'),449731,'De Loods 1','VLAARDINGEN 1',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449731,'Roeland Melief','René Tinge',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449731,'Alexander van den Doel','Bo Speyer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449731,'Hans van Velde','Ron Blok',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449731,'Roeland Melief','Bo Speyer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449731,'Alexander van den Doel','Ron Blok',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449731,'Hans van Velde','René Tinge',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449731,'Hans van Velde','Bo Speyer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449731,'Alexander van den Doel','René Tinge',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449731,'Roeland Melief','Ron Blok',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-06-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Hoofdklasse poule 2' and ssn_id like '2014%'),449844,'De Loods 1','Pompadour 2',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449844,'Roeland Melief','Corné Kuijpers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449844,'Hans van Velde','Corné Kuijpers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449844,'Alexander van den Doel','Corné Kuijpers',1,0);
