delete from cm_match_details where game_id in (select game_id from cm_matches where cpn_id = (select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2014%'));
delete from cm_matches where cpn_id = (select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2014%');
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2014%'),449258,'THE FIFTH PLANET 5','Amsterdams onwettige zonen',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449258,'Edwin van Vugt','Ali Soeleman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449258,'Fred Wurtz','Gethin Davies',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449258,'Edwin van Vugt','Gethin Davies',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449258,'Fred Wurtz','Jeroen van der Linde',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449258,'Fred Wurtz','Ali Soeleman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449258,'Edwin van Vugt','Jeroen van der Linde',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2014%'),449260,'OZEBI 3','Sloten 2',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449260,'Robert Rodenburg','Alex van Hensbergen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449260,'Kees Reijn','Chi Kwong Wu',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449260,'Marijn Sloots','Kilian Steen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449260,'Robert Rodenburg','Chi Kwong Wu',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449260,'Kees Reijn','Kilian Steen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449260,'Marijn Sloots','Alex van Hensbergen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449260,'Marijn Sloots','Chi Kwong Wu',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449260,'Kees Reijn','Alex van Hensbergen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449260,'Robert Rodenburg','Kilian Steen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2014%'),449262,'Amsterdams onwettige zonen','DE BILJARTMAKERS 2',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449262,'Rahman Azimi','Dick Roskamp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449262,'Gethin Davies','Gerard Bocxe',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449262,'Jeroen van der Linde','Lex Franssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449262,'Rahman Azimi','Gerard Bocxe',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449262,'Gethin Davies','Lex Franssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449262,'Jeroen van der Linde','Dick Roskamp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449262,'Jeroen van der Linde','Gerard Bocxe',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449262,'Gethin Davies','Dick Roskamp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449262,'Rahman Azimi','Lex Franssen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2014%'),449263,'DE BILJARTMAKERS 1','OZEBI 3',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449263,'Michael Salentijn','Marijn Sloots',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449263,'Edwin Stokkermans','Jeroen Sloots',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449263,'Erik de Ruiter','Kees Reijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449263,'Michael Salentijn','Jeroen Sloots',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449263,'Edwin Stokkermans','Kees Reijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449263,'Erik de Ruiter','Marijn Sloots',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449263,'Erik de Ruiter','Jeroen Sloots',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449263,'Edwin Stokkermans','Marijn Sloots',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449263,'Michael Salentijn','Kees Reijn',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2014%'),449264,'DE BILJARTMAKERS 2','Sloten 2',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449264,'Dick Roskamp','Alex van Hensbergen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449264,'Lex Franssen','Chi Kwong Wu',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449264,'Gerard Bocxe','Kilian Steen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449264,'Dick Roskamp','Chi Kwong Wu',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449264,'Lex Franssen','Kilian Steen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449264,'Gerard Bocxe','Alex van Hensbergen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449264,'Gerard Bocxe','Chi Kwong Wu',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449264,'Lex Franssen','Alex van Hensbergen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449264,'Dick Roskamp','Kilian Steen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2014%'),449265,'DE BILJARTMAKERS 1','Amsterdams onwettige zonen',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449265,'Michael Salentijn','Rahman Azimi',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449265,'Edwin Stokkermans','Jeroen van der Linde',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449265,'Erik de Ruiter','Ali Soeleman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449265,'Michael Salentijn','Jeroen van der Linde',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449265,'Edwin Stokkermans','Ali Soeleman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449265,'Erik de Ruiter','Rahman Azimi',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449265,'Erik de Ruiter','Jeroen van der Linde',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449265,'Edwin Stokkermans','Rahman Azimi',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449265,'Michael Salentijn','Ali Soeleman',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2014%'),449266,'OZEBI 3','THE FIFTH PLANET 5',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449266,'René Kerkhoven','Peter Fokker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449266,'Robert Rodenburg','Edwin van Vugt',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449266,'Jeroen Sloots','Cor Wever',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449266,'René Kerkhoven','Edwin van Vugt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449266,'Robert Rodenburg','Cor Wever',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449266,'Jeroen Sloots','Peter Fokker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449266,'Jeroen Sloots','Edwin van Vugt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449266,'Robert Rodenburg','Peter Fokker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449266,'René Kerkhoven','Cor Wever',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('25-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2014%'),449575,'DE BILJARTMAKERS 2','DE BILJARTMAKERS 1',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449575,'Lex Franssen','Edwin Stokkermans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449575,'Dick Roskamp','Erik de Ruiter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449575,'Gerard Bocxe','Michael Salentijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449575,'Lex Franssen','Erik de Ruiter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449575,'Dick Roskamp','Michael Salentijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449575,'Gerard Bocxe','Edwin Stokkermans',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449575,'Gerard Bocxe','Erik de Ruiter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449575,'Dick Roskamp','Edwin Stokkermans',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449575,'Lex Franssen','Michael Salentijn',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('01-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2014%'),449268,'Sloten 2','DE BILJARTMAKERS 1',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449268,'Kilian Steen','Edwin Stokkermans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449268,'Chi Kwong Wu','Erik de Ruiter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449268,'Roy Steinraht','Michael Salentijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449268,'Kilian Steen','Erik de Ruiter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449268,'Chi Kwong Wu','Michael Salentijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449268,'Roy Steinraht','Edwin Stokkermans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449268,'Roy Steinraht','Erik de Ruiter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449268,'Chi Kwong Wu','Edwin Stokkermans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449268,'Kilian Steen','Michael Salentijn',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('01-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2014%'),449269,'Amsterdams onwettige zonen','OZEBI 3',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2014%'),449482,'THE FIFTH PLANET 5','DE BILJARTMAKERS 2',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449482,'Peter Fokker','Gerard Bocxe',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449482,'Cor Wever','Dick Roskamp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449482,'Peter Fokker','Dick Roskamp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449482,'Cor Wever','Lex Franssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449482,'Cor Wever','Gerard Bocxe',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449482,'Peter Fokker','Lex Franssen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2014%'),449270,'Amsterdams onwettige zonen','Sloten 2',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2014%'),449272,'OZEBI 3','DE BILJARTMAKERS 2',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449272,'Robert Rodenburg','Dick Roskamp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449272,'Marijn Sloots','Gerard Bocxe',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449272,'René Kerkhoven','Lex Franssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449272,'Robert Rodenburg','Gerard Bocxe',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449272,'Marijn Sloots','Lex Franssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449272,'René Kerkhoven','Dick Roskamp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449272,'René Kerkhoven','Gerard Bocxe',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449272,'Marijn Sloots','Dick Roskamp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449272,'Robert Rodenburg','Lex Franssen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2014%'),449273,'Sloten 2','OZEBI 3',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2014%'),449274,'Amsterdams onwettige zonen','THE FIFTH PLANET 5',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2014%'),449613,'DE BILJARTMAKERS 1','THE FIFTH PLANET 5',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449613,'Michael Salentijn','Peter Fokker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449613,'Edwin Stokkermans','Fred Wurtz',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449613,'Erik de Ruiter','Cor Wever',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449613,'Michael Salentijn','Fred Wurtz',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449613,'Edwin Stokkermans','Cor Wever',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449613,'Erik de Ruiter','Peter Fokker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449613,'Erik de Ruiter','Fred Wurtz',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449613,'Edwin Stokkermans','Peter Fokker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449613,'Michael Salentijn','Cor Wever',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2014%'),449519,'Sloten 2','THE FIFTH PLANET 5',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449519,'Kilian Steen','Peter Fokker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449519,'Chi Kwong Wu','Fred Wurtz',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449519,'Kilian Steen','Fred Wurtz',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449519,'Roy Steinraht','Peter Fokker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449519,'Roy Steinraht','Fred Wurtz',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449519,'Chi Kwong Wu','Peter Fokker',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2014%'),449277,'DE BILJARTMAKERS 2','Amsterdams onwettige zonen',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449277,'Gerard Bocxe','Rahman Azimi',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449277,'Lex Franssen','Etienne Verheem',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449277,'Dick Roskamp','Jeroen van der Linde',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449277,'Gerard Bocxe','Etienne Verheem',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449277,'Lex Franssen','Jeroen van der Linde',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449277,'Dick Roskamp','Rahman Azimi',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449277,'Dick Roskamp','Etienne Verheem',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449277,'Lex Franssen','Rahman Azimi',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449277,'Gerard Bocxe','Jeroen van der Linde',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2014%'),449280,'Sloten 2','DE BILJARTMAKERS 2',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2014%'),449282,'DE BILJARTMAKERS 2','THE FIFTH PLANET 5',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449282,'Gerard Bocxe','Edwin van Vugt',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449282,'Dick Roskamp','Fred Wurtz',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449282,'Lex Franssen','Peter Fokker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449282,'Gerard Bocxe','Fred Wurtz',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449282,'Dick Roskamp','Peter Fokker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449282,'Lex Franssen','Edwin van Vugt',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449282,'Lex Franssen','Fred Wurtz',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449282,'Dick Roskamp','Edwin van Vugt',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449282,'Gerard Bocxe','Peter Fokker',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2014%'),449284,'OZEBI 3','Amsterdams onwettige zonen',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2014%'),449286,'DE BILJARTMAKERS 2','OZEBI 3',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449286,'Gerard Bocxe','Kees Reijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449286,'Dick Roskamp','Robert Rodenburg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449286,'Lex Franssen','Jeroen Sloots',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449286,'Gerard Bocxe','Robert Rodenburg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449286,'Dick Roskamp','Jeroen Sloots',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449286,'Lex Franssen','Kees Reijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449286,'Lex Franssen','Robert Rodenburg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449286,'Dick Roskamp','Kees Reijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449286,'Gerard Bocxe','Jeroen Sloots',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2014%'),449287,'Sloten 2','Amsterdams onwettige zonen',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449287,'Alex van Hensbergen','Gethin Davies',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449287,'Chi Kwong Wu','Jeroen van der Linde',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449287,'Roy Steinraht','Rahman Azimi',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449287,'Alex van Hensbergen','Jeroen van der Linde',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449287,'Chi Kwong Wu','Rahman Azimi',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449287,'Roy Steinraht','Gethin Davies',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449287,'Roy Steinraht','Jeroen van der Linde',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449287,'Chi Kwong Wu','Gethin Davies',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449287,'Alex van Hensbergen','Rahman Azimi',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('29-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2014%'),449485,'THE FIFTH PLANET 5','DE BILJARTMAKERS 1',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449485,'Edwin van Vugt','Edwin Stokkermans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449485,'Peter Fokker','Michael Salentijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449485,'Edwin van Vugt','Erik de Ruiter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449485,'Peter Fokker','Edwin Stokkermans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449485,'Peter Fokker','Erik de Ruiter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449485,'Edwin van Vugt','Michael Salentijn',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-06-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2014%'),449615,'Amsterdams onwettige zonen','DE BILJARTMAKERS 1',8,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-06-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2014%'),449614,'OZEBI 3','DE BILJARTMAKERS 1',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449614,'Marijn Sloots','Edwin Stokkermans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449614,'Jeroen Sloots','Erik de Ruiter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449614,'René Kerkhoven','Michael Salentijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449614,'Marijn Sloots','Erik de Ruiter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449614,'Jeroen Sloots','Michael Salentijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449614,'René Kerkhoven','Edwin Stokkermans',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449614,'René Kerkhoven','Erik de Ruiter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449614,'Jeroen Sloots','Edwin Stokkermans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449614,'Marijn Sloots','Michael Salentijn',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-06-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2014%'),449802,'THE FIFTH PLANET 5','Sloten 2',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449802,'Cor Wever','Chi Kwong Wu',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449802,'Edwin van Vugt','Kilian Steen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449802,'Cor Wever','Roy Steinraht',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449802,'Edwin van Vugt','Chi Kwong Wu',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449802,'Edwin van Vugt','Roy Steinraht',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449802,'Cor Wever','Kilian Steen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-06-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2014%'),449841,'DE BILJARTMAKERS 1','Sloten 2',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449841,'Michael Salentijn','Chi Kwong Wu',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449841,'Erik de Ruiter','Alex van Hensbergen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449841,'Edwin Stokkermans','Kilian Steen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449841,'Michael Salentijn','Alex van Hensbergen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449841,'Erik de Ruiter','Kilian Steen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449841,'Edwin Stokkermans','Chi Kwong Wu',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449841,'Edwin Stokkermans','Alex van Hensbergen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449841,'Erik de Ruiter','Chi Kwong Wu',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449841,'Michael Salentijn','Kilian Steen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-06-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2014%'),449843,'DE BILJARTMAKERS 1','DE BILJARTMAKERS 2',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449843,'Michael Salentijn','Dick Roskamp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449843,'Edwin Stokkermans','Gerard Bocxe',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449843,'Erik de Ruiter','Lex Franssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449843,'Michael Salentijn','Gerard Bocxe',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449843,'Edwin Stokkermans','Lex Franssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449843,'Erik de Ruiter','Dick Roskamp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449843,'Erik de Ruiter','Gerard Bocxe',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449843,'Edwin Stokkermans','Dick Roskamp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449843,'Michael Salentijn','Lex Franssen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-06-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2014%'),449801,'THE FIFTH PLANET 5','OZEBI 3',4,5);
