delete from cm_match_details where game_id in (select game_id from cm_matches where cpn_id = (select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2011%'));
delete from cm_matches where cpn_id = (select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2011%');
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-09-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2011%'),293779,'NNPV','Koetshuis 1',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293779,'Nico van Veen','Benjamin Tros',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293779,'Mark Molier','Marco Kuperus',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293779,'Ruud Heufke Kantelaar','Richard Kiljan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293779,'Nico van Veen','Marco Kuperus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293779,'Mark Molier','Richard Kiljan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293779,'Ruud Heufke Kantelaar','Benjamin Tros',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293779,'Ruud Heufke Kantelaar','Marco Kuperus',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293779,'Mark Molier','Benjamin Tros',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293779,'Nico van Veen','Richard Kiljan',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-09-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2011%'),293784,'SNOOKERIJ 6','SNOOKERIJ 10',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293784,'Edwin van Orssagen','Steve Course',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293784,'Robert van Nieuwkoop','Harry Bartels',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293784,'Mark van Vliet','Peter Hoekstra',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293784,'Edwin van Orssagen','Harry Bartels',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293784,'Robert van Nieuwkoop','Peter Hoekstra',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293784,'Mark van Vliet','Steve Course',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293784,'Mark van Vliet','Harry Bartels',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293784,'Robert van Nieuwkoop','Steve Course',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293784,'Edwin van Orssagen','Peter Hoekstra',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('28-09-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2011%'),293786,'Team 1048','THE FIFTH PLANET 5',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293786,'Juan Moreno','Thom Leenders',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293786,'Erik Veerman','Fred Wurtz',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293786,'Wouter Kager','Kilian Steen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293786,'Juan Moreno','Fred Wurtz',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293786,'Erik Veerman','Kilian Steen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293786,'Wouter Kager','Thom Leenders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293786,'Wouter Kager','Fred Wurtz',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293786,'Erik Veerman','Thom Leenders',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293786,'Juan Moreno','Kilian Steen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('28-09-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2011%'),293787,'JUMBO 13','NNPV',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293787,'Harry Vogelzang','Rob Molier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293787,'Anton Lindhout','Marco Roeleveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293787,'Jeroen Keijzer','Nico van Veen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293787,'Harry Vogelzang','Marco Roeleveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293787,'Anton Lindhout','Nico van Veen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293787,'Jeroen Keijzer','Rob Molier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293787,'Jeroen Keijzer','Marco Roeleveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293787,'Anton Lindhout','Rob Molier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293787,'Harry Vogelzang','Nico van Veen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-10-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2011%'),293790,'SNOOKERIJ 10','Team 1048',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-10-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2011%'),293791,'THE FIFTH PLANET 5','Koetshuis 1',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293791,'Alex van Hensbergen','Benjamin Tros',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293791,'Cor Wever','Richard Kiljan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293791,'Fred Wurtz','Hans Reijerkerk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293791,'Alex van Hensbergen','Richard Kiljan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293791,'Cor Wever','Hans Reijerkerk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293791,'Fred Wurtz','Benjamin Tros',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293791,'Fred Wurtz','Richard Kiljan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293791,'Cor Wever','Benjamin Tros',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293791,'Alex van Hensbergen','Hans Reijerkerk',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('01-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2011%'),293793,'Koetshuis 1','SNOOKERIJ 10',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293793,'Richard Kiljan','Margot Olree',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293793,'Marco Kuperus','Hans Wolvers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293793,'Hans Reijerkerk','Kitt van der Jagt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293793,'Richard Kiljan','Hans Wolvers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293793,'Marco Kuperus','Kitt van der Jagt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293793,'Hans Reijerkerk','Margot Olree',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293793,'Hans Reijerkerk','Hans Wolvers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293793,'Marco Kuperus','Margot Olree',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293793,'Richard Kiljan','Kitt van der Jagt',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('01-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2011%'),293794,'SNOOKERIJ 6','JUMBO 13',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293794,'Robert van Nieuwkoop','Jeroen Keijzer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293794,'David Mourette','Harry Vogelzang',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293794,'Roger Planje','Menno Beugelsdijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293794,'Robert van Nieuwkoop','Harry Vogelzang',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293794,'David Mourette','Menno Beugelsdijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293794,'Roger Planje','Jeroen Keijzer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293794,'Roger Planje','Harry Vogelzang',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293794,'David Mourette','Jeroen Keijzer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293794,'Robert van Nieuwkoop','Menno Beugelsdijk',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2011%'),305550,'THE FIFTH PLANET 5','SNOOKERIJ 6',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(305550,'Thom Leenders','Robert van Nieuwkoop',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(305550,'Fred Wurtz','Roger Planje',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(305550,'Alex van Hensbergen','Mark van Vliet',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(305550,'Thom Leenders','Roger Planje',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(305550,'Fred Wurtz','Mark van Vliet',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(305550,'Alex van Hensbergen','Robert van Nieuwkoop',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(305550,'Alex van Hensbergen','Roger Planje',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(305550,'Fred Wurtz','Robert van Nieuwkoop',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(305550,'Thom Leenders','Mark van Vliet',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2011%'),293799,'NNPV','THE FIFTH PLANET 5',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293799,'Marco Roeleveld','Alex van Hensbergen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293799,'Mark Molier','Peter Fokker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293799,'Rob Molier','Kilian Steen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293799,'Marco Roeleveld','Peter Fokker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293799,'Mark Molier','Kilian Steen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293799,'Rob Molier','Alex van Hensbergen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293799,'Rob Molier','Peter Fokker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293799,'Mark Molier','Alex van Hensbergen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293799,'Marco Roeleveld','Kilian Steen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2011%'),293802,'JUMBO 13','Team 1048',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293802,'Harry Vogelzang','Juan Moreno',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293802,'Jeroen Keijzer','Wouter Kager',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293802,'Lea Lindhout','Erik Veerman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293802,'Harry Vogelzang','Wouter Kager',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293802,'Jeroen Keijzer','Erik Veerman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293802,'Lea Lindhout','Juan Moreno',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293802,'Lea Lindhout','Wouter Kager',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293802,'Jeroen Keijzer','Juan Moreno',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293802,'Harry Vogelzang','Erik Veerman',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2011%'),293803,'THE FIFTH PLANET 5','SNOOKERIJ 10',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293803,'Thom Leenders','Peter Hoekstra',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293803,'Alex van Hensbergen','Harry Bartels',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293803,'Cor Wever','Margot Olree',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293803,'Thom Leenders','Harry Bartels',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293803,'Alex van Hensbergen','Margot Olree',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293803,'Cor Wever','Peter Hoekstra',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293803,'Cor Wever','Harry Bartels',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293803,'Alex van Hensbergen','Peter Hoekstra',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293803,'Thom Leenders','Margot Olree',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2011%'),293804,'Koetshuis 1','JUMBO 13',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293804,'Benjamin Tros','Jeroen Keijzer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293804,'Richard Kiljan','Menno Beugelsdijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293804,'Hans Reijerkerk','Harry Vogelzang',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293804,'Benjamin Tros','Menno Beugelsdijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293804,'Richard Kiljan','Harry Vogelzang',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293804,'Hans Reijerkerk','Jeroen Keijzer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293804,'Hans Reijerkerk','Menno Beugelsdijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293804,'Richard Kiljan','Jeroen Keijzer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293804,'Benjamin Tros','Harry Vogelzang',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2011%'),293805,'SNOOKERIJ 6','NNPV',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293805,'Edwin van Orssagen','Mark Molier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293805,'Mark van Vliet','Ruud Heufke Kantelaar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293805,'Robert van Nieuwkoop','Nico van Veen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293805,'Edwin van Orssagen','Ruud Heufke Kantelaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293805,'Mark van Vliet','Nico van Veen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293805,'Robert van Nieuwkoop','Mark Molier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293805,'Robert van Nieuwkoop','Ruud Heufke Kantelaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293805,'Mark van Vliet','Mark Molier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293805,'Edwin van Orssagen','Nico van Veen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-12-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2011%'),293810,'SNOOKERIJ 6','Team 1048',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-12-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2011%'),307759,'NNPV','SNOOKERIJ 10',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(307759,'Marco Roeleveld','Steve Course',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(307759,'Mark Molier','Margot Olree',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(307759,'Rob Molier','Peter Hoekstra',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(307759,'Marco Roeleveld','Margot Olree',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(307759,'Mark Molier','Peter Hoekstra',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(307759,'Rob Molier','Steve Course',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(307759,'Rob Molier','Margot Olree',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(307759,'Mark Molier','Steve Course',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(307759,'Marco Roeleveld','Peter Hoekstra',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-12-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2011%'),293814,'THE FIFTH PLANET 5','JUMBO 13',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293814,'Kilian Steen','Anton Lindhout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293814,'Alex van Hensbergen','Menno Beugelsdijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293814,'Peter Fokker','Harry Vogelzang',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293814,'Kilian Steen','Menno Beugelsdijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293814,'Alex van Hensbergen','Harry Vogelzang',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293814,'Peter Fokker','Anton Lindhout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293814,'Peter Fokker','Menno Beugelsdijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293814,'Alex van Hensbergen','Anton Lindhout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293814,'Kilian Steen','Harry Vogelzang',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-12-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2011%'),293815,'Koetshuis 1','SNOOKERIJ 6',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293815,'Benjamin Tros','Robert van Nieuwkoop',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293815,'Richard Kiljan','Edwin van Orssagen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293815,'Hans Reijerkerk','Roger Planje',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293815,'Benjamin Tros','Edwin van Orssagen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293815,'Richard Kiljan','Roger Planje',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293815,'Hans Reijerkerk','Robert van Nieuwkoop',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293815,'Hans Reijerkerk','Edwin van Orssagen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293815,'Richard Kiljan','Robert van Nieuwkoop',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293815,'Benjamin Tros','Roger Planje',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-12-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2011%'),293817,'Team 1048','NNPV',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293817,'Erik Veerman','Nico van Veen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293817,'Wouter Kager','Rob Molier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293817,'Erik Veerman','Ruud Heufke Kantelaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293817,'Wouter Kager','Nico van Veen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293817,'Wouter Kager','Ruud Heufke Kantelaar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293817,'Erik Veerman','Rob Molier',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2011%'),293821,'Team 1048','Koetshuis 1',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293821,'Erik Veerman','Hans Reijerkerk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293821,'Ruud van Mierlo','Benjamin Tros',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293821,'Daniël Veenboer','Richard Kiljan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293821,'Erik Veerman','Benjamin Tros',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293821,'Ruud van Mierlo','Richard Kiljan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293821,'Daniël Veenboer','Hans Reijerkerk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293821,'Daniël Veenboer','Benjamin Tros',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293821,'Ruud van Mierlo','Hans Reijerkerk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293821,'Erik Veerman','Richard Kiljan',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2011%'),293822,'JUMBO 13','SNOOKERIJ 10',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293822,'Menno Beugelsdijk','Kitt van der Jagt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293822,'Anton Lindhout','Steve Course',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293822,'Harry Vogelzang','Harry Bartels',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293822,'Menno Beugelsdijk','Steve Course',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293822,'Anton Lindhout','Harry Bartels',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293822,'Harry Vogelzang','Kitt van der Jagt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293822,'Harry Vogelzang','Steve Course',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293822,'Anton Lindhout','Kitt van der Jagt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293822,'Menno Beugelsdijk','Harry Bartels',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2011%'),293823,'Koetshuis 1','NNPV',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293823,'Benjamin Tros','Mark Molier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293823,'Hans Reijerkerk','Nico van Veen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293823,'Richard Kiljan','Ruud Heufke Kantelaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293823,'Benjamin Tros','Nico van Veen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293823,'Hans Reijerkerk','Ruud Heufke Kantelaar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293823,'Richard Kiljan','Mark Molier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293823,'Richard Kiljan','Nico van Veen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293823,'Hans Reijerkerk','Mark Molier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293823,'Benjamin Tros','Ruud Heufke Kantelaar',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2011%'),293824,'SNOOKERIJ 6','THE FIFTH PLANET 5',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293824,'Edwin van Orssagen','Thom Leenders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293824,'David Mourette','Cor Wever',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293824,'Roger Planje','Kilian Steen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293824,'Edwin van Orssagen','Cor Wever',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293824,'David Mourette','Kilian Steen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293824,'Roger Planje','Thom Leenders',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293824,'Roger Planje','Cor Wever',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293824,'David Mourette','Thom Leenders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293824,'Edwin van Orssagen','Kilian Steen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-02-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2011%'),293829,'NNPV','JUMBO 13',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293829,'Nico van Veen','Anton Lindhout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293829,'Rob Molier','Jeroen Keijzer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293829,'Ruud Heufke Kantelaar','Menno Beugelsdijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293829,'Nico van Veen','Jeroen Keijzer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293829,'Rob Molier','Menno Beugelsdijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293829,'Ruud Heufke Kantelaar','Anton Lindhout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293829,'Ruud Heufke Kantelaar','Jeroen Keijzer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293829,'Rob Molier','Anton Lindhout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293829,'Nico van Veen','Menno Beugelsdijk',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-02-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2011%'),293830,'SNOOKERIJ 10','SNOOKERIJ 6',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293830,'Peter Hoekstra','Mark van Vliet',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293830,'Hans Wolvers','Edwin van Orssagen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293830,'Kitt van der Jagt','Robert van Nieuwkoop',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293830,'Peter Hoekstra','Edwin van Orssagen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293830,'Hans Wolvers','Robert van Nieuwkoop',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293830,'Kitt van der Jagt','Mark van Vliet',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293830,'Kitt van der Jagt','Edwin van Orssagen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293830,'Hans Wolvers','Mark van Vliet',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293830,'Peter Hoekstra','Robert van Nieuwkoop',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-02-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2011%'),293831,'THE FIFTH PLANET 5','Team 1048',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293831,'Kilian Steen','Wouter Kager',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293831,'Alex van Hensbergen','Ruud van Mierlo',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293831,'Peter Fokker','Daniël Veenboer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293831,'Kilian Steen','Ruud van Mierlo',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293831,'Alex van Hensbergen','Daniël Veenboer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293831,'Peter Fokker','Wouter Kager',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293831,'Peter Fokker','Ruud van Mierlo',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293831,'Alex van Hensbergen','Wouter Kager',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293831,'Kilian Steen','Daniël Veenboer',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-02-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2011%'),293833,'Koetshuis 1','THE FIFTH PLANET 5',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293833,'Benjamin Tros','Cor Wever',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293833,'Richard Kiljan','Peter Fokker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293833,'Hans Reijerkerk','Thom Leenders',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293833,'Benjamin Tros','Peter Fokker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293833,'Richard Kiljan','Thom Leenders',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293833,'Hans Reijerkerk','Cor Wever',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293833,'Hans Reijerkerk','Peter Fokker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293833,'Richard Kiljan','Cor Wever',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293833,'Benjamin Tros','Thom Leenders',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-02-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2011%'),293837,'Team 1048','SNOOKERIJ 10',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293837,'Wouter Kager','Margot Olree',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293837,'Pieter van Tilburg','Kitt van der Jagt',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293837,'Wouter Kager','Hans Wolvers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293837,'Pieter van Tilburg','Margot Olree',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293837,'Pieter van Tilburg','Hans Wolvers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293837,'Wouter Kager','Kitt van der Jagt',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-03-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2011%'),293840,'SNOOKERIJ 10','Koetshuis 1',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293840,'Peter Hoekstra','Marco Kuperus',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293840,'Harry Bartels','Hans Reijerkerk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293840,'Kitt van der Jagt','Benjamin Tros',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293840,'Peter Hoekstra','Hans Reijerkerk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293840,'Harry Bartels','Benjamin Tros',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293840,'Kitt van der Jagt','Marco Kuperus',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293840,'Kitt van der Jagt','Hans Reijerkerk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293840,'Harry Bartels','Marco Kuperus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293840,'Peter Hoekstra','Benjamin Tros',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-03-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2011%'),293842,'JUMBO 13','SNOOKERIJ 6',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293842,'Menno Beugelsdijk','Robert van Nieuwkoop',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293842,'Anton Lindhout','Roger Planje',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293842,'Harry Vogelzang','Mark van Vliet',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293842,'Menno Beugelsdijk','Roger Planje',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293842,'Anton Lindhout','Mark van Vliet',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293842,'Harry Vogelzang','Robert van Nieuwkoop',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293842,'Harry Vogelzang','Roger Planje',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293842,'Anton Lindhout','Robert van Nieuwkoop',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293842,'Menno Beugelsdijk','Mark van Vliet',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-03-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2011%'),293843,'THE FIFTH PLANET 5','NNPV',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293843,'Kilian Steen','Rob Molier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293843,'Cor Wever','Marco Roeleveld',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293843,'Peter Fokker','Mark Molier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293843,'Kilian Steen','Marco Roeleveld',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293843,'Cor Wever','Mark Molier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293843,'Peter Fokker','Rob Molier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293843,'Peter Fokker','Marco Roeleveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293843,'Cor Wever','Rob Molier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293843,'Kilian Steen','Mark Molier',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('28-03-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2011%'),293847,'Team 1048','JUMBO 13',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293847,'Pieter van Tilburg','Jeroen Keijzer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293847,'Daniël Veenboer','Harry Vogelzang',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293847,'Juan Moreno','Menno Beugelsdijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293847,'Pieter van Tilburg','Harry Vogelzang',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293847,'Daniël Veenboer','Menno Beugelsdijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293847,'Juan Moreno','Jeroen Keijzer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293847,'Juan Moreno','Harry Vogelzang',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293847,'Daniël Veenboer','Jeroen Keijzer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293847,'Pieter van Tilburg','Menno Beugelsdijk',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-04-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2011%'),293849,'NNPV','SNOOKERIJ 6',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293849,'Marco Roeleveld','Roger Planje',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293849,'Ruud Heufke Kantelaar','Edwin van Orssagen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293849,'Nico van Veen','Mark van Vliet',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293849,'Marco Roeleveld','Edwin van Orssagen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293849,'Ruud Heufke Kantelaar','Mark van Vliet',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293849,'Nico van Veen','Roger Planje',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293849,'Nico van Veen','Edwin van Orssagen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293849,'Ruud Heufke Kantelaar','Roger Planje',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293849,'Marco Roeleveld','Mark van Vliet',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-04-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2011%'),293850,'SNOOKERIJ 10','THE FIFTH PLANET 5',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-04-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2011%'),293852,'JUMBO 13','Koetshuis 1',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293852,'Anton Lindhout','Benjamin Tros',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293852,'Jeroen Keijzer','Sander Nijssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293852,'Harry Vogelzang','Hans Reijerkerk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293852,'Anton Lindhout','Sander Nijssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293852,'Jeroen Keijzer','Hans Reijerkerk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293852,'Harry Vogelzang','Benjamin Tros',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293852,'Harry Vogelzang','Sander Nijssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293852,'Jeroen Keijzer','Benjamin Tros',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293852,'Anton Lindhout','Hans Reijerkerk',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-04-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2011%'),293853,'SNOOKERIJ 10','NNPV',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-04-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2011%'),293857,'Team 1048','SNOOKERIJ 6',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293857,'Ruud van Mierlo','David Mourette',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293857,'Daniël Veenboer','Robert van Nieuwkoop',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293857,'Wouter Kager','Roger Planje',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293857,'Ruud van Mierlo','Robert van Nieuwkoop',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293857,'Daniël Veenboer','Roger Planje',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293857,'Wouter Kager','David Mourette',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293857,'Wouter Kager','Robert van Nieuwkoop',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293857,'Daniël Veenboer','David Mourette',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293857,'Ruud van Mierlo','Roger Planje',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2011%'),293859,'NNPV','Team 1048',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2011%'),293860,'SNOOKERIJ 6','Koetshuis 1',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293860,'Edwin van Orssagen','Benjamin Tros',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293860,'Robert van Nieuwkoop','Hans Reijerkerk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293860,'David Mourette','Marco Kuperus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293860,'Edwin van Orssagen','Hans Reijerkerk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293860,'Robert van Nieuwkoop','Marco Kuperus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293860,'David Mourette','Benjamin Tros',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293860,'David Mourette','Hans Reijerkerk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293860,'Robert van Nieuwkoop','Benjamin Tros',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293860,'Edwin van Orssagen','Marco Kuperus',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2011%'),293862,'JUMBO 13','THE FIFTH PLANET 5',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293862,'Harry Vogelzang','Cor Wever',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293862,'Jeroen Keijzer','Fred Wurtz',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293862,'Menno Beugelsdijk','Peter Fokker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293862,'Harry Vogelzang','Fred Wurtz',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293862,'Jeroen Keijzer','Peter Fokker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293862,'Menno Beugelsdijk','Cor Wever',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293862,'Menno Beugelsdijk','Fred Wurtz',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293862,'Jeroen Keijzer','Cor Wever',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293862,'Harry Vogelzang','Peter Fokker',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2011%'),293864,'SNOOKERIJ 10','JUMBO 13',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293864,'Peter Hoekstra','Harry Vogelzang',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293864,'Margot Olree','Menno Beugelsdijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293864,'Kitt van der Jagt','Jeroen Keijzer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293864,'Peter Hoekstra','Menno Beugelsdijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293864,'Margot Olree','Jeroen Keijzer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293864,'Kitt van der Jagt','Harry Vogelzang',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293864,'Kitt van der Jagt','Menno Beugelsdijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293864,'Margot Olree','Harry Vogelzang',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293864,'Peter Hoekstra','Jeroen Keijzer',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 1' and ssn_id like '2011%'),293866,'Koetshuis 1','Team 1048',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293866,'Benjamin Tros','Erik Veerman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293866,'Richard Kiljan','Pieter van Tilburg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293866,'Hans Reijerkerk','Wouter Kager',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293866,'Benjamin Tros','Pieter van Tilburg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293866,'Richard Kiljan','Wouter Kager',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293866,'Hans Reijerkerk','Erik Veerman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293866,'Hans Reijerkerk','Pieter van Tilburg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293866,'Richard Kiljan','Erik Veerman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293866,'Benjamin Tros','Wouter Kager',0,1);
