delete from cm_match_details where game_id in (select game_id from cm_matches where cpn_id = (select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'));
delete from cm_matches where cpn_id = (select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%');
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-09-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424333,'OLD REBELS','SU 3 Fouls doen we nie',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424333,'Eric Feteridge','Debabrata Panja',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424333,'John Rodrigues Garcia','Peter Verstraten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424333,'Jef Raber','Michiel Vlootman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424333,'Eric Feteridge','Peter Verstraten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424333,'John Rodrigues Garcia','Michiel Vlootman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424333,'Jef Raber','Debabrata Panja',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424333,'Jef Raber','Peter Verstraten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424333,'John Rodrigues Garcia','Debabrata Panja',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424333,'Eric Feteridge','Michiel Vlootman',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-09-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424334,'SNOOKERIJ 5','SPDC 1',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424334,'Robert van Nieuwkoop','Roland Reinders',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424334,'Pascal Hendrikse','Jacques Niehof',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424334,'Joris Scharpff','Martin Rakké',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424334,'Robert van Nieuwkoop','Jacques Niehof',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424334,'Pascal Hendrikse','Martin Rakké',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424334,'Joris Scharpff','Roland Reinders',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424334,'Joris Scharpff','Jacques Niehof',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424334,'Pascal Hendrikse','Roland Reinders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424334,'Robert van Nieuwkoop','Martin Rakké',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-09-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424335,'SNOOKERIJ 10','SNOOKERIJ 17',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-09-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424338,'SU 3 Fouls doen we nie','SNOOKERIJ 10',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424338,'Michiel Vlootman','Kitt van der Jagt',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424338,'Debabrata Panja','Peter Hoekstra',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424338,'Wouter Teensma','Margot Olree',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424338,'Michiel Vlootman','Peter Hoekstra',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424338,'Debabrata Panja','Margot Olree',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424338,'Wouter Teensma','Kitt van der Jagt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424338,'Wouter Teensma','Peter Hoekstra',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424338,'Debabrata Panja','Kitt van der Jagt',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424338,'Michiel Vlootman','Margot Olree',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('26-09-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424339,'Spaernehuis 1','SNOOKERIJ 5',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('01-10-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424342,'THE FIFTH PLANET 5','SU 3 Fouls doen we nie',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424342,'Peter Fokker','Debabrata Panja',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424342,'Edwin van Vugt','Wouter Teensma',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424342,'Peter Fokker','Wouter Teensma',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424342,'Fred Wurtz','Debabrata Panja',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424342,'Fred Wurtz','Wouter Teensma',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424342,'Edwin van Vugt','Debabrata Panja',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-10-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),426935,'SPDC 1','OLD REBELS',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(426935,'Martin Rakké','Eric Feteridge',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(426935,'Roland Reinders','John Rodrigues Garcia',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(426935,'Jacques Niehof','Jef Raber',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(426935,'Martin Rakké','John Rodrigues Garcia',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(426935,'Roland Reinders','Jef Raber',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(426935,'Jacques Niehof','Eric Feteridge',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(426935,'Jacques Niehof','John Rodrigues Garcia',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(426935,'Roland Reinders','Eric Feteridge',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(426935,'Martin Rakké','Jef Raber',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-10-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),428967,'SNOOKERIJ 10','SPDC 1',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(428967,'Nico Seisveld','Roland Reinders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(428967,'Harry Bartels','Jacques Niehof',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(428967,'Margot Olree','Martin Rakké',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(428967,'Nico Seisveld','Jacques Niehof',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(428967,'Harry Bartels','Martin Rakké',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(428967,'Margot Olree','Roland Reinders',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(428967,'Margot Olree','Jacques Niehof',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(428967,'Harry Bartels','Roland Reinders',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(428967,'Nico Seisveld','Martin Rakké',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-10-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424346,'SNOOKERIJ 5','OLD REBELS',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-10-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424347,'SPDC 1','THE FIFTH PLANET 5',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424347,'Martin Rakké','Cor Wever',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424347,'Roland Reinders','Peter Fokker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424347,'Jacques Niehof','Edwin van Vugt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424347,'Martin Rakké','Peter Fokker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424347,'Roland Reinders','Edwin van Vugt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424347,'Jacques Niehof','Cor Wever',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424347,'Jacques Niehof','Peter Fokker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424347,'Roland Reinders','Cor Wever',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424347,'Martin Rakké','Edwin van Vugt',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-10-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424349,'Spaernehuis 1','SNOOKERIJ 10',9,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424349,'David Prins','Steve Course',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424349,'Anton Kerstholt','Kitt van der Jagt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424349,'Barry Lambers','Nico Seisveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424349,'David Prins','Kitt van der Jagt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424349,'Anton Kerstholt','Nico Seisveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424349,'Barry Lambers','Steve Course',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424349,'Barry Lambers','Kitt van der Jagt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424349,'Anton Kerstholt','Steve Course',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424349,'David Prins','Nico Seisveld',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-10-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424350,'SNOOKERIJ 17','OZEBI 3',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424350,'Jan Willem Basselier','Marijn Sloots',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424350,'Pieter Verbeek','René Kerkhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424350,'Timo van Poppel','Kees Reijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424350,'Jan Willem Basselier','René Kerkhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424350,'Pieter Verbeek','Kees Reijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424350,'Timo van Poppel','Marijn Sloots',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424350,'Timo van Poppel','René Kerkhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424350,'Pieter Verbeek','Marijn Sloots',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424350,'Jan Willem Basselier','Kees Reijn',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-10-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424353,'THE FIFTH PLANET 5','Spaernehuis 1',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424353,'Peter Fokker','Anton Kerstholt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424353,'Fred Wurtz','Barry Lambers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424353,'Cor Wever','David Prins',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424353,'Peter Fokker','Barry Lambers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424353,'Fred Wurtz','David Prins',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424353,'Cor Wever','Anton Kerstholt',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424353,'Cor Wever','Barry Lambers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424353,'Fred Wurtz','Anton Kerstholt',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424353,'Peter Fokker','David Prins',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-10-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424354,'SNOOKERIJ 10','SNOOKERIJ 5',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-10-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424355,'OZEBI 3','SU 3 Fouls doen we nie',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424355,'Marijn Sloots','Wouter Teensma',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424355,'Jeroen Sloots','Debabrata Panja',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424355,'Robert Rodenburg','Wouter Teensma',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424355,'Marijn Sloots','Debabrata Panja',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424355,'Jeroen Sloots','Wouter Teensma',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424355,'Robert Rodenburg','Debabrata Panja',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('31-10-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),431065,'SNOOKERIJ 17','THE FIFTH PLANET 5',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431065,'Hermen Breugem','Cor Wever',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431065,'Jan Willem Basselier','Thom Leenders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431065,'Timo van Poppel','Edwin van Vugt',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431065,'Hermen Breugem','Thom Leenders',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431065,'Jan Willem Basselier','Edwin van Vugt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431065,'Timo van Poppel','Cor Wever',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431065,'Timo van Poppel','Thom Leenders',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431065,'Jan Willem Basselier','Cor Wever',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431065,'Hermen Breugem','Edwin van Vugt',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-11-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424356,'OLD REBELS','SNOOKERIJ 10',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424356,'Eric Feteridge','Steve Course',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424356,'John Rodrigues Garcia','Nico Seisveld',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424356,'Ed van den Berg','Margot Olree',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424356,'Eric Feteridge','Nico Seisveld',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424356,'John Rodrigues Garcia','Margot Olree',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424356,'Ed van den Berg','Steve Course',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424356,'Ed van den Berg','Nico Seisveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424356,'John Rodrigues Garcia','Steve Course',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424356,'Eric Feteridge','Margot Olree',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-11-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424357,'SNOOKERIJ 5','THE FIFTH PLANET 5',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424357,'Jan van Amsterdam','Edwin van Vugt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424357,'Robert van Nieuwkoop','Cor Wever',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424357,'Joris Scharpff','Peter Fokker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424357,'Jan van Amsterdam','Cor Wever',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424357,'Robert van Nieuwkoop','Peter Fokker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424357,'Joris Scharpff','Edwin van Vugt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424357,'Joris Scharpff','Cor Wever',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424357,'Robert van Nieuwkoop','Edwin van Vugt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424357,'Jan van Amsterdam','Peter Fokker',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-11-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424358,'SPDC 1','OZEBI 3',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424358,'Martin Rakké','Marijn Sloots',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424358,'Roland Reinders','Kees Reijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424358,'Jacques Niehof','René Kerkhoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424358,'Martin Rakké','Kees Reijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424358,'Roland Reinders','René Kerkhoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424358,'Jacques Niehof','Marijn Sloots',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424358,'Jacques Niehof','Kees Reijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424358,'Roland Reinders','Marijn Sloots',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424358,'Martin Rakké','René Kerkhoven',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-11-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424363,'THE FIFTH PLANET 5','OLD REBELS',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424363,'Fred Wurtz','John Rodrigues Garcia',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424363,'Cor Wever','Jef Raber',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424363,'Thom Leenders','Eric Feteridge',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424363,'Fred Wurtz','Jef Raber',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424363,'Cor Wever','Eric Feteridge',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424363,'Thom Leenders','John Rodrigues Garcia',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424363,'Thom Leenders','Jef Raber',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424363,'Cor Wever','John Rodrigues Garcia',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424363,'Fred Wurtz','Eric Feteridge',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-11-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424364,'SNOOKERIJ 17','SU 3 Fouls doen we nie',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424364,'Jan Willem Basselier','Wouter Teensma',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424364,'Timo van Poppel','Michiel Vlootman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424364,'Hermen Breugem','Michiel Vlootman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424364,'Timo van Poppel','Wouter Teensma',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424364,'Hermen Breugem','Wouter Teensma',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424364,'Jan Willem Basselier','Michiel Vlootman',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-11-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424365,'OZEBI 3','Spaernehuis 1',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('26-11-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424367,'SNOOKERIJ 5','OZEBI 3',8,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('26-11-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424368,'SPDC 1','SNOOKERIJ 17',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424368,'Martin Rakké','Hermen Breugem',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424368,'Roland Reinders','Timo van Poppel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424368,'Jacques Niehof','Jan Willem Basselier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424368,'Martin Rakké','Timo van Poppel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424368,'Roland Reinders','Jan Willem Basselier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424368,'Jacques Niehof','Hermen Breugem',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424368,'Jacques Niehof','Timo van Poppel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424368,'Roland Reinders','Hermen Breugem',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424368,'Martin Rakké','Jan Willem Basselier',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('28-11-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424370,'SNOOKERIJ 10','THE FIFTH PLANET 5',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424370,'Nico Seisveld','Edwin van Vugt',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424370,'Kitt van der Jagt','Thom Leenders',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424370,'Harry Bartels','Peter Fokker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424370,'Nico Seisveld','Thom Leenders',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424370,'Kitt van der Jagt','Peter Fokker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424370,'Harry Bartels','Edwin van Vugt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424370,'Harry Bartels','Thom Leenders',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424370,'Kitt van der Jagt','Edwin van Vugt',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424370,'Nico Seisveld','Peter Fokker',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-12-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424373,'SU 3 Fouls doen we nie','SPDC 1',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424373,'Michiel Vlootman','Roland Reinders',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424373,'Peter Verstraten','Jacques Niehof',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424373,'Wouter Teensma','Martin Rakké',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424373,'Michiel Vlootman','Jacques Niehof',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424373,'Peter Verstraten','Martin Rakké',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424373,'Wouter Teensma','Roland Reinders',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424373,'Wouter Teensma','Jacques Niehof',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424373,'Peter Verstraten','Roland Reinders',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424373,'Michiel Vlootman','Martin Rakké',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-12-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424374,'SNOOKERIJ 17','Spaernehuis 1',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-12-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424375,'OZEBI 3','OLD REBELS',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424375,'Robert Rodenburg','Eric Feteridge',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424375,'Kees Reijn','John Rodrigues Garcia',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424375,'Marijn Sloots','Ed van den Berg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424375,'Robert Rodenburg','John Rodrigues Garcia',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424375,'Kees Reijn','Ed van den Berg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424375,'Marijn Sloots','Eric Feteridge',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424375,'Marijn Sloots','John Rodrigues Garcia',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424375,'Kees Reijn','Eric Feteridge',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424375,'Robert Rodenburg','Ed van den Berg',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-12-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),431292,'OLD REBELS','Spaernehuis 1',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431292,'Eric Feteridge','Anton Kerstholt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431292,'Ed van den Berg','Barry Lambers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431292,'Jef Raber','David Prins',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431292,'Eric Feteridge','Barry Lambers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431292,'Ed van den Berg','David Prins',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431292,'Jef Raber','Anton Kerstholt',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431292,'Jef Raber','Barry Lambers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431292,'Ed van den Berg','Anton Kerstholt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431292,'Eric Feteridge','David Prins',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-12-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424378,'SNOOKERIJ 5','SNOOKERIJ 17',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424378,'Robert van Nieuwkoop','Hermen Breugem',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424378,'Pascal Hendrikse','Timo van Poppel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424378,'Joris Scharpff','Jan Willem Basselier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424378,'Robert van Nieuwkoop','Timo van Poppel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424378,'Pascal Hendrikse','Jan Willem Basselier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424378,'Joris Scharpff','Hermen Breugem',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424378,'Joris Scharpff','Timo van Poppel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424378,'Pascal Hendrikse','Hermen Breugem',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424378,'Robert van Nieuwkoop','Jan Willem Basselier',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-12-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424379,'Spaernehuis 1','SU 3 Fouls doen we nie',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424379,'David Prins','Wouter Teensma',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424379,'Anton Kerstholt','Michiel Vlootman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424379,'David Prins','Michiel Vlootman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424379,'Barry Lambers','Wouter Teensma',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424379,'Barry Lambers','Michiel Vlootman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424379,'Anton Kerstholt','Wouter Teensma',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-12-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424380,'SNOOKERIJ 10','OZEBI 3',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-01-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424382,'SPDC 1','Spaernehuis 1',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424382,'Martin Rakké','Anton Kerstholt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424382,'Roland Reinders','Barry Lambers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424382,'Jacques Niehof','David Prins',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424382,'Martin Rakké','Barry Lambers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424382,'Roland Reinders','David Prins',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424382,'Jacques Niehof','Anton Kerstholt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424382,'Jacques Niehof','Barry Lambers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424382,'Roland Reinders','Anton Kerstholt',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424382,'Martin Rakké','David Prins',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-01-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424383,'SU 3 Fouls doen we nie','SNOOKERIJ 5',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424383,'Debabrata Panja','Robert van Nieuwkoop',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424383,'Peter Verstraten','David Mourette',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424383,'Debabrata Panja','Pascal Hendrikse',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424383,'Peter Verstraten','Robert van Nieuwkoop',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424383,'Peter Verstraten','Pascal Hendrikse',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424383,'Debabrata Panja','David Mourette',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-01-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424384,'SNOOKERIJ 17','OLD REBELS',8,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-01-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424385,'OZEBI 3','THE FIFTH PLANET 5',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424385,'Marijn Sloots','Edwin van Vugt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424385,'Kees Reijn','Fred Wurtz',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424385,'René Kerkhoven','Peter Fokker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424385,'Marijn Sloots','Fred Wurtz',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424385,'Kees Reijn','Peter Fokker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424385,'René Kerkhoven','Edwin van Vugt',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424385,'René Kerkhoven','Fred Wurtz',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424385,'Kees Reijn','Edwin van Vugt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424385,'Marijn Sloots','Peter Fokker',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-01-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424387,'SPDC 1','SNOOKERIJ 5',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424387,'Martin Rakké','Pascal Hendrikse',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424387,'Roland Reinders','Joris Scharpff',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424387,'Jacques Niehof','David Mourette',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424387,'Martin Rakké','Joris Scharpff',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424387,'Roland Reinders','David Mourette',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424387,'Jacques Niehof','Pascal Hendrikse',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424387,'Jacques Niehof','Joris Scharpff',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424387,'Roland Reinders','Pascal Hendrikse',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424387,'Martin Rakké','David Mourette',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-01-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424388,'SU 3 Fouls doen we nie','OLD REBELS',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-01-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424389,'SNOOKERIJ 17','SNOOKERIJ 10',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('25-02-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424392,'THE FIFTH PLANET 5','SNOOKERIJ 17',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424392,'Peter Fokker','Jan Willem Basselier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424392,'Fred Wurtz','Hermen Breugem',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424392,'Cor Wever','Timo van Poppel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424392,'Peter Fokker','Hermen Breugem',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424392,'Fred Wurtz','Timo van Poppel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424392,'Cor Wever','Jan Willem Basselier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424392,'Cor Wever','Hermen Breugem',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424392,'Fred Wurtz','Jan Willem Basselier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424392,'Peter Fokker','Timo van Poppel',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('25-02-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424394,'SNOOKERIJ 5','Spaernehuis 1',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424394,'David Mourette','Anton Kerstholt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424394,'Pascal Hendrikse','Barry Lambers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424394,'Joris Scharpff','David Prins',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424394,'David Mourette','Barry Lambers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424394,'Pascal Hendrikse','David Prins',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424394,'Joris Scharpff','Anton Kerstholt',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424394,'Joris Scharpff','Barry Lambers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424394,'Pascal Hendrikse','Anton Kerstholt',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424394,'David Mourette','David Prins',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-03-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424397,'SPDC 1','SNOOKERIJ 10',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-03-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424398,'SU 3 Fouls doen we nie','THE FIFTH PLANET 5',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424398,'Michiel Vlootman','Cor Wever',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424398,'Debabrata Panja','Thom Leenders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424398,'Peter Verstraten','Peter Fokker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424398,'Michiel Vlootman','Thom Leenders',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424398,'Debabrata Panja','Peter Fokker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424398,'Peter Verstraten','Cor Wever',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424398,'Peter Verstraten','Thom Leenders',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424398,'Debabrata Panja','Cor Wever',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424398,'Michiel Vlootman','Peter Fokker',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-03-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424399,'Spaernehuis 1','OLD REBELS',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424399,'Barry Lambers','Ed van den Berg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424399,'Anton Kerstholt','Eric Feteridge',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424399,'David Prins','John Rodrigues Garcia',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424399,'Barry Lambers','Eric Feteridge',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424399,'Anton Kerstholt','John Rodrigues Garcia',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424399,'David Prins','Ed van den Berg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424399,'David Prins','Eric Feteridge',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424399,'Anton Kerstholt','Ed van den Berg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424399,'Barry Lambers','John Rodrigues Garcia',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-03-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424402,'THE FIFTH PLANET 5','SPDC 1',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424402,'Edwin van Vugt','Martin Rakké',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424402,'Fred Wurtz','Jacques Niehof',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424402,'Thom Leenders','Roland Reinders',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424402,'Edwin van Vugt','Jacques Niehof',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424402,'Fred Wurtz','Roland Reinders',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424402,'Thom Leenders','Martin Rakké',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424402,'Thom Leenders','Jacques Niehof',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424402,'Fred Wurtz','Martin Rakké',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424402,'Edwin van Vugt','Roland Reinders',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-03-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424403,'OLD REBELS','SNOOKERIJ 5',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424403,'Eric Feteridge','Robert van Nieuwkoop',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424403,'John Rodrigues Garcia','David Mourette',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424403,'Jef Raber','Jan van Amsterdam',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424403,'Eric Feteridge','David Mourette',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424403,'John Rodrigues Garcia','Jan van Amsterdam',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424403,'Jef Raber','Robert van Nieuwkoop',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424403,'Jef Raber','David Mourette',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424403,'John Rodrigues Garcia','Robert van Nieuwkoop',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424403,'Eric Feteridge','Jan van Amsterdam',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-03-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424404,'SNOOKERIJ 10','Spaernehuis 1',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424404,'Nico Seisveld','Anton Kerstholt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424404,'Harry Bartels','Barry Lambers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424404,'Margot Olree','David Prins',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424404,'Nico Seisveld','Barry Lambers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424404,'Harry Bartels','David Prins',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424404,'Margot Olree','Anton Kerstholt',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424404,'Margot Olree','Barry Lambers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424404,'Harry Bartels','Anton Kerstholt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424404,'Nico Seisveld','David Prins',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-03-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424405,'OZEBI 3','SNOOKERIJ 17',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-03-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424406,'SNOOKERIJ 5','SNOOKERIJ 10',8,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-03-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424408,'SU 3 Fouls doen we nie','OZEBI 3',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-03-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),434059,'OLD REBELS','THE FIFTH PLANET 5',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434059,'Jef Raber','Edwin van Vugt',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434059,'Eric Feteridge','Cor Wever',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434059,'Ed van den Berg','Peter Fokker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434059,'Jef Raber','Cor Wever',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434059,'Eric Feteridge','Peter Fokker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434059,'Ed van den Berg','Edwin van Vugt',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434059,'Ed van den Berg','Cor Wever',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434059,'Eric Feteridge','Edwin van Vugt',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434059,'Jef Raber','Peter Fokker',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-03-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424409,'Spaernehuis 1','THE FIFTH PLANET 5',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424409,'David Prins','Cor Wever',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424409,'Anton Kerstholt','Edwin van Vugt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424409,'Barry Lambers','Peter Fokker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424409,'David Prins','Edwin van Vugt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424409,'Anton Kerstholt','Peter Fokker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424409,'Barry Lambers','Cor Wever',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424409,'Barry Lambers','Edwin van Vugt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424409,'Anton Kerstholt','Cor Wever',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424409,'David Prins','Peter Fokker',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-04-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424413,'THE FIFTH PLANET 5','SNOOKERIJ 5',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424413,'Peter Fokker','David Mourette',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424413,'Edwin van Vugt','Joris Scharpff',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424413,'Cor Wever','Jan van Amsterdam',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424413,'Peter Fokker','Joris Scharpff',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424413,'Edwin van Vugt','Jan van Amsterdam',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424413,'Cor Wever','David Mourette',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424413,'Cor Wever','Joris Scharpff',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424413,'Edwin van Vugt','David Mourette',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424413,'Peter Fokker','Jan van Amsterdam',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-04-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424414,'SNOOKERIJ 10','OLD REBELS',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-04-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424415,'OZEBI 3','SPDC 1',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424415,'Robert Rodenburg','Roland Reinders',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424415,'Kees Reijn','Jacques Niehof',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424415,'Marijn Sloots','Martin Rakké',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424415,'Robert Rodenburg','Jacques Niehof',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424415,'Kees Reijn','Martin Rakké',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424415,'Marijn Sloots','Roland Reinders',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424415,'Marijn Sloots','Jacques Niehof',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424415,'Kees Reijn','Roland Reinders',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424415,'Robert Rodenburg','Martin Rakké',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-04-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424419,'SU 3 Fouls doen we nie','SNOOKERIJ 17',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424419,'Justin van Emstede','Hermen Breugem',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424419,'Rene Bos','Timo van Poppel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424419,'Peter Verstraten','Jan Willem Basselier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424419,'Justin van Emstede','Timo van Poppel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424419,'Rene Bos','Jan Willem Basselier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424419,'Peter Verstraten','Hermen Breugem',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424419,'Peter Verstraten','Timo van Poppel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424419,'Rene Bos','Hermen Breugem',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424419,'Justin van Emstede','Jan Willem Basselier',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-04-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),434516,'SNOOKERIJ 10','SU 3 Fouls doen we nie',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-04-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424420,'Spaernehuis 1','OZEBI 3',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424420,'David Prins','Jeroen Sloots',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424420,'Anton Kerstholt','René Kerkhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424420,'Barry Lambers','Kees Reijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424420,'David Prins','René Kerkhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424420,'Anton Kerstholt','Kees Reijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424420,'Barry Lambers','Jeroen Sloots',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424420,'Barry Lambers','René Kerkhoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424420,'Anton Kerstholt','Jeroen Sloots',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424420,'David Prins','Kees Reijn',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-04-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424423,'THE FIFTH PLANET 5','SNOOKERIJ 10',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424423,'Peter Fokker','Peter Hoekstra',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424423,'Edwin van Vugt','Nico Seisveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424423,'Fred Wurtz','Kitt van der Jagt',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424423,'Peter Fokker','Nico Seisveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424423,'Edwin van Vugt','Kitt van der Jagt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424423,'Fred Wurtz','Peter Hoekstra',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424423,'Fred Wurtz','Nico Seisveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424423,'Edwin van Vugt','Peter Hoekstra',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424423,'Peter Fokker','Kitt van der Jagt',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-04-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424424,'SNOOKERIJ 17','SPDC 1',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-04-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424425,'OZEBI 3','SNOOKERIJ 5',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-05-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424426,'OLD REBELS','OZEBI 3',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424426,'Ed van den Berg','Marijn Sloots',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424426,'Eric Feteridge','Jeroen Sloots',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424426,'John Rodrigues Garcia','Kees Reijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424426,'Ed van den Berg','Jeroen Sloots',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424426,'Eric Feteridge','Kees Reijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424426,'John Rodrigues Garcia','Marijn Sloots',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424426,'John Rodrigues Garcia','Jeroen Sloots',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424426,'Eric Feteridge','Marijn Sloots',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424426,'Ed van den Berg','Kees Reijn',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-05-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424428,'SPDC 1','SU 3 Fouls doen we nie',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424428,'Martin Rakké','Wouter Teensma',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424428,'Roland Reinders','Peter Verstraten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424428,'Jacques Niehof','Rene Bos',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424428,'Martin Rakké','Peter Verstraten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424428,'Roland Reinders','Rene Bos',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424428,'Jacques Niehof','Wouter Teensma',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424428,'Jacques Niehof','Peter Verstraten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424428,'Roland Reinders','Wouter Teensma',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424428,'Martin Rakké','Rene Bos',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-05-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424429,'Spaernehuis 1','SNOOKERIJ 17',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424429,'David Prins','Pieter Verbeek',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424429,'Anton Kerstholt','Jan Willem Basselier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424429,'Barry Lambers','Timo van Poppel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424429,'David Prins','Jan Willem Basselier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424429,'Anton Kerstholt','Timo van Poppel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424429,'Barry Lambers','Pieter Verbeek',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424429,'Barry Lambers','Jan Willem Basselier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424429,'Anton Kerstholt','Pieter Verbeek',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424429,'David Prins','Timo van Poppel',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-05-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),435076,'OLD REBELS','SPDC 1',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435076,'Eric Feteridge','Roland Reinders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435076,'Ed van den Berg','Jacques Niehof',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435076,'Jef Raber','Martin Rakké',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435076,'Eric Feteridge','Jacques Niehof',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435076,'Ed van den Berg','Martin Rakké',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435076,'Jef Raber','Roland Reinders',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435076,'Jef Raber','Jacques Niehof',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435076,'Ed van den Berg','Roland Reinders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435076,'Eric Feteridge','Martin Rakké',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-05-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424433,'SU 3 Fouls doen we nie','Spaernehuis 1',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-05-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424434,'SNOOKERIJ 17','SNOOKERIJ 5',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-05-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424435,'OZEBI 3','SNOOKERIJ 10',8,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-05-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),433121,'Spaernehuis 1','SPDC 1',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433121,'David Prins','Roland Reinders',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433121,'Anton Kerstholt','Jacques Niehof',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433121,'Barry Lambers','Martin Rakké',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433121,'David Prins','Jacques Niehof',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433121,'Anton Kerstholt','Martin Rakké',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433121,'Barry Lambers','Roland Reinders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433121,'Barry Lambers','Jacques Niehof',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433121,'Anton Kerstholt','Roland Reinders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433121,'David Prins','Martin Rakké',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-05-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424436,'THE FIFTH PLANET 5','OZEBI 3',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-05-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424437,'OLD REBELS','SNOOKERIJ 17',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424437,'Ed van den Berg','Hermen Breugem',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424437,'Jef Raber','Timo van Poppel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424437,'Eric Feteridge','Jan Willem Basselier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424437,'Ed van den Berg','Timo van Poppel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424437,'Jef Raber','Jan Willem Basselier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424437,'Eric Feteridge','Hermen Breugem',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424437,'Eric Feteridge','Timo van Poppel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424437,'Jef Raber','Hermen Breugem',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424437,'Ed van den Berg','Jan Willem Basselier',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-05-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede divisie A' and ssn_id like '2013%'),424438,'SNOOKERIJ 5','SU 3 Fouls doen we nie',4,5);
