delete from cm_match_details where game_id in (select game_id from cm_matches where cpn_id = (select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'));
delete from cm_matches where cpn_id = (select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%');
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-09-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293868,'BSCZ 2','Deltaplant',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-09-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293870,'JUMBO 3','HOGEWOERD 3',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293870,'Arnoud Videler','Aniel Kalicharan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293870,'Debbie Anthonissen','Dian Koning',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293870,'Arnoud Videler','Soerin Ganga',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293870,'Debbie Anthonissen','Aniel Kalicharan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293870,'Debbie Anthonissen','Soerin Ganga',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293870,'Arnoud Videler','Dian Koning',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-09-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293871,'THE POCKET 2','SNOOKERIJ 8',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293871,'Kees van Duijn','Huibert van de Putte',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293871,'Thomas Glasbergen','Harry van Exter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293871,'Johan Keizer','Rinus Devilee',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293871,'Kees van Duijn','Harry van Exter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293871,'Thomas Glasbergen','Rinus Devilee',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293871,'Johan Keizer','Huibert van de Putte',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293871,'Johan Keizer','Harry van Exter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293871,'Thomas Glasbergen','Huibert van de Putte',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293871,'Kees van Duijn','Rinus Devilee',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('26-09-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293873,'Deltaplant','JUMBO 3',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293873,'Regi Verdoorn','Rob Oudshoorn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293873,'Peter Bruggeman','Arnoud Videler',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293873,'Regi Verdoorn','Arnoud Videler',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293873,'Martijn Laan','Rob Oudshoorn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293873,'Martijn Laan','Arnoud Videler',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293873,'Peter Bruggeman','Rob Oudshoorn',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('26-09-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293874,'HOGEWOERD 3','SNOOKERIJ 5',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('30-09-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293877,'SNOOKERIJ 8','BSCZ 2',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293877,'Rinus Devilee','Peter Hulst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293877,'Huibert van de Putte','Richard Blouw',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293877,'Rinus Devilee','Paul van Leeuwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293877,'Huibert van de Putte','Peter Hulst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293877,'Huibert van de Putte','Paul van Leeuwen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293877,'Rinus Devilee','Richard Blouw',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-10-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293878,'BSCZ 2','JUMBO 3',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293878,'Lars Onvlee','Rob Oudshoorn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293878,'Peter Hulst','Debbie Anthonissen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293878,'Lars Onvlee','Debbie Anthonissen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293878,'Richard Blouw','Rob Oudshoorn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293878,'Richard Blouw','Debbie Anthonissen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293878,'Peter Hulst','Rob Oudshoorn',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-10-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293879,'SNOOKERIJ 5','Deltaplant',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293879,'John Meijer','Frank van der Laan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293879,'Joris Scharpff','Peter Bruggeman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293879,'Pascal Hendrikse','John Pape',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293879,'John Meijer','Peter Bruggeman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293879,'Joris Scharpff','John Pape',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293879,'Pascal Hendrikse','Frank van der Laan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293879,'Pascal Hendrikse','Peter Bruggeman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293879,'Joris Scharpff','Frank van der Laan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293879,'John Meijer','John Pape',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-10-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293880,'THE POCKET 2','BSCZ 1',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293880,'Kees van Duijn','Peter den Boer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293880,'Marcel van de Oever','Glenn van Polanen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293880,'Kees van Duijn','Glenn van Polanen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293880,'Thomas Glasbergen','Peter den Boer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293880,'Thomas Glasbergen','Glenn van Polanen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293880,'Marcel van de Oever','Peter den Boer',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-10-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293882,'SNOOKERIJ 8','SNOOKERIJ 17',0,9);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293882,'Rinus Devilee','Jan Willem Basselier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293882,'Harry van Exter','Hermen Breugem',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293882,'Rinus Devilee','Pieter Verbeek',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293882,'Harry van Exter','Jan Willem Basselier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293882,'Harry van Exter','Pieter Verbeek',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293882,'Rinus Devilee','Hermen Breugem',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-10-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),306190,'SNOOKERIJ 17','THE POCKET 2',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('25-10-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),306337,'SNOOKERIJ 5','BSCZ 1',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(306337,'John Meijer','Koos Drunen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(306337,'Joris Scharpff','Peter den Boer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(306337,'John Meijer','Peter den Boer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(306337,'Martijn Verzaal','Koos Drunen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(306337,'Martijn Verzaal','Peter den Boer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(306337,'Joris Scharpff','Koos Drunen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('31-10-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293884,'HOGEWOERD 3','THE POCKET 2',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293884,'Aniel Kalicharan','Thomas Glasbergen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293884,'Dian Koning','Johan Keizer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293884,'Martijn Korner','Marcel van de Oever',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293884,'Aniel Kalicharan','Johan Keizer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293884,'Dian Koning','Marcel van de Oever',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293884,'Martijn Korner','Thomas Glasbergen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293884,'Martijn Korner','Johan Keizer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293884,'Dian Koning','Thomas Glasbergen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293884,'Aniel Kalicharan','Marcel van de Oever',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('01-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293886,'BSCZ 1','SNOOKERIJ 8',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293886,'Koos Drunen','Huibert van de Putte',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293886,'Glenn van Polanen','Rinus Devilee',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293886,'Koos Drunen','Rinus Devilee',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293886,'Glenn van Polanen','Huibert van de Putte',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293885,'JUMBO 3','SNOOKERIJ 5',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293885,'Debbie Anthonissen','Pascal Hendrikse',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293885,'Arnoud Videler','Martijn Verzaal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293885,'Stefan Osnabrug','Joris Scharpff',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293885,'Debbie Anthonissen','Martijn Verzaal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293885,'Arnoud Videler','Joris Scharpff',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293885,'Stefan Osnabrug','Pascal Hendrikse',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293885,'Stefan Osnabrug','Martijn Verzaal',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293885,'Arnoud Videler','Pascal Hendrikse',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293885,'Debbie Anthonissen','Joris Scharpff',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293887,'SNOOKERIJ 17','BSCZ 2',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293887,'Timo van Poppel','Paul van Leeuwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293887,'Jan Willem Basselier','Richard Blouw',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293887,'Pieter Verbeek','Kees Willemstein',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293887,'Timo van Poppel','Richard Blouw',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293887,'Jan Willem Basselier','Kees Willemstein',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293887,'Pieter Verbeek','Paul van Leeuwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293887,'Pieter Verbeek','Richard Blouw',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293887,'Jan Willem Basselier','Paul van Leeuwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293887,'Timo van Poppel','Kees Willemstein',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293888,'BSCZ 2','SNOOKERIJ 5',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293888,'Richard Blouw','Joris Scharpff',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293888,'Paul van Leeuwen','Pascal Hendrikse',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293888,'Lars Onvlee','John Meijer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293888,'Richard Blouw','Pascal Hendrikse',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293888,'Paul van Leeuwen','John Meijer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293888,'Lars Onvlee','Joris Scharpff',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293888,'Lars Onvlee','Pascal Hendrikse',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293888,'Paul van Leeuwen','Joris Scharpff',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293888,'Richard Blouw','John Meijer',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293891,'SNOOKERIJ 17','BSCZ 1',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293892,'SNOOKERIJ 8','HOGEWOERD 3',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293892,'Harry van Exter','Martijn Korner',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293892,'Huibert van de Putte','Dian Koning',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293892,'Harry van Exter','Dian Koning',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293892,'Huibert van de Putte','Soerin Ganga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293892,'Huibert van de Putte','Martijn Korner',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293892,'Harry van Exter','Soerin Ganga',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293893,'Deltaplant','SNOOKERIJ 8',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293893,'Martijn Laan','Huibert van de Putte',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293893,'Peter Bruggeman','Huibert van de Putte',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293893,'Martijn Laan','Harry van Exter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293893,'Peter Bruggeman','Harry van Exter',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293894,'HOGEWOERD 3','SNOOKERIJ 17',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293897,'BSCZ 1','BSCZ 2',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293897,'Ron Reeuwijk','Richard Blouw',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293897,'Peter den Boer','Paul van Leeuwen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293897,'Koos Drunen','Peter Hulst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293897,'Ron Reeuwijk','Paul van Leeuwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293897,'Peter den Boer','Peter Hulst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293897,'Koos Drunen','Richard Blouw',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293897,'Koos Drunen','Paul van Leeuwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293897,'Peter den Boer','Richard Blouw',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293897,'Ron Reeuwijk','Peter Hulst',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293896,'JUMBO 3','THE POCKET 2',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293896,'Stefan Osnabrug','Kees van Duijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293896,'Arnoud Videler','Marcel van de Oever',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293896,'Rob Oudshoorn','Johan Keizer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293896,'Stefan Osnabrug','Marcel van de Oever',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293896,'Arnoud Videler','Johan Keizer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293896,'Rob Oudshoorn','Kees van Duijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293896,'Rob Oudshoorn','Marcel van de Oever',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293896,'Arnoud Videler','Kees van Duijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293896,'Stefan Osnabrug','Johan Keizer',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-12-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293899,'THE POCKET 2','SNOOKERIJ 5',0,9);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293899,'Johan Keizer','Martijn Verzaal',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293899,'Thomas Glasbergen','John Meijer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293899,'Marcel van de Oever','Joris Scharpff',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293899,'Johan Keizer','John Meijer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293899,'Thomas Glasbergen','Joris Scharpff',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293899,'Marcel van de Oever','Martijn Verzaal',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293899,'Marcel van de Oever','John Meijer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293899,'Thomas Glasbergen','Martijn Verzaal',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293899,'Johan Keizer','Joris Scharpff',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-12-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293902,'SNOOKERIJ 8','JUMBO 3',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293902,'Harry van Exter','Arnoud Videler',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293902,'Huibert van de Putte','Rob Oudshoorn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293902,'Harry van Exter','Rob Oudshoorn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293902,'Huibert van de Putte','Debbie Anthonissen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293902,'Huibert van de Putte','Arnoud Videler',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293902,'Harry van Exter','Debbie Anthonissen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-12-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293903,'Deltaplant','BSCZ 1',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293903,'John Pape','Peter den Boer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293903,'Peter Bruggeman','Glenn van Polanen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293903,'John Pape','Glenn van Polanen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293903,'Martijn Laan','Peter den Boer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293903,'Martijn Laan','Glenn van Polanen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293903,'Peter Bruggeman','Peter den Boer',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-12-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293904,'HOGEWOERD 3','BSCZ 2',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-12-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293905,'SNOOKERIJ 5','SNOOKERIJ 8',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293905,'Joris Scharpff','Harry van Exter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293905,'Pascal Hendrikse','Huibert van de Putte',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293905,'Martijn Verzaal','Rinus Devilee',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293905,'Joris Scharpff','Huibert van de Putte',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293905,'Pascal Hendrikse','Rinus Devilee',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293905,'Martijn Verzaal','Harry van Exter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293905,'Martijn Verzaal','Huibert van de Putte',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293905,'Pascal Hendrikse','Harry van Exter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293905,'Joris Scharpff','Rinus Devilee',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-12-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293906,'JUMBO 3','SNOOKERIJ 17',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293906,'Arnoud Videler','Robert Groenewegen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293906,'Rob Oudshoorn','Jan Willem Basselier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293906,'Arnoud Videler','Jan Willem Basselier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293906,'Rob Oudshoorn','Timo van Poppel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293906,'Rob Oudshoorn','Robert Groenewegen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293906,'Arnoud Videler','Timo van Poppel',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),307553,'THE POCKET 2','Deltaplant',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(307553,'Kees van Duijn','Frank van der Laan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(307553,'Marcel van de Oever','Regi Verdoorn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(307553,'Thomas Glasbergen','John Pape',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(307553,'Kees van Duijn','Regi Verdoorn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(307553,'Marcel van de Oever','John Pape',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(307553,'Thomas Glasbergen','Frank van der Laan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(307553,'Thomas Glasbergen','Regi Verdoorn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(307553,'Marcel van de Oever','Frank van der Laan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(307553,'Kees van Duijn','John Pape',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293908,'HOGEWOERD 3','Deltaplant',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293909,'BSCZ 2','THE POCKET 2',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293909,'Paul van Leeuwen','Kees van Duijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293909,'Richard Blouw','Johan Keizer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293909,'Peter Hulst','Johan Keizer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293909,'Richard Blouw','Kees van Duijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293909,'Peter Hulst','Kees van Duijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293909,'Paul van Leeuwen','Johan Keizer',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293910,'BSCZ 1','JUMBO 3',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293910,'Peter den Boer','Debbie Anthonissen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293910,'Ron Reeuwijk','Stefan Osnabrug',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293910,'Ron Reeuwijk','Debbie Anthonissen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293910,'Peter den Boer','Stefan Osnabrug',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293911,'SNOOKERIJ 17','SNOOKERIJ 5',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293911,'Timo van Poppel','Pascal Hendrikse',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293911,'Jan Willem Basselier','Martijn Verzaal',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293911,'Pieter Verbeek','Joris Scharpff',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293911,'Timo van Poppel','Martijn Verzaal',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293911,'Jan Willem Basselier','Joris Scharpff',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293911,'Pieter Verbeek','Pascal Hendrikse',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293911,'Pieter Verbeek','Martijn Verzaal',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293911,'Jan Willem Basselier','Pascal Hendrikse',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293911,'Timo van Poppel','Joris Scharpff',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293913,'Deltaplant','BSCZ 2',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293913,'John Pape','Kees Willemstein',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293913,'Peter Bruggeman','Paul van Leeuwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293913,'Martijn Laan','Lars Onvlee',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293913,'John Pape','Paul van Leeuwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293913,'Peter Bruggeman','Lars Onvlee',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293913,'Martijn Laan','Kees Willemstein',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293913,'Martijn Laan','Paul van Leeuwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293913,'Peter Bruggeman','Kees Willemstein',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293913,'John Pape','Lars Onvlee',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293914,'HOGEWOERD 3','JUMBO 3',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293915,'BSCZ 1','SNOOKERIJ 5',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293915,'Koos Drunen','Pascal Hendrikse',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293915,'Glenn van Polanen','Martijn Verzaal',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293915,'Ron Reeuwijk','Joris Scharpff',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293915,'Koos Drunen','Martijn Verzaal',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293915,'Glenn van Polanen','Joris Scharpff',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293915,'Ron Reeuwijk','Pascal Hendrikse',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293915,'Ron Reeuwijk','Martijn Verzaal',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293915,'Glenn van Polanen','Pascal Hendrikse',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293915,'Koos Drunen','Joris Scharpff',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293917,'SNOOKERIJ 8','THE POCKET 2',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293917,'Harry van Exter','Thomas Glasbergen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293917,'Huibert van de Putte','Johan Keizer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293917,'Rinus Devilee','Johan Keizer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293917,'Huibert van de Putte','Thomas Glasbergen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293917,'Rinus Devilee','Thomas Glasbergen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293917,'Harry van Exter','Johan Keizer',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-02-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293918,'BSCZ 2','SNOOKERIJ 8',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293918,'Lars Onvlee','Harry van Exter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293918,'Peter Hulst','Huibert van de Putte',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293918,'Lars Onvlee','Huibert van de Putte',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293918,'Richard Blouw','Harry van Exter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293918,'Richard Blouw','Huibert van de Putte',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293918,'Peter Hulst','Harry van Exter',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-02-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293919,'SNOOKERIJ 5','HOGEWOERD 3',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293919,'John Meijer','Aniel Kalicharan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293919,'Pascal Hendrikse','Martijn Korner',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293919,'Martijn Verzaal','Dian Koning',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293919,'John Meijer','Martijn Korner',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293919,'Pascal Hendrikse','Dian Koning',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293919,'Martijn Verzaal','Aniel Kalicharan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293919,'Martijn Verzaal','Martijn Korner',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293919,'Pascal Hendrikse','Aniel Kalicharan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293919,'John Meijer','Dian Koning',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-02-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293920,'JUMBO 3','Deltaplant',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-02-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293921,'THE POCKET 2','SNOOKERIJ 17',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-02-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293923,'Deltaplant','SNOOKERIJ 5',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-02-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293926,'BSCZ 1','THE POCKET 2',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293926,'Ron Reeuwijk','Kees van Duijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293926,'Koos Drunen','Marcel van de Oever',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293926,'Glenn van Polanen','Johan Keizer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293926,'Ron Reeuwijk','Marcel van de Oever',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293926,'Koos Drunen','Johan Keizer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293926,'Glenn van Polanen','Kees van Duijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293926,'Glenn van Polanen','Marcel van de Oever',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293926,'Koos Drunen','Kees van Duijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293926,'Ron Reeuwijk','Johan Keizer',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-02-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293925,'JUMBO 3','BSCZ 2',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293925,'Arnoud Videler','Paul van Leeuwen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293925,'Arnoud Videler','Peter Hulst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293925,'Arnoud Videler','Kees Willemstein',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-02-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),308403,'SNOOKERIJ 17','Deltaplant',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('28-02-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),308938,'BSCZ 1','HOGEWOERD 3',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308938,'Peter den Boer','Soerin Ganga',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308938,'Ron Reeuwijk','Martijn Korner',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308938,'Peter den Boer','Martijn Korner',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308938,'Ron Reeuwijk','Dian Koning',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308938,'Ron Reeuwijk','Soerin Ganga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308938,'Peter den Boer','Dian Koning',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-03-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293929,'SNOOKERIJ 5','JUMBO 3',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-03-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293930,'THE POCKET 2','HOGEWOERD 3',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293930,'Marcel van de Oever','Soerin Ganga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293930,'Thomas Glasbergen','Dian Koning',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293930,'Johan Keizer','Martijn Korner',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293930,'Marcel van de Oever','Dian Koning',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293930,'Thomas Glasbergen','Martijn Korner',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293930,'Johan Keizer','Soerin Ganga',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293930,'Johan Keizer','Dian Koning',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293930,'Thomas Glasbergen','Soerin Ganga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293930,'Marcel van de Oever','Martijn Korner',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-03-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293932,'SNOOKERIJ 8','BSCZ 1',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293932,'Harry van Exter','Glenn van Polanen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293932,'Huibert van de Putte','Peter den Boer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293932,'Huibert van de Putte','Glenn van Polanen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293932,'Harry van Exter','Peter den Boer',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('26-03-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293933,'Deltaplant','THE POCKET 2',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293933,'Peter Bruggeman','Marcel van de Oever',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293933,'Martijn Laan','Johan Keizer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293933,'Frank van der Laan','Johan Keizer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293933,'Martijn Laan','Marcel van de Oever',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293933,'Frank van der Laan','Marcel van de Oever',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293933,'Peter Bruggeman','Johan Keizer',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('26-03-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293934,'HOGEWOERD 3','SNOOKERIJ 8',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293934,'Dian Koning','Harry van Exter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293934,'Aniel Kalicharan','Huibert van de Putte',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293934,'Dian Koning','Huibert van de Putte',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293934,'Martijn Korner','Harry van Exter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293934,'Martijn Korner','Huibert van de Putte',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293934,'Aniel Kalicharan','Harry van Exter',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-03-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293935,'SNOOKERIJ 5','BSCZ 2',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293935,'Joris Scharpff','Paul van Leeuwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293935,'Pascal Hendrikse','Peter Hulst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293935,'Martijn Verzaal','Kees Willemstein',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293935,'Joris Scharpff','Peter Hulst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293935,'Pascal Hendrikse','Kees Willemstein',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293935,'Martijn Verzaal','Paul van Leeuwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293935,'Martijn Verzaal','Peter Hulst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293935,'Pascal Hendrikse','Paul van Leeuwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293935,'Joris Scharpff','Kees Willemstein',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-03-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293937,'BSCZ 1','SNOOKERIJ 17',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-04-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),309337,'SNOOKERIJ 17','SNOOKERIJ 8',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309337,'Hermen Breugem','Harry van Exter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309337,'Pieter Verbeek','Rinus Devilee',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309337,'Jan Willem Basselier','Rinus Devilee',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309337,'Pieter Verbeek','Harry van Exter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309337,'Jan Willem Basselier','Harry van Exter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309337,'Hermen Breugem','Rinus Devilee',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-04-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293939,'THE POCKET 2','JUMBO 3',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293939,'Thomas Glasbergen','Stefan Osnabrug',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293939,'Marcel van de Oever','Rob Oudshoorn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293939,'Thomas Glasbergen','Rob Oudshoorn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293939,'Johan Keizer','Stefan Osnabrug',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293939,'Johan Keizer','Rob Oudshoorn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293939,'Marcel van de Oever','Stefan Osnabrug',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-04-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293942,'SNOOKERIJ 8','Deltaplant',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293942,'Rinus Devilee','Frank van der Laan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293942,'Harry van Exter','John Pape',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293942,'Rinus Devilee','Martijn Laan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293942,'Harry van Exter','Frank van der Laan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293942,'Harry van Exter','Martijn Laan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293942,'Rinus Devilee','John Pape',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-04-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),309485,'BSCZ 2','BSCZ 1',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309485,'Lars Onvlee','Peter den Boer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309485,'Paul van Leeuwen','Ron Reeuwijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309485,'Peter Hulst','Koos Drunen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309485,'Lars Onvlee','Ron Reeuwijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309485,'Paul van Leeuwen','Koos Drunen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309485,'Peter Hulst','Peter den Boer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309485,'Peter Hulst','Ron Reeuwijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309485,'Paul van Leeuwen','Peter den Boer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309485,'Lars Onvlee','Koos Drunen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-04-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293945,'SNOOKERIJ 5','THE POCKET 2',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293945,'Joris Scharpff','Thomas Glasbergen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293945,'Pascal Hendrikse','Marcel van de Oever',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293945,'Martijn Verzaal','Johan Keizer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293945,'Joris Scharpff','Marcel van de Oever',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293945,'Pascal Hendrikse','Johan Keizer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293945,'Martijn Verzaal','Thomas Glasbergen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293945,'Martijn Verzaal','Marcel van de Oever',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293945,'Pascal Hendrikse','Thomas Glasbergen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293945,'Joris Scharpff','Johan Keizer',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-04-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293946,'JUMBO 3','SNOOKERIJ 8',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293946,'Stefan Osnabrug','Rinus Devilee',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293946,'Jelle Kijlstra','Harry van Exter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293946,'Rob Oudshoorn','Huibert van de Putte',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293946,'Stefan Osnabrug','Harry van Exter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293946,'Jelle Kijlstra','Huibert van de Putte',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293946,'Rob Oudshoorn','Rinus Devilee',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293946,'Rob Oudshoorn','Harry van Exter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293946,'Jelle Kijlstra','Rinus Devilee',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293946,'Stefan Osnabrug','Huibert van de Putte',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),309571,'BSCZ 2','SNOOKERIJ 17',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309571,'Lars Onvlee','Timo van Poppel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309571,'Kees Willemstein','Jan Willem Basselier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309571,'Peter Hulst','Hermen Breugem',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309571,'Lars Onvlee','Jan Willem Basselier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309571,'Kees Willemstein','Hermen Breugem',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309571,'Peter Hulst','Timo van Poppel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309571,'Peter Hulst','Jan Willem Basselier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309571,'Kees Willemstein','Timo van Poppel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309571,'Lars Onvlee','Hermen Breugem',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),309570,'Deltaplant','SNOOKERIJ 17',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309570,'John Pape','Hermen Breugem',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309570,'Peter Bruggeman','Timo van Poppel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309570,'Martijn Laan','Robert Groenewegen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309570,'John Pape','Timo van Poppel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309570,'Peter Bruggeman','Robert Groenewegen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309570,'Martijn Laan','Hermen Breugem',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309570,'Martijn Laan','Timo van Poppel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309570,'Peter Bruggeman','Hermen Breugem',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309570,'John Pape','Robert Groenewegen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),309486,'HOGEWOERD 3','BSCZ 1',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309486,'Martijn Korner','Glenn van Polanen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309486,'Dian Koning','Ron Reeuwijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309486,'Aniel Kalicharan','Koos Drunen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309486,'Martijn Korner','Ron Reeuwijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309486,'Dian Koning','Koos Drunen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309486,'Aniel Kalicharan','Glenn van Polanen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309486,'Aniel Kalicharan','Ron Reeuwijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309486,'Dian Koning','Glenn van Polanen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309486,'Martijn Korner','Koos Drunen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293948,'BSCZ 2','HOGEWOERD 3',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293950,'BSCZ 1','Deltaplant',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293950,'Ron Reeuwijk','Frank van der Laan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293950,'Glenn van Polanen','Regi Verdoorn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293950,'Koos Drunen','John Pape',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293950,'Ron Reeuwijk','Regi Verdoorn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293950,'Glenn van Polanen','John Pape',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293950,'Koos Drunen','Frank van der Laan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293950,'Koos Drunen','Regi Verdoorn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293950,'Glenn van Polanen','Frank van der Laan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293950,'Ron Reeuwijk','John Pape',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293951,'SNOOKERIJ 17','JUMBO 3',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293951,'Hermen Breugem','Debbie Anthonissen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293951,'Pieter Verbeek','Arnoud Videler',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293951,'Timo van Poppel','Arnoud Videler',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293951,'Pieter Verbeek','Debbie Anthonissen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293951,'Timo van Poppel','Debbie Anthonissen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293951,'Hermen Breugem','Arnoud Videler',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293952,'SNOOKERIJ 8','SNOOKERIJ 5',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293952,'Harry van Exter','Martijn Verzaal',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293952,'Huibert van de Putte','Joris Scharpff',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293952,'Harry van Exter','Joris Scharpff',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293952,'Huibert van de Putte','Pascal Hendrikse',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293952,'Huibert van de Putte','Martijn Verzaal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293952,'Harry van Exter','Pascal Hendrikse',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293953,'Deltaplant','HOGEWOERD 3',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293953,'Regi Verdoorn','Aniel Kalicharan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293953,'Peter Bruggeman','Soerin Ganga',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293953,'Frank van der Laan','Martijn Korner',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293953,'Regi Verdoorn','Soerin Ganga',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293953,'Peter Bruggeman','Martijn Korner',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293953,'Frank van der Laan','Aniel Kalicharan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293953,'Frank van der Laan','Soerin Ganga',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293953,'Peter Bruggeman','Aniel Kalicharan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293953,'Regi Verdoorn','Martijn Korner',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293954,'SNOOKERIJ 5','SNOOKERIJ 17',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293954,'Joris Scharpff','Timo van Poppel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293954,'Pascal Hendrikse','Jan Willem Basselier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293954,'Martijn Verzaal','Hermen Breugem',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293954,'Joris Scharpff','Jan Willem Basselier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293954,'Pascal Hendrikse','Hermen Breugem',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293954,'Martijn Verzaal','Timo van Poppel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293954,'Martijn Verzaal','Jan Willem Basselier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293954,'Pascal Hendrikse','Timo van Poppel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293954,'Joris Scharpff','Hermen Breugem',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293955,'JUMBO 3','BSCZ 1',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293955,'Stefan Osnabrug','Glenn van Polanen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293955,'Arnoud Videler','Peter den Boer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293955,'Arnoud Videler','Glenn van Polanen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293955,'Stefan Osnabrug','Peter den Boer',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),309926,'SNOOKERIJ 17','HOGEWOERD 3',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309926,'Hermen Breugem','Dian Koning',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309926,'Jan Willem Basselier','Soerin Ganga',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309926,'Pieter Verbeek','Martijn Korner',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309926,'Hermen Breugem','Soerin Ganga',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309926,'Jan Willem Basselier','Martijn Korner',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309926,'Pieter Verbeek','Dian Koning',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309926,'Pieter Verbeek','Soerin Ganga',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309926,'Jan Willem Basselier','Dian Koning',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309926,'Hermen Breugem','Martijn Korner',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2011%'),293956,'THE POCKET 2','BSCZ 2',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293956,'Johan Keizer','Kees Willemstein',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293956,'Kees van Duijn','Peter Hulst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293956,'Thomas Glasbergen','Lars Onvlee',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293956,'Johan Keizer','Peter Hulst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293956,'Kees van Duijn','Lars Onvlee',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293956,'Thomas Glasbergen','Kees Willemstein',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293956,'Thomas Glasbergen','Peter Hulst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293956,'Kees van Duijn','Kees Willemstein',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293956,'Johan Keizer','Lars Onvlee',1,0);
