delete from cm_match_details where game_id in (select game_id from cm_matches where cpn_id = (select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'));
delete from cm_matches where cpn_id = (select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%');
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-09-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350892,'NNPV','SNOOKERIJ 17',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350892,'Rob Molier','Jan Willem Basselier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350892,'Mark Molier','Timo van Poppel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350892,'Marco Roeleveld','Pieter Verbeek',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350892,'Rob Molier','Timo van Poppel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350892,'Mark Molier','Pieter Verbeek',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350892,'Marco Roeleveld','Jan Willem Basselier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350892,'Marco Roeleveld','Timo van Poppel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350892,'Mark Molier','Jan Willem Basselier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350892,'Rob Molier','Pieter Verbeek',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-09-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350895,'Capelle Vaaf','BSCZ 1',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350895,'Kevin Jansen','Peter den Boer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350895,'Chris Bakker','Ron Reeuwijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350895,'Kevin Jansen','Ron Reeuwijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350895,'Richard Mostert','Peter den Boer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350895,'Richard Mostert','Ron Reeuwijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350895,'Chris Bakker','Peter den Boer',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-09-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350896,'SNOOKERIJ 8','Deltaplant',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-09-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350897,'Azzurri','HOGEWOERD 3',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-09-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350898,'HOGEWOERD 3','Capelle Vaaf',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350898,'Soerin Ganga','Chris Bakker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350898,'Dian Koning','Kevin Jansen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350898,'Martijn Korner','Stefan Osnabrug',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350898,'Soerin Ganga','Kevin Jansen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350898,'Dian Koning','Stefan Osnabrug',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350898,'Martijn Korner','Chris Bakker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350898,'Martijn Korner','Kevin Jansen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350898,'Dian Koning','Chris Bakker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350898,'Soerin Ganga','Stefan Osnabrug',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-09-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350900,'Deltaplant','Azzurri',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-09-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350901,'BSCZ 1','Spijkenisse Quattro',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350901,'Peter den Boer','Leslie van Leeuwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350901,'Glenn van Polanen','Marcel Paulus',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350901,'Peter den Boer','Marcel Paulus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350901,'Glenn van Polanen','Bas Lange',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350901,'Glenn van Polanen','Leslie van Leeuwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350901,'Peter den Boer','Bas Lange',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-09-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350903,'SNOOKERIJ 17','SNOOKERIJ 8',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350903,'Fabian Carrasco','Rinus Devilee',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350903,'Hermen Breugem','Harry van Exter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350903,'Pieter Verbeek','Rinus Devilee',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350903,'Fabian Carrasco','Harry van Exter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350903,'Hermen Breugem','Rinus Devilee',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350903,'Pieter Verbeek','Harry van Exter',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-10-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350907,'Spijkenisse Quattro','HOGEWOERD 3',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350907,'Bas Lange','Dian Koning',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350907,'Leslie van Leeuwen','Soerin Ganga',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350907,'Marcel Paulus','Aniel Kalicharan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350907,'Bas Lange','Soerin Ganga',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350907,'Leslie van Leeuwen','Aniel Kalicharan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350907,'Marcel Paulus','Dian Koning',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350907,'Marcel Paulus','Soerin Ganga',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350907,'Leslie van Leeuwen','Dian Koning',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350907,'Bas Lange','Aniel Kalicharan',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-10-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350909,'Azzurri','Capelle Vaaf',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-10-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350912,'Capelle Vaaf','Spijkenisse Quattro',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350912,'David Uljee','Leslie van Leeuwen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350912,'Chris Bakker','Marcel Paulus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350912,'Kevin Jansen','Bas Lange',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350912,'David Uljee','Marcel Paulus',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350912,'Chris Bakker','Bas Lange',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350912,'Kevin Jansen','Leslie van Leeuwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350912,'Kevin Jansen','Marcel Paulus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350912,'Chris Bakker','Leslie van Leeuwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350912,'David Uljee','Bas Lange',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-10-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350913,'BSCZ 1','NNPV',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350913,'Ron Reeuwijk','Mark Molier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350913,'Paul van Leeuwen','Marco Roeleveld',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350913,'Peter Hulst','Rob Molier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350913,'Ron Reeuwijk','Marco Roeleveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350913,'Paul van Leeuwen','Rob Molier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350913,'Peter Hulst','Mark Molier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350913,'Peter Hulst','Marco Roeleveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350913,'Paul van Leeuwen','Mark Molier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350913,'Ron Reeuwijk','Rob Molier',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-10-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350916,'HOGEWOERD 3','NNPV',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('26-10-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350920,'SNOOKERIJ 8','BSCZ 1',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350920,'Huibert van de Putte','Ron Reeuwijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350920,'Harry van Exter','Peter den Boer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350920,'Huibert van de Putte','Peter den Boer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350920,'Harry van Exter','Ron Reeuwijk',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('26-10-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350921,'Azzurri','Spijkenisse Quattro',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('29-10-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350922,'HOGEWOERD 3','SNOOKERIJ 8',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('01-11-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350925,'Capelle Vaaf','NNPV',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350925,'Cees Hogchem','Rob Molier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350925,'René van Lier','Marco Roeleveld',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350925,'Chris Bakker','Mark Molier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350925,'Cees Hogchem','Marco Roeleveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350925,'René van Lier','Mark Molier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350925,'Chris Bakker','Rob Molier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350925,'Chris Bakker','Marco Roeleveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350925,'René van Lier','Rob Molier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350925,'Cees Hogchem','Mark Molier',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-11-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),361608,'Deltaplant','SNOOKERIJ 17',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-11-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350928,'NNPV','Spijkenisse Quattro',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350928,'Rob Molier','Leslie van Leeuwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350928,'Mark Molier','Marcel Paulus',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350928,'Marco Roeleveld','Bas Lange',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350928,'Rob Molier','Marcel Paulus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350928,'Mark Molier','Bas Lange',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350928,'Marco Roeleveld','Leslie van Leeuwen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350928,'Marco Roeleveld','Marcel Paulus',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350928,'Mark Molier','Leslie van Leeuwen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350928,'Rob Molier','Bas Lange',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-11-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350929,'Deltaplant','HOGEWOERD 3',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-11-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350931,'SNOOKERIJ 17','BSCZ 1',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350931,'Fabian Carrasco','Glenn van Polanen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350931,'Jan Willem Basselier','Ron Reeuwijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350931,'Timo van Poppel','Peter den Boer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350931,'Fabian Carrasco','Ron Reeuwijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350931,'Jan Willem Basselier','Peter den Boer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350931,'Timo van Poppel','Glenn van Polanen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350931,'Timo van Poppel','Ron Reeuwijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350931,'Jan Willem Basselier','Glenn van Polanen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350931,'Fabian Carrasco','Peter den Boer',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-11-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350932,'SNOOKERIJ 8','Capelle Vaaf',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-11-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),362888,'BSCZ 1','Deltaplant',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(362888,'Peter den Boer','John Pape',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(362888,'Ron Reeuwijk','Regi Verdoorn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(362888,'Paul van Leeuwen','Martijn Laan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(362888,'Peter den Boer','Regi Verdoorn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(362888,'Ron Reeuwijk','Martijn Laan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(362888,'Paul van Leeuwen','John Pape',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(362888,'Paul van Leeuwen','Regi Verdoorn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(362888,'Ron Reeuwijk','John Pape',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(362888,'Peter den Boer','Martijn Laan',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('29-11-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350937,'Spijkenisse Quattro','SNOOKERIJ 8',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350937,'Leslie van Leeuwen','Huibert van de Putte',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350937,'Marcel Paulus','Harry van Exter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350937,'Bas Lange','Huibert van de Putte',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350937,'Leslie van Leeuwen','Harry van Exter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350937,'Marcel Paulus','Huibert van de Putte',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350937,'Bas Lange','Harry van Exter',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('29-11-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350938,'Capelle Vaaf','Deltaplant',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-12-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350941,'Deltaplant','Spijkenisse Quattro',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350941,'Martijn Laan','Leslie van Leeuwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350941,'John Pape','Marcel Paulus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350941,'Frank van der Laan','Bas Lange',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350941,'Martijn Laan','Marcel Paulus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350941,'John Pape','Bas Lange',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350941,'Frank van der Laan','Leslie van Leeuwen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350941,'Frank van der Laan','Marcel Paulus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350941,'John Pape','Leslie van Leeuwen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350941,'Martijn Laan','Bas Lange',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-12-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350943,'SNOOKERIJ 17','Capelle Vaaf',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350943,'Jan Willem Basselier','Stefan Osnabrug',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350943,'Hermen Breugem','René van Lier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350943,'Pieter Verbeek','Cees Hogchem',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350943,'Jan Willem Basselier','René van Lier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350943,'Hermen Breugem','Cees Hogchem',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350943,'Pieter Verbeek','Stefan Osnabrug',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350943,'Pieter Verbeek','René van Lier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350943,'Hermen Breugem','Stefan Osnabrug',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350943,'Jan Willem Basselier','Cees Hogchem',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-12-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350945,'Azzurri','NNPV',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-12-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350946,'NNPV','SNOOKERIJ 8',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350946,'Mark Molier','Rinus Devilee',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350946,'Marco Roeleveld','Harry van Exter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350946,'Rob Molier','Rinus Devilee',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350946,'Mark Molier','Harry van Exter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350946,'Marco Roeleveld','Rinus Devilee',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350946,'Rob Molier','Harry van Exter',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-12-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350949,'Spijkenisse Quattro','SNOOKERIJ 17',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350949,'Bas Lange','Fabian Carrasco',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350949,'Leslie van Leeuwen','Jan Willem Basselier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350949,'Marcel Paulus','Timo van Poppel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350949,'Bas Lange','Jan Willem Basselier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350949,'Leslie van Leeuwen','Timo van Poppel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350949,'Marcel Paulus','Fabian Carrasco',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350949,'Marcel Paulus','Jan Willem Basselier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350949,'Leslie van Leeuwen','Fabian Carrasco',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350949,'Bas Lange','Timo van Poppel',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-12-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350951,'BSCZ 1','Azzurri',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350951,'Peter den Boer','Arno van Vlokhoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350951,'Glenn van Polanen','Gozewijn van Laatum',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350951,'Ron Reeuwijk','René de Winter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350951,'Peter den Boer','Gozewijn van Laatum',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350951,'Glenn van Polanen','René de Winter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350951,'Ron Reeuwijk','Arno van Vlokhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350951,'Ron Reeuwijk','Gozewijn van Laatum',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350951,'Glenn van Polanen','Arno van Vlokhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350951,'Peter den Boer','René de Winter',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-12-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),363659,'HOGEWOERD 3','SNOOKERIJ 17',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-01-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),364189,'SNOOKERIJ 17','Azzurri',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-01-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350953,'Deltaplant','NNPV',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350953,'Martijn Laan','Marco Roeleveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350953,'Regi Verdoorn','Mark Molier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350953,'Peter Bruggeman','Rob Molier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350953,'Martijn Laan','Mark Molier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350953,'Regi Verdoorn','Rob Molier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350953,'Peter Bruggeman','Marco Roeleveld',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350953,'Peter Bruggeman','Mark Molier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350953,'Regi Verdoorn','Marco Roeleveld',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350953,'Martijn Laan','Rob Molier',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-01-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350954,'BSCZ 1','HOGEWOERD 3',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('25-01-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350957,'Azzurri','SNOOKERIJ 8',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('28-01-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350958,'HOGEWOERD 3','Azzurri',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('29-01-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350960,'Deltaplant','SNOOKERIJ 8',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('31-01-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350961,'BSCZ 1','Capelle Vaaf',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350961,'Glenn van Polanen','Cees Hogchem',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350961,'Peter Hulst','Kevin Jansen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350961,'Glenn van Polanen','Kevin Jansen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350961,'Peter Hulst','Jan Rouw',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350961,'Peter Hulst','Cees Hogchem',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350961,'Glenn van Polanen','Jan Rouw',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('31-01-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350963,'SNOOKERIJ 17','NNPV',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350963,'Jan Willem Basselier','Mark Molier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350963,'Pieter Verbeek','Marco Roeleveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350963,'Hermen Breugem','Rob Molier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350963,'Jan Willem Basselier','Marco Roeleveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350963,'Pieter Verbeek','Rob Molier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350963,'Hermen Breugem','Mark Molier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350963,'Hermen Breugem','Marco Roeleveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350963,'Pieter Verbeek','Mark Molier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350963,'Jan Willem Basselier','Rob Molier',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-02-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350968,'SNOOKERIJ 8','SNOOKERIJ 17',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350968,'Harry van Exter','Jan Willem Basselier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350968,'Huibert van de Putte','Timo van Poppel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350968,'Rinus Devilee','Fabian Carrasco',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350968,'Harry van Exter','Timo van Poppel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350968,'Huibert van de Putte','Fabian Carrasco',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350968,'Rinus Devilee','Jan Willem Basselier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350968,'Rinus Devilee','Timo van Poppel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350968,'Huibert van de Putte','Jan Willem Basselier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350968,'Harry van Exter','Fabian Carrasco',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-02-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350969,'Azzurri','Deltaplant',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-02-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350970,'HOGEWOERD 3','Spijkenisse Quattro',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350970,'Dian Koning','Leslie van Leeuwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350970,'Martijn Korner','Marcel Paulus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350970,'Rogier Wijnans','Bas Lange',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350970,'Dian Koning','Marcel Paulus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350970,'Martijn Korner','Bas Lange',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350970,'Rogier Wijnans','Leslie van Leeuwen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350970,'Rogier Wijnans','Marcel Paulus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350970,'Martijn Korner','Leslie van Leeuwen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350970,'Dian Koning','Bas Lange',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-02-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350972,'Capelle Vaaf','Azzurri',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350972,'René van Lier','Arno van Vlokhoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350972,'David Uljee','Gozewijn van Laatum',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350972,'Stefan Osnabrug','René de Winter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350972,'René van Lier','Gozewijn van Laatum',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350972,'David Uljee','René de Winter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350972,'Stefan Osnabrug','Arno van Vlokhoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350972,'Stefan Osnabrug','Gozewijn van Laatum',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350972,'David Uljee','Arno van Vlokhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350972,'René van Lier','René de Winter',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-02-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350975,'SNOOKERIJ 17','Deltaplant',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350975,'Jan Willem Basselier','Frank van der Laan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350975,'Hermen Breugem','Martijn Laan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350975,'Pieter Verbeek','John Pape',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350975,'Jan Willem Basselier','Martijn Laan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350975,'Hermen Breugem','John Pape',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350975,'Pieter Verbeek','Frank van der Laan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350975,'Pieter Verbeek','Martijn Laan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350975,'Hermen Breugem','Frank van der Laan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350975,'Jan Willem Basselier','John Pape',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('25-02-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350976,'NNPV','BSCZ 1',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350976,'Rob Molier','Peter den Boer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350976,'Mark Molier','Glenn van Polanen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350976,'Rob Molier','Glenn van Polanen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350976,'Marco Roeleveld','Peter den Boer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350976,'Marco Roeleveld','Glenn van Polanen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350976,'Mark Molier','Peter den Boer',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-03-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),365576,'Spijkenisse Quattro','BSCZ 1',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365576,'Bas Lange','Ron Reeuwijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365576,'Leslie van Leeuwen','Glenn van Polanen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365576,'Marcel Paulus','Peter den Boer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365576,'Bas Lange','Glenn van Polanen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365576,'Leslie van Leeuwen','Peter den Boer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365576,'Marcel Paulus','Ron Reeuwijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365576,'Marcel Paulus','Glenn van Polanen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365576,'Leslie van Leeuwen','Ron Reeuwijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365576,'Bas Lange','Peter den Boer',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-03-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),365367,'Capelle Vaaf','HOGEWOERD 3',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365367,'Stefan Osnabrug','Rogier Wijnans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365367,'David Uljee','Dian Koning',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365367,'Kevin Jansen','Mitra Dewkalie',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365367,'Stefan Osnabrug','Dian Koning',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365367,'David Uljee','Mitra Dewkalie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365367,'Kevin Jansen','Rogier Wijnans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365367,'Kevin Jansen','Dian Koning',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365367,'David Uljee','Rogier Wijnans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365367,'Stefan Osnabrug','Mitra Dewkalie',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-03-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350982,'NNPV','HOGEWOERD 3',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-03-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350986,'BSCZ 1','SNOOKERIJ 8',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350986,'Ron Reeuwijk','Rinus Devilee',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350986,'Paul van Leeuwen','Harry van Exter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350986,'Glenn van Polanen','Rinus Devilee',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350986,'Ron Reeuwijk','Harry van Exter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350986,'Paul van Leeuwen','Rinus Devilee',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350986,'Glenn van Polanen','Harry van Exter',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-03-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),365935,'Spijkenisse Quattro','Capelle Vaaf',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365935,'Bas Lange','Jan Rouw',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365935,'Leslie van Leeuwen','Kevin Jansen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365935,'Marcel Paulus','Cees Hogchem',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365935,'Bas Lange','Kevin Jansen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365935,'Leslie van Leeuwen','Cees Hogchem',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365935,'Marcel Paulus','Jan Rouw',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365935,'Marcel Paulus','Kevin Jansen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365935,'Leslie van Leeuwen','Jan Rouw',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365935,'Bas Lange','Cees Hogchem',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('25-03-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350988,'NNPV','Capelle Vaaf',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350988,'Rob Molier','Jan Rouw',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350988,'Mark Molier','Kevin Jansen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350988,'Marco Roeleveld','Stefan Osnabrug',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350988,'Rob Molier','Kevin Jansen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350988,'Mark Molier','Stefan Osnabrug',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350988,'Marco Roeleveld','Jan Rouw',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350988,'Marco Roeleveld','Kevin Jansen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350988,'Mark Molier','Jan Rouw',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350988,'Rob Molier','Stefan Osnabrug',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('26-03-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350990,'Deltaplant','BSCZ 1',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350990,'John Pape','Paul van Leeuwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350990,'Peter Bruggeman','Peter Hulst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350990,'Frank van der Laan','Ron Reeuwijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350990,'John Pape','Peter Hulst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350990,'Peter Bruggeman','Ron Reeuwijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350990,'Frank van der Laan','Paul van Leeuwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350990,'Frank van der Laan','Peter Hulst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350990,'Peter Bruggeman','Paul van Leeuwen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350990,'John Pape','Ron Reeuwijk',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('29-03-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),366069,'Spijkenisse Quattro','Azzurri',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366069,'Bas Lange','Bert van der Linden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366069,'Leslie van Leeuwen','René de Winter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366069,'Marcel Paulus','Sancho Hepsakker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366069,'Bas Lange','René de Winter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366069,'Leslie van Leeuwen','Sancho Hepsakker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366069,'Marcel Paulus','Bert van der Linden',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366069,'Marcel Paulus','René de Winter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366069,'Leslie van Leeuwen','Bert van der Linden',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366069,'Bas Lange','Sancho Hepsakker',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('29-03-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350992,'SNOOKERIJ 8','HOGEWOERD 3',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-04-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350997,'Spijkenisse Quattro','NNPV',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350997,'Bas Lange','Mark Molier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350997,'Leslie van Leeuwen','Marco Roeleveld',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350997,'Marcel Paulus','Rob Molier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350997,'Bas Lange','Marco Roeleveld',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350997,'Leslie van Leeuwen','Rob Molier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350997,'Marcel Paulus','Mark Molier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350997,'Marcel Paulus','Marco Roeleveld',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350997,'Leslie van Leeuwen','Mark Molier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350997,'Bas Lange','Rob Molier',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-04-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350998,'Capelle Vaaf','SNOOKERIJ 8',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350998,'René van Lier','Huibert van de Putte',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350998,'Jan Rouw','Harry van Exter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350998,'David Uljee','Harry van Exter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350998,'Jan Rouw','Huibert van de Putte',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350998,'David Uljee','Huibert van de Putte',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350998,'René van Lier','Harry van Exter',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-04-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),350999,'BSCZ 1','SNOOKERIJ 17',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350999,'Peter den Boer','Jan Willem Basselier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350999,'Glenn van Polanen','Hermen Breugem',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350999,'Peter Hulst','Fabian Carrasco',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350999,'Peter den Boer','Hermen Breugem',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350999,'Glenn van Polanen','Fabian Carrasco',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350999,'Peter Hulst','Jan Willem Basselier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350999,'Peter Hulst','Hermen Breugem',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350999,'Glenn van Polanen','Jan Willem Basselier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(350999,'Peter den Boer','Fabian Carrasco',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-04-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),351001,'Deltaplant','Capelle Vaaf',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351001,'Martijn Laan','René van Lier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351001,'John Pape','Chris Bakker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351001,'Regi Verdoorn','Kevin Jansen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351001,'Martijn Laan','Chris Bakker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351001,'John Pape','Kevin Jansen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351001,'Regi Verdoorn','René van Lier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351001,'Regi Verdoorn','Chris Bakker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351001,'John Pape','René van Lier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351001,'Martijn Laan','Kevin Jansen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-04-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),351003,'SNOOKERIJ 17','HOGEWOERD 3',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351003,'Fabian Carrasco','Soerin Ganga',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351003,'Hermen Breugem','Aniel Kalicharan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351003,'Pieter Verbeek','Mitra Dewkalie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351003,'Fabian Carrasco','Aniel Kalicharan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351003,'Hermen Breugem','Mitra Dewkalie',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351003,'Pieter Verbeek','Soerin Ganga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351003,'Pieter Verbeek','Aniel Kalicharan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351003,'Hermen Breugem','Soerin Ganga',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351003,'Fabian Carrasco','Mitra Dewkalie',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-04-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),351004,'SNOOKERIJ 8','Spijkenisse Quattro',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351004,'Harry van Exter','Leslie van Leeuwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351004,'Huibert van de Putte','Bas Lange',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351004,'Harry van Exter','Marcel Paulus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351004,'Huibert van de Putte','Leslie van Leeuwen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351004,'Huibert van de Putte','Marcel Paulus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351004,'Harry van Exter','Bas Lange',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-04-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),366193,'Azzurri','SNOOKERIJ 17',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-04-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),366146,'HOGEWOERD 3','Deltaplant',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366146,'Martijn Korner','Frank van der Laan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366146,'Soerin Ganga','Peter Bruggeman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366146,'Rogier Wijnans','Martijn Laan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366146,'Martijn Korner','Peter Bruggeman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366146,'Soerin Ganga','Martijn Laan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366146,'Rogier Wijnans','Frank van der Laan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366146,'Rogier Wijnans','Peter Bruggeman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366146,'Soerin Ganga','Frank van der Laan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366146,'Martijn Korner','Martijn Laan',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-04-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),351006,'NNPV','Azzurri',8,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('25-04-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),351009,'Spijkenisse Quattro','Deltaplant',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351009,'Bas Lange','Frank van der Laan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351009,'Leslie van Leeuwen','Peter Bruggeman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351009,'Marcel Paulus','Martijn Laan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351009,'Bas Lange','Peter Bruggeman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351009,'Leslie van Leeuwen','Martijn Laan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351009,'Marcel Paulus','Frank van der Laan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351009,'Marcel Paulus','Peter Bruggeman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351009,'Leslie van Leeuwen','Frank van der Laan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351009,'Bas Lange','Martijn Laan',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('25-04-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),351010,'Capelle Vaaf','SNOOKERIJ 17',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351010,'Stefan Osnabrug','Pieter Verbeek',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351010,'Kevin Jansen','Fabian Carrasco',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351010,'David Uljee','Jan Willem Basselier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351010,'Stefan Osnabrug','Fabian Carrasco',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351010,'Kevin Jansen','Jan Willem Basselier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351010,'David Uljee','Pieter Verbeek',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351010,'David Uljee','Fabian Carrasco',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351010,'Kevin Jansen','Pieter Verbeek',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351010,'Stefan Osnabrug','Jan Willem Basselier',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-05-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),351016,'SNOOKERIJ 8','NNPV',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351016,'Harry van Exter','Mark Molier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351016,'Rinus Devilee','Rob Molier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351016,'Harry van Exter','Marco Roeleveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351016,'Rinus Devilee','Mark Molier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351016,'Rinus Devilee','Marco Roeleveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351016,'Harry van Exter','Rob Molier',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-05-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),351018,'NNPV','Deltaplant',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351018,'Rob Molier','Martijn Laan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351018,'Marco Roeleveld','Frank van der Laan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351018,'Mark Molier','Regi Verdoorn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351018,'Rob Molier','Frank van der Laan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351018,'Marco Roeleveld','Regi Verdoorn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351018,'Mark Molier','Martijn Laan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351018,'Mark Molier','Frank van der Laan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351018,'Marco Roeleveld','Martijn Laan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351018,'Rob Molier','Regi Verdoorn',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-05-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),351019,'HOGEWOERD 3','BSCZ 1',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351019,'Aniel Kalicharan','Glenn van Polanen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351019,'Dian Koning','Paul van Leeuwen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351019,'Soerin Ganga','Peter den Boer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351019,'Aniel Kalicharan','Paul van Leeuwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351019,'Dian Koning','Peter den Boer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351019,'Soerin Ganga','Glenn van Polanen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351019,'Soerin Ganga','Paul van Leeuwen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351019,'Dian Koning','Glenn van Polanen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351019,'Aniel Kalicharan','Peter den Boer',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-05-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),366659,'Azzurri','BSCZ 1',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-05-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2012%'),366660,'SNOOKERIJ 8','Azzurri',0,9);
