delete from cm_match_details where game_id in (select game_id from cm_matches where cpn_id = (select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2011%'));
delete from cm_matches where cpn_id = (select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2011%');
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-09-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2011%'),293959,'VINK 1','Ames 2 De Zwervers',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293959,'Roelan Derks','Wim Manders',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293959,'Peter Kok','Math van der Linden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293959,'Ruud de Jong','Frans van Poppel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293959,'Roelan Derks','Math van der Linden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293959,'Peter Kok','Frans van Poppel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293959,'Ruud de Jong','Wim Manders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293959,'Ruud de Jong','Math van der Linden',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293959,'Peter Kok','Wim Manders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293959,'Roelan Derks','Frans van Poppel',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('28-09-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2011%'),293963,'VEGHEL 2','HYPRO.BE',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293963,'Gertjan Huiskes','Henri van de Coevering',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293963,'Theo van den Anker','Mark Voermans',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293963,'Jacques Willem van Melis','Laurens Boleij',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293963,'Gertjan Huiskes','Mark Voermans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293963,'Theo van den Anker','Laurens Boleij',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293963,'Jacques Willem van Melis','Henri van de Coevering',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293963,'Jacques Willem van Melis','Mark Voermans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293963,'Theo van den Anker','Henri van de Coevering',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293963,'Gertjan Huiskes','Laurens Boleij',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-10-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2011%'),293965,'AVVL','VEGHEL 2',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293965,'Sicco Vollema','Gertjan Huiskes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293965,'Herman van Deutekom','Jacques Willem van Melis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293965,'Raymond Ruesink','Gertjan Huiskes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293965,'Sicco Vollema','Jacques Willem van Melis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293965,'Herman van Deutekom','Gertjan Huiskes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293965,'Raymond Ruesink','Jacques Willem van Melis',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-10-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2011%'),293966,'HYPRO.BE','Ames 2 De Zwervers',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293966,'Laurens Boleij','Math van der Linden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293966,'Henri van de Coevering','Wim Manders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293966,'Mark Voermans','Anthony Bisschops',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293966,'Laurens Boleij','Wim Manders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293966,'Henri van de Coevering','Anthony Bisschops',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293966,'Mark Voermans','Math van der Linden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293966,'Mark Voermans','Wim Manders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293966,'Henri van de Coevering','Math van der Linden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293966,'Laurens Boleij','Anthony Bisschops',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-10-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2011%'),293967,'Ames 2 De Zwervers','AVVL',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293967,'Math van der Linden','Sicco Vollema',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293967,'Frans van Poppel','Raymond Ruesink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293967,'Anthony Bisschops','Herman van Deutekom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293967,'Math van der Linden','Raymond Ruesink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293967,'Frans van Poppel','Herman van Deutekom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293967,'Anthony Bisschops','Sicco Vollema',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293967,'Anthony Bisschops','Raymond Ruesink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293967,'Frans van Poppel','Sicco Vollema',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293967,'Math van der Linden','Herman van Deutekom',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('28-10-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2011%'),305577,'HYPRO.BE','AVVL',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(305577,'Laurens Boleij','Herman van Deutekom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(305577,'Mark Voermans','Sicco Vollema',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(305577,'Henri van de Coevering','Raymond Ruesink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(305577,'Laurens Boleij','Sicco Vollema',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(305577,'Mark Voermans','Raymond Ruesink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(305577,'Henri van de Coevering','Herman van Deutekom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(305577,'Henri van de Coevering','Sicco Vollema',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(305577,'Mark Voermans','Herman van Deutekom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(305577,'Laurens Boleij','Raymond Ruesink',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2011%'),293970,'VEGHEL 2','Ames 2 De Zwervers',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293970,'Jacques Willem van Melis','Math van der Linden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293970,'Theo van den Anker','Hans Moerkerk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293970,'Gertjan Huiskes','Wim Manders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293970,'Jacques Willem van Melis','Hans Moerkerk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293970,'Theo van den Anker','Wim Manders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293970,'Gertjan Huiskes','Math van der Linden',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293970,'Gertjan Huiskes','Hans Moerkerk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293970,'Theo van den Anker','Math van der Linden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293970,'Jacques Willem van Melis','Wim Manders',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2011%'),293972,'HYPRO.BE','VINK 1',9,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293972,'Laurens Boleij','Peter Kok',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293972,'Mark Voermans','Roelan Derks',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293972,'Henri van de Coevering','Michiel Heslinga',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293972,'Laurens Boleij','Roelan Derks',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293972,'Mark Voermans','Michiel Heslinga',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293972,'Henri van de Coevering','Peter Kok',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293972,'Henri van de Coevering','Roelan Derks',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293972,'Mark Voermans','Peter Kok',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293972,'Laurens Boleij','Michiel Heslinga',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2011%'),306934,'AVVL','De Dieze 4',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(306934,'Raymond Ruesink','Ko van Zeeland',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(306934,'Sicco Vollema','Dion Jaspers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(306934,'Herman van Deutekom','Hennie van Kuijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(306934,'Raymond Ruesink','Dion Jaspers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(306934,'Sicco Vollema','Hennie van Kuijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(306934,'Herman van Deutekom','Ko van Zeeland',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(306934,'Herman van Deutekom','Dion Jaspers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(306934,'Sicco Vollema','Ko van Zeeland',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(306934,'Raymond Ruesink','Hennie van Kuijk',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2011%'),306714,'De Dieze 4','HYPRO.BE',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(306714,'Mario Veltman','René van de Brand',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(306714,'Dion Jaspers','Laurens Boleij',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(306714,'Sander Mosselman','Henri van de Coevering',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(306714,'Mario Veltman','Laurens Boleij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(306714,'Dion Jaspers','Henri van de Coevering',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(306714,'Sander Mosselman','René van de Brand',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(306714,'Sander Mosselman','Laurens Boleij',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(306714,'Dion Jaspers','René van de Brand',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(306714,'Mario Veltman','Henri van de Coevering',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2011%'),293974,'De Dieze 4','VEGHEL 2',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293974,'Sander Mosselman','Gertjan Huiskes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293974,'Ko van Zeeland','Theo van den Anker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293974,'Hennie van Kuijk','Gertjan Huiskes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293974,'Sander Mosselman','Theo van den Anker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293974,'Ko van Zeeland','Gertjan Huiskes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293974,'Hennie van Kuijk','Theo van den Anker',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2011%'),293975,'VINK 1','AVVL',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293975,'Hijlko Soepboer','Herman van Deutekom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293975,'Roelan Derks','Sicco Vollema',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293975,'Ruud de Jong','Raymond Ruesink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293975,'Hijlko Soepboer','Sicco Vollema',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293975,'Roelan Derks','Raymond Ruesink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293975,'Ruud de Jong','Herman van Deutekom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293975,'Ruud de Jong','Sicco Vollema',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293975,'Roelan Derks','Herman van Deutekom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293975,'Hijlko Soepboer','Raymond Ruesink',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2011%'),293976,'Ames 2 De Zwervers','De Dieze 4',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293976,'Math van der Linden','Sander Mosselman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293976,'Wim Manders','Hennie van Kuijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293976,'Frans van Poppel','Dion Jaspers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293976,'Math van der Linden','Hennie van Kuijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293976,'Wim Manders','Dion Jaspers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293976,'Frans van Poppel','Sander Mosselman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293976,'Frans van Poppel','Hennie van Kuijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293976,'Wim Manders','Sander Mosselman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293976,'Math van der Linden','Dion Jaspers',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2011%'),293977,'VEGHEL 2','VINK 1',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('29-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2011%'),293979,'Ames 2 De Zwervers','VINK 1',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293979,'Hans Moerkerk','Roelan Derks',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293979,'Wim Manders','Hijlko Soepboer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293979,'Anthony Bisschops','Michiel Heslinga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293979,'Hans Moerkerk','Hijlko Soepboer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293979,'Wim Manders','Michiel Heslinga',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293979,'Anthony Bisschops','Roelan Derks',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293979,'Anthony Bisschops','Hijlko Soepboer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293979,'Wim Manders','Roelan Derks',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293979,'Hans Moerkerk','Michiel Heslinga',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('30-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2011%'),293981,'AVVL','HYPRO.BE',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293981,'Raymond Ruesink','Laurens Boleij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293981,'Sicco Vollema','René van de Brand',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293981,'Herman van Deutekom','Mark Voermans',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293981,'Raymond Ruesink','René van de Brand',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293981,'Sicco Vollema','Mark Voermans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293981,'Herman van Deutekom','Laurens Boleij',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293981,'Herman van Deutekom','René van de Brand',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293981,'Sicco Vollema','Laurens Boleij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293981,'Raymond Ruesink','Mark Voermans',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-12-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2011%'),307478,'De Dieze 4','VINK 1',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(307478,'Hennie van Kuijk','Michiel Heslinga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(307478,'Dion Jaspers','Hijlko Soepboer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(307478,'Sander Mosselman','Ruud de Jong',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(307478,'Hennie van Kuijk','Hijlko Soepboer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(307478,'Dion Jaspers','Ruud de Jong',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(307478,'Sander Mosselman','Michiel Heslinga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(307478,'Sander Mosselman','Hijlko Soepboer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(307478,'Dion Jaspers','Michiel Heslinga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(307478,'Hennie van Kuijk','Ruud de Jong',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-12-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2011%'),293984,'HYPRO.BE','VEGHEL 2',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293984,'Laurens Boleij','Theo van den Anker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293984,'René van de Brand','Carlo Hommeles',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293984,'Henri van de Coevering','Carlo Hommeles',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293984,'René van de Brand','Theo van den Anker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293984,'Henri van de Coevering','Theo van den Anker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293984,'Laurens Boleij','Carlo Hommeles',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2011%'),293985,'Ames 2 De Zwervers','HYPRO.BE',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293985,'Wim Manders','Henri van de Coevering',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293985,'Frans van Poppel','René van de Brand',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293985,'Hans Moerkerk','Mark Voermans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293985,'Wim Manders','René van de Brand',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293985,'Frans van Poppel','Mark Voermans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293985,'Hans Moerkerk','Henri van de Coevering',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293985,'Hans Moerkerk','René van de Brand',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293985,'Frans van Poppel','Henri van de Coevering',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293985,'Wim Manders','Mark Voermans',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2011%'),308056,'VINK 1','De Dieze 4',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308056,'Michiel Heslinga','Sander Mosselman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308056,'Peter Kok','Mario Veltman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308056,'Ruud de Jong','Ko van Zeeland',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308056,'Michiel Heslinga','Mario Veltman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308056,'Peter Kok','Ko van Zeeland',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308056,'Ruud de Jong','Sander Mosselman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308056,'Ruud de Jong','Mario Veltman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308056,'Peter Kok','Sander Mosselman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308056,'Michiel Heslinga','Ko van Zeeland',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2011%'),293989,'AVVL','Ames 2 De Zwervers',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293989,'Herman van Deutekom','Frans van Poppel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293989,'Sicco Vollema','Anthony Bisschops',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293989,'Raymond Ruesink','Wim Manders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293989,'Herman van Deutekom','Anthony Bisschops',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293989,'Sicco Vollema','Wim Manders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293989,'Raymond Ruesink','Frans van Poppel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293989,'Raymond Ruesink','Anthony Bisschops',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293989,'Sicco Vollema','Frans van Poppel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293989,'Herman van Deutekom','Wim Manders',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2011%'),293991,'Ames 2 De Zwervers','VEGHEL 2',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293991,'Math van der Linden','Theo van den Anker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293991,'Frans van Poppel','Gertjan Huiskes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293991,'Hans Moerkerk','Gertjan Huiskes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293991,'Frans van Poppel','Theo van den Anker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293991,'Hans Moerkerk','Theo van den Anker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293991,'Math van der Linden','Gertjan Huiskes',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('25-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2011%'),293992,'De Dieze 4','AVVL',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293992,'Sander Mosselman','Sicco Vollema',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293992,'Mario Veltman','Raymond Ruesink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293992,'Ko van Zeeland','Herman van Deutekom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293992,'Sander Mosselman','Raymond Ruesink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293992,'Mario Veltman','Herman van Deutekom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293992,'Ko van Zeeland','Sicco Vollema',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293992,'Ko van Zeeland','Raymond Ruesink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293992,'Mario Veltman','Sicco Vollema',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293992,'Sander Mosselman','Herman van Deutekom',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('26-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2011%'),293993,'VINK 1','HYPRO.BE',9,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293993,'Peter Kok','Mark Voermans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293993,'Michiel Heslinga','René van de Brand',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293993,'Hijlko Soepboer','Laurens Boleij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293993,'Peter Kok','René van de Brand',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293993,'Michiel Heslinga','Laurens Boleij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293993,'Hijlko Soepboer','Mark Voermans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293993,'Hijlko Soepboer','René van de Brand',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293993,'Michiel Heslinga','Mark Voermans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293993,'Peter Kok','Laurens Boleij',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('01-02-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2011%'),308447,'VEGHEL 2','AVVL',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308447,'Carlo Hommeles','Herman van Deutekom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308447,'Theo van den Anker','Raymond Ruesink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308447,'Gertjan Huiskes','Sicco Vollema',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308447,'Carlo Hommeles','Raymond Ruesink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308447,'Theo van den Anker','Sicco Vollema',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308447,'Gertjan Huiskes','Herman van Deutekom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308447,'Gertjan Huiskes','Raymond Ruesink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308447,'Theo van den Anker','Herman van Deutekom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308447,'Carlo Hommeles','Sicco Vollema',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-02-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2011%'),293994,'VEGHEL 2','De Dieze 4',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293994,'Jacques Willem van Melis','Dion Jaspers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293994,'Gertjan Huiskes','Hennie van Kuijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293994,'Jacques Willem van Melis','Sander Mosselman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293994,'Gertjan Huiskes','Dion Jaspers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293994,'Gertjan Huiskes','Sander Mosselman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293994,'Jacques Willem van Melis','Hennie van Kuijk',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-02-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2011%'),293995,'AVVL','VINK 1',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293995,'Herman van Deutekom','Ruud de Jong',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293995,'Sicco Vollema','Hijlko Soepboer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293995,'Raymond Ruesink','Roelan Derks',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293995,'Herman van Deutekom','Hijlko Soepboer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293995,'Sicco Vollema','Roelan Derks',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293995,'Raymond Ruesink','Ruud de Jong',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293995,'Raymond Ruesink','Hijlko Soepboer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293995,'Sicco Vollema','Ruud de Jong',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293995,'Herman van Deutekom','Roelan Derks',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-02-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2011%'),293998,'De Dieze 4','Ames 2 De Zwervers',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293998,'Hennie van Kuijk','Anthony Bisschops',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293998,'Mario Veltman','Frans van Poppel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293998,'Ko van Zeeland','Wim Manders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293998,'Hennie van Kuijk','Frans van Poppel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293998,'Mario Veltman','Wim Manders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293998,'Ko van Zeeland','Anthony Bisschops',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293998,'Ko van Zeeland','Frans van Poppel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293998,'Mario Veltman','Anthony Bisschops',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(293998,'Hennie van Kuijk','Wim Manders',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('01-03-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2011%'),294001,'VINK 1','Ames 2 De Zwervers',9,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294001,'Roelan Derks','Anthony Bisschops',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294001,'Ruud de Jong','Frans van Poppel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294001,'Hijlko Soepboer','Math van der Linden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294001,'Roelan Derks','Frans van Poppel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294001,'Ruud de Jong','Math van der Linden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294001,'Hijlko Soepboer','Anthony Bisschops',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294001,'Hijlko Soepboer','Frans van Poppel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294001,'Ruud de Jong','Anthony Bisschops',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294001,'Roelan Derks','Math van der Linden',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-03-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2011%'),308399,'HYPRO.BE','De Dieze 4',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308399,'Laurens Boleij','Hennie van Kuijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308399,'Henri van de Coevering','Ko van Zeeland',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308399,'Mark Voermans','Dion Jaspers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308399,'Laurens Boleij','Ko van Zeeland',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308399,'Henri van de Coevering','Dion Jaspers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308399,'Mark Voermans','Hennie van Kuijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308399,'Mark Voermans','Ko van Zeeland',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308399,'Henri van de Coevering','Hennie van Kuijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308399,'Laurens Boleij','Dion Jaspers',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-03-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2011%'),309033,'VINK 1','VEGHEL 2',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309033,'Peter Kok','Gertjan Huiskes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309033,'Hijlko Soepboer','Theo van den Anker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309033,'Michiel Heslinga','Theo van den Anker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309033,'Hijlko Soepboer','Gertjan Huiskes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309033,'Michiel Heslinga','Gertjan Huiskes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309033,'Peter Kok','Theo van den Anker',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-03-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2011%'),308413,'HYPRO.BE','AVVL',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308413,'Laurens Boleij','Sicco Vollema',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308413,'Henri van de Coevering','Raymond Ruesink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308413,'René van de Brand','Herman van Deutekom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308413,'Laurens Boleij','Raymond Ruesink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308413,'Henri van de Coevering','Herman van Deutekom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308413,'René van de Brand','Sicco Vollema',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308413,'René van de Brand','Raymond Ruesink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308413,'Henri van de Coevering','Sicco Vollema',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308413,'Laurens Boleij','Herman van Deutekom',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-03-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2011%'),308958,'AVVL','De Dieze 4',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308958,'Herman van Deutekom','Dion Jaspers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308958,'Sicco Vollema','Sander Mosselman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308958,'Raymond Ruesink','Ko van Zeeland',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308958,'Herman van Deutekom','Sander Mosselman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308958,'Sicco Vollema','Ko van Zeeland',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308958,'Raymond Ruesink','Dion Jaspers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308958,'Raymond Ruesink','Sander Mosselman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308958,'Sicco Vollema','Dion Jaspers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308958,'Herman van Deutekom','Ko van Zeeland',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('28-03-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2011%'),294004,'De Dieze 4','VINK 1',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294004,'Dion Jaspers','Hijlko Soepboer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294004,'Sander Mosselman','Ruud de Jong',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294004,'Mario Veltman','Roelan Derks',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294004,'Dion Jaspers','Ruud de Jong',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294004,'Sander Mosselman','Roelan Derks',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294004,'Mario Veltman','Hijlko Soepboer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294004,'Mario Veltman','Ruud de Jong',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294004,'Sander Mosselman','Hijlko Soepboer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294004,'Dion Jaspers','Roelan Derks',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('28-03-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2011%'),294005,'VEGHEL 2','HYPRO.BE',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294005,'Theo van den Anker','Mark Voermans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294005,'Gertjan Huiskes','René van de Brand',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294005,'Carlo Hommeles','Henri van de Coevering',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294005,'Theo van den Anker','René van de Brand',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294005,'Gertjan Huiskes','Henri van de Coevering',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294005,'Carlo Hommeles','Mark Voermans',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294005,'Carlo Hommeles','René van de Brand',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294005,'Gertjan Huiskes','Mark Voermans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294005,'Theo van den Anker','Henri van de Coevering',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-04-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2011%'),294007,'AVVL','VEGHEL 2',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294007,'Sicco Vollema','René van Bavel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294007,'Raymond Ruesink','Gertjan Huiskes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294007,'Herman van Deutekom','René van Bavel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294007,'Sicco Vollema','Gertjan Huiskes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294007,'Raymond Ruesink','René van Bavel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294007,'Herman van Deutekom','Gertjan Huiskes',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-04-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2011%'),294008,'HYPRO.BE','Ames 2 De Zwervers',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294008,'Laurens Boleij','Anthony Bisschops',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294008,'Mark Voermans','Frans van Poppel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294008,'René van de Brand','Wim Manders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294008,'Laurens Boleij','Frans van Poppel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294008,'Mark Voermans','Wim Manders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294008,'René van de Brand','Anthony Bisschops',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294008,'René van de Brand','Frans van Poppel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294008,'Mark Voermans','Anthony Bisschops',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294008,'Laurens Boleij','Wim Manders',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-04-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2011%'),294009,'Ames 2 De Zwervers','AVVL',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294009,'Wim Manders','Sicco Vollema',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294009,'Math van der Linden','Raymond Ruesink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294009,'Hans Moerkerk','Herman van Deutekom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294009,'Wim Manders','Raymond Ruesink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294009,'Math van der Linden','Herman van Deutekom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294009,'Hans Moerkerk','Sicco Vollema',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294009,'Hans Moerkerk','Raymond Ruesink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294009,'Math van der Linden','Sicco Vollema',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294009,'Wim Manders','Herman van Deutekom',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-04-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2011%'),294010,'De Dieze 4','HYPRO.BE',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294010,'Hennie van Kuijk','Henri van de Coevering',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294010,'Sander Mosselman','René van de Brand',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294010,'Mario Veltman','Laurens Boleij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294010,'Hennie van Kuijk','René van de Brand',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294010,'Sander Mosselman','Laurens Boleij',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294010,'Mario Veltman','Henri van de Coevering',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294010,'Mario Veltman','René van de Brand',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294010,'Sander Mosselman','Henri van de Coevering',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294010,'Hennie van Kuijk','Laurens Boleij',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-04-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2011%'),294012,'VEGHEL 2','Ames 2 De Zwervers',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294012,'Jacques Willem van Melis','Wim Manders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294012,'Theo van den Anker','Frans van Poppel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294012,'Gertjan Huiskes','Math van der Linden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294012,'Jacques Willem van Melis','Frans van Poppel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294012,'Theo van den Anker','Math van der Linden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294012,'Gertjan Huiskes','Wim Manders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294012,'Gertjan Huiskes','Frans van Poppel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294012,'Theo van den Anker','Wim Manders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294012,'Jacques Willem van Melis','Math van der Linden',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2011%'),309608,'HYPRO.BE','VINK 1',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309608,'Laurens Boleij','Roelan Derks',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309608,'Henri van de Coevering','Ruud de Jong',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309608,'René van de Brand','Hijlko Soepboer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309608,'Laurens Boleij','Ruud de Jong',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309608,'Henri van de Coevering','Hijlko Soepboer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309608,'René van de Brand','Roelan Derks',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309608,'René van de Brand','Ruud de Jong',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309608,'Henri van de Coevering','Roelan Derks',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309608,'Laurens Boleij','Hijlko Soepboer',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2011%'),294017,'VINK 1','AVVL',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294017,'Peter Kok','Sicco Vollema',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294017,'Michiel Heslinga','Raymond Ruesink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294017,'Hijlko Soepboer','Herman van Deutekom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294017,'Peter Kok','Raymond Ruesink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294017,'Michiel Heslinga','Herman van Deutekom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294017,'Hijlko Soepboer','Sicco Vollema',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294017,'Hijlko Soepboer','Raymond Ruesink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294017,'Michiel Heslinga','Sicco Vollema',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294017,'Peter Kok','Herman van Deutekom',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2011%'),294018,'Ames 2 De Zwervers','De Dieze 4',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294018,'Math van der Linden','Sander Mosselman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294018,'Hans Moerkerk','Dion Jaspers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294018,'Frans van Poppel','Hennie van Kuijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294018,'Math van der Linden','Dion Jaspers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294018,'Hans Moerkerk','Hennie van Kuijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294018,'Frans van Poppel','Sander Mosselman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294018,'Frans van Poppel','Dion Jaspers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294018,'Hans Moerkerk','Sander Mosselman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294018,'Math van der Linden','Hennie van Kuijk',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2011%'),294019,'VEGHEL 2','VINK 1',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294019,'Theo van den Anker','Michiel Heslinga',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294019,'Gertjan Huiskes','Ruud de Jong',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294019,'Theo van den Anker','Roelan Derks',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294019,'Gertjan Huiskes','Michiel Heslinga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294019,'Gertjan Huiskes','Roelan Derks',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294019,'Theo van den Anker','Ruud de Jong',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2011%'),309791,'De Dieze 4','VEGHEL 2',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309791,'Dion Jaspers','Gertjan Huiskes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309791,'Ko van Zeeland','Theo van den Anker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309791,'Mario Veltman','Theo van den Anker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309791,'Ko van Zeeland','Gertjan Huiskes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309791,'Mario Veltman','Gertjan Huiskes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309791,'Dion Jaspers','Theo van den Anker',0,1);
