delete from cm_match_details where game_id in (select game_id from cm_matches where cpn_id = (select id from cm_competitions where name = 'Tweede klasse poule 5' and ssn_id like '2011%'));
delete from cm_matches where cpn_id = (select id from cm_competitions where name = 'Tweede klasse poule 5' and ssn_id like '2011%');
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-09-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 5' and ssn_id like '2011%'),294081,'SNOOKERPALACE PUTTE','Spijkenisse Quattro',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294081,'Ward van Doren','Dennis de Ruiter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294081,'Peter de Brie','Marcel Paulus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294081,'Peter van Someren','Marcel Paulus',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294081,'Peter de Brie','Dennis de Ruiter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294081,'Peter van Someren','Dennis de Ruiter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294081,'Ward van Doren','Marcel Paulus',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-09-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 5' and ssn_id like '2011%'),294083,'THE GREEN SENSATIONS','Los Reyes 2',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294083,'Dennis van der Marel','René de Winter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294083,'Michael van der Wulp','Arno van Vlokhoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294083,'Roland van der Wulp','Gozewijn van Laatum',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294083,'Dennis van der Marel','Arno van Vlokhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294083,'Michael van der Wulp','Gozewijn van Laatum',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294083,'Roland van der Wulp','René de Winter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294083,'Roland van der Wulp','Arno van Vlokhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294083,'Michael van der Wulp','René de Winter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294083,'Dennis van der Marel','Gozewijn van Laatum',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-09-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 5' and ssn_id like '2011%'),294085,'Spijkenisse Quattro','Reyerboys',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294085,'Bas Lange','Gerard van Vliet',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294085,'Leslie van Leeuwen','Frans Romeijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294085,'Marcel Paulus','Marcel van der Heiden',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294085,'Bas Lange','Frans Romeijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294085,'Leslie van Leeuwen','Marcel van der Heiden',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294085,'Marcel Paulus','Gerard van Vliet',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294085,'Marcel Paulus','Frans Romeijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294085,'Leslie van Leeuwen','Gerard van Vliet',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294085,'Bas Lange','Marcel van der Heiden',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('30-09-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 5' and ssn_id like '2011%'),294086,'Los Reyes 2','SNOOKERPALACE PUTTE',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294086,'René de Winter','David Smeekens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294086,'Arno van Vlokhoven','Ward van Doren',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294086,'Bert van der Linden','Peter de Brie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294086,'René de Winter','Ward van Doren',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294086,'Arno van Vlokhoven','Peter de Brie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294086,'Bert van der Linden','David Smeekens',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294086,'Bert van der Linden','Ward van Doren',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294086,'Arno van Vlokhoven','David Smeekens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294086,'René de Winter','Peter de Brie',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-10-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 5' and ssn_id like '2011%'),294089,'Reyerboys','THE GREEN SENSATIONS',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294089,'Marcel van der Heiden','Jeffrey de Wijs',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294089,'Gerard van Vliet','Roland van der Wulp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294089,'Frans Romeijn','Dennis van der Marel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294089,'Marcel van der Heiden','Roland van der Wulp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294089,'Gerard van Vliet','Dennis van der Marel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294089,'Frans Romeijn','Jeffrey de Wijs',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294089,'Frans Romeijn','Roland van der Wulp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294089,'Gerard van Vliet','Jeffrey de Wijs',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294089,'Marcel van der Heiden','Dennis van der Marel',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-10-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 5' and ssn_id like '2011%'),294091,'THE GREEN SENSATIONS','SNOOKERPALACE PUTTE',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294091,'Dennis van der Marel','David Smeekens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294091,'Jeroen Gode','Peter de Brie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294091,'Jeroen Hofmeester','Ward van Doren',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294091,'Dennis van der Marel','Peter de Brie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294091,'Jeroen Gode','Ward van Doren',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294091,'Jeroen Hofmeester','David Smeekens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294091,'Jeroen Hofmeester','Peter de Brie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294091,'Jeroen Gode','David Smeekens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294091,'Dennis van der Marel','Ward van Doren',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-10-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 5' and ssn_id like '2011%'),294092,'Los Reyes 2','Reyerboys',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294092,'Gozewijn van Laatum','Gerard van Vliet',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294092,'René de Winter','Frans Romeijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294092,'Arno van Vlokhoven','Marcel van der Heiden',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294092,'Gozewijn van Laatum','Frans Romeijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294092,'René de Winter','Marcel van der Heiden',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294092,'Arno van Vlokhoven','Gerard van Vliet',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294092,'Arno van Vlokhoven','Frans Romeijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294092,'René de Winter','Gerard van Vliet',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294092,'Gozewijn van Laatum','Marcel van der Heiden',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('31-10-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 5' and ssn_id like '2011%'),306742,'Spijkenisse Quattro','Los Reyes 2',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(306742,'Dennis de Ruiter','Bert van der Linden',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(306742,'Bas Lange','Arno van Vlokhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(306742,'Marcel Paulus','René de Winter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(306742,'Dennis de Ruiter','Arno van Vlokhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(306742,'Bas Lange','René de Winter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(306742,'Marcel Paulus','Bert van der Linden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(306742,'Marcel Paulus','Arno van Vlokhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(306742,'Bas Lange','Bert van der Linden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(306742,'Dennis de Ruiter','René de Winter',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 5' and ssn_id like '2011%'),294093,'Spijkenisse Quattro','THE GREEN SENSATIONS',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294093,'Bas Lange','Roel Pet',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294093,'Dennis de Ruiter','Roland van der Wulp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294093,'Bas Lange','Roland van der Wulp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294093,'Dennis de Ruiter','Dennis van der Marel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294093,'Dennis de Ruiter','Roel Pet',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294093,'Bas Lange','Dennis van der Marel',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 5' and ssn_id like '2011%'),294094,'Reyerboys','SNOOKERPALACE PUTTE',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294094,'Marcel van der Heiden','David Smeekens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294094,'Gerard van Vliet','Peter de Brie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294094,'Frans Romeijn','Ward van Doren',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294094,'Marcel van der Heiden','Peter de Brie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294094,'Gerard van Vliet','Ward van Doren',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294094,'Frans Romeijn','David Smeekens',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294094,'Frans Romeijn','Peter de Brie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294094,'Gerard van Vliet','David Smeekens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294094,'Marcel van der Heiden','Ward van Doren',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 5' and ssn_id like '2011%'),294097,'Spijkenisse Quattro','SNOOKERPALACE PUTTE',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294097,'Dennis de Ruiter','Ward van Doren',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294097,'Bas Lange','Sien Hoppenbrouwers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294097,'Marcel Paulus','Peter de Brie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294097,'Dennis de Ruiter','Sien Hoppenbrouwers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294097,'Bas Lange','Peter de Brie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294097,'Marcel Paulus','Ward van Doren',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294097,'Marcel Paulus','Sien Hoppenbrouwers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294097,'Bas Lange','Ward van Doren',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294097,'Dennis de Ruiter','Peter de Brie',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 5' and ssn_id like '2011%'),294098,'Los Reyes 2','THE GREEN SENSATIONS',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294098,'Gozewijn van Laatum','Jeroen Hofmeester',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294098,'René de Winter','Dennis van der Marel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294098,'Arno van Vlokhoven','Jeroen Gode',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294098,'Gozewijn van Laatum','Dennis van der Marel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294098,'René de Winter','Jeroen Gode',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294098,'Arno van Vlokhoven','Jeroen Hofmeester',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294098,'Arno van Vlokhoven','Dennis van der Marel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294098,'René de Winter','Jeroen Hofmeester',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294098,'Gozewijn van Laatum','Jeroen Gode',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 5' and ssn_id like '2011%'),294100,'Reyerboys','Spijkenisse Quattro',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-12-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 5' and ssn_id like '2011%'),294103,'THE GREEN SENSATIONS','Reyerboys',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294103,'Dennis van der Marel','Gerard van Vliet',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294103,'Michael van der Wulp','Frans Romeijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294103,'Jeroen Hofmeester','Marcel van der Heiden',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294103,'Dennis van der Marel','Frans Romeijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294103,'Michael van der Wulp','Marcel van der Heiden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294103,'Jeroen Hofmeester','Gerard van Vliet',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294103,'Jeroen Hofmeester','Frans Romeijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294103,'Michael van der Wulp','Gerard van Vliet',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294103,'Dennis van der Marel','Marcel van der Heiden',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-12-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 5' and ssn_id like '2011%'),294104,'Los Reyes 2','Spijkenisse Quattro',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-12-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 5' and ssn_id like '2011%'),294105,'SNOOKERPALACE PUTTE','THE GREEN SENSATIONS',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294105,'Ward van Doren','Jeffrey de Wijs',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294105,'Peter van Someren','Michael van der Wulp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294105,'Peter de Brie','Jeroen Gode',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294105,'Ward van Doren','Michael van der Wulp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294105,'Peter van Someren','Jeroen Gode',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294105,'Peter de Brie','Jeffrey de Wijs',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294105,'Peter de Brie','Michael van der Wulp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294105,'Peter van Someren','Jeffrey de Wijs',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294105,'Ward van Doren','Jeroen Gode',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-12-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 5' and ssn_id like '2011%'),294107,'Reyerboys','Los Reyes 2',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 5' and ssn_id like '2011%'),294110,'THE GREEN SENSATIONS','Spijkenisse Quattro',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294110,'Roel Pet','Bas Lange',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294110,'Dennis van der Marel','Marcel Paulus',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294110,'Michael van der Wulp','Dennis de Ruiter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294110,'Roel Pet','Marcel Paulus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294110,'Dennis van der Marel','Dennis de Ruiter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294110,'Michael van der Wulp','Bas Lange',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294110,'Michael van der Wulp','Marcel Paulus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294110,'Dennis van der Marel','Bas Lange',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294110,'Roel Pet','Dennis de Ruiter',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-02-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 5' and ssn_id like '2011%'),294119,'Reyerboys','THE GREEN SENSATIONS',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-02-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 5' and ssn_id like '2011%'),308755,'Los Reyes 2','SNOOKERPALACE PUTTE',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308755,'Gozewijn van Laatum','Peter de Brie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308755,'René de Winter','Ward van Doren',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308755,'Arno van Vlokhoven','Peter van Someren',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308755,'Gozewijn van Laatum','Ward van Doren',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308755,'René de Winter','Peter van Someren',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308755,'Arno van Vlokhoven','Peter de Brie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308755,'Arno van Vlokhoven','Ward van Doren',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308755,'René de Winter','Peter de Brie',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308755,'Gozewijn van Laatum','Peter van Someren',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('01-03-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 5' and ssn_id like '2011%'),294121,'THE GREEN SENSATIONS','SNOOKERPALACE PUTTE',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294121,'Dennis van der Marel','Ward van Doren',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294121,'Jeroen Gode','Peter de Brie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294121,'Michael van der Wulp','David Smeekens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294121,'Dennis van der Marel','Peter de Brie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294121,'Jeroen Gode','David Smeekens',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294121,'Michael van der Wulp','Ward van Doren',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294121,'Michael van der Wulp','Peter de Brie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294121,'Jeroen Gode','Ward van Doren',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294121,'Dennis van der Marel','David Smeekens',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-03-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 5' and ssn_id like '2011%'),294122,'Los Reyes 2','Reyerboys',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294122,'Gozewijn van Laatum','Frans Romeijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294122,'Arno van Vlokhoven','Gerard van Vliet',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294122,'René de Winter','Gerard van Vliet',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294122,'Arno van Vlokhoven','Frans Romeijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294122,'René de Winter','Frans Romeijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294122,'Gozewijn van Laatum','Gerard van Vliet',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-03-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 5' and ssn_id like '2011%'),308872,'Spijkenisse Quattro','Reyerboys',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308872,'Dennis de Ruiter','Gerard van Vliet',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308872,'Bas Lange','Frans Romeijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308872,'Marcel Paulus','Marcel van der Heiden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308872,'Dennis de Ruiter','Frans Romeijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308872,'Bas Lange','Marcel van der Heiden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308872,'Marcel Paulus','Gerard van Vliet',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308872,'Marcel Paulus','Frans Romeijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308872,'Bas Lange','Gerard van Vliet',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308872,'Dennis de Ruiter','Marcel van der Heiden',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-03-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 5' and ssn_id like '2011%'),308779,'THE GREEN SENSATIONS','Los Reyes 2',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-03-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 5' and ssn_id like '2011%'),308663,'Spijkenisse Quattro','Los Reyes 2',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308663,'Dennis de Ruiter','René de Winter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308663,'Bas Lange','Arno van Vlokhoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308663,'Marcel Paulus','Bert van der Linden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308663,'Dennis de Ruiter','Arno van Vlokhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308663,'Bas Lange','Bert van der Linden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308663,'Marcel Paulus','René de Winter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308663,'Marcel Paulus','Arno van Vlokhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308663,'Bas Lange','René de Winter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308663,'Dennis de Ruiter','Bert van der Linden',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-03-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 5' and ssn_id like '2011%'),308871,'SNOOKERPALACE PUTTE','Reyerboys',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308871,'David Smeekens','Gerard van Vliet',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308871,'Peter de Brie','Marcel van der Heiden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308871,'Peter van Someren','Frans Romeijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308871,'David Smeekens','Marcel van der Heiden',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308871,'Peter de Brie','Frans Romeijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308871,'Peter van Someren','Gerard van Vliet',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308871,'Peter van Someren','Marcel van der Heiden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308871,'Peter de Brie','Gerard van Vliet',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308871,'David Smeekens','Frans Romeijn',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-03-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 5' and ssn_id like '2011%'),294123,'Spijkenisse Quattro','THE GREEN SENSATIONS',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294123,'Dennis de Ruiter','Jeroen Gode',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294123,'Bas Lange','Jeffrey de Wijs',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294123,'Marcel Paulus','Dennis van der Marel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294123,'Dennis de Ruiter','Jeffrey de Wijs',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294123,'Bas Lange','Dennis van der Marel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294123,'Marcel Paulus','Jeroen Gode',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294123,'Marcel Paulus','Jeffrey de Wijs',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294123,'Bas Lange','Jeroen Gode',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294123,'Dennis de Ruiter','Dennis van der Marel',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-03-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 5' and ssn_id like '2011%'),294124,'Reyerboys','SNOOKERPALACE PUTTE',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294124,'Frans Romeijn','David Smeekens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294124,'Marcel van der Heiden','Peter de Brie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294124,'Gerard van Vliet','Peter van Someren',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294124,'Frans Romeijn','Peter de Brie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294124,'Marcel van der Heiden','Peter van Someren',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294124,'Gerard van Vliet','David Smeekens',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294124,'Gerard van Vliet','Peter de Brie',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294124,'Marcel van der Heiden','David Smeekens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294124,'Frans Romeijn','Peter van Someren',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('31-03-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 5' and ssn_id like '2011%'),308756,'SNOOKERPALACE PUTTE','Los Reyes 2',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308756,'Ward van Doren','Gozewijn van Laatum',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308756,'David Smeekens','Arno van Vlokhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308756,'Peter de Brie','René de Winter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308756,'Ward van Doren','Arno van Vlokhoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308756,'David Smeekens','René de Winter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308756,'Peter de Brie','Gozewijn van Laatum',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308756,'Peter de Brie','Arno van Vlokhoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308756,'David Smeekens','Gozewijn van Laatum',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308756,'Ward van Doren','René de Winter',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('31-03-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 5' and ssn_id like '2011%'),308757,'SNOOKERPALACE PUTTE','Los Reyes 2',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308757,'Ward van Doren','Gozewijn van Laatum',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308757,'David Smeekens','Arno van Vlokhoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308757,'Peter de Brie','René de Winter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308757,'Ward van Doren','Arno van Vlokhoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308757,'David Smeekens','René de Winter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308757,'Peter de Brie','Gozewijn van Laatum',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308757,'Peter de Brie','Arno van Vlokhoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308757,'David Smeekens','Gozewijn van Laatum',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308757,'Ward van Doren','René de Winter',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-04-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 5' and ssn_id like '2011%'),294128,'Los Reyes 2','THE GREEN SENSATIONS',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294128,'Gozewijn van Laatum','Jeroen Gode',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294128,'René de Winter','Michael van der Wulp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294128,'Arno van Vlokhoven','Dennis van der Marel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294128,'Gozewijn van Laatum','Michael van der Wulp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294128,'René de Winter','Dennis van der Marel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294128,'Arno van Vlokhoven','Jeroen Gode',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294128,'Arno van Vlokhoven','Michael van der Wulp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294128,'René de Winter','Jeroen Gode',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294128,'Gozewijn van Laatum','Dennis van der Marel',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-04-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 5' and ssn_id like '2011%'),309414,'Spijkenisse Quattro','SNOOKERPALACE PUTTE',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309414,'Dennis de Ruiter','Peter de Brie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309414,'Bas Lange','Peter van Someren',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309414,'Bas Lange','Peter de Brie',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309414,'Dennis de Ruiter','Peter van Someren',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-04-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 5' and ssn_id like '2011%'),294133,'THE GREEN SENSATIONS','Reyerboys',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-04-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 5' and ssn_id like '2011%'),294134,'Los Reyes 2','Spijkenisse Quattro',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 5' and ssn_id like '2011%'),294135,'SNOOKERPALACE PUTTE','THE GREEN SENSATIONS',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294135,'David Smeekens','Jeffrey de Wijs',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294135,'Ward van Doren','Dennis van der Marel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294135,'Peter de Brie','Michael van der Wulp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294135,'David Smeekens','Dennis van der Marel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294135,'Ward van Doren','Michael van der Wulp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294135,'Peter de Brie','Jeffrey de Wijs',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294135,'Peter de Brie','Dennis van der Marel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294135,'Ward van Doren','Jeffrey de Wijs',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294135,'David Smeekens','Michael van der Wulp',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 5' and ssn_id like '2011%'),294137,'Reyerboys','Los Reyes 2',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 5' and ssn_id like '2011%'),294138,'SNOOKERPALACE PUTTE','Reyerboys',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294138,'Ward van Doren','Marcel van der Heiden',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294138,'David Smeekens','Gerard van Vliet',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294138,'Peter de Brie','Frans Romeijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294138,'Ward van Doren','Gerard van Vliet',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294138,'David Smeekens','Frans Romeijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294138,'Peter de Brie','Marcel van der Heiden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294138,'Peter de Brie','Gerard van Vliet',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294138,'David Smeekens','Marcel van der Heiden',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294138,'Ward van Doren','Frans Romeijn',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 5' and ssn_id like '2011%'),294140,'THE GREEN SENSATIONS','Spijkenisse Quattro',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294140,'Dennis van der Marel','Bas Lange',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294140,'Jeroen Gode','Marcel Paulus',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294140,'Jeffrey de Wijs','Dennis de Ruiter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294140,'Dennis van der Marel','Marcel Paulus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294140,'Jeroen Gode','Dennis de Ruiter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294140,'Jeffrey de Wijs','Bas Lange',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294140,'Jeffrey de Wijs','Marcel Paulus',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294140,'Jeroen Gode','Bas Lange',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294140,'Dennis van der Marel','Dennis de Ruiter',0,1);
