delete from cm_match_details where game_id in (select game_id from cm_matches where cpn_id = (select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'));
delete from cm_matches where cpn_id = (select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%');
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-09-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424442,'Spijkenisse Quattro','NNPV',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424442,'Leslie van Leeuwen','Mark Molier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424442,'Marcel Paulus','Marco Roeleveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424442,'Dennis de Ruiter','Rob Molier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424442,'Leslie van Leeuwen','Marco Roeleveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424442,'Marcel Paulus','Rob Molier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424442,'Dennis de Ruiter','Mark Molier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424442,'Dennis de Ruiter','Marco Roeleveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424442,'Marcel Paulus','Mark Molier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424442,'Leslie van Leeuwen','Rob Molier',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-09-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424443,'JUMBO 13','Ketel 1',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424443,'Lea Lindhout','Dave Lodder',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424443,'Jeroen Keijzer','Paul Timmerman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424443,'Harry Vogelzang','Mark Oortwijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424443,'Lea Lindhout','Paul Timmerman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424443,'Jeroen Keijzer','Mark Oortwijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424443,'Harry Vogelzang','Dave Lodder',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424443,'Harry Vogelzang','Paul Timmerman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424443,'Jeroen Keijzer','Dave Lodder',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424443,'Lea Lindhout','Mark Oortwijn',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-09-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),427828,'Azzurri','JUMBO 3',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(427828,'René de Winter','Csabi Honffy',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(427828,'Arno van Vlokhoven','Rob Oudshoorn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(427828,'Gozewijn van Laatum','Csabi Honffy',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(427828,'René de Winter','Rob Oudshoorn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(427828,'Arno van Vlokhoven','Csabi Honffy',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(427828,'Gozewijn van Laatum','Rob Oudshoorn',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-09-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424446,'NNPV','Azzurri',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424446,'Ruud Heufke Kantelaar','René de Winter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424446,'Nico van Veen','Arno van Vlokhoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424446,'Marco Roeleveld','Gozewijn van Laatum',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424446,'Ruud Heufke Kantelaar','Arno van Vlokhoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424446,'Nico van Veen','Gozewijn van Laatum',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424446,'Marco Roeleveld','René de Winter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424446,'Marco Roeleveld','Arno van Vlokhoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424446,'Nico van Veen','René de Winter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424446,'Ruud Heufke Kantelaar','Gozewijn van Laatum',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-09-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424447,'Ketel 1','BSCZ 1',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424447,'Mark Oortwijn','Peter den Boer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424447,'Erik Oortwijn','Niels Kelder',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424447,'Bas Verwijmeren','Peter Hulst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424447,'Mark Oortwijn','Niels Kelder',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424447,'Erik Oortwijn','Peter Hulst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424447,'Bas Verwijmeren','Peter den Boer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424447,'Bas Verwijmeren','Niels Kelder',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424447,'Erik Oortwijn','Peter den Boer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424447,'Mark Oortwijn','Peter Hulst',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-09-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424448,'Deltaplant','Spijkenisse Quattro',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424448,'John Pape','Marcel Paulus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424448,'Frank van der Laan','Dennis de Ruiter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424448,'Martijn Laan','Bas Lange',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424448,'John Pape','Dennis de Ruiter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424448,'Frank van der Laan','Bas Lange',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424448,'Martijn Laan','Marcel Paulus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424448,'Martijn Laan','Dennis de Ruiter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424448,'Frank van der Laan','Marcel Paulus',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424448,'John Pape','Bas Lange',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('25-09-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424449,'JUMBO 3','JUMBO 13',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424449,'Csabi Honffy','Anton Lindhout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424449,'Rob Oudshoorn','Jeroen Keijzer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424449,'Csabi Honffy','Jeroen Keijzer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424449,'Rob Oudshoorn','Menno Beugelsdijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424449,'Rob Oudshoorn','Anton Lindhout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424449,'Csabi Honffy','Menno Beugelsdijk',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-09-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424450,'SNOOKERIJ 8','HOGEWOERD 3',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('30-09-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424451,'HOGEWOERD 3','Ketel 1',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-10-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424453,'JUMBO 13','NNPV',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424453,'Menno Beugelsdijk','Marco Roeleveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424453,'Lea Lindhout','Nico van Veen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424453,'Harry Vogelzang','Mark Molier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424453,'Menno Beugelsdijk','Nico van Veen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424453,'Lea Lindhout','Mark Molier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424453,'Harry Vogelzang','Marco Roeleveld',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424453,'Harry Vogelzang','Nico van Veen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424453,'Lea Lindhout','Marco Roeleveld',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424453,'Menno Beugelsdijk','Mark Molier',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-10-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424454,'BSCZ 1','JUMBO 3',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424454,'Ron Reeuwijk','Rob Oudshoorn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424454,'Ron Reeuwijk','Csabi Honffy',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424454,'Niels Kelder','Rob Oudshoorn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424454,'Niels Kelder','Csabi Honffy',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-10-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424455,'Azzurri','Deltaplant',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424455,'Gozewijn van Laatum','John Pape',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424455,'René de Winter','Peter Bruggeman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424455,'Arno van Vlokhoven','Regi Verdoorn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424455,'Gozewijn van Laatum','Peter Bruggeman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424455,'René de Winter','Regi Verdoorn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424455,'Arno van Vlokhoven','John Pape',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424455,'Arno van Vlokhoven','Peter Bruggeman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424455,'René de Winter','John Pape',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424455,'Gozewijn van Laatum','Regi Verdoorn',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-10-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424456,'NNPV','BSCZ 1',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424456,'Rob Molier','Glenn van Polanen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424456,'Mark Molier','Peter Hulst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424456,'Marco Roeleveld','Niels Kelder',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424456,'Rob Molier','Peter Hulst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424456,'Mark Molier','Niels Kelder',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424456,'Marco Roeleveld','Glenn van Polanen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424456,'Marco Roeleveld','Peter Hulst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424456,'Mark Molier','Glenn van Polanen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424456,'Rob Molier','Niels Kelder',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-10-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424458,'Spijkenisse Quattro','Azzurri',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424458,'Bas Lange','Arno van Vlokhoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424458,'Dennis de Ruiter','Gozewijn van Laatum',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424458,'Marcel Paulus','René de Winter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424458,'Bas Lange','Gozewijn van Laatum',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424458,'Dennis de Ruiter','René de Winter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424458,'Marcel Paulus','Arno van Vlokhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424458,'Marcel Paulus','Gozewijn van Laatum',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424458,'Dennis de Ruiter','Arno van Vlokhoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424458,'Bas Lange','René de Winter',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-10-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424459,'Deltaplant','JUMBO 13',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424459,'Regi Verdoorn','Jeroen Keijzer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424459,'John Pape','Lea Lindhout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424459,'Peter Bruggeman','Anton Lindhout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424459,'Regi Verdoorn','Lea Lindhout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424459,'John Pape','Anton Lindhout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424459,'Peter Bruggeman','Jeroen Keijzer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424459,'Peter Bruggeman','Lea Lindhout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424459,'John Pape','Jeroen Keijzer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424459,'Regi Verdoorn','Anton Lindhout',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-10-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424460,'JUMBO 3','HOGEWOERD 3',9,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-10-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424461,'HOGEWOERD 3','NNPV',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-10-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424463,'JUMBO 13','Spijkenisse Quattro',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424463,'Anton Lindhout','Dennis de Ruiter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424463,'Jeroen Keijzer','Leslie van Leeuwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424463,'Harry Vogelzang','Marcel Paulus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424463,'Anton Lindhout','Leslie van Leeuwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424463,'Jeroen Keijzer','Marcel Paulus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424463,'Harry Vogelzang','Dennis de Ruiter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424463,'Harry Vogelzang','Leslie van Leeuwen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424463,'Jeroen Keijzer','Dennis de Ruiter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424463,'Anton Lindhout','Marcel Paulus',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('25-10-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424465,'SNOOKERIJ 8','Ketel 1',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('31-10-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),431630,'BSCZ 1','Deltaplant',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431630,'Niels Kelder','Frank van der Laan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431630,'Peter Hulst','Peter Bruggeman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431630,'Niels Kelder','Martijn Laan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431630,'Peter Hulst','Frank van der Laan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431630,'Peter Hulst','Martijn Laan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431630,'Niels Kelder','Peter Bruggeman',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-11-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424467,'Spijkenisse Quattro','BSCZ 1',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424467,'Leslie van Leeuwen','Ron Reeuwijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424467,'Dennis de Ruiter','Niels Kelder',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424467,'Bas Lange','Ron Reeuwijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424467,'Leslie van Leeuwen','Niels Kelder',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424467,'Dennis de Ruiter','Ron Reeuwijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424467,'Bas Lange','Niels Kelder',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-11-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424468,'Deltaplant','HOGEWOERD 3',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424468,'John Pape','Aniel Kalicharan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424468,'Peter Bruggeman','Martijn Korner',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424468,'Martijn Laan','Soerin Ganga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424468,'John Pape','Martijn Korner',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424468,'Peter Bruggeman','Soerin Ganga',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424468,'Martijn Laan','Aniel Kalicharan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424468,'Martijn Laan','Martijn Korner',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424468,'Peter Bruggeman','Aniel Kalicharan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424468,'John Pape','Soerin Ganga',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-11-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424469,'JUMBO 3','SNOOKERIJ 8',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424469,'Csabi Honffy','Rinus Devilee',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424469,'Frank de Rooij','Rinus Devilee',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424469,'Csabi Honffy','Huibert van de Putte',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424469,'Frank de Rooij','Huibert van de Putte',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-11-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424470,'Azzurri','JUMBO 13',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424470,'René de Winter','Menno Beugelsdijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424470,'Arno van Vlokhoven','Lea Lindhout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424470,'Gozewijn van Laatum','Harry Vogelzang',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424470,'René de Winter','Lea Lindhout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424470,'Arno van Vlokhoven','Harry Vogelzang',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424470,'Gozewijn van Laatum','Menno Beugelsdijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424470,'Gozewijn van Laatum','Lea Lindhout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424470,'Arno van Vlokhoven','Menno Beugelsdijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424470,'René de Winter','Harry Vogelzang',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-11-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424473,'Ketel 1','JUMBO 3',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-11-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424475,'BSCZ 1','Azzurri',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424475,'Peter den Boer','Arno van Vlokhoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424475,'Glenn van Polanen','Gozewijn van Laatum',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424475,'Peter Hulst','René de Winter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424475,'Peter den Boer','Gozewijn van Laatum',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424475,'Glenn van Polanen','René de Winter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424475,'Peter Hulst','Arno van Vlokhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424475,'Peter Hulst','Gozewijn van Laatum',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424475,'Glenn van Polanen','Arno van Vlokhoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424475,'Peter den Boer','René de Winter',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-11-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424476,'SNOOKERIJ 8','NNPV',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424476,'Huibert van de Putte','Mark Molier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424476,'Rinus Devilee','Rob Molier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424476,'Huibert van de Putte','Marco Roeleveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424476,'Rinus Devilee','Mark Molier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424476,'Rinus Devilee','Marco Roeleveld',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424476,'Huibert van de Putte','Rob Molier',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('25-11-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424477,'NNPV','Ketel 1',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-11-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424480,'JUMBO 13','BSCZ 1',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424480,'Jeroen Keijzer','Peter den Boer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424480,'Lea Lindhout','Ron Reeuwijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424480,'Menno Beugelsdijk','Niels Kelder',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424480,'Jeroen Keijzer','Ron Reeuwijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424480,'Lea Lindhout','Niels Kelder',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424480,'Menno Beugelsdijk','Peter den Boer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424480,'Menno Beugelsdijk','Ron Reeuwijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424480,'Lea Lindhout','Peter den Boer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424480,'Jeroen Keijzer','Niels Kelder',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('29-11-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424481,'Azzurri','HOGEWOERD 3',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-12-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424482,'HOGEWOERD 3','JUMBO 13',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424482,'Soerin Ganga','Menno Beugelsdijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424482,'Aniel Kalicharan','Lea Lindhout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424482,'Martijn Korner','Harry Vogelzang',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424482,'Soerin Ganga','Lea Lindhout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424482,'Aniel Kalicharan','Harry Vogelzang',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424482,'Martijn Korner','Menno Beugelsdijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424482,'Martijn Korner','Lea Lindhout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424482,'Aniel Kalicharan','Menno Beugelsdijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424482,'Soerin Ganga','Harry Vogelzang',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-12-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424483,'Ketel 1','Deltaplant',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-12-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424485,'JUMBO 3','NNPV',8,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-12-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),432234,'SNOOKERIJ 8','Spijkenisse Quattro',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(432234,'Debbie Anthonissen','Marcel Paulus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(432234,'Huibert van de Putte','Dennis de Ruiter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(432234,'Harry van Exter','Bas Lange',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(432234,'Debbie Anthonissen','Dennis de Ruiter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(432234,'Huibert van de Putte','Bas Lange',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(432234,'Harry van Exter','Marcel Paulus',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(432234,'Harry van Exter','Dennis de Ruiter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(432234,'Huibert van de Putte','Marcel Paulus',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(432234,'Debbie Anthonissen','Bas Lange',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-12-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),431953,'BSCZ 1','SNOOKERIJ 8',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431953,'Niels Kelder','Debbie Anthonissen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431953,'Ron Reeuwijk','Huibert van de Putte',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431953,'Glenn van Polanen','Huibert van de Putte',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431953,'Ron Reeuwijk','Debbie Anthonissen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431953,'Glenn van Polanen','Debbie Anthonissen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(431953,'Niels Kelder','Huibert van de Putte',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-12-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424486,'Spijkenisse Quattro','Ketel 1',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424486,'Bas Lange','Jordy Bax',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424486,'Marcel Paulus','Joram Hensens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424486,'Dennis de Ruiter','Mark Oortwijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424486,'Bas Lange','Joram Hensens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424486,'Marcel Paulus','Mark Oortwijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424486,'Dennis de Ruiter','Jordy Bax',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424486,'Dennis de Ruiter','Joram Hensens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424486,'Marcel Paulus','Jordy Bax',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424486,'Bas Lange','Mark Oortwijn',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-12-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424487,'Deltaplant','JUMBO 3',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424487,'John Pape','Frank de Rooij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424487,'Frank van der Laan','Rob Oudshoorn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424487,'John Pape','Rob Oudshoorn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424487,'Martijn Laan','Frank de Rooij',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424487,'Martijn Laan','Rob Oudshoorn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424487,'Frank van der Laan','Frank de Rooij',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-12-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424489,'BSCZ 1','HOGEWOERD 3',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424489,'Peter den Boer','Aniel Kalicharan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424489,'Ron Reeuwijk','Martijn Korner',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424489,'Peter Hulst','Soerin Ganga',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424489,'Peter den Boer','Martijn Korner',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424489,'Ron Reeuwijk','Soerin Ganga',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424489,'Peter Hulst','Aniel Kalicharan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424489,'Peter Hulst','Martijn Korner',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424489,'Ron Reeuwijk','Aniel Kalicharan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424489,'Peter den Boer','Soerin Ganga',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-12-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424490,'Azzurri','SNOOKERIJ 8',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-01-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424491,'NNPV','Deltaplant',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-01-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424492,'Ketel 1','Azzurri',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-01-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424494,'JUMBO 3','Spijkenisse Quattro',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424494,'Frank de Rooij','Dennis de Ruiter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424494,'Rob Oudshoorn','Bas Lange',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424494,'Frank de Rooij','Bas Lange',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424494,'Rob Oudshoorn','Marcel Paulus',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424494,'Rob Oudshoorn','Dennis de Ruiter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424494,'Frank de Rooij','Marcel Paulus',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-01-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424495,'SNOOKERIJ 8','JUMBO 13',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424495,'Harry van Exter','Harry Vogelzang',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424495,'Huibert van de Putte','Jeroen Keijzer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424495,'Harry van Exter','Jeroen Keijzer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424495,'Huibert van de Putte','Anton Lindhout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424495,'Huibert van de Putte','Harry Vogelzang',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424495,'Harry van Exter','Anton Lindhout',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-01-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424497,'Ketel 1','JUMBO 13',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424497,'Joram Hensens','Menno Beugelsdijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424497,'Jordy Bax','Lea Lindhout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424497,'Dave Lodder','Anton Lindhout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424497,'Joram Hensens','Lea Lindhout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424497,'Jordy Bax','Anton Lindhout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424497,'Dave Lodder','Menno Beugelsdijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424497,'Dave Lodder','Lea Lindhout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424497,'Jordy Bax','Menno Beugelsdijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424497,'Joram Hensens','Anton Lindhout',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-01-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424499,'JUMBO 3','Azzurri',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-01-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424500,'SNOOKERIJ 8','BSCZ 1',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424500,'Huibert van de Putte','Ron Reeuwijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424500,'Harry van Exter','Peter Hulst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424500,'Huibert van de Putte','Peter Hulst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424500,'Harry van Exter','Glenn van Polanen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424500,'Harry van Exter','Ron Reeuwijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424500,'Huibert van de Putte','Glenn van Polanen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-01-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),433348,'NNPV','Spijkenisse Quattro',0,9);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433348,'Rob Molier','Marcel Paulus',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433348,'Marco Roeleveld','Leslie van Leeuwen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433348,'Nico van Veen','Bas Lange',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433348,'Rob Molier','Leslie van Leeuwen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433348,'Marco Roeleveld','Bas Lange',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433348,'Nico van Veen','Marcel Paulus',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433348,'Nico van Veen','Leslie van Leeuwen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433348,'Marco Roeleveld','Marcel Paulus',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433348,'Rob Molier','Bas Lange',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-01-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),432285,'Deltaplant','SNOOKERIJ 8',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-02-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),433658,'HOGEWOERD 3','Spijkenisse Quattro',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433658,'Martijn Korner','Marcel Paulus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433658,'Soerin Ganga','Dennis de Ruiter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433658,'Aniel Kalicharan','Bas Lange',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433658,'Martijn Korner','Dennis de Ruiter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433658,'Soerin Ganga','Bas Lange',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433658,'Aniel Kalicharan','Marcel Paulus',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433658,'Aniel Kalicharan','Dennis de Ruiter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433658,'Soerin Ganga','Marcel Paulus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(433658,'Martijn Korner','Bas Lange',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-02-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424501,'HOGEWOERD 3','SNOOKERIJ 8',8,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('25-02-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424502,'Spijkenisse Quattro','Deltaplant',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424502,'Bas Lange','Frank van der Laan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424502,'Leslie van Leeuwen','Martijn Laan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424502,'Marcel Paulus','John Pape',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424502,'Bas Lange','Martijn Laan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424502,'Leslie van Leeuwen','John Pape',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424502,'Marcel Paulus','Frank van der Laan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424502,'Marcel Paulus','Martijn Laan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424502,'Leslie van Leeuwen','Frank van der Laan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424502,'Bas Lange','John Pape',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('26-02-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424503,'JUMBO 13','JUMBO 3',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424503,'Anton Lindhout','Rob Oudshoorn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424503,'Harry Vogelzang','Frank de Rooij',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424503,'Jeroen Keijzer','Frank de Rooij',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424503,'Harry Vogelzang','Rob Oudshoorn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424503,'Jeroen Keijzer','Rob Oudshoorn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424503,'Anton Lindhout','Frank de Rooij',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-02-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424504,'BSCZ 1','Ketel 1',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424504,'Niels Kelder','Jordy Bax',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424504,'Peter den Boer','Mark Oortwijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424504,'Niels Kelder','Joram Hensens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424504,'Peter den Boer','Jordy Bax',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424504,'Peter den Boer','Joram Hensens',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424504,'Niels Kelder','Mark Oortwijn',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-03-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424506,'NNPV','JUMBO 13',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424506,'Marco Roeleveld','Jeroen Keijzer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424506,'Nico van Veen','Anton Lindhout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424506,'Ruud Heufke Kantelaar','Harry Vogelzang',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424506,'Marco Roeleveld','Anton Lindhout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424506,'Nico van Veen','Harry Vogelzang',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424506,'Ruud Heufke Kantelaar','Jeroen Keijzer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424506,'Ruud Heufke Kantelaar','Anton Lindhout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424506,'Nico van Veen','Jeroen Keijzer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424506,'Marco Roeleveld','Harry Vogelzang',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-03-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424507,'Ketel 1','HOGEWOERD 3',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-03-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424508,'Deltaplant','Azzurri',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424508,'Peter Bruggeman','Arno van Vlokhoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424508,'Frank van der Laan','Gozewijn van Laatum',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424508,'Martijn Laan','René de Winter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424508,'Peter Bruggeman','Gozewijn van Laatum',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424508,'Frank van der Laan','René de Winter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424508,'Martijn Laan','Arno van Vlokhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424508,'Martijn Laan','Gozewijn van Laatum',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424508,'Frank van der Laan','Arno van Vlokhoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424508,'Peter Bruggeman','René de Winter',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-03-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424509,'JUMBO 3','BSCZ 1',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424509,'Frank de Rooij','Peter den Boer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424509,'Rob Oudshoorn','Glenn van Polanen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424509,'Frank de Rooij','Glenn van Polanen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424509,'Rob Oudshoorn','Niels Kelder',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424509,'Rob Oudshoorn','Peter den Boer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424509,'Frank de Rooij','Niels Kelder',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-03-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424513,'JUMBO 13','Deltaplant',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424513,'Menno Beugelsdijk','Peter Bruggeman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424513,'Anton Lindhout','Frank van der Laan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424513,'Harry Vogelzang','John Pape',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424513,'Menno Beugelsdijk','Frank van der Laan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424513,'Anton Lindhout','John Pape',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424513,'Harry Vogelzang','Peter Bruggeman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424513,'Harry Vogelzang','Frank van der Laan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424513,'Anton Lindhout','Peter Bruggeman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424513,'Menno Beugelsdijk','John Pape',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-03-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424514,'BSCZ 1','NNPV',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424514,'Ron Reeuwijk','Rob Molier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424514,'Peter den Boer','Ruud Heufke Kantelaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424514,'Glenn van Polanen','Mark Molier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424514,'Ron Reeuwijk','Ruud Heufke Kantelaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424514,'Peter den Boer','Mark Molier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424514,'Glenn van Polanen','Rob Molier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424514,'Glenn van Polanen','Ruud Heufke Kantelaar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424514,'Peter den Boer','Rob Molier',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424514,'Ron Reeuwijk','Mark Molier',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-03-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424515,'Azzurri','Spijkenisse Quattro',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424515,'René de Winter','Marcel Paulus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424515,'Gozewijn van Laatum','Dennis de Ruiter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424515,'Arno van Vlokhoven','Bas Lange',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424515,'René de Winter','Dennis de Ruiter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424515,'Gozewijn van Laatum','Bas Lange',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424515,'Arno van Vlokhoven','Marcel Paulus',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424515,'Arno van Vlokhoven','Dennis de Ruiter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424515,'Gozewijn van Laatum','Marcel Paulus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424515,'René de Winter','Bas Lange',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-03-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424517,'Ketel 1','SNOOKERIJ 8',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-03-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424518,'Spijkenisse Quattro','JUMBO 13',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424518,'Bas Lange','Menno Beugelsdijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424518,'Marcel Paulus','Jeroen Keijzer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424518,'Dennis de Ruiter','Lea Lindhout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424518,'Bas Lange','Jeroen Keijzer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424518,'Marcel Paulus','Lea Lindhout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424518,'Dennis de Ruiter','Menno Beugelsdijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424518,'Dennis de Ruiter','Jeroen Keijzer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424518,'Marcel Paulus','Menno Beugelsdijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424518,'Bas Lange','Lea Lindhout',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-03-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424519,'Deltaplant','BSCZ 1',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424519,'John Pape','Peter den Boer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424519,'Peter Bruggeman','Ron Reeuwijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424519,'Frank van der Laan','Niels Kelder',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424519,'John Pape','Ron Reeuwijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424519,'Peter Bruggeman','Niels Kelder',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424519,'Frank van der Laan','Peter den Boer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424519,'Frank van der Laan','Ron Reeuwijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424519,'Peter Bruggeman','Peter den Boer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424519,'John Pape','Niels Kelder',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-03-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),434041,'Azzurri','NNPV',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('31-03-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),434397,'NNPV','HOGEWOERD 3',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434397,'Marco Roeleveld','Aniel Kalicharan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434397,'Mark Molier','Martijn Korner',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434397,'Nico van Veen','Soerin Ganga',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434397,'Marco Roeleveld','Martijn Korner',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434397,'Mark Molier','Soerin Ganga',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434397,'Nico van Veen','Aniel Kalicharan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434397,'Nico van Veen','Martijn Korner',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434397,'Mark Molier','Aniel Kalicharan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434397,'Marco Roeleveld','Soerin Ganga',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-04-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424521,'HOGEWOERD 3','Deltaplant',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424521,'Soerin Ganga','Frank van der Laan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424521,'Aniel Kalicharan','Martijn Laan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424521,'Martijn Korner','John Pape',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424521,'Soerin Ganga','Martijn Laan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424521,'Aniel Kalicharan','John Pape',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424521,'Martijn Korner','Frank van der Laan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424521,'Martijn Korner','Martijn Laan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424521,'Aniel Kalicharan','Frank van der Laan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424521,'Soerin Ganga','John Pape',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-04-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424523,'JUMBO 13','Azzurri',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-04-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424524,'BSCZ 1','Spijkenisse Quattro',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424524,'Glenn van Polanen','Marcel Paulus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424524,'Peter Hulst','Bas Lange',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424524,'Glenn van Polanen','Bas Lange',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424524,'Peter Hulst','Leslie van Leeuwen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424524,'Peter Hulst','Marcel Paulus',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424524,'Glenn van Polanen','Leslie van Leeuwen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-04-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424525,'SNOOKERIJ 8','JUMBO 3',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-04-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424526,'NNPV','SNOOKERIJ 8',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424526,'Marco Roeleveld','Rinus Devilee',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424526,'Ruud Heufke Kantelaar','Debbie Anthonissen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424526,'Mark Molier','Huibert van de Putte',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424526,'Marco Roeleveld','Debbie Anthonissen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424526,'Ruud Heufke Kantelaar','Huibert van de Putte',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424526,'Mark Molier','Rinus Devilee',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424526,'Mark Molier','Debbie Anthonissen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424526,'Ruud Heufke Kantelaar','Rinus Devilee',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424526,'Marco Roeleveld','Huibert van de Putte',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-04-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424527,'Spijkenisse Quattro','HOGEWOERD 3',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-04-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424529,'JUMBO 3','Ketel 1',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-04-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424534,'BSCZ 1','JUMBO 13',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424534,'Niels Kelder','Jeroen Keijzer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424534,'Peter den Boer','Lea Lindhout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424534,'Ron Reeuwijk','Menno Beugelsdijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424534,'Niels Kelder','Lea Lindhout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424534,'Peter den Boer','Menno Beugelsdijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424534,'Ron Reeuwijk','Jeroen Keijzer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424534,'Ron Reeuwijk','Lea Lindhout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424534,'Peter den Boer','Jeroen Keijzer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424534,'Niels Kelder','Menno Beugelsdijk',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('25-04-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424535,'SNOOKERIJ 8','Deltaplant',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('28-04-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),434571,'Ketel 1','NNPV',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-05-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424536,'NNPV','JUMBO 3',1,8);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-05-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424537,'Spijkenisse Quattro','SNOOKERIJ 8',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-05-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424539,'JUMBO 13','HOGEWOERD 3',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424539,'Menno Beugelsdijk','Aniel Kalicharan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424539,'Jeroen Keijzer','Martijn Korner',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424539,'Harry Vogelzang','Soerin Ganga',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424539,'Menno Beugelsdijk','Martijn Korner',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424539,'Jeroen Keijzer','Soerin Ganga',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424539,'Harry Vogelzang','Aniel Kalicharan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424539,'Harry Vogelzang','Martijn Korner',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424539,'Jeroen Keijzer','Aniel Kalicharan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424539,'Menno Beugelsdijk','Soerin Ganga',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-05-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),434735,'Azzurri','BSCZ 1',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434735,'René de Winter','Peter den Boer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434735,'Arno van Vlokhoven','Ron Reeuwijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434735,'Gozewijn van Laatum','Niels Kelder',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434735,'René de Winter','Ron Reeuwijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434735,'Arno van Vlokhoven','Niels Kelder',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434735,'Gozewijn van Laatum','Peter den Boer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434735,'Gozewijn van Laatum','Ron Reeuwijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434735,'Arno van Vlokhoven','Peter den Boer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(434735,'René de Winter','Niels Kelder',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-05-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424541,'HOGEWOERD 3','BSCZ 1',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-05-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424542,'Ketel 1','Spijkenisse Quattro',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-05-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424544,'JUMBO 3','Deltaplant',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424544,'Frank de Rooij','Frank van der Laan',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424544,'Rob Oudshoorn','Martijn Laan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424544,'Frank de Rooij','Martijn Laan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424544,'Rob Oudshoorn','John Pape',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424544,'Rob Oudshoorn','Frank van der Laan',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424544,'Frank de Rooij','John Pape',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-05-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424545,'SNOOKERIJ 8','Azzurri',8,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('26-05-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),435201,'HOGEWOERD 3','Azzurri',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-05-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424546,'Spijkenisse Quattro','JUMBO 3',1,8);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-05-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424547,'Deltaplant','NNPV',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424547,'Frank van der Laan','Marco Roeleveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424547,'Peter Bruggeman','Rob Molier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424547,'Martijn Laan','Nico van Veen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424547,'Frank van der Laan','Rob Molier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424547,'Peter Bruggeman','Nico van Veen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424547,'Martijn Laan','Marco Roeleveld',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424547,'Martijn Laan','Rob Molier',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424547,'Peter Bruggeman','Marco Roeleveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424547,'Frank van der Laan','Nico van Veen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('28-05-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424548,'JUMBO 13','SNOOKERIJ 8',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424548,'Menno Beugelsdijk','Huibert van de Putte',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424548,'Jeroen Keijzer','Harry van Exter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424548,'Lea Lindhout','Harry van Exter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424548,'Jeroen Keijzer','Huibert van de Putte',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424548,'Lea Lindhout','Huibert van de Putte',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(424548,'Menno Beugelsdijk','Harry van Exter',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('30-05-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),424550,'Azzurri','Ketel 1',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-06-2014','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse B' and ssn_id like '2013%'),435073,'Deltaplant','Ketel 1',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435073,'John Pape','Jordy Bax',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435073,'Peter Bruggeman','Paul Timmerman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435073,'Martijn Laan','Mark Oortwijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435073,'John Pape','Paul Timmerman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435073,'Peter Bruggeman','Mark Oortwijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435073,'Martijn Laan','Jordy Bax',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435073,'Martijn Laan','Paul Timmerman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435073,'Peter Bruggeman','Jordy Bax',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(435073,'John Pape','Mark Oortwijn',0,1);
