delete from cm_match_details where game_id in (select game_id from cm_matches where cpn_id = (select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'));
delete from cm_matches where cpn_id = (select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%');
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-09-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),351084,'SPDC 1','snookerutrecht.nl',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351084,'Martin Rakké','Pierre Linschoten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351084,'Wim Reinders','Evard Boon',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351084,'Roland Reinders','Jasha Kiers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351084,'Martin Rakké','Evard Boon',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351084,'Wim Reinders','Jasha Kiers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351084,'Roland Reinders','Pierre Linschoten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351084,'Roland Reinders','Evard Boon',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351084,'Wim Reinders','Pierre Linschoten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351084,'Martin Rakké','Jasha Kiers',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-09-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),351085,'SU 3 Fouls doen we nie','OZEBI 3',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351085,'Debabrata Panja','René Kerkhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351085,'Peter Verstraten','Jeroen Sloots',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351085,'Wouter Teensma','Kees Reijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351085,'Debabrata Panja','Jeroen Sloots',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351085,'Peter Verstraten','Kees Reijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351085,'Wouter Teensma','René Kerkhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351085,'Wouter Teensma','Jeroen Sloots',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351085,'Peter Verstraten','René Kerkhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351085,'Debabrata Panja','Kees Reijn',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-09-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),351086,'DE BILJARTMAKERS 2','De Biljartmakers 3',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351086,'Gerard Bocxe','Maurijn Maas',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351086,'Dick Roskamp','Tom van Rossum',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351086,'Lex Franssen','Wim Koudstaal',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351086,'Gerard Bocxe','Tom van Rossum',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351086,'Dick Roskamp','Wim Koudstaal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351086,'Lex Franssen','Maurijn Maas',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351086,'Lex Franssen','Tom van Rossum',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351086,'Dick Roskamp','Maurijn Maas',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351086,'Gerard Bocxe','Wim Koudstaal',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('26-09-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),351087,'De Biljartmakers 3','SU 3 Fouls doen we nie',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351087,'Tom van Rossum','Wouter Teensma',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351087,'Wim Koudstaal','Michiel Vlootman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351087,'Wil van Vliet','Wouter Teensma',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351087,'Tom van Rossum','Michiel Vlootman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351087,'Wim Koudstaal','Wouter Teensma',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351087,'Wil van Vliet','Michiel Vlootman',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-09-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),351088,'OZEBI 3','SPDC 1',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('28-09-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),351089,'snookerutrecht.nl','DE BILJARTMAKERS 2',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351089,'Jasha Kiers','Dick Roskamp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351089,'John Zom','Lex Franssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351089,'Pierre Linschoten','Gerard Bocxe',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351089,'Jasha Kiers','Lex Franssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351089,'John Zom','Gerard Bocxe',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351089,'Pierre Linschoten','Dick Roskamp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351089,'Pierre Linschoten','Lex Franssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351089,'John Zom','Dick Roskamp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351089,'Jasha Kiers','Gerard Bocxe',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-10-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),351091,'DE BILJARTMAKERS 2','SU 3 Fouls doen we nie',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-10-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),351092,'snookerutrecht.nl','OZEBI 3',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351092,'Ruud Klarenbeek','Kees Reijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351092,'John Zom','René Kerkhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351092,'Jasha Kiers','Marijn Sloots',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351092,'Ruud Klarenbeek','René Kerkhoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351092,'John Zom','Marijn Sloots',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351092,'Jasha Kiers','Kees Reijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351092,'Jasha Kiers','René Kerkhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351092,'John Zom','Kees Reijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351092,'Ruud Klarenbeek','Marijn Sloots',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-10-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),351093,'SU 3 Fouls doen we nie','SPDC 1',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351093,'Michiel Vlootman','Roland Reinders',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351093,'Peter Verstraten','Jacques Niehof',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351093,'Wouter Teensma','Martin Rakké',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351093,'Michiel Vlootman','Jacques Niehof',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351093,'Peter Verstraten','Martin Rakké',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351093,'Wouter Teensma','Roland Reinders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351093,'Wouter Teensma','Jacques Niehof',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351093,'Peter Verstraten','Roland Reinders',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351093,'Michiel Vlootman','Martin Rakké',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-10-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),351094,'De Biljartmakers 3','snookerutrecht.nl',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351094,'Fred Ensel','Ruud Klarenbeek',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351094,'Maurijn Maas','Pierre Linschoten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351094,'Tom van Rossum','Evard Boon',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351094,'Fred Ensel','Pierre Linschoten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351094,'Maurijn Maas','Evard Boon',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351094,'Tom van Rossum','Ruud Klarenbeek',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351094,'Tom van Rossum','Pierre Linschoten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351094,'Maurijn Maas','Ruud Klarenbeek',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351094,'Fred Ensel','Evard Boon',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-10-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),351095,'OZEBI 3','DE BILJARTMAKERS 2',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351095,'René Kerkhoven','Dick Roskamp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351095,'Kees Reijn','Gerard Bocxe',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351095,'Marijn Sloots','Lex Franssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351095,'René Kerkhoven','Gerard Bocxe',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351095,'Kees Reijn','Lex Franssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351095,'Marijn Sloots','Dick Roskamp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351095,'Marijn Sloots','Gerard Bocxe',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351095,'Kees Reijn','Dick Roskamp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351095,'René Kerkhoven','Lex Franssen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-10-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),361619,'SPDC 1','De Biljartmakers 3',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(361619,'Roland Reinders','Fred Ensel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(361619,'Wim Reinders','Wil van Vliet',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(361619,'Martin Rakké','Wim Koudstaal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(361619,'Roland Reinders','Wil van Vliet',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(361619,'Wim Reinders','Wim Koudstaal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(361619,'Martin Rakké','Fred Ensel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(361619,'Martin Rakké','Wil van Vliet',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(361619,'Wim Reinders','Fred Ensel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(361619,'Roland Reinders','Wim Koudstaal',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-11-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),351098,'snookerutrecht.nl','SU 3 Fouls doen we nie',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351098,'John Zom','Michiel Vlootman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351098,'Evard Boon','Peter Verstraten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351098,'Jasha Kiers','Michiel Vlootman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351098,'John Zom','Peter Verstraten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351098,'Evard Boon','Michiel Vlootman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351098,'Jasha Kiers','Peter Verstraten',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-11-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),351099,'De Biljartmakers 3','DE BILJARTMAKERS 2',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351099,'Wim Koudstaal','Gerard Bocxe',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351099,'Maurijn Maas','Dick Roskamp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351099,'Fred Ensel','Lex Franssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351099,'Wim Koudstaal','Dick Roskamp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351099,'Maurijn Maas','Lex Franssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351099,'Fred Ensel','Gerard Bocxe',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351099,'Fred Ensel','Dick Roskamp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351099,'Maurijn Maas','Gerard Bocxe',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351099,'Wim Koudstaal','Lex Franssen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-11-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),351100,'OZEBI 3','SU 3 Fouls doen we nie',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-11-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),351101,'snookerutrecht.nl','SPDC 1',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351101,'Ruud Klarenbeek','Wim Reinders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351101,'Evard Boon','Martin Rakké',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351101,'Jasha Kiers','Jacques Niehof',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351101,'Ruud Klarenbeek','Martin Rakké',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351101,'Evard Boon','Jacques Niehof',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351101,'Jasha Kiers','Wim Reinders',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351101,'Jasha Kiers','Martin Rakké',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351101,'Evard Boon','Wim Reinders',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351101,'Ruud Klarenbeek','Jacques Niehof',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-11-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),351102,'SPDC 1','OZEBI 3',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351102,'Martin Rakké','René Kerkhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351102,'Roland Reinders','Marijn Sloots',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351102,'Jacques Niehof','Kees Reijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351102,'Martin Rakké','Marijn Sloots',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351102,'Roland Reinders','Kees Reijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351102,'Jacques Niehof','René Kerkhoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351102,'Jacques Niehof','Marijn Sloots',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351102,'Roland Reinders','René Kerkhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351102,'Martin Rakké','Kees Reijn',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-11-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),351103,'SU 3 Fouls doen we nie','De Biljartmakers 3',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351103,'Michiel Vlootman','Maurijn Maas',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351103,'Peter Verstraten','Tom van Rossum',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351103,'Michiel Vlootman','Fred Ensel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351103,'Peter Verstraten','Maurijn Maas',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351103,'Peter Verstraten','Fred Ensel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351103,'Michiel Vlootman','Tom van Rossum',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-11-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),351104,'DE BILJARTMAKERS 2','snookerutrecht.nl',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351104,'Lex Franssen','John Zom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351104,'Dick Roskamp','Ruud Klarenbeek',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351104,'Gerard Bocxe','Evard Boon',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351104,'Lex Franssen','Ruud Klarenbeek',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351104,'Dick Roskamp','Evard Boon',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351104,'Gerard Bocxe','John Zom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351104,'Gerard Bocxe','Ruud Klarenbeek',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351104,'Dick Roskamp','John Zom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351104,'Lex Franssen','Evard Boon',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-11-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),362667,'DE BILJARTMAKERS 2','SPDC 1',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(362667,'Lex Franssen','Wim Reinders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(362667,'Dick Roskamp','Jacques Niehof',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(362667,'Gerard Bocxe','Roland Reinders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(362667,'Lex Franssen','Jacques Niehof',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(362667,'Dick Roskamp','Roland Reinders',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(362667,'Gerard Bocxe','Wim Reinders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(362667,'Gerard Bocxe','Jacques Niehof',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(362667,'Dick Roskamp','Wim Reinders',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(362667,'Lex Franssen','Roland Reinders',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-12-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),351107,'OZEBI 3','snookerutrecht.nl',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-12-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),351108,'SPDC 1','SU 3 Fouls doen we nie',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351108,'Wim Reinders','Debabrata Panja',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351108,'Jacques Niehof','Michiel Vlootman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351108,'Roland Reinders','Michiel Vlootman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351108,'Jacques Niehof','Debabrata Panja',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351108,'Roland Reinders','Debabrata Panja',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351108,'Wim Reinders','Michiel Vlootman',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-12-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),351109,'DE BILJARTMAKERS 2','OZEBI 3',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351109,'Lex Franssen','Kees Reijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351109,'Dick Roskamp','Marijn Sloots',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351109,'Gerard Bocxe','Robert Rodenburg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351109,'Lex Franssen','Marijn Sloots',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351109,'Dick Roskamp','Robert Rodenburg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351109,'Gerard Bocxe','Kees Reijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351109,'Gerard Bocxe','Marijn Sloots',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351109,'Dick Roskamp','Kees Reijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351109,'Lex Franssen','Robert Rodenburg',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-12-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),351110,'snookerutrecht.nl','De Biljartmakers 3',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351110,'John Zom','Maurijn Maas',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351110,'Pierre Linschoten','Wil van Vliet',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351110,'Ruud Klarenbeek','Tom van Rossum',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351110,'John Zom','Wil van Vliet',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351110,'Pierre Linschoten','Tom van Rossum',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351110,'Ruud Klarenbeek','Maurijn Maas',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351110,'Ruud Klarenbeek','Wil van Vliet',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351110,'Pierre Linschoten','Maurijn Maas',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351110,'John Zom','Tom van Rossum',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-12-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),363607,'SU 3 Fouls doen we nie','DE BILJARTMAKERS 2',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363607,'Michiel Vlootman','Dick Roskamp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363607,'Peter Verstraten','Gerard Bocxe',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363607,'Debabrata Panja','Lex Franssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363607,'Michiel Vlootman','Gerard Bocxe',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363607,'Peter Verstraten','Lex Franssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363607,'Debabrata Panja','Dick Roskamp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363607,'Debabrata Panja','Gerard Bocxe',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363607,'Peter Verstraten','Dick Roskamp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363607,'Michiel Vlootman','Lex Franssen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-01-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),363609,'De Biljartmakers 3','SPDC 1',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363609,'Tom van Rossum','Martin Rakké',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363609,'Maurijn Maas','Jacques Niehof',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363609,'Wim Koudstaal','Roland Reinders',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363609,'Tom van Rossum','Jacques Niehof',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363609,'Maurijn Maas','Roland Reinders',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363609,'Wim Koudstaal','Martin Rakké',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363609,'Wim Koudstaal','Jacques Niehof',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363609,'Maurijn Maas','Martin Rakké',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363609,'Tom van Rossum','Roland Reinders',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-01-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),351111,'SPDC 1','DE BILJARTMAKERS 2',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351111,'Martin Rakké','Dick Roskamp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351111,'Wim Reinders','Gerard Bocxe',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351111,'Jacques Niehof','Lex Franssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351111,'Martin Rakké','Gerard Bocxe',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351111,'Wim Reinders','Lex Franssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351111,'Jacques Niehof','Dick Roskamp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351111,'Jacques Niehof','Gerard Bocxe',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351111,'Wim Reinders','Dick Roskamp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351111,'Martin Rakké','Lex Franssen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-01-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),351112,'SU 3 Fouls doen we nie','snookerutrecht.nl',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351112,'Debabrata Panja','Pierre Linschoten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351112,'Wouter Teensma','John Zom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351112,'Debabrata Panja','John Zom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351112,'Wouter Teensma','Evard Boon',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351112,'Wouter Teensma','Pierre Linschoten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351112,'Debabrata Panja','Evard Boon',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-01-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),351113,'De Biljartmakers 3','OZEBI 3',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351113,'Tom van Rossum','Kees Reijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351113,'Maurijn Maas','Jeroen Sloots',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351113,'Wil van Vliet','Robert Rodenburg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351113,'Tom van Rossum','Jeroen Sloots',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351113,'Maurijn Maas','Robert Rodenburg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351113,'Wil van Vliet','Kees Reijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351113,'Wil van Vliet','Jeroen Sloots',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351113,'Maurijn Maas','Kees Reijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351113,'Tom van Rossum','Robert Rodenburg',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('29-01-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),351114,'SPDC 1','snookerutrecht.nl',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351114,'Martin Rakké','Pierre Linschoten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351114,'Jacques Niehof','Ruud Klarenbeek',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351114,'Roland Reinders','John Zom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351114,'Martin Rakké','Ruud Klarenbeek',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351114,'Jacques Niehof','John Zom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351114,'Roland Reinders','Pierre Linschoten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351114,'Roland Reinders','Ruud Klarenbeek',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351114,'Jacques Niehof','Pierre Linschoten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351114,'Martin Rakké','John Zom',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('29-01-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),351115,'SU 3 Fouls doen we nie','OZEBI 3',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351115,'Michiel Vlootman','Kees Reijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351115,'Peter Verstraten','Robert Rodenburg',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351115,'Michiel Vlootman','René Kerkhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351115,'Peter Verstraten','Kees Reijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351115,'Peter Verstraten','René Kerkhoven',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351115,'Michiel Vlootman','Robert Rodenburg',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-02-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),365296,'DE BILJARTMAKERS 2','De Biljartmakers 3',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365296,'Lex Franssen','Maurijn Maas',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365296,'Dick Roskamp','Fred Ensel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365296,'Gerard Bocxe','Tom van Rossum',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365296,'Lex Franssen','Fred Ensel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365296,'Dick Roskamp','Tom van Rossum',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365296,'Gerard Bocxe','Maurijn Maas',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365296,'Gerard Bocxe','Fred Ensel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365296,'Dick Roskamp','Maurijn Maas',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365296,'Lex Franssen','Tom van Rossum',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-02-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),351118,'OZEBI 3','SPDC 1',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351118,'Kees Reijn','Wim Reinders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351118,'René Kerkhoven','Roland Reinders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351118,'Marijn Sloots','Martin Rakké',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351118,'Kees Reijn','Roland Reinders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351118,'René Kerkhoven','Martin Rakké',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351118,'Marijn Sloots','Wim Reinders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351118,'Marijn Sloots','Roland Reinders',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351118,'René Kerkhoven','Wim Reinders',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351118,'Kees Reijn','Martin Rakké',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('25-02-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),365332,'snookerutrecht.nl','DE BILJARTMAKERS 2',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365332,'Richard Beers','Dick Roskamp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365332,'Evard Boon','Gerard Bocxe',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365332,'Ruud Klarenbeek','Lex Franssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365332,'Richard Beers','Gerard Bocxe',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365332,'Evard Boon','Lex Franssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365332,'Ruud Klarenbeek','Dick Roskamp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365332,'Ruud Klarenbeek','Gerard Bocxe',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365332,'Evard Boon','Dick Roskamp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365332,'Richard Beers','Lex Franssen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('26-02-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),351120,'SPDC 1','De Biljartmakers 3',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351120,'Wim Reinders','Maurijn Maas',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351120,'Roland Reinders','Fred Ensel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351120,'Jacques Niehof','Tom van Rossum',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351120,'Wim Reinders','Fred Ensel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351120,'Roland Reinders','Tom van Rossum',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351120,'Jacques Niehof','Maurijn Maas',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351120,'Jacques Niehof','Fred Ensel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351120,'Roland Reinders','Maurijn Maas',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351120,'Wim Reinders','Tom van Rossum',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-02-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),351121,'DE BILJARTMAKERS 2','SU 3 Fouls doen we nie',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351121,'Dick Roskamp','Wouter Teensma',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351121,'Gerard Bocxe','Michiel Vlootman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351121,'Lex Franssen','Wouter Teensma',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351121,'Dick Roskamp','Michiel Vlootman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351121,'Gerard Bocxe','Wouter Teensma',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351121,'Lex Franssen','Michiel Vlootman',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('01-03-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),351122,'snookerutrecht.nl','OZEBI 3',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351122,'Jasha Kiers','Marijn Sloots',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351122,'Evard Boon','Kees Reijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351122,'Pierre Linschoten','Jeroen Sloots',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351122,'Jasha Kiers','Kees Reijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351122,'Evard Boon','Jeroen Sloots',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351122,'Pierre Linschoten','Marijn Sloots',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351122,'Pierre Linschoten','Kees Reijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351122,'Evard Boon','Marijn Sloots',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351122,'Jasha Kiers','Jeroen Sloots',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-03-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),351123,'SU 3 Fouls doen we nie','SPDC 1',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351123,'Michiel Vlootman','Roland Reinders',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351123,'Debabrata Panja','Jacques Niehof',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351123,'Peter Verstraten','Wim Reinders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351123,'Michiel Vlootman','Jacques Niehof',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351123,'Debabrata Panja','Wim Reinders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351123,'Peter Verstraten','Roland Reinders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351123,'Peter Verstraten','Jacques Niehof',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351123,'Debabrata Panja','Roland Reinders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351123,'Michiel Vlootman','Wim Reinders',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-03-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),351124,'De Biljartmakers 3','snookerutrecht.nl',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351124,'Fred Ensel','Jasha Kiers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351124,'Maurijn Maas','Evard Boon',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351124,'Wim Koudstaal','John Zom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351124,'Fred Ensel','Evard Boon',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351124,'Maurijn Maas','John Zom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351124,'Wim Koudstaal','Jasha Kiers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351124,'Wim Koudstaal','Evard Boon',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351124,'Maurijn Maas','Jasha Kiers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351124,'Fred Ensel','John Zom',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-03-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),351125,'OZEBI 3','DE BILJARTMAKERS 2',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351125,'Robert Rodenburg','Dick Roskamp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351125,'Kees Reijn','Gerard Bocxe',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351125,'Marijn Sloots','Lex Franssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351125,'Robert Rodenburg','Gerard Bocxe',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351125,'Kees Reijn','Lex Franssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351125,'Marijn Sloots','Dick Roskamp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351125,'Marijn Sloots','Gerard Bocxe',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351125,'Kees Reijn','Dick Roskamp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351125,'Robert Rodenburg','Lex Franssen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-03-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),351126,'DE BILJARTMAKERS 2','SPDC 1',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351126,'Lex Franssen','Roland Reinders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351126,'Dick Roskamp','Jacques Niehof',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351126,'Gerard Bocxe','Martin Rakké',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351126,'Lex Franssen','Jacques Niehof',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351126,'Dick Roskamp','Martin Rakké',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351126,'Gerard Bocxe','Roland Reinders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351126,'Gerard Bocxe','Jacques Niehof',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351126,'Dick Roskamp','Roland Reinders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351126,'Lex Franssen','Martin Rakké',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-03-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),351127,'OZEBI 3','De Biljartmakers 3',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351127,'Robert Rodenburg','Maurijn Maas',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351127,'Kees Reijn','Wil van Vliet',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351127,'René Kerkhoven','Tom van Rossum',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351127,'Robert Rodenburg','Wil van Vliet',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351127,'Kees Reijn','Tom van Rossum',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351127,'René Kerkhoven','Maurijn Maas',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351127,'René Kerkhoven','Wil van Vliet',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351127,'Kees Reijn','Maurijn Maas',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351127,'Robert Rodenburg','Tom van Rossum',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-03-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),365295,'De Biljartmakers 3','SU 3 Fouls doen we nie',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365295,'Maurijn Maas','Debabrata Panja',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365295,'Wim Koudstaal','Wouter Teensma',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365295,'Tom van Rossum','Debabrata Panja',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365295,'Maurijn Maas','Wouter Teensma',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365295,'Wim Koudstaal','Debabrata Panja',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365295,'Tom van Rossum','Wouter Teensma',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-03-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),365875,'snookerutrecht.nl','SU 3 Fouls doen we nie',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365875,'Evard Boon','Debabrata Panja',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365875,'Ruud Klarenbeek','Michiel Vlootman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365875,'Jasha Kiers','Debabrata Panja',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365875,'Evard Boon','Michiel Vlootman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365875,'Ruud Klarenbeek','Debabrata Panja',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365875,'Jasha Kiers','Michiel Vlootman',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-04-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),351129,'De Biljartmakers 3','DE BILJARTMAKERS 2',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351129,'Tom van Rossum','Lex Franssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351129,'Fred Ensel','Dick Roskamp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351129,'Wim Koudstaal','Gerard Bocxe',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351129,'Tom van Rossum','Dick Roskamp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351129,'Fred Ensel','Gerard Bocxe',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351129,'Wim Koudstaal','Lex Franssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351129,'Wim Koudstaal','Dick Roskamp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351129,'Fred Ensel','Lex Franssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351129,'Tom van Rossum','Gerard Bocxe',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-04-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),351130,'OZEBI 3','SU 3 Fouls doen we nie',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351130,'Kees Reijn','Debabrata Panja',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351130,'Marijn Sloots','Wouter Teensma',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351130,'Kees Reijn','Wouter Teensma',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351130,'René Kerkhoven','Debabrata Panja',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351130,'René Kerkhoven','Wouter Teensma',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351130,'Marijn Sloots','Debabrata Panja',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('05-04-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),351131,'snookerutrecht.nl','SPDC 1',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351131,'Jasha Kiers','Jacques Niehof',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351131,'Evard Boon','Roland Reinders',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351131,'Ruud Klarenbeek','Martin Rakké',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351131,'Jasha Kiers','Roland Reinders',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351131,'Evard Boon','Martin Rakké',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351131,'Ruud Klarenbeek','Jacques Niehof',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351131,'Ruud Klarenbeek','Roland Reinders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351131,'Evard Boon','Jacques Niehof',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351131,'Jasha Kiers','Martin Rakké',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-04-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),351132,'SPDC 1','OZEBI 3',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351132,'Wim Reinders','René Kerkhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351132,'Martin Rakké','Jeroen Sloots',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351132,'Jacques Niehof','Kees Reijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351132,'Wim Reinders','Jeroen Sloots',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351132,'Martin Rakké','Kees Reijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351132,'Jacques Niehof','René Kerkhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351132,'Jacques Niehof','Jeroen Sloots',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351132,'Martin Rakké','René Kerkhoven',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351132,'Wim Reinders','Kees Reijn',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-04-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),351133,'SU 3 Fouls doen we nie','De Biljartmakers 3',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351133,'Debabrata Panja','Wim Koudstaal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351133,'Wouter Teensma','Maurijn Maas',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351133,'Debabrata Panja','Maurijn Maas',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351133,'Wouter Teensma','Fred Ensel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351133,'Wouter Teensma','Wim Koudstaal',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351133,'Debabrata Panja','Fred Ensel',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-04-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),351134,'DE BILJARTMAKERS 2','snookerutrecht.nl',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351134,'Lex Franssen','John Zom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351134,'Dick Roskamp','Evard Boon',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351134,'Gerard Bocxe','Richard Beers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351134,'Lex Franssen','Evard Boon',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351134,'Dick Roskamp','Richard Beers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351134,'Gerard Bocxe','John Zom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351134,'Gerard Bocxe','Evard Boon',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351134,'Dick Roskamp','John Zom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351134,'Lex Franssen','Richard Beers',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-04-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),351135,'SU 3 Fouls doen we nie','DE BILJARTMAKERS 2',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351135,'Debabrata Panja','Gerard Bocxe',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351135,'Wouter Teensma','Lex Franssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351135,'Debabrata Panja','Lex Franssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351135,'Wouter Teensma','Dick Roskamp',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351135,'Wouter Teensma','Gerard Bocxe',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351135,'Debabrata Panja','Dick Roskamp',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-04-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),351136,'De Biljartmakers 3','SPDC 1',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351136,'Fred Ensel','Jacques Niehof',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351136,'Tom van Rossum','Martin Rakké',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351136,'Wim Koudstaal','Roland Reinders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351136,'Fred Ensel','Martin Rakké',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351136,'Tom van Rossum','Roland Reinders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351136,'Wim Koudstaal','Jacques Niehof',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351136,'Wim Koudstaal','Martin Rakké',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351136,'Tom van Rossum','Jacques Niehof',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351136,'Fred Ensel','Roland Reinders',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-04-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),351137,'OZEBI 3','snookerutrecht.nl',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('01-05-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),351139,'DE BILJARTMAKERS 2','OZEBI 3',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351139,'Lex Franssen','Kees Reijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351139,'Dick Roskamp','Marijn Sloots',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351139,'Gerard Bocxe','Robert Rodenburg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351139,'Lex Franssen','Marijn Sloots',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351139,'Dick Roskamp','Robert Rodenburg',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351139,'Gerard Bocxe','Kees Reijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351139,'Gerard Bocxe','Marijn Sloots',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351139,'Dick Roskamp','Kees Reijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351139,'Lex Franssen','Robert Rodenburg',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-05-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),366134,'SPDC 1','SU 3 Fouls doen we nie',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366134,'Wim Reinders','Debabrata Panja',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366134,'Martin Rakké','Peter Verstraten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366134,'Wim Reinders','Peter Verstraten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366134,'Jacques Niehof','Debabrata Panja',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366134,'Jacques Niehof','Peter Verstraten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366134,'Martin Rakké','Debabrata Panja',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-05-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),351142,'SU 3 Fouls doen we nie','snookerutrecht.nl',0,9);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351142,'Debabrata Panja','John Zom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351142,'Peter Verstraten','Ruud Klarenbeek',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351142,'Wouter Teensma','Jasha Kiers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351142,'Debabrata Panja','Ruud Klarenbeek',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351142,'Peter Verstraten','Jasha Kiers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351142,'Wouter Teensma','John Zom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351142,'Wouter Teensma','Ruud Klarenbeek',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351142,'Peter Verstraten','John Zom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351142,'Debabrata Panja','Jasha Kiers',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-05-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),351143,'De Biljartmakers 3','OZEBI 3',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351143,'Tom van Rossum','Jeroen Sloots',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351143,'Maurijn Maas','Kees Reijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351143,'Fred Ensel','Marijn Sloots',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351143,'Tom van Rossum','Kees Reijn',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351143,'Maurijn Maas','Marijn Sloots',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351143,'Fred Ensel','Jeroen Sloots',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351143,'Fred Ensel','Kees Reijn',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351143,'Maurijn Maas','Jeroen Sloots',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351143,'Tom van Rossum','Marijn Sloots',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-05-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),366156,'snookerutrecht.nl','De Biljartmakers 3',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-05-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 4' and ssn_id like '2012%'),366493,'SPDC 1','DE BILJARTMAKERS 2',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366493,'Martin Rakké','Dick Roskamp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366493,'Roland Reinders','Gerard Bocxe',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366493,'Jacques Niehof','Lex Franssen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366493,'Martin Rakké','Gerard Bocxe',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366493,'Roland Reinders','Lex Franssen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366493,'Jacques Niehof','Dick Roskamp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366493,'Jacques Niehof','Gerard Bocxe',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366493,'Roland Reinders','Dick Roskamp',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366493,'Martin Rakké','Lex Franssen',1,0);
