delete from cm_match_details where game_id in (select game_id from cm_matches where cpn_id = (select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'));
delete from cm_matches where cpn_id = (select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%');
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-09-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294141,'Cue Palace  4','DIE HARDS',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294141,'Berdj Shahin','Martin Montanaro',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294141,'Ara Kazo','Martin Engbers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294141,'Renato di Nunzio','John Schoor',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294141,'Berdj Shahin','Martin Engbers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294141,'Ara Kazo','John Schoor',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294141,'Renato di Nunzio','Martin Montanaro',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294141,'Renato di Nunzio','Martin Engbers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294141,'Ara Kazo','Martin Montanaro',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294141,'Berdj Shahin','John Schoor',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-09-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294143,'T.Z.S.','Peng Peng in the Pocket',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294143,'Jarno Bergman','Marco Markerink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294143,'Roger Wolthuis','Sander Vrielink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294143,'Jeroen van Valkenhoef','Pieter Alberts',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294143,'Jarno Bergman','Sander Vrielink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294143,'Roger Wolthuis','Pieter Alberts',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294143,'Jeroen van Valkenhoef','Marco Markerink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294143,'Jeroen van Valkenhoef','Sander Vrielink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294143,'Roger Wolthuis','Marco Markerink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294143,'Jarno Bergman','Pieter Alberts',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-09-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294144,'Peng Peng in the Pocket','Cue Palace 3',1,8);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-09-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294145,'DIE HARDS','T.Z.S.',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294145,'John Schoor','Frank Embsen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294145,'Martin Montanaro','Jeroen van Valkenhoef',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294145,'Colin Adams','Patrick Hekhuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294145,'John Schoor','Jeroen van Valkenhoef',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294145,'Martin Montanaro','Patrick Hekhuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294145,'Colin Adams','Frank Embsen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294145,'Colin Adams','Jeroen van Valkenhoef',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294145,'Martin Montanaro','Frank Embsen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294145,'John Schoor','Patrick Hekhuis',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('28-09-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294146,'good goan','Cue Palace  4',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294146,'Bob Meis','Berdj Shahin',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294146,'Gemo Meis','Ara Kazo',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294146,'Meindert Grootehaar','Renato di Nunzio',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294146,'Bob Meis','Ara Kazo',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294146,'Gemo Meis','Renato di Nunzio',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294146,'Meindert Grootehaar','Berdj Shahin',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294146,'Meindert Grootehaar','Ara Kazo',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294146,'Gemo Meis','Berdj Shahin',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294146,'Bob Meis','Renato di Nunzio',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-10-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294147,'Cue Palace  4','Peng Peng in the Pocket',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294147,'Renato di Nunzio','Pieter Alberts',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294147,'Berdj Shahin','Marco Markerink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294147,'Ara Kazo','Arjan ter Avest',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294147,'Renato di Nunzio','Marco Markerink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294147,'Berdj Shahin','Arjan ter Avest',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294147,'Ara Kazo','Pieter Alberts',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294147,'Ara Kazo','Marco Markerink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294147,'Berdj Shahin','Pieter Alberts',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294147,'Renato di Nunzio','Arjan ter Avest',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-10-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294148,'DIE HARDS','good goan',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294148,'John Schoor','Meindert Grootehaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294148,'Martin Montanaro','Tonny Vos',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294148,'Colin Adams','Gemo Meis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294148,'John Schoor','Tonny Vos',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294148,'Martin Montanaro','Gemo Meis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294148,'Colin Adams','Meindert Grootehaar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294148,'Colin Adams','Tonny Vos',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294148,'Martin Montanaro','Meindert Grootehaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294148,'John Schoor','Gemo Meis',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-10-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294149,'T.Z.S.','Cue Palace 3',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294149,'Patrick Hekhuis','Michel Brand',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294149,'Jarno Bergman','Gerko Reints',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294149,'Frank Hekhuis','Jordy Achten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294149,'Patrick Hekhuis','Gerko Reints',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294149,'Jarno Bergman','Jordy Achten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294149,'Frank Hekhuis','Michel Brand',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294149,'Frank Hekhuis','Gerko Reints',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294149,'Jarno Bergman','Michel Brand',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294149,'Patrick Hekhuis','Jordy Achten',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-10-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294150,'Cue Palace 3','Cue Palace  4',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294150,'Jordy Achten','Henk Regeling',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294150,'Michel Brand','Ara Kazo',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294150,'Gerko Reints','Renato di Nunzio',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294150,'Jordy Achten','Ara Kazo',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294150,'Michel Brand','Renato di Nunzio',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294150,'Gerko Reints','Henk Regeling',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294150,'Gerko Reints','Ara Kazo',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294150,'Michel Brand','Henk Regeling',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294150,'Jordy Achten','Renato di Nunzio',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-10-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294152,'good goan','T.Z.S.',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('25-10-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),306929,'Peng Peng in the Pocket','DIE HARDS',1,8);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294153,'DIE HARDS','Cue Palace 3',9,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294154,'T.Z.S.','Cue Palace  4',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294154,'Frank Embsen','Berdj Shahin',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294154,'Roger Wolthuis','Ara Kazo',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294154,'Frank Hekhuis','Henk Regeling',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294154,'Frank Embsen','Ara Kazo',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294154,'Roger Wolthuis','Henk Regeling',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294154,'Frank Hekhuis','Berdj Shahin',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294154,'Frank Hekhuis','Ara Kazo',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294154,'Roger Wolthuis','Berdj Shahin',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294154,'Frank Embsen','Henk Regeling',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294155,'good goan','Peng Peng in the Pocket',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294155,'Bob Meis','Marco Markerink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294155,'Gemo Meis','Sander Vrielink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294155,'Meindert Grootehaar','Arjan ter Avest',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294155,'Bob Meis','Sander Vrielink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294155,'Gemo Meis','Arjan ter Avest',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294155,'Meindert Grootehaar','Marco Markerink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294155,'Meindert Grootehaar','Sander Vrielink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294155,'Gemo Meis','Marco Markerink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294155,'Bob Meis','Arjan ter Avest',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294156,'Peng Peng in the Pocket','T.Z.S.',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294156,'Arjan ter Avest','Roger Wolthuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294156,'Pieter Alberts','Frank Hekhuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294156,'Marco Markerink','Patrick Hekhuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294156,'Arjan ter Avest','Frank Hekhuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294156,'Pieter Alberts','Patrick Hekhuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294156,'Marco Markerink','Roger Wolthuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294156,'Marco Markerink','Frank Hekhuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294156,'Pieter Alberts','Roger Wolthuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294156,'Arjan ter Avest','Patrick Hekhuis',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294157,'DIE HARDS','Cue Palace  4',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294157,'Martin Montanaro','Berdj Shahin',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294157,'Martin Engbers','Ara Kazo',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294157,'Colin Adams','Renato di Nunzio',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294157,'Martin Montanaro','Ara Kazo',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294157,'Martin Engbers','Renato di Nunzio',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294157,'Colin Adams','Berdj Shahin',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294157,'Colin Adams','Ara Kazo',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294157,'Martin Engbers','Berdj Shahin',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294157,'Martin Montanaro','Renato di Nunzio',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294158,'good goan','Cue Palace 3',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294158,'Tonny Vos','Michel Brand',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294158,'Bob Meis','Jordy Achten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294158,'Meindert Grootehaar','Gerko Reints',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294158,'Tonny Vos','Jordy Achten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294158,'Bob Meis','Gerko Reints',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294158,'Meindert Grootehaar','Michel Brand',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294158,'Meindert Grootehaar','Jordy Achten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294158,'Bob Meis','Michel Brand',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294158,'Tonny Vos','Gerko Reints',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294159,'Cue Palace  4','good goan',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294159,'Berdj Shahin','Tonny Vos',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294159,'Ara Kazo','Bob Meis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294159,'Berdj Shahin','Bob Meis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294159,'Ara Kazo','Gemo Meis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294159,'Ara Kazo','Tonny Vos',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294159,'Berdj Shahin','Gemo Meis',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-11-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294161,'T.Z.S.','DIE HARDS',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294161,'Roger Wolthuis','Martin Engbers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294161,'Frank Hekhuis','Colin Adams',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294161,'Jeroen van Valkenhoef','Martin Montanaro',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294161,'Roger Wolthuis','Colin Adams',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294161,'Frank Hekhuis','Martin Montanaro',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294161,'Jeroen van Valkenhoef','Martin Engbers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294161,'Jeroen van Valkenhoef','Colin Adams',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294161,'Frank Hekhuis','Martin Engbers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294161,'Roger Wolthuis','Martin Montanaro',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-12-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294162,'Cue Palace 3','T.Z.S.',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294162,'Jordy Achten','Roger Wolthuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294162,'Michel Brand','Frank Hekhuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294162,'Gerko Reints','Frank Embsen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294162,'Jordy Achten','Frank Hekhuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294162,'Michel Brand','Frank Embsen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294162,'Gerko Reints','Roger Wolthuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294162,'Gerko Reints','Frank Hekhuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294162,'Michel Brand','Roger Wolthuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294162,'Jordy Achten','Frank Embsen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-12-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294163,'Peng Peng in the Pocket','Cue Palace  4',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294163,'Arjan ter Avest','Henk Regeling',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294163,'Pieter Alberts','Berdj Shahin',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294163,'Marco Markerink','Renato di Nunzio',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294163,'Arjan ter Avest','Berdj Shahin',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294163,'Pieter Alberts','Renato di Nunzio',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294163,'Marco Markerink','Henk Regeling',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294163,'Marco Markerink','Berdj Shahin',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294163,'Pieter Alberts','Henk Regeling',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294163,'Arjan ter Avest','Renato di Nunzio',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-12-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),307815,'Cue Palace 3','Peng Peng in the Pocket',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(307815,'Jordy Achten','Marco Markerink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(307815,'Michel Brand','Sander Vrielink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(307815,'Gerko Reints','Pieter Alberts',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(307815,'Jordy Achten','Sander Vrielink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(307815,'Michel Brand','Pieter Alberts',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(307815,'Gerko Reints','Marco Markerink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(307815,'Gerko Reints','Sander Vrielink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(307815,'Michel Brand','Marco Markerink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(307815,'Jordy Achten','Pieter Alberts',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-12-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294165,'Cue Palace  4','Cue Palace 3',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294165,'Henk Regeling','Michel Brand',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294165,'Berdj Shahin','Gerko Reints',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294165,'Ara Kazo','Jordy Achten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294165,'Henk Regeling','Gerko Reints',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294165,'Berdj Shahin','Jordy Achten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294165,'Ara Kazo','Michel Brand',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294165,'Ara Kazo','Gerko Reints',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294165,'Berdj Shahin','Michel Brand',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294165,'Henk Regeling','Jordy Achten',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-12-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294166,'DIE HARDS','Peng Peng in the Pocket',9,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294166,'John Schoor','Marco Markerink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294166,'Martin Montanaro','Sander Vrielink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294166,'Colin Adams','Arjan ter Avest',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294166,'John Schoor','Sander Vrielink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294166,'Martin Montanaro','Arjan ter Avest',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294166,'Colin Adams','Marco Markerink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294166,'Colin Adams','Sander Vrielink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294166,'Martin Montanaro','Marco Markerink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294166,'John Schoor','Arjan ter Avest',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-12-2011','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294167,'T.Z.S.','good goan',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294167,'Patrick Hekhuis','Tonny Vos',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294167,'Frank Embsen','Meindert Grootehaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294167,'Jarno Bergman','Meindert Grootehaar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294167,'Frank Embsen','Tonny Vos',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294167,'Jarno Bergman','Tonny Vos',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294167,'Patrick Hekhuis','Meindert Grootehaar',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294168,'Cue Palace  4','T.Z.S.',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294168,'Renato di Nunzio','Roger Wolthuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294168,'Berdj Shahin','Frank Hekhuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294168,'Ara Kazo','Frank Embsen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294168,'Renato di Nunzio','Frank Hekhuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294168,'Berdj Shahin','Frank Embsen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294168,'Ara Kazo','Roger Wolthuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294168,'Ara Kazo','Frank Hekhuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294168,'Berdj Shahin','Roger Wolthuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294168,'Renato di Nunzio','Frank Embsen',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294169,'Cue Palace 3','DIE HARDS',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294169,'Jordy Achten','Martin Montanaro',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294169,'Michel Brand','Martin Engbers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294169,'Gerko Reints','John Schoor',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294169,'Jordy Achten','Martin Engbers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294169,'Michel Brand','John Schoor',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294169,'Gerko Reints','Martin Montanaro',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294169,'Gerko Reints','Martin Engbers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294169,'Michel Brand','Martin Montanaro',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294169,'Jordy Achten','John Schoor',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294170,'Peng Peng in the Pocket','good goan',3,6);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294171,'Cue Palace  4','DIE HARDS',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294171,'Renato di Nunzio','Martin Engbers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294171,'Henk Regeling','Colin Adams',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294171,'Ara Kazo','Martin Montanaro',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294171,'Renato di Nunzio','Colin Adams',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294171,'Henk Regeling','Martin Montanaro',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294171,'Ara Kazo','Martin Engbers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294171,'Ara Kazo','Colin Adams',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294171,'Henk Regeling','Martin Engbers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294171,'Renato di Nunzio','Martin Montanaro',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294172,'Cue Palace 3','good goan',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294172,'Jordy Achten','Meindert Grootehaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294172,'Gerko Reints','Bob Meis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294172,'Michel Brand','Tonny Vos',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294172,'Jordy Achten','Bob Meis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294172,'Gerko Reints','Tonny Vos',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294172,'Michel Brand','Meindert Grootehaar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294172,'Michel Brand','Bob Meis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294172,'Gerko Reints','Meindert Grootehaar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294172,'Jordy Achten','Tonny Vos',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),308400,'T.Z.S.','Peng Peng in the Pocket',9,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308400,'Frank Embsen','Pieter Alberts',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308400,'Roger Wolthuis','Marco Markerink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308400,'Frank Hekhuis','Arjan ter Avest',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308400,'Frank Embsen','Marco Markerink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308400,'Roger Wolthuis','Arjan ter Avest',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308400,'Frank Hekhuis','Pieter Alberts',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308400,'Frank Hekhuis','Marco Markerink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308400,'Roger Wolthuis','Pieter Alberts',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308400,'Frank Embsen','Arjan ter Avest',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('31-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294174,'Peng Peng in the Pocket','Cue Palace 3',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('31-01-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294175,'DIE HARDS','T.Z.S.',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294175,'Colin Adams','Roger Wolthuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294175,'John Schoor','Patrick Hekhuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294175,'Martin Engbers','Frank Hekhuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294175,'Colin Adams','Patrick Hekhuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294175,'John Schoor','Frank Hekhuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294175,'Martin Engbers','Roger Wolthuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294175,'Martin Engbers','Patrick Hekhuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294175,'John Schoor','Roger Wolthuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294175,'Colin Adams','Frank Hekhuis',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('01-02-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294176,'good goan','Cue Palace  4',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294176,'Meindert Grootehaar','Ara Kazo',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294176,'Tonny Vos','Berdj Shahin',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294176,'Gemo Meis','Ara Kazo',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294176,'Meindert Grootehaar','Berdj Shahin',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294176,'Tonny Vos','Ara Kazo',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294176,'Gemo Meis','Berdj Shahin',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-02-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294178,'DIE HARDS','good goan',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-02-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294179,'T.Z.S.','Cue Palace 3',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294179,'Frank Embsen','Gerko Reints',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294179,'Roger Wolthuis','Michel Brand',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294179,'Frank Hekhuis','Jordy Achten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294179,'Frank Embsen','Michel Brand',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294179,'Roger Wolthuis','Jordy Achten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294179,'Frank Hekhuis','Gerko Reints',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294179,'Frank Hekhuis','Michel Brand',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294179,'Roger Wolthuis','Gerko Reints',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294179,'Frank Embsen','Jordy Achten',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-02-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),308752,'good goan','DIE HARDS',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308752,'Tonny Vos','John Schoor',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308752,'Bob Meis','Martin Engbers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308752,'Meindert Grootehaar','Martin Montanaro',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308752,'Tonny Vos','Martin Engbers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308752,'Bob Meis','Martin Montanaro',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308752,'Meindert Grootehaar','John Schoor',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308752,'Meindert Grootehaar','Martin Engbers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308752,'Bob Meis','John Schoor',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308752,'Tonny Vos','Martin Montanaro',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-02-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),308814,'Cue Palace  4','Peng Peng in the Pocket',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308814,'Henk Regeling','Marco Markerink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308814,'Berdj Shahin','Sander Vrielink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308814,'Ara Kazo','Pieter Alberts',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308814,'Henk Regeling','Sander Vrielink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308814,'Berdj Shahin','Pieter Alberts',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308814,'Ara Kazo','Marco Markerink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308814,'Ara Kazo','Sander Vrielink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308814,'Berdj Shahin','Marco Markerink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308814,'Henk Regeling','Pieter Alberts',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('28-02-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294180,'Cue Palace 3','Cue Palace  4',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294180,'Jordy Achten','Berdj Shahin',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294180,'Michel Brand','Renato di Nunzio',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294180,'Gerko Reints','Ara Kazo',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294180,'Jordy Achten','Renato di Nunzio',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294180,'Michel Brand','Ara Kazo',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294180,'Gerko Reints','Berdj Shahin',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294180,'Gerko Reints','Renato di Nunzio',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294180,'Michel Brand','Berdj Shahin',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294180,'Jordy Achten','Ara Kazo',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('28-02-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294181,'Peng Peng in the Pocket','DIE HARDS',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('29-02-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294182,'good goan','T.Z.S.',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294182,'Bob Meis','Frank Embsen',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294182,'Meindert Grootehaar','Jeroen van Valkenhoef',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294182,'Tonny Vos','Patrick Hekhuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294182,'Bob Meis','Jeroen van Valkenhoef',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294182,'Meindert Grootehaar','Patrick Hekhuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294182,'Tonny Vos','Frank Embsen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294182,'Tonny Vos','Jeroen van Valkenhoef',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294182,'Meindert Grootehaar','Frank Embsen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294182,'Bob Meis','Patrick Hekhuis',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-03-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294183,'DIE HARDS','Cue Palace 3',7,2);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-03-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294184,'T.Z.S.','Cue Palace  4',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294184,'Jeroen van Valkenhoef','Berdj Shahin',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294184,'Roger Wolthuis','Ara Kazo',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294184,'Frank Hekhuis','Renato di Nunzio',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294184,'Jeroen van Valkenhoef','Ara Kazo',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294184,'Roger Wolthuis','Renato di Nunzio',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294184,'Frank Hekhuis','Berdj Shahin',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294184,'Frank Hekhuis','Ara Kazo',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294184,'Roger Wolthuis','Berdj Shahin',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294184,'Jeroen van Valkenhoef','Renato di Nunzio',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-04-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),308933,'Cue Palace 3','good goan',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308933,'Jordy Achten','Meindert Grootehaar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308933,'Michel Brand','Tonny Vos',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308933,'Gerko Reints','Bob Meis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308933,'Jordy Achten','Tonny Vos',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308933,'Michel Brand','Bob Meis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308933,'Gerko Reints','Meindert Grootehaar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308933,'Gerko Reints','Tonny Vos',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308933,'Michel Brand','Meindert Grootehaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(308933,'Jordy Achten','Bob Meis',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-04-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294186,'Peng Peng in the Pocket','T.Z.S.',0,9);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294186,'Pieter Alberts','Roger Wolthuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294186,'Marco Markerink','Frank Hekhuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294186,'Sander Vrielink','Jarno Bergman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294186,'Pieter Alberts','Frank Hekhuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294186,'Marco Markerink','Jarno Bergman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294186,'Sander Vrielink','Roger Wolthuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294186,'Sander Vrielink','Frank Hekhuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294186,'Marco Markerink','Roger Wolthuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294186,'Pieter Alberts','Jarno Bergman',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-04-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294187,'DIE HARDS','Cue Palace  4',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-04-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294188,'good goan','Cue Palace 3',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294188,'Gemo Meis','Michel Brand',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294188,'Bob Meis','Jordy Achten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294188,'Tonny Vos','Gerko Reints',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294188,'Gemo Meis','Jordy Achten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294188,'Bob Meis','Gerko Reints',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294188,'Tonny Vos','Michel Brand',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294188,'Tonny Vos','Jordy Achten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294188,'Bob Meis','Michel Brand',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294188,'Gemo Meis','Gerko Reints',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-04-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294190,'Cue Palace 3','Peng Peng in the Pocket',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294190,'Jordy Achten','Marco Markerink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294190,'Michel Brand','Arjan ter Avest',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294190,'Gerko Reints','Pieter Alberts',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294190,'Jordy Achten','Arjan ter Avest',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294190,'Michel Brand','Pieter Alberts',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294190,'Gerko Reints','Marco Markerink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294190,'Gerko Reints','Arjan ter Avest',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294190,'Michel Brand','Marco Markerink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294190,'Jordy Achten','Pieter Alberts',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-04-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294191,'T.Z.S.','DIE HARDS',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294191,'Patrick Hekhuis','Martin Engbers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294191,'Roger Wolthuis','Colin Adams',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294191,'Frank Hekhuis','John Schoor',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294191,'Patrick Hekhuis','Colin Adams',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294191,'Roger Wolthuis','John Schoor',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294191,'Frank Hekhuis','Martin Engbers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294191,'Frank Hekhuis','Colin Adams',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294191,'Roger Wolthuis','Martin Engbers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294191,'Patrick Hekhuis','John Schoor',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-04-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294192,'Cue Palace 3','T.Z.S.',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294192,'Jordy Achten','Roger Wolthuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294192,'Gerko Reints','Frank Hekhuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294192,'Michel Brand','Frank Embsen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294192,'Jordy Achten','Frank Hekhuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294192,'Gerko Reints','Frank Embsen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294192,'Michel Brand','Roger Wolthuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294192,'Michel Brand','Frank Hekhuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294192,'Gerko Reints','Roger Wolthuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294192,'Jordy Achten','Frank Embsen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-04-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294193,'Peng Peng in the Pocket','Cue Palace  4',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294193,'Arjan ter Avest','Berdj Shahin',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294193,'Pieter Alberts','Ara Kazo',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294193,'Marco Markerink','Henk Regeling',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294193,'Arjan ter Avest','Ara Kazo',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294193,'Pieter Alberts','Henk Regeling',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294193,'Marco Markerink','Berdj Shahin',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294193,'Marco Markerink','Ara Kazo',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294193,'Pieter Alberts','Berdj Shahin',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294193,'Arjan ter Avest','Henk Regeling',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-04-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294194,'good goan','DIE HARDS',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294194,'Bob Meis','Martin Montanaro',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294194,'Meindert Grootehaar','Martin Engbers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294194,'Tonny Vos','John Schoor',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294194,'Bob Meis','Martin Engbers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294194,'Meindert Grootehaar','John Schoor',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294194,'Tonny Vos','Martin Montanaro',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294194,'Tonny Vos','Martin Engbers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294194,'Meindert Grootehaar','Martin Montanaro',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294194,'Bob Meis','John Schoor',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),309788,'Cue Palace  4','good goan',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309788,'Renato di Nunzio','Gemo Meis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309788,'Berdj Shahin','Meindert Grootehaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309788,'Ara Kazo','Tonny Vos',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309788,'Renato di Nunzio','Meindert Grootehaar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309788,'Berdj Shahin','Tonny Vos',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309788,'Ara Kazo','Gemo Meis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309788,'Ara Kazo','Meindert Grootehaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309788,'Berdj Shahin','Gemo Meis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(309788,'Renato di Nunzio','Tonny Vos',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294195,'Cue Palace  4','Cue Palace 3',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294195,'Renato di Nunzio','Michel Brand',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294195,'Henk Regeling','Gerko Reints',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294195,'Berdj Shahin','Jordy Achten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294195,'Renato di Nunzio','Gerko Reints',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294195,'Henk Regeling','Jordy Achten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294195,'Berdj Shahin','Michel Brand',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294195,'Berdj Shahin','Gerko Reints',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294195,'Henk Regeling','Michel Brand',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294195,'Renato di Nunzio','Jordy Achten',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294196,'DIE HARDS','Peng Peng in the Pocket',9,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294196,'Martin Montanaro','Pieter Alberts',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294196,'Martin Engbers','Marco Markerink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294196,'Colin Adams','Arjan ter Avest',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294196,'Martin Montanaro','Marco Markerink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294196,'Martin Engbers','Arjan ter Avest',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294196,'Colin Adams','Pieter Alberts',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294196,'Colin Adams','Marco Markerink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294196,'Martin Engbers','Pieter Alberts',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294196,'Martin Montanaro','Arjan ter Avest',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('15-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294197,'T.Z.S.','good goan',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294197,'Frank Embsen','Meindert Grootehaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294197,'Roger Wolthuis','Tonny Vos',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294197,'Frank Hekhuis','Bob Meis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294197,'Frank Embsen','Tonny Vos',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294197,'Roger Wolthuis','Bob Meis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294197,'Frank Hekhuis','Meindert Grootehaar',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294197,'Frank Hekhuis','Tonny Vos',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294197,'Roger Wolthuis','Meindert Grootehaar',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294197,'Frank Embsen','Bob Meis',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294198,'Cue Palace  4','T.Z.S.',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294198,'Berdj Shahin','Roger Wolthuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294198,'Henk Regeling','Frank Hekhuis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294198,'Ara Kazo','Frank Embsen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294198,'Berdj Shahin','Frank Hekhuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294198,'Henk Regeling','Frank Embsen',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294198,'Ara Kazo','Roger Wolthuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294198,'Ara Kazo','Frank Hekhuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294198,'Henk Regeling','Roger Wolthuis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294198,'Berdj Shahin','Frank Embsen',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-05-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 6' and ssn_id like '2011%'),294199,'Cue Palace 3','DIE HARDS',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294199,'Jordy Achten','John Schoor',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294199,'Michel Brand','Colin Adams',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294199,'Gerko Reints','Martin Montanaro',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294199,'Jordy Achten','Colin Adams',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294199,'Michel Brand','Martin Montanaro',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294199,'Gerko Reints','John Schoor',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294199,'Gerko Reints','Colin Adams',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294199,'Michel Brand','John Schoor',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(294199,'Jordy Achten','Martin Montanaro',1,0);
