delete from cm_match_details where game_id in (select game_id from cm_matches where cpn_id = (select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2014%'));
delete from cm_matches where cpn_id = (select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2014%');
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2014%'),449288,'SNOOKERIJ 3','Hogewoerd 4',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449288,'John van Ruiten','Thomas Janmaat',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449288,'Pim Monteba','Ilja Steenhorst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449288,'Peter Stoute','Emiel van der Hart',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449288,'John van Ruiten','Ilja Steenhorst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449288,'Pim Monteba','Emiel van der Hart',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449288,'Peter Stoute','Thomas Janmaat',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449288,'Peter Stoute','Ilja Steenhorst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449288,'Pim Monteba','Thomas Janmaat',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449288,'John van Ruiten','Emiel van der Hart',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('04-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2014%'),449289,'JUMBO 13','SNOOKERIJ 10',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449289,'Anton Lindhout','Nico Seisveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449289,'Jeroen Keijzer','Harry Bartels',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449289,'Harry Vogelzang','Margot Olree',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449289,'Anton Lindhout','Harry Bartels',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449289,'Jeroen Keijzer','Margot Olree',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449289,'Harry Vogelzang','Nico Seisveld',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449289,'Harry Vogelzang','Harry Bartels',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449289,'Jeroen Keijzer','Nico Seisveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449289,'Anton Lindhout','Margot Olree',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2014%'),449290,'Hogewoerd 4','JUMBO 13',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449290,'Thomas Janmaat','Lea Lindhout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449290,'Ilja Steenhorst','Menno Beugelsdijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449290,'Piotr Nerka','Anton Lindhout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449290,'Thomas Janmaat','Menno Beugelsdijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449290,'Ilja Steenhorst','Anton Lindhout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449290,'Piotr Nerka','Lea Lindhout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449290,'Piotr Nerka','Menno Beugelsdijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449290,'Ilja Steenhorst','Lea Lindhout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449290,'Thomas Janmaat','Anton Lindhout',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2014%'),449292,'JUMBO 13','Spaernehuis 1',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449292,'Anton Lindhout','David Prins',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449292,'Jeroen Keijzer','Barry Lambers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449292,'Harry Vogelzang','Jonas de Vries',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449292,'Anton Lindhout','Barry Lambers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449292,'Jeroen Keijzer','Jonas de Vries',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449292,'Harry Vogelzang','David Prins',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449292,'Harry Vogelzang','Barry Lambers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449292,'Jeroen Keijzer','David Prins',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449292,'Anton Lindhout','Jonas de Vries',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2014%'),449293,'SNOOKERIJ 10','Hogewoerd 4',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('31-03-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2014%'),449294,'SNOOKERIJ 3','JUMBO 13',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449294,'John van Ruiten','Lea Lindhout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449294,'Pim Monteba','Menno Beugelsdijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449294,'Arjen Joosten','Anton Lindhout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449294,'John van Ruiten','Menno Beugelsdijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449294,'Pim Monteba','Anton Lindhout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449294,'Arjen Joosten','Lea Lindhout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449294,'Arjen Joosten','Menno Beugelsdijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449294,'Pim Monteba','Lea Lindhout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449294,'John van Ruiten','Anton Lindhout',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2014%'),449295,'Spaernehuis 1','SNOOKERIJ 10',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449295,'Jonas de Vries','Steve Course',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449295,'Anton Kerstholt','Peter Hoekstra',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449295,'Barry Lambers','Nico Seisveld',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449295,'Jonas de Vries','Peter Hoekstra',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449295,'Anton Kerstholt','Nico Seisveld',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449295,'Barry Lambers','Steve Course',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449295,'Barry Lambers','Peter Hoekstra',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449295,'Anton Kerstholt','Steve Course',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449295,'Jonas de Vries','Nico Seisveld',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2014%'),449296,'Hogewoerd 4','Spaernehuis 1',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449296,'Piotr Nerka','Anton Kerstholt',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449296,'Ilja Steenhorst','Barry Lambers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449296,'Emiel van der Hart','David Prins',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449296,'Piotr Nerka','Barry Lambers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449296,'Ilja Steenhorst','David Prins',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449296,'Emiel van der Hart','Anton Kerstholt',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449296,'Emiel van der Hart','Barry Lambers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449296,'Ilja Steenhorst','Anton Kerstholt',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449296,'Piotr Nerka','David Prins',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2014%'),449297,'SNOOKERIJ 10','SNOOKERIJ 3',6,3);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2014%'),449298,'Hogewoerd 4','SNOOKERIJ 3',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449298,'Emiel van der Hart','Pim Monteba',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449298,'Thomas Janmaat','Peter Stoute',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449298,'Laurens Steernberg','John van Ruiten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449298,'Emiel van der Hart','Peter Stoute',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449298,'Thomas Janmaat','John van Ruiten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449298,'Laurens Steernberg','Pim Monteba',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449298,'Laurens Steernberg','Peter Stoute',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449298,'Thomas Janmaat','Pim Monteba',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449298,'Emiel van der Hart','John van Ruiten',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2014%'),449299,'SNOOKERIJ 10','JUMBO 13',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449299,'Kitt van der Jagt','Jeroen Keijzer',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449299,'Nico Seisveld','Menno Beugelsdijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449299,'Margot Olree','Harry Vogelzang',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449299,'Kitt van der Jagt','Menno Beugelsdijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449299,'Nico Seisveld','Harry Vogelzang',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449299,'Margot Olree','Jeroen Keijzer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449299,'Margot Olree','Menno Beugelsdijk',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449299,'Nico Seisveld','Jeroen Keijzer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449299,'Kitt van der Jagt','Harry Vogelzang',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-04-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2014%'),449536,'Spaernehuis 1','SNOOKERIJ 3',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449536,'Jonas de Vries','Pim Monteba',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449536,'David Prins','Arjen Joosten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449536,'Barry Lambers','John van Ruiten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449536,'Jonas de Vries','Arjen Joosten',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449536,'David Prins','John van Ruiten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449536,'Barry Lambers','Pim Monteba',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449536,'Barry Lambers','Arjen Joosten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449536,'David Prins','Pim Monteba',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449536,'Jonas de Vries','John van Ruiten',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2014%'),449301,'JUMBO 13','Hogewoerd 4',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449301,'Menno Beugelsdijk','Thomas Janmaat',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449301,'Lea Lindhout','Ilja Steenhorst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449301,'Jeroen Keijzer','Emiel van der Hart',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449301,'Menno Beugelsdijk','Ilja Steenhorst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449301,'Lea Lindhout','Emiel van der Hart',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449301,'Jeroen Keijzer','Thomas Janmaat',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449301,'Jeroen Keijzer','Ilja Steenhorst',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449301,'Lea Lindhout','Thomas Janmaat',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449301,'Menno Beugelsdijk','Emiel van der Hart',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2014%'),449302,'Hogewoerd 4','SNOOKERIJ 10',0,9);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449302,'Ilja Steenhorst','Margot Olree',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449302,'Thomas Janmaat','Nico Seisveld',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449302,'Piotr Nerka','Harry Bartels',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449302,'Ilja Steenhorst','Nico Seisveld',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449302,'Thomas Janmaat','Harry Bartels',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449302,'Piotr Nerka','Margot Olree',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449302,'Piotr Nerka','Nico Seisveld',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449302,'Thomas Janmaat','Margot Olree',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449302,'Ilja Steenhorst','Harry Bartels',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2014%'),449303,'Spaernehuis 1','JUMBO 13',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449303,'David Prins','Menno Beugelsdijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449303,'Anton Kerstholt','Jeroen Keijzer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449303,'Barry Lambers','Lea Lindhout',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449303,'David Prins','Jeroen Keijzer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449303,'Anton Kerstholt','Lea Lindhout',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449303,'Barry Lambers','Menno Beugelsdijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449303,'Barry Lambers','Jeroen Keijzer',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449303,'Anton Kerstholt','Menno Beugelsdijk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449303,'David Prins','Lea Lindhout',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2014%'),449304,'JUMBO 13','SNOOKERIJ 3',9,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449304,'Menno Beugelsdijk','Arjen Joosten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449304,'Jeroen Keijzer','Peter Stoute',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449304,'Harry Vogelzang','John van Ruiten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449304,'Menno Beugelsdijk','Peter Stoute',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449304,'Jeroen Keijzer','John van Ruiten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449304,'Harry Vogelzang','Arjen Joosten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449304,'Harry Vogelzang','Peter Stoute',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449304,'Jeroen Keijzer','Arjen Joosten',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449304,'Menno Beugelsdijk','John van Ruiten',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2014%'),449305,'SNOOKERIJ 10','Spaernehuis 1',4,5);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('26-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2014%'),449306,'SNOOKERIJ 3','SNOOKERIJ 10',2,7);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('28-05-2015','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 2' and ssn_id like '2014%'),449307,'Spaernehuis 1','Hogewoerd 4',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449307,'David Prins','Ilja Steenhorst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449307,'Anton Kerstholt','Emiel van der Hart',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449307,'Barry Lambers','Piotr Nerka',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449307,'David Prins','Emiel van der Hart',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449307,'Anton Kerstholt','Piotr Nerka',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449307,'Barry Lambers','Ilja Steenhorst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449307,'Barry Lambers','Emiel van der Hart',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449307,'Anton Kerstholt','Ilja Steenhorst',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(449307,'David Prins','Piotr Nerka',1,0);
