delete from cm_match_details where game_id in (select game_id from cm_matches where cpn_id = (select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2012%'));
delete from cm_matches where cpn_id = (select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2012%');
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-09-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2012%'),358574,'De Dieze 4','Ames 2 De Zwervers',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(358574,'Sander Mosselman','Ko de Ruijter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(358574,'Dion Jaspers','Math van der Linden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(358574,'Ko van Zeeland','Tijs van Kessel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(358574,'Sander Mosselman','Math van der Linden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(358574,'Dion Jaspers','Tijs van Kessel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(358574,'Ko van Zeeland','Ko de Ruijter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(358574,'Ko van Zeeland','Math van der Linden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(358574,'Dion Jaspers','Ko de Ruijter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(358574,'Sander Mosselman','Tijs van Kessel',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-09-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2012%'),351026,'VEGHEL 2','Rond de 100...',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351026,'Sebastiaan Henstra','Henri van de Coevering',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351026,'Theo van den Anker','Laurens Boleij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351026,'Pieter Anne van Melis','Mark Voermans',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351026,'Sebastiaan Henstra','Laurens Boleij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351026,'Theo van den Anker','Mark Voermans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351026,'Pieter Anne van Melis','Henri van de Coevering',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351026,'Pieter Anne van Melis','Laurens Boleij',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351026,'Theo van den Anker','Henri van de Coevering',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351026,'Sebastiaan Henstra','Mark Voermans',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-09-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2012%'),358970,'Rond de 100...','De Dieze 4',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(358970,'Mark Voermans','Dion Jaspers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(358970,'Henri van de Coevering','Ko van Zeeland',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(358970,'Laurens Boleij','Sander Mosselman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(358970,'Mark Voermans','Ko van Zeeland',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(358970,'Henri van de Coevering','Sander Mosselman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(358970,'Laurens Boleij','Dion Jaspers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(358970,'Laurens Boleij','Ko van Zeeland',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(358970,'Henri van de Coevering','Dion Jaspers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(358970,'Mark Voermans','Sander Mosselman',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('25-09-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2012%'),351027,'Ames 2 De Zwervers','AVVL',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351027,'Ko de Ruijter','Herman van Deutekom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351027,'Wim Manders','Sicco Vollema',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351027,'Anthony Bisschops','Raymond Ruesink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351027,'Ko de Ruijter','Sicco Vollema',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351027,'Wim Manders','Raymond Ruesink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351027,'Anthony Bisschops','Herman van Deutekom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351027,'Anthony Bisschops','Sicco Vollema',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351027,'Wim Manders','Herman van Deutekom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351027,'Ko de Ruijter','Raymond Ruesink',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-10-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2012%'),351030,'Ames 2 De Zwervers','Rond de 100...',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351030,'Frans van Poppel','Henri van de Coevering',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351030,'Math van der Linden','Laurens Boleij',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351030,'Hans Moerkerk','Mark Voermans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351030,'Frans van Poppel','Laurens Boleij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351030,'Math van der Linden','Mark Voermans',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351030,'Hans Moerkerk','Henri van de Coevering',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351030,'Hans Moerkerk','Laurens Boleij',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351030,'Math van der Linden','Henri van de Coevering',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351030,'Frans van Poppel','Mark Voermans',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('09-10-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2012%'),361620,'AVVL','VEGHEL 2',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(361620,'Raymond Ruesink','Gertjan Huiskes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(361620,'Herman van Deutekom','Theo van den Anker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(361620,'Sicco Vollema','Sebastiaan Henstra',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(361620,'Raymond Ruesink','Theo van den Anker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(361620,'Herman van Deutekom','Sebastiaan Henstra',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(361620,'Sicco Vollema','Gertjan Huiskes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(361620,'Sicco Vollema','Theo van den Anker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(361620,'Herman van Deutekom','Gertjan Huiskes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(361620,'Raymond Ruesink','Sebastiaan Henstra',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('11-10-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2012%'),351035,'VEGHEL 2','De Dieze 4',5,4);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-10-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2012%'),361860,'Rond de 100...','AVVL',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(361860,'Mark Voermans','Herman van Deutekom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(361860,'Henri van de Coevering','Sicco Vollema',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(361860,'Laurens Boleij','Raymond Ruesink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(361860,'Mark Voermans','Sicco Vollema',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(361860,'Henri van de Coevering','Raymond Ruesink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(361860,'Laurens Boleij','Herman van Deutekom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(361860,'Laurens Boleij','Sicco Vollema',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(361860,'Henri van de Coevering','Herman van Deutekom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(361860,'Mark Voermans','Raymond Ruesink',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('30-10-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2012%'),351036,'Ames 2 De Zwervers','VEGHEL 2',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351036,'Wim Manders','Gertjan Huiskes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351036,'Anthony Bisschops','Theo van den Anker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351036,'Frans van Poppel','Sebastiaan Henstra',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351036,'Wim Manders','Theo van den Anker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351036,'Anthony Bisschops','Sebastiaan Henstra',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351036,'Frans van Poppel','Gertjan Huiskes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351036,'Frans van Poppel','Theo van den Anker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351036,'Anthony Bisschops','Gertjan Huiskes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351036,'Wim Manders','Sebastiaan Henstra',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-11-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2012%'),351039,'Ames 2 De Zwervers','De Dieze 4',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351039,'Math van der Linden','Ko van Zeeland',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351039,'Hans Moerkerk','Dion Jaspers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351039,'Frans van Poppel','Sander Mosselman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351039,'Math van der Linden','Dion Jaspers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351039,'Hans Moerkerk','Sander Mosselman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351039,'Frans van Poppel','Ko van Zeeland',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351039,'Frans van Poppel','Dion Jaspers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351039,'Hans Moerkerk','Ko van Zeeland',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351039,'Math van der Linden','Sander Mosselman',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('14-11-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2012%'),351043,'De Dieze 4','Rond de 100...',0,9);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351043,'Sander Mosselman','Henri van de Coevering',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351043,'Dion Jaspers','Laurens Boleij',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351043,'Ko van Zeeland','Mark Voermans',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351043,'Sander Mosselman','Laurens Boleij',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351043,'Dion Jaspers','Mark Voermans',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351043,'Ko van Zeeland','Henri van de Coevering',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351043,'Ko van Zeeland','Laurens Boleij',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351043,'Dion Jaspers','Henri van de Coevering',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351043,'Sander Mosselman','Mark Voermans',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('27-11-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2012%'),362929,'AVVL','Ames 2 De Zwervers',9,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(362929,'Raymond Ruesink','Wim Manders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(362929,'Sicco Vollema','Ko de Ruijter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(362929,'Herman van Deutekom','Frans van Poppel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(362929,'Raymond Ruesink','Ko de Ruijter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(362929,'Sicco Vollema','Frans van Poppel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(362929,'Herman van Deutekom','Wim Manders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(362929,'Herman van Deutekom','Ko de Ruijter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(362929,'Sicco Vollema','Wim Manders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(362929,'Raymond Ruesink','Frans van Poppel',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-12-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2012%'),351050,'De Dieze 4','VEGHEL 2',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351050,'Sander Mosselman','Theo van den Anker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351050,'Dion Jaspers','Jacques Willem van Melis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351050,'Ko van Zeeland','Gertjan Huiskes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351050,'Sander Mosselman','Jacques Willem van Melis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351050,'Dion Jaspers','Gertjan Huiskes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351050,'Ko van Zeeland','Theo van den Anker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351050,'Ko van Zeeland','Jacques Willem van Melis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351050,'Dion Jaspers','Theo van den Anker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351050,'Sander Mosselman','Gertjan Huiskes',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('19-12-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2012%'),363008,'Rond de 100...','Ames 2 De Zwervers',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363008,'Mark Voermans','Frans van Poppel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363008,'Henri van de Coevering','Tijs van Kessel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363008,'Laurens Boleij','Math van der Linden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363008,'Mark Voermans','Tijs van Kessel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363008,'Henri van de Coevering','Math van der Linden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363008,'Laurens Boleij','Frans van Poppel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363008,'Laurens Boleij','Tijs van Kessel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363008,'Henri van de Coevering','Frans van Poppel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363008,'Mark Voermans','Math van der Linden',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('20-12-2012','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2012%'),363945,'VEGHEL 2','AVVL',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363945,'René van Bavel','Sicco Vollema',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363945,'Sebastiaan Henstra','Raymond Ruesink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363945,'Pieter Anne van Melis','Herman van Deutekom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363945,'René van Bavel','Raymond Ruesink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363945,'Sebastiaan Henstra','Herman van Deutekom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363945,'Pieter Anne van Melis','Sicco Vollema',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363945,'Pieter Anne van Melis','Raymond Ruesink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363945,'Sebastiaan Henstra','Sicco Vollema',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363945,'René van Bavel','Herman van Deutekom',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-01-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2012%'),364088,'AVVL','Rond de 100...',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(364088,'Herman van Deutekom','Henri van de Coevering',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(364088,'Sicco Vollema','Laurens Boleij',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(364088,'Raymond Ruesink','Mark Voermans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(364088,'Herman van Deutekom','Laurens Boleij',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(364088,'Sicco Vollema','Mark Voermans',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(364088,'Raymond Ruesink','Henri van de Coevering',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(364088,'Raymond Ruesink','Laurens Boleij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(364088,'Sicco Vollema','Henri van de Coevering',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(364088,'Herman van Deutekom','Mark Voermans',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-01-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2012%'),363946,'AVVL','De Dieze 4',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363946,'Raymond Ruesink','Dion Jaspers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363946,'Herman van Deutekom','Ko van Zeeland',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363946,'Sicco Vollema','Sander Mosselman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363946,'Raymond Ruesink','Ko van Zeeland',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363946,'Herman van Deutekom','Sander Mosselman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363946,'Sicco Vollema','Dion Jaspers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363946,'Sicco Vollema','Ko van Zeeland',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363946,'Herman van Deutekom','Dion Jaspers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363946,'Raymond Ruesink','Sander Mosselman',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-01-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2012%'),363754,'Rond de 100...','VEGHEL 2',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363754,'Mark Voermans','Gertjan Huiskes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363754,'Henri van de Coevering','Jacques Willem van Melis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363754,'Laurens Boleij','Sebastiaan Henstra',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363754,'Mark Voermans','Jacques Willem van Melis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363754,'Henri van de Coevering','Sebastiaan Henstra',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363754,'Laurens Boleij','Gertjan Huiskes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363754,'Laurens Boleij','Jacques Willem van Melis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363754,'Henri van de Coevering','Gertjan Huiskes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(363754,'Mark Voermans','Sebastiaan Henstra',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('23-01-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2012%'),351051,'De Dieze 4','AVVL',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351051,'Sander Mosselman','Herman van Deutekom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351051,'Dion Jaspers','Sicco Vollema',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351051,'Ko van Zeeland','Raymond Ruesink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351051,'Sander Mosselman','Sicco Vollema',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351051,'Dion Jaspers','Raymond Ruesink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351051,'Ko van Zeeland','Herman van Deutekom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351051,'Ko van Zeeland','Sicco Vollema',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351051,'Dion Jaspers','Herman van Deutekom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351051,'Sander Mosselman','Raymond Ruesink',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('24-01-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2012%'),351053,'VEGHEL 2','Ames 2 De Zwervers',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351053,'Theo van den Anker','Wim Manders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351053,'Jacques Willem van Melis','Ko de Ruijter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351053,'Pieter Anne van Melis','Tijs van Kessel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351053,'Theo van den Anker','Ko de Ruijter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351053,'Jacques Willem van Melis','Tijs van Kessel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351053,'Pieter Anne van Melis','Wim Manders',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351053,'Pieter Anne van Melis','Ko de Ruijter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351053,'Jacques Willem van Melis','Wim Manders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351053,'Theo van den Anker','Tijs van Kessel',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('30-01-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2012%'),351055,'De Dieze 4','Ames 2 De Zwervers',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351055,'Sander Mosselman','Math van der Linden',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351055,'Dion Jaspers','Frans van Poppel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351055,'Ko van Zeeland','Ko de Ruijter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351055,'Sander Mosselman','Frans van Poppel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351055,'Dion Jaspers','Ko de Ruijter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351055,'Ko van Zeeland','Math van der Linden',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351055,'Ko van Zeeland','Frans van Poppel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351055,'Dion Jaspers','Math van der Linden',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351055,'Sander Mosselman','Ko de Ruijter',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('31-01-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2012%'),351056,'VEGHEL 2','Rond de 100...',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351056,'Gertjan Huiskes','Henri van de Coevering',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351056,'Jacques Willem van Melis','Laurens Boleij',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351056,'Sebastiaan Henstra','Mark Voermans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351056,'Gertjan Huiskes','Laurens Boleij',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351056,'Jacques Willem van Melis','Mark Voermans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351056,'Sebastiaan Henstra','Henri van de Coevering',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351056,'Sebastiaan Henstra','Laurens Boleij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351056,'Jacques Willem van Melis','Henri van de Coevering',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351056,'Gertjan Huiskes','Mark Voermans',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-02-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2012%'),351057,'Ames 2 De Zwervers','AVVL',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351057,'Tijs van Kessel','Herman van Deutekom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351057,'Wim Manders','Sicco Vollema',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351057,'Hans Moerkerk','Raymond Ruesink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351057,'Tijs van Kessel','Sicco Vollema',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351057,'Wim Manders','Raymond Ruesink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351057,'Hans Moerkerk','Herman van Deutekom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351057,'Hans Moerkerk','Sicco Vollema',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351057,'Wim Manders','Herman van Deutekom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351057,'Tijs van Kessel','Raymond Ruesink',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('13-02-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2012%'),351059,'Rond de 100...','De Dieze 4',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351059,'Mark Voermans','Dion Jaspers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351059,'Henri van de Coevering','Ko van Zeeland',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351059,'Laurens Boleij','Sander Mosselman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351059,'Mark Voermans','Ko van Zeeland',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351059,'Henri van de Coevering','Sander Mosselman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351059,'Laurens Boleij','Dion Jaspers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351059,'Laurens Boleij','Ko van Zeeland',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351059,'Henri van de Coevering','Dion Jaspers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351059,'Mark Voermans','Sander Mosselman',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('21-02-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2012%'),365288,'VEGHEL 2','De Dieze 4',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365288,'Gertjan Huiskes','Ko van Zeeland',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365288,'Jacques Willem van Melis','Dion Jaspers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365288,'Pieter Anne van Melis','Sander Mosselman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365288,'Gertjan Huiskes','Dion Jaspers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365288,'Jacques Willem van Melis','Sander Mosselman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365288,'Pieter Anne van Melis','Ko van Zeeland',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365288,'Pieter Anne van Melis','Dion Jaspers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365288,'Jacques Willem van Melis','Ko van Zeeland',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(365288,'Gertjan Huiskes','Sander Mosselman',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('26-02-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2012%'),351060,'Ames 2 De Zwervers','Rond de 100...',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351060,'Math van der Linden','Henri van de Coevering',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351060,'Anthony Bisschops','Laurens Boleij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351060,'Frans van Poppel','Mark Voermans',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351060,'Math van der Linden','Laurens Boleij',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351060,'Anthony Bisschops','Mark Voermans',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351060,'Frans van Poppel','Henri van de Coevering',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351060,'Frans van Poppel','Laurens Boleij',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351060,'Anthony Bisschops','Henri van de Coevering',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351060,'Math van der Linden','Mark Voermans',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('26-02-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2012%'),351061,'AVVL','VEGHEL 2',6,3);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351061,'Raymond Ruesink','Theo van den Anker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351061,'Herman van Deutekom','Jacques Willem van Melis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351061,'Sicco Vollema','Gertjan Huiskes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351061,'Raymond Ruesink','Jacques Willem van Melis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351061,'Herman van Deutekom','Gertjan Huiskes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351061,'Sicco Vollema','Theo van den Anker',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351061,'Sicco Vollema','Jacques Willem van Melis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351061,'Herman van Deutekom','Theo van den Anker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351061,'Raymond Ruesink','Gertjan Huiskes',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('06-03-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2012%'),351064,'Rond de 100...','AVVL',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351064,'Mark Voermans','Herman van Deutekom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351064,'Henri van de Coevering','Sicco Vollema',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351064,'Laurens Boleij','Raymond Ruesink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351064,'Mark Voermans','Sicco Vollema',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351064,'Henri van de Coevering','Raymond Ruesink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351064,'Laurens Boleij','Herman van Deutekom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351064,'Laurens Boleij','Sicco Vollema',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351064,'Henri van de Coevering','Herman van Deutekom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351064,'Mark Voermans','Raymond Ruesink',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-03-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2012%'),351066,'Ames 2 De Zwervers','VEGHEL 2',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351066,'Wim Manders','René van Bavel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351066,'Frans van Poppel','Sebastiaan Henstra',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351066,'Hans Moerkerk','Gertjan Huiskes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351066,'Wim Manders','Sebastiaan Henstra',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351066,'Frans van Poppel','Gertjan Huiskes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351066,'Hans Moerkerk','René van Bavel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351066,'Hans Moerkerk','Sebastiaan Henstra',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351066,'Frans van Poppel','René van Bavel',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351066,'Wim Manders','Gertjan Huiskes',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('12-03-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2012%'),351067,'AVVL','De Dieze 4',7,2);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351067,'Raymond Ruesink','Dion Jaspers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351067,'Herman van Deutekom','Ko van Zeeland',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351067,'Sicco Vollema','Sander Mosselman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351067,'Raymond Ruesink','Ko van Zeeland',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351067,'Herman van Deutekom','Sander Mosselman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351067,'Sicco Vollema','Dion Jaspers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351067,'Sicco Vollema','Ko van Zeeland',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351067,'Herman van Deutekom','Dion Jaspers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351067,'Raymond Ruesink','Sander Mosselman',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('02-04-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2012%'),351069,'Ames 2 De Zwervers','De Dieze 4',4,5);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351069,'Tijs van Kessel','Sander Mosselman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351069,'Math van der Linden','Ko van Zeeland',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351069,'Anthony Bisschops','Dion Jaspers',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351069,'Tijs van Kessel','Ko van Zeeland',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351069,'Math van der Linden','Dion Jaspers',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351069,'Anthony Bisschops','Sander Mosselman',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351069,'Anthony Bisschops','Ko van Zeeland',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351069,'Math van der Linden','Sander Mosselman',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351069,'Tijs van Kessel','Dion Jaspers',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('03-04-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2012%'),351071,'Rond de 100...','VEGHEL 2',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351071,'Mark Voermans','Theo van den Anker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351071,'Henri van de Coevering','Jacques Willem van Melis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351071,'Laurens Boleij','Gertjan Huiskes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351071,'Mark Voermans','Jacques Willem van Melis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351071,'Henri van de Coevering','Gertjan Huiskes',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351071,'Laurens Boleij','Theo van den Anker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351071,'Laurens Boleij','Jacques Willem van Melis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351071,'Henri van de Coevering','Theo van den Anker',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351071,'Mark Voermans','Gertjan Huiskes',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('10-04-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2012%'),351073,'De Dieze 4','Rond de 100...',2,7);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351073,'Sander Mosselman','Henri van de Coevering',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351073,'Dion Jaspers','Laurens Boleij',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351073,'Ko van Zeeland','Mark Voermans',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351073,'Sander Mosselman','Laurens Boleij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351073,'Dion Jaspers','Mark Voermans',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351073,'Ko van Zeeland','Henri van de Coevering',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351073,'Ko van Zeeland','Laurens Boleij',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351073,'Dion Jaspers','Henri van de Coevering',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351073,'Sander Mosselman','Mark Voermans',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('17-04-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2012%'),351076,'Rond de 100...','Ames 2 De Zwervers',9,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351076,'Mark Voermans','Frans van Poppel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351076,'Henri van de Coevering','Wim Manders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351076,'Laurens Boleij','Hans Moerkerk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351076,'Mark Voermans','Wim Manders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351076,'Henri van de Coevering','Hans Moerkerk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351076,'Laurens Boleij','Frans van Poppel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351076,'Laurens Boleij','Wim Manders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351076,'Henri van de Coevering','Frans van Poppel',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351076,'Mark Voermans','Hans Moerkerk',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('18-04-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2012%'),351077,'VEGHEL 2','AVVL',1,8);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351077,'Sebastiaan Henstra','Herman van Deutekom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351077,'Gertjan Huiskes','Sicco Vollema',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351077,'Pieter Anne van Melis','Raymond Ruesink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351077,'Sebastiaan Henstra','Sicco Vollema',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351077,'Gertjan Huiskes','Raymond Ruesink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351077,'Pieter Anne van Melis','Herman van Deutekom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351077,'Pieter Anne van Melis','Sicco Vollema',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351077,'Gertjan Huiskes','Herman van Deutekom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351077,'Sebastiaan Henstra','Raymond Ruesink',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('30-04-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2012%'),351079,'AVVL','Rond de 100...',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351079,'Herman van Deutekom','Henri van de Coevering',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351079,'Raymond Ruesink','Laurens Boleij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351079,'Sicco Vollema','Mark Voermans',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351079,'Herman van Deutekom','Laurens Boleij',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351079,'Raymond Ruesink','Mark Voermans',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351079,'Sicco Vollema','Henri van de Coevering',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351079,'Sicco Vollema','Laurens Boleij',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351079,'Raymond Ruesink','Henri van de Coevering',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(351079,'Herman van Deutekom','Mark Voermans',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('07-05-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2012%'),366306,'De Dieze 4','AVVL',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366306,'Sander Mosselman','Herman van Deutekom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366306,'Dion Jaspers','Sicco Vollema',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366306,'Ko van Zeeland','Raymond Ruesink',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366306,'Sander Mosselman','Sicco Vollema',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366306,'Dion Jaspers','Raymond Ruesink',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366306,'Ko van Zeeland','Herman van Deutekom',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366306,'Ko van Zeeland','Sicco Vollema',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366306,'Dion Jaspers','Herman van Deutekom',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366306,'Sander Mosselman','Raymond Ruesink',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('08-05-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2012%'),366305,'AVVL','Ames 2 De Zwervers',8,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366305,'Raymond Ruesink','Hans Moerkerk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366305,'Herman van Deutekom','Ko de Ruijter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366305,'Sicco Vollema','Anthony Bisschops',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366305,'Raymond Ruesink','Ko de Ruijter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366305,'Herman van Deutekom','Anthony Bisschops',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366305,'Sicco Vollema','Hans Moerkerk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366305,'Sicco Vollema','Ko de Ruijter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366305,'Herman van Deutekom','Hans Moerkerk',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366305,'Raymond Ruesink','Anthony Bisschops',1,0);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('16-05-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2012%'),366233,'VEGHEL 2','Ames 2 De Zwervers',5,4);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366233,'Gertjan Huiskes','Ko de Ruijter',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366233,'Theo van den Anker','Wim Manders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366233,'Gertjan Huiskes','Wim Manders',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366233,'Theo van den Anker','Anthony Bisschops',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366233,'Theo van den Anker','Ko de Ruijter',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366233,'Gertjan Huiskes','Anthony Bisschops',0,1);
insert into cm_matches(playdate, cpn_id, game_id, home_team, away_team, home_score, away_score) values(str_to_date('22-05-2013','%d-%m-%Y'),(select id from cm_competitions where name = 'Tweede klasse poule 3' and ssn_id like '2012%'),366502,'De Dieze 4','VEGHEL 2',3,6);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366502,'Sander Mosselman','Jacques Willem van Melis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366502,'Dion Jaspers','Pieter Anne van Melis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366502,'Ko van Zeeland','Gertjan Huiskes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366502,'Sander Mosselman','Pieter Anne van Melis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366502,'Dion Jaspers','Gertjan Huiskes',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366502,'Ko van Zeeland','Jacques Willem van Melis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366502,'Ko van Zeeland','Pieter Anne van Melis',1,0);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366502,'Dion Jaspers','Jacques Willem van Melis',0,1);
insert into cm_match_details(game_id, home_player, away_player, home_score, away_score) values(366502,'Sander Mosselman','Gertjan Huiskes',0,1);
